/**************************
***** Compiler Parameters *****
***************************
@P EffectName: Shader_333986049
***************************
****  ConstantBuffers  ****
***************************
cbuffer Inputs [Size: 112]
@C    input_4163284725_id39 => input_4163284725
@C    input_134282503_id40 => input_134282503
@C    input_3745251935_id41 => input_3745251935
@C    input_1514389348_id42 => input_1514389348
@C    input_2639673907_id43 => input_2639673907
cbuffer PerDraw [Size: 416]
@C    World_id24 => Transformation.World
@C    WorldInverse_id25 => Transformation.WorldInverse
@C    WorldInverseTranspose_id26 => Transformation.WorldInverseTranspose
@C    WorldView_id27 => Transformation.WorldView
@C    WorldViewInverse_id28 => Transformation.WorldViewInverse
@C    WorldViewProjection_id29 => Transformation.WorldViewProjection
@C    WorldScale_id30 => Transformation.WorldScale
@C    EyeMS_id31 => Transformation.EyeMS
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    SamplerInput_4158042989_id38 => SamplerInput_4158042989 [Stage: Pixel, Slot: (0-0)]
@R    TextureInput_3575833107_id37 => TextureInput_3575833107 [Stage: Pixel, Slot: (0-0)]
@R    Inputs => Inputs [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Shader_333986049 => eb115f56d2fcdcb961cd4935b5f926be
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    NormalStream => ea68512133899a045766d21afb59733a
***************************
*****     Stages      *****
***************************
@G    Vertex => 9274efd9116d5ab7a947f1996630bc3c
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id24;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id25;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id26;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id27;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id28;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id29; // Offset:  320 Size:    64
//   float3 WorldScale_id30;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id31;                 // Offset:  400 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyzw        1     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.Position_id14.x; v0.y <- __input__.Position_id14.y; v0.z <- __input__.Position_id14.z; v0.w <- __input__.Position_id14.w; 
//   v1.x <- __input__.meshNormal_id32.x; v1.y <- __input__.meshNormal_id32.y; v1.z <- __input__.meshNormal_id32.z; 
//   o1.x <- <VSMain return value>.Position_id14.x; o1.y <- <VSMain return value>.Position_id14.y; o1.z <- <VSMain return value>.Position_id14.z; o1.w <- <VSMain return value>.Position_id14.w; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 141 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_333986049_f22318b129f24b4c905b38dcae8ff2cd.hlsl"
dp4 o0.x, v0.xyzw, cb0[20].xyzw
dp4 o0.y, v0.xyzw, cb0[21].xyzw
dp4 o0.z, v0.xyzw, cb0[22].xyzw
dp4 o0.w, v0.xyzw, cb0[23].xyzw

#line 150
mov o1.xyzw, v0.xyzw
ret 
// Approximately 6 instruction slots used
@G    Pixel => 127da17bf4a352355a53ac0871be0698
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Inputs
// {
//
//   float3 input_4163284725_id39;      // Offset:    0 Size:    12
//   float4x4 input_134282503_id40;     // Offset:   16 Size:    64
//   float2 input_3745251935_id41;      // Offset:   80 Size:     8
//   float input_1514389348_id42;       // Offset:   88 Size:     4
//   float4 input_2639673907_id43;      // Offset:   96 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_4158042989_id38      sampler      NA          NA             s0      1 
// TextureInput_3575833107_id37      texture  float4          2d             t0      1 
// Inputs                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// POSITION                 0   xyzw        1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.Position_id14.x; v1.y <- __input__.Position_id14.y; v1.z <- __input__.Position_id14.z; v1.w <- __input__.Position_id14.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 69 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_333986049_f22318b129f24b4c905b38dcae8ff2cd.hlsl"
add r0.xyz, v1.xyzx, cb0[0].xyzx  // r0.x <- result_768265896.x; r0.y <- result_768265896.y; r0.z <- result_768265896.z

#line 72
max r0.w, |r0.x|, |r0.z|
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
min r1.x, |r0.x|, |r0.z|
mul r0.w, r0.w, r1.x
mul r1.x, r0.w, r0.w
mad r1.y, r1.x, l(0.020835), l(-0.085133)
mad r1.y, r1.x, r1.y, l(0.180141)
mad r1.y, r1.x, r1.y, l(-0.330299)
mad r1.x, r1.x, r1.y, l(0.999866)
mul r1.y, r0.w, r1.x
mad r1.y, r1.y, l(-2.000000), l(1.570796)
lt r1.z, |r0.x|, |r0.z|
and r1.y, r1.z, r1.y
mad r0.w, r0.w, r1.x, r1.y
lt r1.x, r0.x, -r0.x
and r1.x, r1.x, l(0xc0490fdb)
add r0.w, r0.w, r1.x
min r1.x, r0.x, r0.z
lt r1.x, r1.x, -r1.x
max r1.y, r0.x, r0.z
ge r1.y, r1.y, -r1.y
and r1.x, r1.y, r1.x
movc r0.w, r1.x, -r0.w, r0.w  // r0.w <- atan2_1013562188

#line 73
mul r0.w, r0.w, l(0.159155)  // r0.w <- result_2319789908

#line 75
frc r0.w, r0.w  // r0.w <- frac_112862627

#line 84
add r0.w, r0.w, l(0.500000)  // r0.w <- result_3536739629

#line 85
frc r0.w, r0.w  // r0.w <- frac_2312329351

#line 90
mul r0.w, r0.w, l(6.283185)  // r0.w <- result_3279942731

#line 91
sincos r1.x, r2.x, r0.w  // r2.x <- cos_3469213090; r1.x <- sin_1358531364

#line 77
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x  // r0.x <- length_3849636158

#line 78
div r0.x, r0.y, r0.x  // r0.x <- result_36533875

#line 79
mad r0.y, |r0.x|, l(-0.018729), l(0.074261)
mad r0.y, r0.y, |r0.x|, l(-0.212114)
mad r0.y, r0.y, |r0.x|, l(1.570729)
add r0.z, -|r0.x|, l(1.000000)
lt r0.x, r0.x, -r0.x
sqrt r0.z, r0.z
mul r0.w, r0.z, r0.y
mad r0.w, r0.w, l(-2.000000), l(3.141593)
and r0.x, r0.x, r0.w
mad r0.x, r0.y, r0.z, r0.x

#line 80
add r0.x, -r0.x, l(3.141593)  // r0.x <- result_2788130101

#line 87
mad r0.x, -r0.x, l(0.318310), l(1.000000)  // r0.x <- result_3291670590

#line 94
mad r0.x, r0.x, l(3.141593), l(-1.570796)  // r0.x <- result_1478783293

#line 95
sincos r0.x, r3.x, r0.x  // r3.x <- cos_400427646; r0.x <- sin_3500386155

#line 96
mul r2.x, r2.x, r3.x  // r2.x <- result_3422554398

#line 99
mul r2.z, r1.x, r3.x  // r2.z <- result_2879644452

#line 102
mov r2.y, r0.x
mov r2.w, l(1.000000)
dp4 r0.z, r2.xyzw, cb0[3].xyzw  // r0.z <- mul_3666814564.z
dp4 r0.x, r2.xyzw, cb0[1].xyzw  // r0.x <- mul_3666814564.x
dp4 r0.y, r2.xyzw, cb0[2].xyzw  // r0.y <- mul_3666814564.y

#line 106
max r0.w, |r0.x|, |r0.z|
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
min r1.x, |r0.x|, |r0.z|
mul r0.w, r0.w, r1.x
mul r1.x, r0.w, r0.w
mad r1.y, r1.x, l(0.020835), l(-0.085133)
mad r1.y, r1.x, r1.y, l(0.180141)
mad r1.y, r1.x, r1.y, l(-0.330299)
mad r1.x, r1.x, r1.y, l(0.999866)
mul r1.y, r0.w, r1.x
mad r1.y, r1.y, l(-2.000000), l(1.570796)
lt r1.z, |r0.x|, |r0.z|
and r1.y, r1.z, r1.y
mad r0.w, r0.w, r1.x, r1.y
lt r1.x, r0.x, -r0.x
and r1.x, r1.x, l(0xc0490fdb)
add r0.w, r0.w, r1.x
min r1.x, r0.x, r0.z
lt r1.x, r1.x, -r1.x
max r1.y, r0.x, r0.z

#line 111
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x  // r0.x <- length_884035943

#line 112
div r0.x, r0.y, r0.x  // r0.x <- result_2695269666

#line 106
ge r0.y, r1.y, -r1.y
and r0.y, r0.y, r1.x
movc r0.y, r0.y, -r0.w, r0.w  // r0.y <- atan2_4057462467

#line 107
mul r0.y, r0.y, l(0.159155)  // r0.y <- result_3078869547

#line 109
frc r1.x, r0.y  // r1.x <- frac_1810543932

#line 113
mad r0.y, |r0.x|, l(-0.018729), l(0.074261)
mad r0.y, r0.y, |r0.x|, l(-0.212114)
mad r0.y, r0.y, |r0.x|, l(1.570729)
add r0.z, -|r0.x|, l(1.000000)
lt r0.x, r0.x, -r0.x
sqrt r0.z, r0.z
mul r0.w, r0.z, r0.y
mad r0.w, r0.w, l(-2.000000), l(3.141593)
and r0.x, r0.x, r0.w
mad r0.x, r0.y, r0.z, r0.x

#line 114
add r0.x, -r0.x, l(3.141593)  // r0.x <- result_197603622

#line 115
mul r1.y, r0.x, l(0.318310)  // r1.y <- result_3870952908

#line 117
add r0.xy, r1.xyxx, l(-0.375000, -0.250000, 0.000000, 0.000000)  // r0.x <- result_3368492993.x; r0.y <- result_3368492993.y

#line 121
mad r0.xy, r0.xyxx, l(8.000000, 4.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)  // r0.x <- result_525281949.x; r0.y <- result_525281949.y

#line 122
div r0.xy, r0.xyxx, cb0[5].xyxx  // r0.x <- result_757256261.x; r0.y <- result_757256261.y

#line 123
add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // r0.x <- result_3636383563.x; r0.y <- result_3636383563.y

#line 124
mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)  // r0.x <- result_753126773.x; r0.y <- result_753126773.y

#line 125
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyxx, t0.xyzw, s0  // r0.x <- textureNode_116866913.x; r0.y <- textureNode_116866913.y; r0.z <- textureNode_116866913.z; r0.w <- textureNode_116866913.w

#line 127
eq r1.x, r0.w, cb0[5].z  // r1.x <- Assign_1915958409

#line 128
movc o0.xyzw, r1.xxxx, cb0[6].xyzw, r0.xyzw

#line 132
ret 
// Approximately 103 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float4 Position_id14;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
};
struct VS_STREAMS 
{
    float4 Position_id14;
    float3 meshNormal_id32;
    float4 PositionWS_id15;
    float3 normalWS_id35;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
};
struct VS_INPUT 
{
    float4 Position_id14 : POSITION;
    float3 meshNormal_id32 : NORMAL;
};
cbuffer Inputs 
{
    float3 input_4163284725_id39;
    float4x4 input_134282503_id40;
    float2 input_3745251935_id41;
    float input_1514389348_id42;
    float4 input_2639673907_id43;
};
cbuffer PerDraw 
{
    float4x4 World_id24;
    float4x4 WorldInverse_id25;
    float4x4 WorldInverseTranspose_id26;
    float4x4 WorldView_id27;
    float4x4 WorldViewInverse_id28;
    float4x4 WorldViewProjection_id29;
    float3 WorldScale_id30;
    float4 EyeMS_id31;
};
cbuffer PerView 
{
    float4x4 View_id17;
    float4x4 ViewInverse_id18;
    float4x4 Projection_id19;
    float4x4 ProjectionInverse_id20;
    float4x4 ViewProjection_id21;
    float2 ProjScreenRay_id22;
    float4 Eye_id23;
};
Texture2D TextureInput_3575833107_id37;
SamplerState SamplerInput_4158042989_id38;
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    float3 PositionXyz_1036650505 = streams.Position_id14.xyz;
    float3 result_768265896 = (PositionXyz_1036650505 + input_4163284725_id39);
    float resultZ_65349507 = result_768265896.z;
    float resultX_1932285498 = result_768265896.x;
    float atan2_1013562188 = atan2(resultZ_65349507, resultX_1932285498);
    float result_2319789908 = (atan2_1013562188 / 6.2831855);
    float result_1368061627 = (result_2319789908 + 1);
    float frac_112862627 = frac(result_1368061627);
    float resultY_2354114135 = result_768265896.y;
    float length_3849636158 = length(result_768265896);
    float result_36533875 = (resultY_2354114135 / length_3849636158);
    float asin_274857525 = asin(result_36533875);
    float result_2788130101 = (asin_274857525 + 1.5707964);
    float result_2096696371 = (result_2788130101 / 3.1415927);
    float2 float2Join_2522341882 = float2(frac_112862627, result_2096696371);
    float float2JoinX_1046669460 = float2Join_2522341882.x;
    float result_3536739629 = (float2JoinX_1046669460 + 0.5);
    float frac_2312329351 = frac(result_3536739629);
    float float2JoinY_2987950200 = float2Join_2522341882.y;
    float result_3291670590 = (1 - float2JoinY_2987950200);
    float2 float2Join_2597568769 = float2(frac_2312329351, result_3291670590);
    float float2JoinX_1811232006 = float2Join_2597568769.x;
    float result_3279942731 = (float2JoinX_1811232006 * 6.2831855);
    float cos_3469213090 = cos(result_3279942731);
    float float2JoinY_3840311370 = float2Join_2597568769.y;
    float result_1518270093 = (float2JoinY_3840311370 * 3.1415927);
    float result_1478783293 = (result_1518270093 - 1.5707964);
    float cos_400427646 = cos(result_1478783293);
    float result_3422554398 = (cos_3469213090 * cos_400427646);
    float sin_3500386155 = sin(result_1478783293);
    float sin_1358531364 = sin(result_3279942731);
    float result_2879644452 = (cos_400427646 * sin_1358531364);
    float3 Float3Join_2673463380 = float3(result_3422554398, sin_3500386155, result_2879644452);
    float4 join_19119165 = float4(Float3Join_2673463380, 1);
    float4 mul_3666814564 = mul(join_19119165, input_134282503_id40);
    float3 mulXyz_2903144911 = mul_3666814564.xyz;
    float mulXyzZ_414528684 = mulXyz_2903144911.z;
    float mulXyzX_149758427 = mulXyz_2903144911.x;
    float atan2_4057462467 = atan2(mulXyzZ_414528684, mulXyzX_149758427);
    float result_3078869547 = (atan2_4057462467 / 6.2831855);
    float result_974999236 = (result_3078869547 + 1);
    float frac_1810543932 = frac(result_974999236);
    float mulXyzY_2299894824 = mulXyz_2903144911.y;
    float length_884035943 = length(mulXyz_2903144911);
    float result_2695269666 = (mulXyzY_2299894824 / length_884035943);
    float asin_3178925854 = asin(result_2695269666);
    float result_197603622 = (asin_3178925854 + 1.5707964);
    float result_3870952908 = (result_197603622 / 3.1415927);
    float2 float2Join_2281969345 = float2(frac_1810543932, result_3870952908);
    float2 result_3368492993 = (float2Join_2281969345 - float2(0.375, 0.25));
    float2 result_3118713710 = (float2(0.625, 0.75) - float2(0.375, 0.25));
    float2 result_733754774 = (result_3368492993 / result_3118713710);
    float2 result_2108963025 = (result_733754774 * float2(2, 2));
    float2 result_525281949 = (result_2108963025 - float2(1, 1));
    float2 result_757256261 = (result_525281949 / input_3745251935_id41);
    float2 result_3636383563 = (result_757256261 + float2(1, 1));
    float2 result_753126773 = (result_3636383563 * float2(0.5, 0.5));
    float4 textureNode_116866913 = TextureInput_3575833107_id37.Sample(SamplerInput_4158042989_id38, result_753126773);
    float textureNodeW_4126518177 = textureNode_116866913.w;
    bool Assign_1915958409 = textureNodeW_4126518177 == input_1514389348_id42;
    float4 expression_3448467469 = Assign_1915958409 ? input_2639673907_id43 : textureNode_116866913;
    streams.ColorTarget_id2 = expression_3448467469;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    streams.meshNormal_id32 = __input__.meshNormal_id32;
    float4 mul_3614193389 = mul(streams.Position_id14, World_id24);
    streams.PositionWS_id15 = mul_3614193389;
    float4 mul_1295054772 = mul(streams.Position_id14, WorldViewProjection_id29);
    streams.ShadingPosition_id0 = mul_1295054772;
    float4 join_2852086183 = float4(streams.meshNormal_id32, 0);
    float4 mul_2848733323 = mul(join_2852086183, WorldInverseTranspose_id26);
    float3 mulXyz_2440637054 = mul_2848733323.xyz;
    streams.normalWS_id35 = mulXyz_2440637054;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.Position_id14 = streams.Position_id14;
    return __output__;
}
