/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1473342860]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 176]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_2286105837_id23 => input_2286105837
@C    input_3327715922_id24 => input_3327715922
@C    input_3894900822_id25 => input_3894900822
@C    input_1865221673_id26 => input_1865221673
@C    input_1483622063_id27 => input_1483622063
@C    input_2626109447_id28 => input_2626109447
@C    input_564890853_id29 => input_564890853
@C    input_3643268080_id30 => input_3643268080
***************************
******  Resources    ******
***************************
@R    TextureInput_4131200007_id22 => TextureInput_4131200007 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1473342860 => 7a8cbaff103e5cf5ecf42195a7bd498e
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCommonSDF => fd4404bbb9c85d9cbb82982e21c1e34b
@S    FuseCoreMath => b5527ab1f8082f68a6dcc7c3959ee99a
@S    FuseCoreTransform => b43eea1eed94d0f94cf8f317663a8207
@S    FuseCommonTypes => 6c2f0b095ce5f1d9e2781b56961676cd
@S    FuseCoreDomain => c1f7878dfca3e7c2b893bc77be2f5c29
@S    FuseCoreMathMap => a3c63d7e99620b0750ae90d499eee2ad
***************************
*****     Stages      *****
***************************
@G    Compute => 111a917ffff5afaf1a52cab3bc22bf7a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_2286105837_id23;        // Offset:   16 Size:    12
//   float input_3327715922_id24;       // Offset:   28 Size:     4 [unused]
//   float3 input_3894900822_id25;      // Offset:   32 Size:    12 [unused]
//   int3 input_1865221673_id26;        // Offset:   48 Size:    12
//   float3 input_1483622063_id27;      // Offset:   64 Size:    12 [unused]
//   float4x4 input_2626109447_id28;    // Offset:   80 Size:    64
//   float3 input_564890853_id29;       // Offset:  144 Size:    12
//   float3 input_3643268080_id30;      // Offset:  160 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_4131200007_id22          UAV   float          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[11], immediateIndexed
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 2
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 58 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_560cf5388711aeebe88f50f02b822274.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_536001411; r0.y <- Assign_3859735600; r0.z <- Assign_42903651

#line 59
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_1581015312

#line 64
if_z r0.x

#line 71
  utof r0.xyz, vThreadID.xyzx

#line 72
  add r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r0.x <- result_4176904314.x; r0.y <- result_4176904314.y; r0.z <- result_4176904314.z

#line 73
  itof r1.xyz, cb0[3].xyzx

#line 74
  div r0.xyz, r0.xyzx, r1.xyzx  // r0.x <- result_2018726859.x; r0.y <- result_2018726859.y; r0.z <- result_2018726859.z

#line 75
  add r0.xyz, r0.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)  // r0.x <- result_1693076261.x; r0.y <- result_1693076261.y; r0.z <- result_1693076261.z

#line 80
  mov r0.w, l(1.000000)
  dp4 r1.x, r0.xyzw, cb0[5].xyzw  // r1.x <- mul_776158911.x
  dp4 r1.y, r0.xyzw, cb0[6].xyzw  // r1.y <- mul_776158911.y
  dp4 r1.z, r0.xyzw, cb0[7].xyzw  // r1.z <- mul_776158911.z

#line 82
  add r0.xyz, r1.xyzx, -cb0[9].xyzx  // r0.x <- result_376861959.x; r0.y <- result_376861959.y; r0.z <- result_376861959.z

#line 42
  mad r0.xyz, -cb0[10].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), |r0.xyzx|
  add r0.xyz, r0.xyzx, l(8.000000, 8.000000, 8.000000, 0.000000)
  max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  dp3 r0.x, r0.xyzx, r0.xyzx
  sqrt r0.x, r0.x
  add r0.x, r0.x, l(-8.000000)  // r0.x <- <fRBox_id75 return value>

#line 85
  lt r0.x, l(0.100000), r0.x  // r0.x <- Assign_2129520040

#line 86
  and r0.x, r0.x, l(0x3f800000)

#line 88
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 114
ret 
// Approximately 25 instruction slots used
***************************
*************************/
static const float PI_id12 = 3.1415926535897;
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct Matrix4x4 
{
    float4x4 Matrix;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_2286105837_id23;
    float input_3327715922_id24;
    float3 input_3894900822_id25;
    int3 input_1865221673_id26;
    float3 input_1483622063_id27;
    float4x4 input_2626109447_id28;
    float3 input_564890853_id29;
    float3 input_3643268080_id30;
};
Texture3D<float> TextureInput_2510865218_id21;
RWTexture3D<float> TextureInput_4131200007_id22;
float cast11_id76(float p)
{
    return p;
}
float fRBox_id75(float3 p, float3 b, float rad)
{
    return length(max(abs(p) - b + rad, 0.0)) - rad;
}
float3 cast33_id74(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_2247141374 = streams.DispatchThreadId_id1.x;
    int inputX_1046803885 = input_2286105837_id23.x;
    bool Assign_536001411 = DispatchThreadIdX_2247141374 >= inputX_1046803885;
    int DispatchThreadIdY_717330578 = streams.DispatchThreadId_id1.y;
    int inputY_3027621359 = input_2286105837_id23.y;
    bool Assign_3859735600 = DispatchThreadIdY_717330578 >= inputY_3027621359;
    int DispatchThreadIdZ_2793580973 = streams.DispatchThreadId_id1.z;
    int inputZ_1984482882 = input_2286105837_id23.z;
    bool Assign_42903651 = DispatchThreadIdZ_2793580973 >= inputZ_1984482882;
    bool result_1581015312 = (Assign_536001411 || Assign_3859735600 || Assign_42903651);
    if (result_1581015312)
    {
        return;
    }
    float obstacle_169094072 = TextureInput_2510865218_id21[streams.DispatchThreadId_id1];
    float deltatime_991763999 = 0;
    deltatime_991763999 = input_3327715922_id24;
    int3 index_3834372314 = int3(0, 0, 0);
    index_3834372314 = streams.DispatchThreadId_id1;
    float3 resourcescale_3139356457 = float3(0, 0, 0);
    resourcescale_3139356457 = input_3894900822_id25;
    float3 cast33_173323759 = cast33_id74(streams.DispatchThreadId_id1);
    float3 result_4176904314 = (cast33_173323759 + float3(0.5, 0.5, 0.5));
    float3 cast33_516830269 = cast33_id74(input_1865221673_id26);
    float3 result_2018726859 = (result_4176904314 / cast33_516830269);
    float3 result_1693076261 = (result_2018726859 - 0.5);
    float3 result_2315774062 = (float3(0.5, 0.5, 0.5) - float3(0.5, 0.5, 0.5));
    float3 result_836499057 = (result_2315774062 * input_1483622063_id27);
    float3 result_4260037279 = (result_1693076261 + result_836499057);
    float4 join_1339032214 = float4(result_4260037279, 1);
    float4 mul_776158911 = mul(join_1339032214, input_2626109447_id28);
    float3 mulXyz_3522941060 = mul_776158911.xyz;
    float3 result_376861959 = (mulXyz_3522941060 - input_564890853_id29);
    float3 result_1476762969 = (input_3643268080_id30 * 0.5);
    float fRBox_2540093571 = fRBox_id75(result_376861959, result_1476762969, 8);
    bool Assign_2129520040 = fRBox_2540093571 > 0.1;
    float cast11_1453316571 = cast11_id76(Assign_2129520040);
    obstacle_169094072 = cast11_1453316571;
    TextureInput_4131200007_id22[streams.DispatchThreadId_id1] = obstacle_169094072;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
