/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1895743081]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 144]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_1703154449_id19 => input_1703154449
@C    input_524868224_id20 => input_524868224
@C    input_2777777268_id21 => input_2777777268
@C    input_3217863329_id22 => input_3217863329
@C    input_2889620838_id23 => input_2889620838
@C    input_4101896467_id24 => input_4101896467
@C    input_1873775343_id25 => input_1873775343
@C    input_2291850119_id26 => input_2291850119
@C    input_458120889_id27 => input_458120889
@C    input_3503453257_id28 => input_3503453257
@C    input_362125994_id29 => input_362125994
@C    input_2182222056_id30 => input_2182222056
@C    input_2625765118_id31 => input_2625765118
@C    input_2239425391_id32 => input_2239425391
***************************
******  Resources    ******
***************************
@R    SamplerInput_3260188741_id15 => SamplerInput_3260188741 [Stage: Compute, Slot: (0-0)]
@R    SamplerInput_532195180_id16 => SamplerInput_532195180 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_3751006716_id12 => TextureInput_3751006716 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_2694680050_id13 => TextureInput_2694680050 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_520123398_id14 => TextureInput_520123398 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_3468441537_id17 => TextureInput_3468441537 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_3941502923_id18 => TextureInput_3941502923 [Stage: Compute, Slot: (1-1)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1895743081 => 80b2b3ad6e86b9a765bdc5a26e11f5a6
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
***************************
*****     Stages      *****
***************************
@G    Compute => d92cbb7fd7ba2ab1d5a54036da1ad8dd
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_1703154449_id19;        // Offset:   16 Size:    12
//   float input_524868224_id20;        // Offset:   28 Size:     4 [unused]
//   float3 input_2777777268_id21;      // Offset:   32 Size:    12 [unused]
//   bool input_3217863329_id22;        // Offset:   44 Size:     4
//   float input_2889620838_id23;       // Offset:   48 Size:     4
//   float input_4101896467_id24;       // Offset:   52 Size:     4
//   int3 input_1873775343_id25;        // Offset:   64 Size:    12
//   int3 input_2291850119_id26;        // Offset:   80 Size:    12
//   float input_458120889_id27;        // Offset:   92 Size:     4
//   float input_3503453257_id28;       // Offset:   96 Size:     4
//   float input_362125994_id29;        // Offset:  100 Size:     4
//   int3 input_2182222056_id30;        // Offset:  112 Size:    12
//   int3 input_2625765118_id31;        // Offset:  128 Size:    12
//   float input_2239425391_id32;       // Offset:  140 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_3260188741_id15      sampler      NA          NA             s0      1 
// SamplerInput_532195180_id16       sampler      NA          NA             s1      1 
// TextureInput_3751006716_id12      texture  float4          3d             t0      1 
// TextureInput_2694680050_id13      texture   float          3d             t1      1 
// TextureInput_520123398_id14       texture   float          3d             t2      1 
// TextureInput_3468441537_id17          UAV  float4          3d             u0      1 
// TextureInput_3941502923_id18          UAV   float          3d             u1      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[9], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_uav_typed_texture3d (float,float,float,float) u1
dcl_input vThreadID.xyz
dcl_temps 3
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 56 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_05f74c4f82beb7df1ede4fc607ccfff2.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_1403220339; r0.y <- Assign_1745898688; r0.z <- Assign_4076023683

#line 57
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2861774432

#line 62
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyz, r0.xyzw, t0.xyzw  // r1.x <- velocity_2_2109589880.x; r1.y <- velocity_2_2109589880.y; r1.z <- velocity_2_2109589880.z

#line 63
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- obstacle_3389810030

#line 71
  lt r0.x, l(0.000000), r0.x  // r0.x <- Assign_2993165833

#line 72
  ine r0.y, cb0[2].w, l(0)
  or r0.x, r0.x, r0.y  // r0.x <- result_4015485074

#line 73
  utof r0.yzw, vThreadID.xxyz

#line 75
  mul r1.w, cb0[3].y, cb0[3].x  // r1.w <- result_3239606818

#line 77
  mad r1.xyz, -r1.xyzx, r1.wwww, r0.yzwy  // r1.x <- result_1907784739.x; r1.y <- result_1907784739.y; r1.z <- result_1907784739.z

#line 78
  itof r2.xyz, cb0[4].xyzx

#line 79
  add r2.xyz, r2.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- result_1125638938.x; r2.y <- result_1125638938.y; r2.z <- result_1125638938.z

#line 80
  max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r1.xyz, r2.xyzx, r1.xyzx  // r1.x <- clamp_1749416893.x; r1.y <- clamp_1749416893.y; r1.z <- clamp_1749416893.z

#line 81
  add r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r1.x <- result_3518783085.x; r1.y <- result_3518783085.y; r1.z <- result_3518783085.z

#line 82
  itof r2.xyz, cb0[5].xyzx

#line 83
  div r1.xyz, r1.xyzx, r2.xyzx  // r1.x <- result_2479262215.x; r1.y <- result_2479262215.y; r1.z <- result_2479262215.z

#line 84
  sample_l_indexable(texture3d)(float,float,float,float) r2.xyzw, r1.xyzx, t0.xyzw, s0, l(0.000000)  // r2.x <- textureNode_3025500320.x; r2.y <- textureNode_3025500320.y; r2.z <- textureNode_3025500320.z; r2.w <- textureNode_3025500320.w

#line 86
  mul r1.x, r1.w, cb0[5].w  // r1.x <- result_670238599

#line 88
  mad r1.xyzw, -r2.xyzw, r1.xxxx, r2.xyzw  // r1.x <- result_1743967641.x; r1.y <- result_1743967641.y; r1.z <- result_1743967641.z; r1.w <- result_1743967641.w

#line 93
  movc r1.xyzw, r0.xxxx, l(0,0,0,0), r1.xyzw  // r1.x <- output_1545359346.x; r1.y <- output_1545359346.y; r1.z <- output_1545359346.z; r1.w <- output_1545359346.w

#line 99
  mul r2.x, cb0[6].y, cb0[6].x  // r2.x <- result_2230324843

#line 101
  mad r0.yzw, -r1.xxyz, r2.xxxx, r0.yyzw  // r0.y <- result_3737704844.x; r0.z <- result_3737704844.y; r0.w <- result_3737704844.z

#line 102
  itof r2.yzw, cb0[7].xxyz

#line 103
  add r2.yzw, r2.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)  // r2.y <- result_850135091.x; r2.z <- result_850135091.y; r2.w <- result_850135091.z

#line 104
  max r0.yzw, r0.yyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r0.yzw, r2.yyzw, r0.yyzw  // r0.y <- clamp_340388374.x; r0.z <- clamp_340388374.y; r0.w <- clamp_340388374.z

#line 105
  add r0.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)  // r0.y <- result_1888918934.x; r0.z <- result_1888918934.y; r0.w <- result_1888918934.z

#line 106
  itof r2.yzw, cb0[8].xxyz

#line 107
  div r0.yzw, r0.yyzw, r2.yyzw  // r0.y <- result_115504480.x; r0.z <- result_115504480.y; r0.w <- result_115504480.z

#line 108
  sample_l_indexable(texture3d)(float,float,float,float) r0.y, r0.yzwy, t2.yxzw, s1, l(0.000000)  // r0.y <- textureNode_1134807783

#line 110
  mul r0.z, r2.x, cb0[8].w  // r0.z <- result_947544622

#line 112
  mad r0.y, -r0.y, r0.z, r0.y  // r0.y <- result_3088081520

#line 117
  movc r0.x, r0.x, l(0), r0.y  // r0.x <- output_598221887

#line 119
  store_uav_typed u0.xyzw, vThreadID.xyzz, r1.xyzw

#line 120
  store_uav_typed u1.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 146
ret 
// Approximately 42 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_1703154449_id19;
    float input_524868224_id20;
    float3 input_2777777268_id21;
    bool input_3217863329_id22;
    float input_2889620838_id23;
    float input_4101896467_id24;
    int3 input_1873775343_id25;
    int3 input_2291850119_id26;
    float input_458120889_id27;
    float input_3503453257_id28;
    float input_362125994_id29;
    int3 input_2182222056_id30;
    int3 input_2625765118_id31;
    float input_2239425391_id32;
};
Texture3D<float4> TextureInput_3751006716_id12;
Texture3D<float> TextureInput_2694680050_id13;
Texture3D<float> TextureInput_520123398_id14;
SamplerState SamplerInput_3260188741_id15;
SamplerState SamplerInput_532195180_id16;
RWTexture3D<float4> TextureInput_3468441537_id17;
RWTexture3D<float> TextureInput_3941502923_id18;
float3 cast33_id5(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_622466782 = streams.DispatchThreadId_id1.x;
    int inputX_793017481 = input_1703154449_id19.x;
    bool Assign_1403220339 = DispatchThreadIdX_622466782 >= inputX_793017481;
    int DispatchThreadIdY_909295366 = streams.DispatchThreadId_id1.y;
    int inputY_4159513183 = input_1703154449_id19.y;
    bool Assign_1745898688 = DispatchThreadIdY_909295366 >= inputY_4159513183;
    int DispatchThreadIdZ_281173665 = streams.DispatchThreadId_id1.z;
    int inputZ_1973991986 = input_1703154449_id19.z;
    bool Assign_4076023683 = DispatchThreadIdZ_281173665 >= inputZ_1973991986;
    bool result_2861774432 = (Assign_1403220339 || Assign_1745898688 || Assign_4076023683);
    if (result_2861774432)
    {
        return;
    }
    float4 velocity_2_2109589880 = TextureInput_3751006716_id12[streams.DispatchThreadId_id1];
    float obstacle_3389810030 = TextureInput_2694680050_id13[streams.DispatchThreadId_id1];
    float density_3460948108 = TextureInput_520123398_id14[streams.DispatchThreadId_id1];
    float deltatime_2152636231 = 0;
    deltatime_2152636231 = input_524868224_id20;
    int3 index_3565979052 = int3(0, 0, 0);
    index_3565979052 = streams.DispatchThreadId_id1;
    float3 resourcescale_139258001 = float3(0, 0, 0);
    resourcescale_139258001 = input_2777777268_id21;
    bool Assign_2993165833 = obstacle_3389810030 > 0;
    bool result_4015485074 = (input_3217863329_id22 || Assign_2993165833);
    float3 cast33_2215198966 = cast33_id5(streams.DispatchThreadId_id1);
    float3 VelocityXyz_506352026 = velocity_2_2109589880.xyz;
    float result_3239606818 = (input_2889620838_id23 * input_4101896467_id24);
    float3 result_419522994 = (VelocityXyz_506352026 * result_3239606818);
    float3 result_1907784739 = (cast33_2215198966 - result_419522994);
    float3 cast33_406774385 = cast33_id5(input_1873775343_id25);
    float3 result_1125638938 = (cast33_406774385 - float3(1, 1, 1));
    float3 clamp_1749416893 = clamp(result_1907784739, float3(0, 0, 0), result_1125638938);
    float3 result_3518783085 = (clamp_1749416893 + float3(0.5, 0.5, 0.5));
    float3 cast33_3300482555 = cast33_id5(input_2291850119_id26);
    float3 result_2479262215 = (result_3518783085 / cast33_3300482555);
    float4 textureNode_3025500320 = TextureInput_3751006716_id12.SampleLevel(SamplerInput_3260188741_id15, result_2479262215, 0);
    float4 result_1037404429 = (float4(0, 0, 0, 0) - textureNode_3025500320);
    float result_670238599 = (input_458120889_id27 * result_3239606818);
    float4 result_975175125 = (result_1037404429 * result_670238599);
    float4 result_1743967641 = (textureNode_3025500320 + result_975175125);
    float4 output_1545359346 = result_1743967641;
    if (result_4015485074)
    {
        output_1545359346 = float4(0, 0, 0, 0);
    }
    velocity_2_2109589880 = output_1545359346;
    bool Assign_4068616160 = obstacle_3389810030 > 0;
    bool result_1249579561 = (input_3217863329_id22 || Assign_4068616160);
    float3 cast33_2177774413 = cast33_id5(streams.DispatchThreadId_id1);
    float3 VelocityXyz_3171435251 = velocity_2_2109589880.xyz;
    float result_2230324843 = (input_3503453257_id28 * input_362125994_id29);
    float3 result_12204057 = (VelocityXyz_3171435251 * result_2230324843);
    float3 result_3737704844 = (cast33_2177774413 - result_12204057);
    float3 cast33_2113581464 = cast33_id5(input_2182222056_id30);
    float3 result_850135091 = (cast33_2113581464 - float3(1, 1, 1));
    float3 clamp_340388374 = clamp(result_3737704844, float3(0, 0, 0), result_850135091);
    float3 result_1888918934 = (clamp_340388374 + float3(0.5, 0.5, 0.5));
    float3 cast33_2432950388 = cast33_id5(input_2625765118_id31);
    float3 result_115504480 = (result_1888918934 / cast33_2432950388);
    float textureNode_1134807783 = TextureInput_520123398_id14.SampleLevel(SamplerInput_532195180_id16, result_115504480, 0);
    float result_2917929254 = (0 - textureNode_1134807783);
    float result_947544622 = (input_2239425391_id32 * result_2230324843);
    float result_1990052414 = (result_2917929254 * result_947544622);
    float result_3088081520 = (textureNode_1134807783 + result_1990052414);
    float output_598221887 = result_3088081520;
    if (result_1249579561)
    {
        output_598221887 = 0;
    }
    density_3460948108 = output_598221887;
    TextureInput_3468441537_id17[streams.DispatchThreadId_id1] = velocity_2_2109589880;
    TextureInput_3941502923_id18[streams.DispatchThreadId_id1] = density_3460948108;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
