/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin TransformColorChannel_Internal_TextureFX [{Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}]
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 16]
@C    InputValue_id99 => ShaderFX.InputValueFloat4
cbuffer Globals [Size: 352]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
@C    Transform0_id94 => TransformColorChannel_Internal_TextureFX.Transform0
@C    Transform1_id95 => TransformColorChannel_Internal_TextureFX.Transform1
@C    Transform2_id96 => TransformColorChannel_Internal_TextureFX.Transform2
@C    Transform3_id97 => TransformColorChannel_Internal_TextureFX.Transform3
@C    type_id98 => TransformColorChannel_Internal_TextureFX.type
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    LinearSampler_id44 => Texturing.LinearSampler [Stage: Pixel, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (1-1)]
@R    Sampler1_id53 => Texturing.Sampler1 [Stage: Pixel, Slot: (2-2)]
@R    Sampler2_id54 => Texturing.Sampler2 [Stage: Pixel, Slot: (3-3)]
@R    Sampler3_id55 => Texturing.Sampler3 [Stage: Pixel, Slot: (4-4)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (1-1)]
***************************
*****     Sources     *****
***************************
@S    TransformColorChannel_Internal_TextureFX => c4d435845ebf4d9149834b11d65ba122
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    AddonShaderUtils => 0d3496ddd24bfcbde4abd1deae724f64
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 282 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_e0cd1e29503acfe084ab450624cf4917.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 286
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => b5405c0bbed6fc628b07530b3b416287
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id99;            // Offset:    0 Size:    16
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//   float4x4 Transform0_id94;          // Offset:   80 Size:    64
//   float4x4 Transform1_id95;          // Offset:  144 Size:    64
//   float4x4 Transform2_id96;          // Offset:  208 Size:    64
//   float4x4 Transform3_id97;          // Offset:  272 Size:    64
//   int type_id98;                     // Offset:  336 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// LinearSampler_id44                sampler      NA          NA             s0      1 
// Sampler0_id52                     sampler      NA          NA             s1      1 
// Sampler1_id53                     sampler      NA          NA             s2      1 
// Sampler2_id54                     sampler      NA          NA             s3      1 
// Sampler3_id55                     sampler      NA          NA             s4      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// Globals                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB1[22], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 6
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 261 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_e0cd1e29503acfe084ab450624cf4917.hlsl"
sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s1, l(0.000000)  // r0.x <- <InTex0_id26 return value>.x; r0.y <- <InTex0_id26 return value>.y; r0.z <- <InTex0_id26 return value>.z; r0.w <- <InTex0_id26 return value>.w

#line 241
switch cb1[21].x

#line 244
  case l(0)

#line 171
  mad r2.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(-0.500000, 0.500000, 0.000000, 0.000000)
  mov r2.z, l(1.000000)
  dp3 r3.x, r2.xyzx, cb1[5].xywx
  dp3 r3.y, r2.xyzx, cb1[6].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 228
  sample_l_indexable(texture2d)(float,float,float,float) r1.x, r3.xyxx, t0.xyzw, s1, l(0.000000)  // r1.x <- R

#line 171
  dp3 r3.x, r2.xyzx, cb1[9].xywx
  dp3 r3.y, r2.xyzx, cb1[10].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 229
  sample_l_indexable(texture2d)(float,float,float,float) r1.y, r3.xyxx, t0.xyzw, s2, l(0.000000)  // r1.y <- G

#line 171
  dp3 r3.x, r2.xyzx, cb1[13].xywx
  dp3 r3.y, r2.xyzx, cb1[14].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 230
  sample_l_indexable(texture2d)(float,float,float,float) r1.z, r3.xyxx, t0.xyzw, s3, l(0.000000)  // r1.z <- B

#line 171
  dp3 r3.x, r2.xyzx, cb1[17].xywx
  dp3 r3.y, r2.xyzx, cb1[18].xywx
  mad r2.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r2.x <- <TransformUV_id60 return value>.x; r2.y <- <TransformUV_id60 return value>.y

#line 231
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, r2.xyxx, t0.xyzw, s4, l(0.000000)  // r1.w <- A

#line 246
  break 

#line 247
  case l(1)

#line 171
  mad r2.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(-0.500000, 0.500000, 0.000000, 0.000000)
  mov r2.z, l(1.000000)
  dp3 r3.x, r2.xyzx, cb1[5].xywx
  dp3 r3.y, r2.xyzx, cb1[6].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 219
  sample_l_indexable(texture2d)(float,float,float,float) r3.xyw, r3.xyxx, t0.yzwx, s1, l(0.000000)

#line 154
  lt r2.w, r3.x, r3.y
  mov r4.xy, r3.yxyy
  mov r4.zw, l(0,0,-1.000000,0.666667)
  mov r5.xy, r4.yxyy
  mov r5.zw, l(0,0,0,-0.333333)
  movc r4.xyzw, r2.wwww, r4.xyzw, r5.xyzw  // r4.x <- P.x; r4.y <- P.y; r4.z <- P.z; r4.w <- P.w

#line 155
  lt r2.w, r3.w, r4.x
  mov r3.xyz, r4.xywx
  mov r4.xyw, r3.wywx
  movc r3.xyzw, r2.wwww, r3.xyzw, r4.xyzw  // r3.x <- Q.x; r3.y <- Q.y; r3.z <- Q.z; r3.w <- Q.w

#line 156
  min r2.w, r3.y, r3.w
  add r2.w, -r2.w, r3.x  // r2.w <- C

#line 157
  add r3.x, -r3.y, r3.w
  mad r2.w, r2.w, l(6.000000), l(0.000000)
  div r2.w, r3.x, r2.w
  add r2.w, r3.z, r2.w

#line 171
  dp3 r3.x, r2.xyzx, cb1[9].xywx
  dp3 r3.y, r2.xyzx, cb1[10].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 220
  sample_l_indexable(texture2d)(float,float,float,float) r3.xyz, r3.xyxx, t0.yzxw, s2, l(0.000000)

#line 154
  lt r3.w, r3.x, r3.y
  movc r3.xy, r3.wwww, r3.yxyy, r3.xyxx  // r3.x <- P.x; r3.y <- P.y

#line 155
  lt r3.w, r3.z, r3.x
  movc r3.xyz, r3.wwww, r3.xyzx, r3.zyxz  // r3.x <- Q.x; r3.y <- Q.y; r3.z <- Q.w

#line 156
  min r3.y, r3.y, r3.z
  add r3.y, -r3.y, r3.x  // r3.y <- C

#line 194
  add r3.x, r3.x, l(0.000000)
  div r3.x, r3.y, r3.x  // r3.x <- S

#line 171
  dp3 r4.x, r2.xyzx, cb1[13].xywx
  dp3 r4.y, r2.xyzx, cb1[14].xywx
  mad r3.yz, r4.xxyx, l(0.000000, 1.000000, -1.000000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)  // r3.y <- <TransformUV_id60 return value>.x; r3.z <- <TransformUV_id60 return value>.y

#line 221
  sample_l_indexable(texture2d)(float,float,float,float) r3.yzw, r3.yzyy, t0.wxyz, s3, l(0.000000)

#line 154
  max r3.z, r3.w, r3.z  // r3.z <- P.x

#line 155
  max r3.y, r3.z, r3.y  // r3.y <- Q.x

#line 171
  dp3 r4.x, r2.xyzx, cb1[17].xywx
  dp3 r4.y, r2.xyzx, cb1[18].xywx
  mad r2.xy, r4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r2.x <- <TransformUV_id60 return value>.x; r2.y <- <TransformUV_id60 return value>.y

#line 222
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, r2.xyxx, t0.xyzw, s4, l(0.000000)  // r1.w <- A

#line 146
  frc r2.x, |r2.w|  // r2.x <- H

#line 149
  mad r2.xyz, r2.xxxx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 150
  mad_sat r2.xyz, |r2.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r2.x <- <HUEtoRGB_id36 return value>.x; r2.y <- <HUEtoRGB_id36 return value>.y; r2.z <- <HUEtoRGB_id36 return value>.z

#line 189
  add r2.xyz, r2.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
  mad r2.xyz, r2.xyzx, r3.xxxx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r1.xyz, r3.yyyy, r2.xyzx  // r1.x <- <HSVtoRGB_id37 return value>.x; r1.y <- <HSVtoRGB_id37 return value>.y; r1.z <- <HSVtoRGB_id37 return value>.z

#line 249
  break 

#line 250
  case l(2)

#line 171
  mad r2.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(-0.500000, 0.500000, 0.000000, 0.000000)
  mov r2.z, l(1.000000)
  dp3 r3.x, r2.xyzx, cb1[5].xywx
  dp3 r3.y, r2.xyzx, cb1[6].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 210
  sample_l_indexable(texture2d)(float,float,float,float) r3.xyw, r3.xyxx, t0.yzwx, s1, l(0.000000)

#line 154
  lt r2.w, r3.x, r3.y
  mov r4.xy, r3.yxyy
  mov r4.zw, l(0,0,-1.000000,0.666667)
  mov r5.xy, r4.yxyy
  mov r5.zw, l(0,0,0,-0.333333)
  movc r4.xyzw, r2.wwww, r4.xyzw, r5.xyzw  // r4.x <- P.x; r4.y <- P.y; r4.z <- P.z; r4.w <- P.w

#line 155
  lt r2.w, r3.w, r4.x
  mov r3.xyz, r4.xywx
  mov r4.xyw, r3.wywx
  movc r3.xyzw, r2.wwww, r3.xyzw, r4.xyzw  // r3.x <- Q.x; r3.y <- Q.y; r3.z <- Q.z; r3.w <- Q.w

#line 156
  min r2.w, r3.y, r3.w
  add r2.w, -r2.w, r3.x  // r2.w <- C

#line 157
  add r3.x, -r3.y, r3.w
  mad r2.w, r2.w, l(6.000000), l(0.000000)
  div r2.w, r3.x, r2.w
  add r2.w, r3.z, r2.w

#line 171
  dp3 r3.x, r2.xyzx, cb1[9].xywx
  dp3 r3.y, r2.xyzx, cb1[10].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 211
  sample_l_indexable(texture2d)(float,float,float,float) r3.xyz, r3.xyxx, t0.yzxw, s2, l(0.000000)

#line 154
  lt r3.w, r3.x, r3.y
  movc r3.xy, r3.wwww, r3.yxyy, r3.xyxx  // r3.x <- P.x; r3.y <- P.y

#line 155
  lt r3.w, r3.z, r3.x
  movc r3.xyz, r3.wwww, r3.xyzx, r3.zyxz  // r3.x <- Q.x; r3.y <- Q.y; r3.z <- Q.w

#line 156
  min r3.y, r3.y, r3.z
  add r3.y, -r3.y, r3.x  // r3.y <- C

#line 182
  mad r3.x, -r3.y, l(0.500000), r3.x  // r3.x <- L

#line 183
  mad r3.x, r3.x, l(2.000000), l(-1.000000)
  add r3.x, -|r3.x|, l(1.000000)
  div r3.x, r3.y, r3.x  // r3.x <- S

#line 171
  dp3 r4.x, r2.xyzx, cb1[13].xywx
  dp3 r4.y, r2.xyzx, cb1[14].xywx
  mad r3.yz, r4.xxyx, l(0.000000, 1.000000, -1.000000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)  // r3.y <- <TransformUV_id60 return value>.x; r3.z <- <TransformUV_id60 return value>.y

#line 212
  sample_l_indexable(texture2d)(float,float,float,float) r3.yzw, r3.yzyy, t0.wyzx, s3, l(0.000000)

#line 154
  lt r4.x, r3.y, r3.z
  movc r3.yz, r4.xxxx, r3.zzyz, r3.yyzy  // r3.y <- P.x; r3.z <- P.y

#line 155
  lt r4.x, r3.w, r3.y
  movc r3.yzw, r4.xxxx, r3.yyzw, r3.wwzy  // r3.w <- Q.w; r3.y <- Q.x; r3.z <- Q.y

#line 156
  min r3.z, r3.z, r3.w
  add r3.z, -r3.z, r3.y  // r3.z <- C

#line 182
  mad r3.y, -r3.z, l(0.500000), r3.y  // r3.y <- L

#line 171
  dp3 r4.x, r2.xyzx, cb1[17].xywx
  dp3 r4.y, r2.xyzx, cb1[18].xywx
  mad r2.xy, r4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r2.x <- <TransformUV_id60 return value>.x; r2.y <- <TransformUV_id60 return value>.y

#line 213
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, r2.xyxx, t0.xyzw, s4, l(0.000000)  // r1.w <- A

#line 146
  frc r2.x, |r2.w|  // r2.x <- H

#line 149
  mad r2.xyz, r2.xxxx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 150
  mad_sat r2.xyz, |r2.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r2.x <- <HUEtoRGB_id36 return value>.x; r2.y <- <HUEtoRGB_id36 return value>.y; r2.z <- <HUEtoRGB_id36 return value>.z

#line 176
  mad r2.w, r3.y, l(2.000000), l(-1.000000)
  add r2.w, -|r2.w|, l(1.000000)
  mul r2.w, r3.x, r2.w  // r2.w <- C

#line 177
  add r2.xyz, r2.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
  mad r1.xyz, r2.xyzx, r2.wwww, r3.yyyy  // r1.x <- <HSLtoRGB_id38 return value>.x; r1.y <- <HSLtoRGB_id38 return value>.y; r1.z <- <HSLtoRGB_id38 return value>.z

#line 252
  break 

#line 253
  case l(3)

#line 171
  mad r2.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(-0.500000, 0.500000, 0.000000, 0.000000)
  mov r2.z, l(1.000000)
  dp3 r3.x, r2.xyzx, cb1[5].xywx
  dp3 r3.y, r2.xyzx, cb1[6].xywx
  mad r3.xy, r3.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r3.x <- <TransformUV_id60 return value>.x; r3.y <- <TransformUV_id60 return value>.y

#line 200
  sample_l_indexable(texture2d)(float,float,float,float) r3.xyz, r3.xyxx, t0.xyzw, s1, l(0.000000)

#line 166
  max r2.w, r3.y, r3.x
  max r2.w, r3.z, r2.w  // r2.w <- w

#line 167
  add r3.x, -r3.x, r2.w
  div r2.w, r3.x, r2.w
  max r2.w, r2.w, l(0.000000)
  min r3.x, r2.w, l(1.000000)  // r3.x <- <RGBToCMYK_id39 return value>.x

#line 171
  dp3 r4.x, r2.xyzx, cb1[9].xywx
  dp3 r4.y, r2.xyzx, cb1[10].xywx
  mad r4.xy, r4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r4.x <- <TransformUV_id60 return value>.x; r4.y <- <TransformUV_id60 return value>.y

#line 201
  sample_l_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyxx, t0.xyzw, s2, l(0.000000)

#line 166
  max r2.w, r4.y, r4.x
  max r2.w, r4.z, r2.w  // r2.w <- w

#line 167
  add r3.w, -r4.y, r2.w
  div r2.w, r3.w, r2.w
  max r2.w, r2.w, l(0.000000)
  min r3.y, r2.w, l(1.000000)  // r3.y <- <RGBToCMYK_id39 return value>.y

#line 171
  dp3 r4.x, r2.xyzx, cb1[13].xywx
  dp3 r4.y, r2.xyzx, cb1[14].xywx
  mad r4.xy, r4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r4.x <- <TransformUV_id60 return value>.x; r4.y <- <TransformUV_id60 return value>.y

#line 202
  sample_l_indexable(texture2d)(float,float,float,float) r4.xyz, r4.xyxx, t0.xyzw, s3, l(0.000000)

#line 166
  max r2.w, r4.y, r4.x
  max r2.w, r4.z, r2.w  // r2.w <- w

#line 167
  add r3.w, -r4.z, r2.w
  div r2.w, r3.w, r2.w
  max r2.w, r2.w, l(0.000000)
  min r3.z, r2.w, l(1.000000)  // r3.z <- <RGBToCMYK_id39 return value>.z

#line 171
  dp3 r4.x, r2.xyzx, cb1[17].xywx
  dp3 r4.y, r2.xyzx, cb1[18].xywx
  mad r2.xy, r4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)  // r2.x <- <TransformUV_id60 return value>.x; r2.y <- <TransformUV_id60 return value>.y

#line 203
  sample_l_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t0.xyzw, s4, l(0.000000)

#line 166
  max r2.x, r2.y, r2.x
  max r2.x, r2.z, r2.x  // r2.x <- w

#line 167
  add r2.x, -r2.x, l(1.000000)
  max r2.x, r2.x, l(0.000000)
  min r2.x, r2.x, l(1.000000)  // r2.x <- <RGBToCMYK_id39 return value>.w

#line 204
  sample_l_indexable(texture2d)(float,float,float,float) r1.w, v1.xyxx, t0.xyzw, s0, l(0.000000)  // r1.w <- A

#line 162
  add r2.y, -r2.x, l(1.000000)
  mad r2.xyz, r3.xyzx, r2.yyyy, r2.xxxx
  min r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r1.xyz, -r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r1.x <- <CMYKToRGB_id40 return value>.x; r1.y <- <CMYKToRGB_id40 return value>.y; r1.z <- <CMYKToRGB_id40 return value>.z

#line 255
  break 

#line 256
  default 
  break 
endswitch   // r1.x <- c.x; r1.y <- c.y; r1.z <- c.z; r1.w <- c.w

#line 266
add r1.xyzw, -r0.xyzw, r1.xyzw
mad o0.xyzw, cb0[0].xyzw, r1.xyzw, r0.xyzw

#line 275
ret 
// Approximately 189 instruction slots used
***************************
*************************/
static const float Epsilon_id92 = 0.0000000596;
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id99;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
    float4x4 Transform0_id94;
    float4x4 Transform1_id95;
    float4x4 Transform2_id96;
    float4x4 Transform3_id97;
    int type_id98;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float3 HUEtoRGB_id36(in float H)
{
    H = frac(H);
    float R = abs(H * 6 - 3) - 1;
    float G = 2 - abs(H * 6 - 2);
    float B = 2 - abs(H * 6 - 4);
    return saturate(float3(R, G, B));
}
float3 RGBtoHCV_id45(in float3 RGB)
{
    float4 P = (RGB.g < RGB.b) ? float4(RGB.bg, -1.0, 2.0 / 3.0) : float4(RGB.gb, 0.0, -1.0 / 3.0);
    float4 Q = (RGB.r < P.x) ? float4(P.xyw, RGB.r) : float4(RGB.r, P.yzx);
    float C = Q.x - min(Q.w, Q.y);
    float H = abs((Q.w - Q.y) / (6 * C + Epsilon_id92) + Q.z);
    return float3(H, C, Q.x);
}
float3 CMYKToRGB_id40(float4 c)
{
    return 1 - min(1, c.rgb * (1 - c.w) + c.w);
}
float4 RGBToCMYK_id39(float3 c)
{
    float w = max(max(c.r, c.g), c.b);
    return clamp(float4((w - c.rgb) / w, 1.0 - w), 0.00000001, 1.0);
}
float2 TransformUV_id60(float2 uv, float4x4 transform)
{
    return mul(float4((uv.xy * 2 - 1) * float2(1, -1) * 0.5, 0, 1), transform).xy * float2(1, -1) + 0.5;
}
float3 HSLtoRGB_id38(in float3 HSL)
{
    float3 RGB = HUEtoRGB_id36(HSL.x);
    float C = (1 - abs(2 * HSL.z - 1)) * HSL.y;
    return (RGB - 0.5) * C + HSL.z;
}
float3 RGBtoHSL_id47(in float3 RGB)
{
    float3 HCV = RGBtoHCV_id45(RGB);
    float L = HCV.z - HCV.y * 0.5;
    float S = HCV.y / (1 - abs(L * 2 - 1) + Epsilon_id92);
    return float3(HCV.x, S, L);
}
float3 HSVtoRGB_id37(in float3 HSV)
{
    float3 RGB = HUEtoRGB_id36(HSV.x);
    return ((RGB - 1) * HSV.y + 1) * HSV.z;
}
float3 RGBtoHSV_id46(in float3 RGB)
{
    float3 HCV = RGBtoHCV_id45(RGB);
    float S = HCV.y / (HCV.z + Epsilon_id92);
    return float3(HCV.x, S, HCV.z);
}
float4 TransformCMYK_id72(inout PS_STREAMS streams)
{
    float2 uv = streams.TexCoord_id62;
    float C = RGBToCMYK_id39(Texture0_id14.SampleLevel(Sampler0_id52, TransformUV_id60(uv, Transform0_id94), 0).rgb).r;
    float M = RGBToCMYK_id39(Texture0_id14.SampleLevel(Sampler1_id53, TransformUV_id60(uv, Transform1_id95), 0).rgb).g;
    float Y = RGBToCMYK_id39(Texture0_id14.SampleLevel(Sampler2_id54, TransformUV_id60(uv, Transform2_id96), 0).rgb).b;
    float K = RGBToCMYK_id39(Texture0_id14.SampleLevel(Sampler3_id55, TransformUV_id60(uv, Transform3_id97), 0).rgb).a;
    float A = Texture0_id14.SampleLevel(LinearSampler_id44, uv, 0).a;
    return float4(CMYKToRGB_id40(float4(C, M, Y, K)), A);
}
float4 TransformHSLA_id71(inout PS_STREAMS streams)
{
    float2 uv = streams.TexCoord_id62;
    float H = RGBtoHSL_id47(Texture0_id14.SampleLevel(Sampler0_id52, TransformUV_id60(uv, Transform0_id94), 0).rgb).r;
    float S = RGBtoHSL_id47(Texture0_id14.SampleLevel(Sampler1_id53, TransformUV_id60(uv, Transform1_id95), 0).rgb).g;
    float L = RGBtoHSL_id47(Texture0_id14.SampleLevel(Sampler2_id54, TransformUV_id60(uv, Transform2_id96), 0).rgb).b;
    float A = Texture0_id14.SampleLevel(Sampler3_id55, TransformUV_id60(uv, Transform3_id97), 0).a;
    return float4(HSLtoRGB_id38(float3(H, S, L)), A);
}
float4 TransformHSVA_id70(inout PS_STREAMS streams)
{
    float2 uv = streams.TexCoord_id62;
    float H = RGBtoHSV_id46(Texture0_id14.SampleLevel(Sampler0_id52, TransformUV_id60(uv, Transform0_id94), 0).rgb).r;
    float S = RGBtoHSV_id46(Texture0_id14.SampleLevel(Sampler1_id53, TransformUV_id60(uv, Transform1_id95), 0).rgb).g;
    float V = RGBtoHSV_id46(Texture0_id14.SampleLevel(Sampler2_id54, TransformUV_id60(uv, Transform2_id96), 0).rgb).b;
    float A = Texture0_id14.SampleLevel(Sampler3_id55, TransformUV_id60(uv, Transform3_id97), 0).a;
    return float4(HSVtoRGB_id37(float3(H, S, V)), A);
}
float4 TransformRGBA_id69(inout PS_STREAMS streams)
{
    float2 uv = streams.TexCoord_id62;
    float R = Texture0_id14.SampleLevel(Sampler0_id52, TransformUV_id60(uv, Transform0_id94), 0).r;
    float G = Texture0_id14.SampleLevel(Sampler1_id53, TransformUV_id60(uv, Transform1_id95), 0).g;
    float B = Texture0_id14.SampleLevel(Sampler2_id54, TransformUV_id60(uv, Transform2_id96), 0).b;
    float A = Texture0_id14.SampleLevel(Sampler3_id55, TransformUV_id60(uv, Transform3_id97), 0).a;
    return float4(R, G, B, A);
}
float4 Compute_id74()
{
    return InputValue_id99;
}
float4 Filter_id73(inout PS_STREAMS streams, float4 tex0col)
{
    float4 c;
    switch (type_id98)

    {
        case 0:
            c = TransformRGBA_id69(streams);
            break;
        case 1:
            c = TransformHSVA_id70(streams);
            break;
        case 2:
            c = TransformHSLA_id71(streams);
            break;
        case 3:
            c = TransformCMYK_id72(streams);
            break;
    }
    return c;
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id73(streams, col), Compute_id74());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
