/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:64 Y:1 Z:1
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_431363610]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 144]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_4081768635_id13 => input_4081768635
@C    input_1301370092_id14 => input_1301370092
@C    input_3827298800_id15 => input_3827298800
@C    input_3399921919_id16 => input_3399921919
@C    input_3311351993_id17 => input_3311351993
@C    input_4084149407_id18 => input_4084149407
@C    input_3140727368_id19 => input_3140727368
@C    input_1396257543_id20 => input_1396257543
@C    input_3592781609_id21 => input_3592781609
@C    input_190549547_id22 => input_190549547
@C    input_447518577_id23 => input_447518577
@C    input_4280945230_id24 => input_4280945230
@C    input_2707868841_id25 => input_2707868841
@C    input_1287099039_id26 => input_1287099039
@C    input_3951149464_id27 => input_3951149464
@C    input_2184548571_id28 => input_2184548571
@C    input_2996022813_id29 => input_2996022813
***************************
******  Resources    ******
***************************
@R    DynamicBufferInput_739794951_id12 => DynamicBufferInput_739794951 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_431363610 => fb6f636cc15e5b0ac066835c9b50b51c
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCoreMathPCG => e529e3d6e7220073ba1b2dacab9e88b2
***************************
*****     Stages      *****
***************************
@G    Compute => 1bf2ab20544bb94e9308b078175ddc1a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int input_4081768635_id13;         // Offset:   12 Size:     4
//   float input_1301370092_id14;       // Offset:   16 Size:     4 [unused]
//   float3 input_3827298800_id15;      // Offset:   20 Size:    12 [unused]
//   int input_3399921919_id16;         // Offset:   32 Size:     4
//   int input_3311351993_id17;         // Offset:   36 Size:     4
//   float input_4084149407_id18;       // Offset:   40 Size:     4
//   float3 input_3140727368_id19;      // Offset:   48 Size:    12
//   float3 input_1396257543_id20;      // Offset:   64 Size:    12
//   int input_3592781609_id21;         // Offset:   76 Size:     4
//   int input_190549547_id22;          // Offset:   80 Size:     4
//   float3 input_447518577_id23;       // Offset:   84 Size:    12
//   float input_4280945230_id24;       // Offset:   96 Size:     4
//   float4 input_2707868841_id25;      // Offset:  112 Size:    16
//   float input_1287099039_id26;       // Offset:  128 Size:     4
//   float input_3951149464_id27;       // Offset:  132 Size:     4
//   int input_2184548571_id28;         // Offset:  136 Size:     4
//   int input_2996022813_id29;         // Offset:  140 Size:     4
//
// }
//
// Resource bind info for DynamicBufferInput_739794951_id12
// {
//
//   struct Resource10080199
//   {
//       
//       float Age;                     // Offset:    0
//       float LifeTime;                // Offset:    4
//       int Id;                        // Offset:    8
//       float3 PPosition;              // Offset:   12
//       float3 Velocity;               // Offset:   24
//       float Size;                    // Offset:   36
//       float Mass;                    // Offset:   40
//       float4 PColor;                 // Offset:   44
//       int Cycle;                     // Offset:   60
//       float3 Target;                 // Offset:   64
//       float3 AxisX;                  // Offset:   76
//       float3 AxisY;                  // Offset:   88
//       float3 AxisZ;                  // Offset:  100
//       float3 Size3;                  // Offset:  112
//
//   } $Element;                        // Offset:    0 Size:   124
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DynamicBufferInput_739794951_id12        UAV  struct         r/w             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[9], immediateIndexed
dcl_uav_structured u0, 124
dcl_input vThreadID.x
dcl_temps 3
dcl_thread_group 64, 1, 1
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 83 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_c47a63b599b482e8f16d1d995a2cae60.hlsl"
ult r0.x, vThreadID.x, cb0[0].w
if_nz r0.x

#line 84
  ld_structured_indexable(structured_buffer, stride=124)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx  // r0.x <- getBuffer_1174292519.Age; r0.y <- getBuffer_1174292519.LifeTime
  ld_structured_indexable(structured_buffer, stride=124)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(60), u0.xxxx  // r0.z <- getBuffer_1174292519.Cycle

#line 66
  imul null, r1.x, vThreadID.x, l(0x0019660d)
  imul null, r1.yz, cb0[2].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r1.xyz, r1.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r1.x <- v.x; r1.y <- v.y; r1.z <- v.z

#line 67
  imad r2.x, r1.y, r1.z, r1.x  // r2.x <- v.x

#line 68
  imad r2.y, r1.z, r2.x, r1.y  // r2.y <- v.y

#line 69
  imad r2.z, r2.x, r2.y, r1.z  // r2.z <- v.z

#line 70
  ushr r1.xyz, r2.xyzx, l(16, 16, 16, 0)
  xor r1.xyz, r1.xyzx, r2.xyzx  // r1.x <- v.x; r1.y <- v.y; r1.z <- v.z

#line 71
  imad r0.w, r1.y, r1.z, r1.x  // r0.w <- v.x

#line 74
  utof r0.w, r0.w
  mul r0.w, r0.w, l(0.000000)  // r0.w <- <pcg3d_id5 return value>.x

#line 104
  lt r0.w, r0.w, cb0[2].z  // r0.w <- Assign_2095395119

#line 105
  lt r1.x, l(0.000000), r0.x  // r1.x <- Assign_4112388749

#line 106
  ge r0.x, r0.y, r0.x  // r0.x <- Assign_4126925715

#line 107
  and r0.x, r0.x, r1.x  // r0.x <- result_821105071

#line 108
  not r0.x, r0.x  // r0.x <- not_1045510619

#line 109
  and r0.x, r0.x, r0.w  // r0.x <- result_1324915816

#line 115
  if_nz r0.x

#line 66
    imul null, r1.x, vThreadID.x, l(0x0019660d)
    imul null, r1.y, cb0[4].w, l(0x0019660d)
    imul null, r1.z, cb0[5].x, l(0x0019660d)
    iadd r0.xyw, r1.xyxz, l(0x3c6ef35f, 0x3c6ef35f, 0, 0x3c6ef35f)  // r0.x <- v.x; r0.y <- v.y; r0.w <- v.z

#line 67
    imad r1.x, r0.y, r0.w, r0.x  // r1.x <- v.x

#line 68
    imad r1.y, r0.w, r1.x, r0.y  // r1.y <- v.y

#line 69
    imad r1.z, r1.x, r1.y, r0.w  // r1.z <- v.z

#line 70
    ushr r0.xyw, r1.xyxz, l(16, 16, 0, 16)
    xor r0.xyw, r0.xyxw, r1.xyxz  // r0.x <- v.x; r0.y <- v.y; r0.w <- v.z

#line 71
    imad r0.x, r0.y, r0.w, r0.x

#line 72
    imad r0.y, r0.w, r0.x, r0.y

#line 73
    imad r0.w, r0.x, r0.y, r0.w

#line 74
    utof r1.xyz, r0.xywx
    mul r0.xyw, r1.xyxz, l(0.000000, 0.000000, 0.000000, 0.000000)  // r0.x <- <pcg3d_id5 return value>.x; r0.y <- <pcg3d_id5 return value>.y; r0.w <- <pcg3d_id5 return value>.z

#line 120
    add r1.xyz, -cb0[3].xyzx, cb0[4].xyzx
    mad r0.xyw, r0.xyxw, r1.xyxz, cb0[3].xyxz  // r0.x <- lerp_317158489.x; r0.y <- lerp_317158489.y; r0.w <- lerp_317158489.z

#line 66
    imul null, r1.x, vThreadID.x, l(0x0019660d)
    imul null, r1.yz, cb0[8].zzwz, l(0, 0x0019660d, 0x0019660d, 0)
    iadd r1.xyz, r1.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r1.y <- v.y; r1.z <- v.z; r1.x <- v.x

#line 67
    imad r2.x, r1.y, r1.z, r1.x  // r2.x <- v.x

#line 68
    imad r2.y, r1.z, r2.x, r1.y  // r2.y <- v.y

#line 69
    imad r2.z, r2.x, r2.y, r1.z  // r2.z <- v.z

#line 70
    ushr r1.xyz, r2.xyzx, l(16, 16, 16, 0)
    xor r1.xyz, r1.xyzx, r2.xyzx  // r1.y <- v.y; r1.z <- v.z; r1.x <- v.x

#line 71
    imad r1.x, r1.y, r1.z, r1.x

#line 74
    utof r1.x, r1.x
    mul r1.x, r1.x, l(0.000000)  // r1.x <- <pcg3d_id5 return value>.x

#line 129
    add r1.y, -cb0[8].x, cb0[8].y
    mad r1.y, r1.x, r1.y, cb0[8].x  // r1.y <- lerp_4251999291

#line 132
    iadd r2.w, r0.z, l(1)  // r2.w <- result_1876705310

#line 145
    mov r1.x, l(0.000010)
    mov r1.z, vThreadID.x
    mov r1.w, r0.x
    store_structured u0.xyzw, vThreadID.x, l(0), r1.xyzw
    mov r1.xy, r0.ywyy
    mov r1.zw, cb0[5].yyyz
    store_structured u0.xyzw, vThreadID.x, l(16), r1.xyzw
    mov r1.x, cb0[5].w
    mov r1.y, cb0[6].x
    mov r1.z, l(1.000000)
    mov r1.w, cb0[7].x
    store_structured u0.xyzw, vThreadID.x, l(32), r1.xyzw
    mov r2.xyz, cb0[7].yzwy
    store_structured u0.xyzw, vThreadID.x, l(48), r2.xyzw
    store_structured u0.xyz, vThreadID.x, l(64), r0.xywx
  endif 
endif 

#line 171
ret 
// Approximately 70 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct Resource10080199 
{
    float Age;
    float LifeTime;
    int Id;
    float3 PPosition;
    float3 Velocity;
    float Size;
    float Mass;
    float4 PColor;
    int Cycle;
    float3 Target;
    float3 AxisX;
    float3 AxisY;
    float3 AxisZ;
    float3 Size3;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int input_4081768635_id13;
    float input_1301370092_id14;
    float3 input_3827298800_id15;
    int input_3399921919_id16;
    int input_3311351993_id17;
    float input_4084149407_id18;
    float3 input_3140727368_id19;
    float3 input_1396257543_id20;
    int input_3592781609_id21;
    int input_190549547_id22;
    float3 input_447518577_id23;
    float input_4280945230_id24;
    float4 input_2707868841_id25;
    float input_1287099039_id26;
    float input_3951149464_id27;
    int input_2184548571_id28;
    int input_2996022813_id29;
};
RWStructuredBuffer<Resource10080199> DynamicBufferInput_739794951_id12;
float3 cast33_id7(float3 p)
{
    return p;
}
float cast13_id6(float3 p)
{
    return p.x;
}
float3 pcg3d_id5(uint3 v)
{
    v = v * 1664525 + 1013904223;
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    v = v ^ (v >> 16);
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    return float3(v) * (1.0 / float(0xffffffff));
}
void Compute_id4(inout CS_STREAMS streams)
{
    bool Assign_1430140243 = streams.DispatchThreadId_id1.x >= input_4081768635_id13;
    if (Assign_1430140243)
    {
        return;
    }
    int IndexX_2963031124 = streams.DispatchThreadId_id1.x;
    Resource10080199 getBuffer_1174292519 = DynamicBufferInput_739794951_id12[IndexX_2963031124];
    float age_1025773297 = getBuffer_1174292519.Age;
    float lifetime_4126371003 = getBuffer_1174292519.LifeTime;
    int id_3977851781 = getBuffer_1174292519.Id;
    float3 pposition_2348068095 = getBuffer_1174292519.PPosition;
    float3 velocity_2372255410 = getBuffer_1174292519.Velocity;
    float size_2276051380 = getBuffer_1174292519.Size;
    float mass_3740308398 = getBuffer_1174292519.Mass;
    float4 pcolor_3644104368 = getBuffer_1174292519.PColor;
    int cycle_3144253098 = getBuffer_1174292519.Cycle;
    float3 target_4122923021 = getBuffer_1174292519.Target;
    float deltatime_2817416795 = 0;
    deltatime_2817416795 = input_1301370092_id14;
    int3 index_3784446720 = int3(0, 0, 0);
    index_3784446720 = streams.DispatchThreadId_id1;
    float3 resourcescale_342669989 = float3(0, 0, 0);
    resourcescale_342669989 = input_3827298800_id15;
    int3 Int3Join_2526019990 = int3(streams.DispatchThreadId_id1.x, input_3399921919_id16, input_3311351993_id17);
    float3 pcg3d_3072438258 = pcg3d_id5(Int3Join_2526019990);
    float cast13_2406747564 = cast13_id6(pcg3d_3072438258);
    bool Assign_2095395119 = cast13_2406747564 < input_4084149407_id18;
    bool Assign_4112388749 = age_1025773297 > 0;
    bool Assign_4126925715 = age_1025773297 <= lifetime_4126371003;
    bool result_821105071 = (Assign_4112388749 && Assign_4126925715);
    bool not_1045510619 = !result_821105071;
    bool result_1324915816 = (Assign_2095395119 && not_1045510619);
    bool not_2828893478 = !result_1324915816;
    if (not_2828893478)
    {
        return;
    }
    age_1025773297 = 1E-05;
    id_3977851781 = streams.DispatchThreadId_id1.x;
    int3 Int3Join_375894522 = int3(streams.DispatchThreadId_id1.x, input_3592781609_id21, input_190549547_id22);
    float3 pcg3d_1861318978 = pcg3d_id5(Int3Join_375894522);
    float3 cast33_2102062268 = cast33_id7(pcg3d_1861318978);
    float3 lerp_317158489 = lerp(input_3140727368_id19, input_1396257543_id20, cast33_2102062268);
    pposition_2348068095 = lerp_317158489;
    velocity_2372255410 = input_447518577_id23;
    size_2276051380 = input_4280945230_id24;
    mass_3740308398 = 1;
    pcolor_3644104368 = input_2707868841_id25;
    int3 Int3Join_1783215064 = int3(streams.DispatchThreadId_id1.x, input_2184548571_id28, input_2996022813_id29);
    float3 pcg3d_2332336884 = pcg3d_id5(Int3Join_1783215064);
    float cast13_1371821166 = cast13_id6(pcg3d_2332336884);
    float lerp_4251999291 = lerp(input_1287099039_id26, input_3951149464_id27, cast13_1371821166);
    lifetime_4126371003 = lerp_4251999291;
    age_1025773297 = 1E-05;
    int result_1876705310 = (cycle_3144253098 + 1);
    cycle_3144253098 = result_1876705310;
    target_4122923021 = lerp_317158489;
    getBuffer_1174292519.Age = age_1025773297;
    getBuffer_1174292519.LifeTime = lifetime_4126371003;
    getBuffer_1174292519.Id = id_3977851781;
    getBuffer_1174292519.PPosition = pposition_2348068095;
    getBuffer_1174292519.Velocity = velocity_2372255410;
    getBuffer_1174292519.Size = size_2276051380;
    getBuffer_1174292519.Mass = mass_3740308398;
    getBuffer_1174292519.PColor = pcolor_3644104368;
    getBuffer_1174292519.Cycle = cycle_3144253098;
    getBuffer_1174292519.Target = target_4122923021;
    DynamicBufferInput_739794951_id12[IndexX_2963031124] = getBuffer_1174292519;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(64, 1, 1)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 64;
    streams.ThreadCountY_id8 = 1;
    streams.ThreadCountZ_id9 = 1;
    streams.ThreadCountPerGroup_id5 = 64 * 1 * 1;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
