/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1588500295]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 144]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_2286105837_id19 => input_2286105837
@C    input_1487151588_id20 => input_1487151588
@C    input_1076474600_id21 => input_1076474600
@C    input_649862013_id22 => input_649862013
@C    input_1882699846_id23 => input_1882699846
@C    input_462791987_id24 => input_462791987
@C    input_1928778783_id25 => input_1928778783
@C    input_3145851959_id26 => input_3145851959
@C    input_2793655429_id27 => input_2793655429
@C    input_2864602045_id28 => input_2864602045
@C    input_979354314_id29 => input_979354314
@C    input_2650796440_id30 => input_2650796440
@C    input_1283468974_id31 => input_1283468974
@C    input_3753236095_id32 => input_3753236095
***************************
******  Resources    ******
***************************
@R    SamplerInput_759005265_id15 => SamplerInput_759005265 [Stage: Compute, Slot: (0-0)]
@R    SamplerInput_4262113912_id16 => SamplerInput_4262113912 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_2669864248_id12 => TextureInput_2669864248 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_2510865218_id13 => TextureInput_2510865218 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_1532599638_id14 => TextureInput_1532599638 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_1226110717_id17 => TextureInput_1226110717 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_3152934427_id18 => TextureInput_3152934427 [Stage: Compute, Slot: (1-1)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1588500295 => 049e1418aa3a7a69da73e58dba32a9a3
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
***************************
*****     Stages      *****
***************************
@G    Compute => d92cbb7fd7ba2ab1d5a54036da1ad8dd
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_2286105837_id19;        // Offset:   16 Size:    12
//   float input_1487151588_id20;       // Offset:   28 Size:     4 [unused]
//   float3 input_1076474600_id21;      // Offset:   32 Size:    12 [unused]
//   bool input_649862013_id22;         // Offset:   44 Size:     4
//   float input_1882699846_id23;       // Offset:   48 Size:     4
//   float input_462791987_id24;        // Offset:   52 Size:     4
//   int3 input_1928778783_id25;        // Offset:   64 Size:    12
//   int3 input_3145851959_id26;        // Offset:   80 Size:    12
//   float input_2793655429_id27;       // Offset:   92 Size:     4
//   float input_2864602045_id28;       // Offset:   96 Size:     4
//   float input_979354314_id29;        // Offset:  100 Size:     4
//   int3 input_2650796440_id30;        // Offset:  112 Size:    12
//   int3 input_1283468974_id31;        // Offset:  128 Size:    12
//   float input_3753236095_id32;       // Offset:  140 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_759005265_id15       sampler      NA          NA             s0      1 
// SamplerInput_4262113912_id16      sampler      NA          NA             s1      1 
// TextureInput_2669864248_id12      texture  float4          3d             t0      1 
// TextureInput_2510865218_id13      texture   float          3d             t1      1 
// TextureInput_1532599638_id14      texture   float          3d             t2      1 
// TextureInput_1226110717_id17          UAV  float4          3d             u0      1 
// TextureInput_3152934427_id18          UAV   float          3d             u1      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[9], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_uav_typed_texture3d (float,float,float,float) u1
dcl_input vThreadID.xyz
dcl_temps 3
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 56 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_7f3fc353c6f7f4c49a7bc92593c8a53e.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_536001411; r0.y <- Assign_3859735600; r0.z <- Assign_42903651

#line 57
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_1581015312

#line 62
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyz, r0.xyzw, t0.xyzw  // r1.x <- velocity_2_169094072.x; r1.y <- velocity_2_169094072.y; r1.z <- velocity_2_169094072.z

#line 63
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- obstacle_480588738

#line 71
  lt r0.x, l(0.000000), r0.x  // r0.x <- Assign_1453806765

#line 72
  ine r0.y, cb0[2].w, l(0)
  or r0.x, r0.x, r0.y  // r0.x <- result_211996662

#line 73
  utof r0.yzw, vThreadID.xxyz

#line 75
  mul r1.w, cb0[3].y, cb0[3].x  // r1.w <- result_3684270034

#line 77
  mad r1.xyz, -r1.xyzx, r1.wwww, r0.yzwy  // r1.x <- result_3194835987.x; r1.y <- result_3194835987.y; r1.z <- result_3194835987.z

#line 78
  itof r2.xyz, cb0[4].xyzx

#line 79
  add r2.xyz, r2.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- result_648551594.x; r2.y <- result_648551594.y; r2.z <- result_648551594.z

#line 80
  max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r1.xyz, r2.xyzx, r1.xyzx  // r1.x <- clamp_1653036449.x; r1.y <- clamp_1653036449.y; r1.z <- clamp_1653036449.z

#line 81
  add r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r1.x <- result_1704209169.x; r1.y <- result_1704209169.y; r1.z <- result_1704209169.z

#line 82
  itof r2.xyz, cb0[5].xyzx

#line 83
  div r1.xyz, r1.xyzx, r2.xyzx  // r1.x <- result_2176857751.x; r1.y <- result_2176857751.y; r1.z <- result_2176857751.z

#line 84
  sample_l_indexable(texture3d)(float,float,float,float) r2.xyzw, r1.xyzx, t0.xyzw, s0, l(0.000000)  // r2.x <- textureNode_3557819840.x; r2.y <- textureNode_3557819840.y; r2.z <- textureNode_3557819840.z; r2.w <- textureNode_3557819840.w

#line 86
  mul r1.x, r1.w, cb0[5].w  // r1.x <- result_2136703463

#line 88
  mad r1.xyzw, -r2.xyzw, r1.xxxx, r2.xyzw  // r1.x <- result_539686757.x; r1.y <- result_539686757.y; r1.z <- result_539686757.z; r1.w <- result_539686757.w

#line 93
  movc r1.xyzw, r0.xxxx, l(0,0,0,0), r1.xyzw  // r1.x <- output_181591810.x; r1.y <- output_181591810.y; r1.z <- output_181591810.z; r1.w <- output_181591810.w

#line 99
  mul r2.x, cb0[6].y, cb0[6].x  // r2.x <- result_1270368155

#line 101
  mad r0.yzw, -r1.xxyz, r2.xxxx, r0.yyzw  // r0.y <- result_172647036.x; r0.z <- result_172647036.y; r0.w <- result_172647036.z

#line 102
  itof r2.yzw, cb0[7].xxyz

#line 103
  add r2.yzw, r2.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)  // r2.y <- result_3020621123.x; r2.z <- result_3020621123.y; r2.w <- result_3020621123.z

#line 104
  max r0.yzw, r0.yyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r0.yzw, r2.yyzw, r0.yyzw  // r0.y <- clamp_2438742522.x; r0.z <- clamp_2438742522.y; r0.w <- clamp_2438742522.z

#line 105
  add r0.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)  // r0.y <- result_2651754682.x; r0.z <- result_2651754682.y; r0.w <- result_2651754682.z

#line 106
  itof r2.yzw, cb0[8].xxyz

#line 107
  div r0.yzw, r0.yyzw, r2.yyzw  // r0.y <- result_203338224.x; r0.z <- result_203338224.y; r0.w <- result_203338224.z

#line 108
  sample_l_indexable(texture3d)(float,float,float,float) r0.y, r0.yzwy, t2.yxzw, s1, l(0.000000)  // r0.y <- textureNode_3500621319

#line 110
  mul r0.z, r2.x, cb0[8].w  // r0.z <- result_2368512910

#line 112
  mad r0.y, -r0.y, r0.z, r0.y  // r0.y <- result_684750268

#line 117
  movc r0.x, r0.x, l(0), r0.y  // r0.x <- output_3303996495

#line 119
  store_uav_typed u0.xyzw, vThreadID.xyzz, r1.xyzw

#line 120
  store_uav_typed u1.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 146
ret 
// Approximately 42 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_2286105837_id19;
    float input_1487151588_id20;
    float3 input_1076474600_id21;
    bool input_649862013_id22;
    float input_1882699846_id23;
    float input_462791987_id24;
    int3 input_1928778783_id25;
    int3 input_3145851959_id26;
    float input_2793655429_id27;
    float input_2864602045_id28;
    float input_979354314_id29;
    int3 input_2650796440_id30;
    int3 input_1283468974_id31;
    float input_3753236095_id32;
};
Texture3D<float4> TextureInput_2669864248_id12;
Texture3D<float> TextureInput_2510865218_id13;
Texture3D<float> TextureInput_1532599638_id14;
SamplerState SamplerInput_759005265_id15;
SamplerState SamplerInput_4262113912_id16;
RWTexture3D<float4> TextureInput_1226110717_id17;
RWTexture3D<float> TextureInput_3152934427_id18;
float3 cast33_id5(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_2247141374 = streams.DispatchThreadId_id1.x;
    int inputX_1046803885 = input_2286105837_id19.x;
    bool Assign_536001411 = DispatchThreadIdX_2247141374 >= inputX_1046803885;
    int DispatchThreadIdY_717330578 = streams.DispatchThreadId_id1.y;
    int inputY_3027621359 = input_2286105837_id19.y;
    bool Assign_3859735600 = DispatchThreadIdY_717330578 >= inputY_3027621359;
    int DispatchThreadIdZ_2793580973 = streams.DispatchThreadId_id1.z;
    int inputZ_1984482882 = input_2286105837_id19.z;
    bool Assign_42903651 = DispatchThreadIdZ_2793580973 >= inputZ_1984482882;
    bool result_1581015312 = (Assign_536001411 || Assign_3859735600 || Assign_42903651);
    if (result_1581015312)
    {
        return;
    }
    float4 velocity_2_169094072 = TextureInput_2669864248_id12[streams.DispatchThreadId_id1];
    float obstacle_480588738 = TextureInput_2510865218_id13[streams.DispatchThreadId_id1];
    float density_2716743372 = TextureInput_1532599638_id14[streams.DispatchThreadId_id1];
    float deltatime_2262027607 = 0;
    deltatime_2262027607 = input_1487151588_id20;
    int3 index_1257367548 = int3(0, 0, 0);
    index_1257367548 = streams.DispatchThreadId_id1;
    float3 resourcescale_3094376077 = float3(0, 0, 0);
    resourcescale_3094376077 = input_1076474600_id21;
    bool Assign_1453806765 = obstacle_480588738 > 0;
    bool result_211996662 = (input_649862013_id22 || Assign_1453806765);
    float3 cast33_1633268714 = cast33_id5(streams.DispatchThreadId_id1);
    float3 VelocityXyz_3695272330 = velocity_2_169094072.xyz;
    float result_3684270034 = (input_1882699846_id23 * input_462791987_id24);
    float3 result_3356085222 = (VelocityXyz_3695272330 * result_3684270034);
    float3 result_3194835987 = (cast33_1633268714 - result_3356085222);
    float3 cast33_321283605 = cast33_id5(input_1928778783_id25);
    float3 result_648551594 = (cast33_321283605 - float3(1, 1, 1));
    float3 clamp_1653036449 = clamp(result_3194835987, float3(0, 0, 0), result_648551594);
    float3 result_1704209169 = (clamp_1653036449 + float3(0.5, 0.5, 0.5));
    float3 cast33_3891234539 = cast33_id5(input_3145851959_id26);
    float3 result_2176857751 = (result_1704209169 / cast33_3891234539);
    float4 textureNode_3557819840 = TextureInput_2669864248_id12.SampleLevel(SamplerInput_759005265_id15, result_2176857751, 0);
    float4 result_3798804465 = (float4(0, 0, 0, 0) - textureNode_3557819840);
    float result_2136703463 = (input_2793655429_id27 * result_3684270034);
    float4 result_1983958497 = (result_3798804465 * result_2136703463);
    float4 result_539686757 = (textureNode_3557819840 + result_1983958497);
    float4 output_181591810 = result_539686757;
    if (result_211996662)
    {
        output_181591810 = float4(0, 0, 0, 0);
    }
    velocity_2_169094072 = output_181591810;
    bool Assign_1862641924 = obstacle_480588738 > 0;
    bool result_3385295501 = (input_649862013_id22 || Assign_1862641924);
    float3 cast33_1483889089 = cast33_id5(streams.DispatchThreadId_id1);
    float3 VelocityXyz_722786019 = velocity_2_169094072.xyz;
    float result_1270368155 = (input_2864602045_id28 * input_979354314_id29);
    float3 result_19752909 = (VelocityXyz_722786019 * result_1270368155);
    float3 result_172647036 = (cast33_1483889089 - result_19752909);
    float3 cast33_1637852476 = cast33_id5(input_2650796440_id30);
    float3 result_3020621123 = (cast33_1637852476 - float3(1, 1, 1));
    float3 clamp_2438742522 = clamp(result_172647036, float3(0, 0, 0), result_3020621123);
    float3 result_2651754682 = (clamp_2438742522 + float3(0.5, 0.5, 0.5));
    float3 cast33_2186080228 = cast33_id5(input_1283468974_id31);
    float3 result_203338224 = (result_2651754682 / cast33_2186080228);
    float textureNode_3500621319 = TextureInput_1532599638_id14.SampleLevel(SamplerInput_4262113912_id16, result_203338224, 0);
    float result_1847920778 = (0 - textureNode_3500621319);
    float result_2368512910 = (input_3753236095_id32 * result_1270368155);
    float result_711097162 = (result_1847920778 * result_2368512910);
    float result_684750268 = (textureNode_3500621319 + result_711097162);
    float output_3303996495 = result_684750268;
    if (result_3385295501)
    {
        output_3303996495 = 0;
    }
    density_2716743372 = output_3303996495;
    TextureInput_1226110717_id17[streams.DispatchThreadId_id1] = velocity_2_169094072;
    TextureInput_3152934427_id18[streams.DispatchThreadId_id1] = density_2716743372;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
