/**************************
***** Compiler Parameters *****
***************************
@P EffectName: Shader_671181351
***************************
****  ConstantBuffers  ****
***************************
cbuffer Inputs [Size: 96]
@C    input_1061192984_id39 => input_1061192984
@C    input_1440447448_id40 => input_1440447448
@C    input_3153360203_id41 => input_3153360203
@C    input_141605315_id42 => input_141605315
cbuffer PerDraw [Size: 416]
@C    World_id24 => Transformation.World
@C    WorldInverse_id25 => Transformation.WorldInverse
@C    WorldInverseTranspose_id26 => Transformation.WorldInverseTranspose
@C    WorldView_id27 => Transformation.WorldView
@C    WorldViewInverse_id28 => Transformation.WorldViewInverse
@C    WorldViewProjection_id29 => Transformation.WorldViewProjection
@C    WorldScale_id30 => Transformation.WorldScale
@C    EyeMS_id31 => Transformation.EyeMS
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    SamplerInput_436878216_id38 => SamplerInput_436878216 [Stage: Pixel, Slot: (0-0)]
@R    TextureInput_2532546584_id37 => TextureInput_2532546584 [Stage: Pixel, Slot: (0-0)]
@R    Inputs => Inputs [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Shader_671181351 => 104babdd752b2cb70986698e7eb2bdbc
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    NormalStream => ea68512133899a045766d21afb59733a
***************************
*****     Stages      *****
***************************
@G    Vertex => 9274efd9116d5ab7a947f1996630bc3c
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id24;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id25;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id26;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id27;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id28;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id29; // Offset:  320 Size:    64
//   float3 WorldScale_id30;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id31;                 // Offset:  400 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyzw        1     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.Position_id14.x; v0.y <- __input__.Position_id14.y; v0.z <- __input__.Position_id14.z; v0.w <- __input__.Position_id14.w; 
//   v1.x <- __input__.meshNormal_id32.x; v1.y <- __input__.meshNormal_id32.y; v1.z <- __input__.meshNormal_id32.z; 
//   o1.x <- <VSMain return value>.Position_id14.x; o1.y <- <VSMain return value>.Position_id14.y; o1.z <- <VSMain return value>.Position_id14.z; o1.w <- <VSMain return value>.Position_id14.w; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 140 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_671181351_a4e60420f69660391b607038857d3b38.hlsl"
dp4 o0.x, v0.xyzw, cb0[20].xyzw
dp4 o0.y, v0.xyzw, cb0[21].xyzw
dp4 o0.z, v0.xyzw, cb0[22].xyzw
dp4 o0.w, v0.xyzw, cb0[23].xyzw

#line 149
mov o1.xyzw, v0.xyzw
ret 
// Approximately 6 instruction slots used
@G    Pixel => cfcb177a52429fea15bea5d91af7d1d1
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Inputs
// {
//
//   float4x4 input_1061192984_id39;    // Offset:    0 Size:    64
//   float2 input_1440447448_id40;      // Offset:   64 Size:     8
//   float input_3153360203_id41;       // Offset:   72 Size:     4
//   float4 input_141605315_id42;       // Offset:   80 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_436878216_id38       sampler      NA          NA             s0      1 
// TextureInput_2532546584_id37      texture  float4          2d             t0      1 
// Inputs                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// POSITION                 0   xyzw        1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[6], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.Position_id14.x; v1.y <- __input__.Position_id14.y; v1.z <- __input__.Position_id14.z; v1.w <- __input__.Position_id14.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 71 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_671181351_a4e60420f69660391b607038857d3b38.hlsl"
max r0.x, |v1.x|, |v1.z|
div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
min r0.y, |v1.x|, |v1.z|
mul r0.x, r0.x, r0.y
mul r0.y, r0.x, r0.x
mad r0.z, r0.y, l(0.020835), l(-0.085133)
mad r0.z, r0.y, r0.z, l(0.180141)
mad r0.z, r0.y, r0.z, l(-0.330299)
mad r0.y, r0.y, r0.z, l(0.999866)
mul r0.z, r0.y, r0.x
mad r0.z, r0.z, l(-2.000000), l(1.570796)
lt r0.w, |v1.x|, |v1.z|
and r0.z, r0.w, r0.z
mad r0.x, r0.x, r0.y, r0.z
lt r0.y, v1.x, -v1.x
and r0.y, r0.y, l(0xc0490fdb)
add r0.x, r0.y, r0.x
min r0.y, v1.x, v1.z
lt r0.y, r0.y, -r0.y
max r0.z, v1.x, v1.z
ge r0.z, r0.z, -r0.z
and r0.y, r0.z, r0.y
movc r0.x, r0.y, -r0.x, r0.x  // r0.x <- atan2_1732250282

#line 72
mul r0.x, r0.x, l(0.159155)  // r0.x <- result_721537398

#line 74
frc r0.x, r0.x  // r0.x <- frac_3960703073

#line 83
add r0.x, r0.x, l(0.500000)  // r0.x <- result_3108569234

#line 84
frc r0.x, r0.x  // r0.x <- frac_2981021670

#line 89
mul r0.x, r0.x, l(6.283185)  // r0.x <- result_91987578

#line 90
sincos r0.x, r1.x, r0.x  // r1.x <- cos_2479054053; r0.x <- sin_985451177

#line 76
dp3 r0.y, v1.xyzx, v1.xyzx
sqrt r0.y, r0.y  // r0.y <- length_2039779104

#line 77
div r0.y, v1.y, r0.y  // r0.y <- result_1223746101

#line 78
mad r0.z, |r0.y|, l(-0.018729), l(0.074261)
mad r0.z, r0.z, |r0.y|, l(-0.212114)
mad r0.z, r0.z, |r0.y|, l(1.570729)
add r0.w, -|r0.y|, l(1.000000)
lt r0.y, r0.y, -r0.y
sqrt r0.w, r0.w
mul r1.y, r0.w, r0.z
mad r1.y, r1.y, l(-2.000000), l(3.141593)
and r0.y, r0.y, r1.y
mad r0.y, r0.z, r0.w, r0.y

#line 79
add r0.y, -r0.y, l(3.141593)  // r0.y <- result_3033521079

#line 86
mad r0.y, -r0.y, l(0.318310), l(1.000000)  // r0.y <- result_1852623465

#line 93
mad r0.y, r0.y, l(3.141593), l(-1.570796)  // r0.y <- result_4120922842

#line 94
sincos r2.x, r3.x, r0.y  // r3.x <- cos_4009043109; r2.x <- sin_1788155206

#line 95
mul r1.x, r1.x, r3.x  // r1.x <- result_488802765

#line 98
mul r1.z, r0.x, r3.x  // r1.z <- result_3443040821

#line 101
mov r1.y, r2.x
mov r1.w, l(1.000000)
dp4 r0.z, r1.xyzw, cb0[2].xyzw  // r0.z <- mul_1851164053.z
dp4 r0.x, r1.xyzw, cb0[0].xyzw  // r0.x <- mul_1851164053.x
dp4 r0.y, r1.xyzw, cb0[1].xyzw  // r0.y <- mul_1851164053.y

#line 105
max r0.w, |r0.x|, |r0.z|
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
min r1.x, |r0.x|, |r0.z|
mul r0.w, r0.w, r1.x
mul r1.x, r0.w, r0.w
mad r1.y, r1.x, l(0.020835), l(-0.085133)
mad r1.y, r1.x, r1.y, l(0.180141)
mad r1.y, r1.x, r1.y, l(-0.330299)
mad r1.x, r1.x, r1.y, l(0.999866)
mul r1.y, r0.w, r1.x
mad r1.y, r1.y, l(-2.000000), l(1.570796)
lt r1.z, |r0.x|, |r0.z|
and r1.y, r1.z, r1.y
mad r0.w, r0.w, r1.x, r1.y
lt r1.x, r0.x, -r0.x
and r1.x, r1.x, l(0xc0490fdb)
add r0.w, r0.w, r1.x
min r1.x, r0.x, r0.z
lt r1.x, r1.x, -r1.x
max r1.y, r0.x, r0.z

#line 110
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x  // r0.x <- length_4074193966

#line 111
div r0.x, r0.y, r0.x  // r0.x <- result_3780908849

#line 105
ge r0.y, r1.y, -r1.y
and r0.y, r0.y, r1.x
movc r0.y, r0.y, -r0.w, r0.w  // r0.y <- atan2_3048420436

#line 106
mul r0.y, r0.y, l(0.159155)  // r0.y <- result_4016020624

#line 108
frc r1.x, r0.y  // r1.x <- frac_3186770549

#line 112
mad r0.y, |r0.x|, l(-0.018729), l(0.074261)
mad r0.y, r0.y, |r0.x|, l(-0.212114)
mad r0.y, r0.y, |r0.x|, l(1.570729)
add r0.z, -|r0.x|, l(1.000000)
lt r0.x, r0.x, -r0.x
sqrt r0.z, r0.z
mul r0.w, r0.z, r0.y
mad r0.w, r0.w, l(-2.000000), l(3.141593)
and r0.x, r0.x, r0.w
mad r0.x, r0.y, r0.z, r0.x

#line 113
add r0.x, -r0.x, l(3.141593)  // r0.x <- result_2053275007

#line 114
mul r1.y, r0.x, l(0.318310)  // r1.y <- result_3187204101

#line 116
add r0.xy, r1.xyxx, l(-0.375000, -0.250000, 0.000000, 0.000000)  // r0.x <- result_501151590.x; r0.y <- result_501151590.y

#line 120
mad r0.xy, r0.xyxx, l(8.000000, 4.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)  // r0.x <- result_3896859584.x; r0.y <- result_3896859584.y

#line 121
div r0.xy, r0.xyxx, cb0[4].xyxx  // r0.x <- result_3968618848.x; r0.y <- result_3968618848.y

#line 122
add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // r0.x <- result_4194017352.x; r0.y <- result_4194017352.y

#line 123
mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)  // r0.x <- result_1688158618.x; r0.y <- result_1688158618.y

#line 124
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyxx, t0.xyzw, s0  // r0.x <- textureNode_3999172720.x; r0.y <- textureNode_3999172720.y; r0.z <- textureNode_3999172720.z; r0.w <- textureNode_3999172720.w

#line 126
eq r1.x, r0.w, cb0[4].z  // r1.x <- Assign_147875736

#line 127
movc o0.xyzw, r1.xxxx, cb0[5].xyzw, r0.xyzw

#line 131
ret 
// Approximately 102 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float4 Position_id14;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
};
struct VS_STREAMS 
{
    float4 Position_id14;
    float3 meshNormal_id32;
    float4 PositionWS_id15;
    float3 normalWS_id35;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
};
struct VS_INPUT 
{
    float4 Position_id14 : POSITION;
    float3 meshNormal_id32 : NORMAL;
};
cbuffer Inputs 
{
    float4x4 input_1061192984_id39;
    float2 input_1440447448_id40;
    float input_3153360203_id41;
    float4 input_141605315_id42;
};
cbuffer PerDraw 
{
    float4x4 World_id24;
    float4x4 WorldInverse_id25;
    float4x4 WorldInverseTranspose_id26;
    float4x4 WorldView_id27;
    float4x4 WorldViewInverse_id28;
    float4x4 WorldViewProjection_id29;
    float3 WorldScale_id30;
    float4 EyeMS_id31;
};
cbuffer PerView 
{
    float4x4 View_id17;
    float4x4 ViewInverse_id18;
    float4x4 Projection_id19;
    float4x4 ProjectionInverse_id20;
    float4x4 ViewProjection_id21;
    float2 ProjScreenRay_id22;
    float4 Eye_id23;
};
Texture2D TextureInput_2532546584_id37;
SamplerState SamplerInput_436878216_id38;
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    float3 PositionXyz_3610730504 = streams.Position_id14.xyz;
    float3 result_982008492 = (PositionXyz_3610730504 + float3(0, 0, 0));
    float resultZ_2186106373 = result_982008492.z;
    float resultX_2605828632 = result_982008492.x;
    float atan2_1732250282 = atan2(resultZ_2186106373, resultX_2605828632);
    float result_721537398 = (atan2_1732250282 / 6.2831855);
    float result_3362967741 = (result_721537398 + 1);
    float frac_3960703073 = frac(result_3362967741);
    float resultY_2012894297 = result_982008492.y;
    float length_2039779104 = length(result_982008492);
    float result_1223746101 = (resultY_2012894297 / length_2039779104);
    float asin_657269299 = asin(result_1223746101);
    float result_3033521079 = (asin_657269299 + 1.5707964);
    float result_2585795121 = (result_3033521079 / 3.1415927);
    float2 float2Join_3123118044 = float2(frac_3960703073, result_2585795121);
    float float2JoinX_3364588951 = float2Join_3123118044.x;
    float result_3108569234 = (float2JoinX_3364588951 + 0.5);
    float frac_2981021670 = frac(result_3108569234);
    float float2JoinY_3490513993 = float2Join_3123118044.y;
    float result_1852623465 = (1 - float2JoinY_3490513993);
    float2 float2Join_486308803 = float2(frac_2981021670, result_1852623465);
    float float2JoinX_322105645 = float2Join_486308803.x;
    float result_91987578 = (float2JoinX_322105645 * 6.2831855);
    float cos_2479054053 = cos(result_91987578);
    float float2JoinY_2466695079 = float2Join_486308803.y;
    float result_3106773392 = (float2JoinY_2466695079 * 3.1415927);
    float result_4120922842 = (result_3106773392 - 1.5707964);
    float cos_4009043109 = cos(result_4120922842);
    float result_488802765 = (cos_2479054053 * cos_4009043109);
    float sin_1788155206 = sin(result_4120922842);
    float sin_985451177 = sin(result_91987578);
    float result_3443040821 = (cos_4009043109 * sin_985451177);
    float3 Float3Join_610583707 = float3(result_488802765, sin_1788155206, result_3443040821);
    float4 join_3394624716 = float4(Float3Join_610583707, 1);
    float4 mul_1851164053 = mul(join_3394624716, input_1061192984_id39);
    float3 mulXyz_459400350 = mul_1851164053.xyz;
    float mulXyzZ_2073817385 = mulXyz_459400350.z;
    float mulXyzX_2831973534 = mulXyz_459400350.x;
    float atan2_3048420436 = atan2(mulXyzZ_2073817385, mulXyzX_2831973534);
    float result_4016020624 = (atan2_3048420436 / 6.2831855);
    float result_3327507273 = (result_4016020624 + 1);
    float frac_3186770549 = frac(result_3327507273);
    float mulXyzY_531387429 = mulXyz_459400350.y;
    float length_4074193966 = length(mulXyz_459400350);
    float result_3780908849 = (mulXyzY_531387429 / length_4074193966);
    float asin_2712414459 = asin(result_3780908849);
    float result_2053275007 = (asin_2712414459 + 1.5707964);
    float result_3187204101 = (result_2053275007 / 3.1415927);
    float2 float2Join_1307396730 = float2(frac_3186770549, result_3187204101);
    float2 result_501151590 = (float2Join_1307396730 - float2(0.375, 0.25));
    float2 result_4214081587 = (float2(0.625, 0.75) - float2(0.375, 0.25));
    float2 result_3773429585 = (result_501151590 / result_4214081587);
    float2 result_3376342786 = (result_3773429585 * float2(2, 2));
    float2 result_3896859584 = (result_3376342786 - float2(1, 1));
    float2 result_3968618848 = (result_3896859584 / input_1440447448_id40);
    float2 result_4194017352 = (result_3968618848 + float2(1, 1));
    float2 result_1688158618 = (result_4194017352 * float2(0.5, 0.5));
    float4 textureNode_3999172720 = TextureInput_2532546584_id37.Sample(SamplerInput_436878216_id38, result_1688158618);
    float textureNodeW_4187383014 = textureNode_3999172720.w;
    bool Assign_147875736 = textureNodeW_4187383014 == input_3153360203_id41;
    float4 expression_1510846770 = Assign_147875736 ? input_141605315_id42 : textureNode_3999172720;
    streams.ColorTarget_id2 = expression_1510846770;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    streams.meshNormal_id32 = __input__.meshNormal_id32;
    float4 mul_2899512353 = mul(streams.Position_id14, World_id24);
    streams.PositionWS_id15 = mul_2899512353;
    float4 mul_4224526262 = mul(streams.Position_id14, WorldViewProjection_id29);
    streams.ShadingPosition_id0 = mul_4224526262;
    float4 join_2336411027 = float4(streams.meshNormal_id32, 0);
    float4 mul_3938129919 = mul(join_2336411027, WorldInverseTranspose_id26);
    float3 mulXyz_3018913496 = mul_3938129919.xyz;
    streams.normalWS_id35 = mulXyz_3018913496;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.Position_id14 = streams.Position_id14;
    return __output__;
}
