/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin LinearSpreadSampling_Internal_TextureFX [{Center = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}, {Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}, {Phase = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}, {Width = InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>}]
@P Phase: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P Center: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
@P Width: InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 32]
@C    InputValue_id99 => ShaderFX.InputValueFloat4
@C    InputValue_id100 => ShaderFX.InputValueFloat.i1
@C    InputValue_id101 => ShaderFX.InputValueFloat
@C    InputValue_id102 => ShaderFX.InputValueFloat.i2
cbuffer Globals [Size: 96]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
@C    Count_id94 => LinearSpreadSampling_Internal_TextureFX.Count
@C    type_id98 => LinearSpreadSampling_Internal_TextureFX.type
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    LinearSampler_id44 => Texturing.LinearSampler [Stage: Pixel, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (1-1)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (1-1)]
***************************
*****     Sources     *****
***************************
@S    LinearSpreadSampling_Internal_TextureFX => d6b95ead1df8b413106cbdf4b48f0b8e
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    AddonShaderUtils => 0d3496ddd24bfcbde4abd1deae724f64
@S    BlendOperations => 63b352c733fb868f9162fdac1eacd48b
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 573 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_67f712567dc91d254d2f82d096ac6388.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 577
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => c1cd0b01ea1f7d22b39f3066e4de06d4
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id99;            // Offset:    0 Size:    16
//   float InputValue_id100;            // Offset:   16 Size:     4
//   float InputValue_id101;            // Offset:   20 Size:     4
//   float InputValue_id102;            // Offset:   24 Size:     4
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//   int Count_id94;                    // Offset:   80 Size:     4
//      = 0x00000001 
//   int type_id98;                     // Offset:   84 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// LinearSampler_id44                sampler      NA          NA             s0      1 
// Sampler0_id52                     sampler      NA          NA             s1      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// Globals                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_constantbuffer CB1[6], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 20
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 552 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_67f712567dc91d254d2f82d096ac6388.hlsl"
sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s1, l(0.000000)  // r0.x <- <InTex0_id26 return value>.x; r0.y <- <InTex0_id26 return value>.y; r0.z <- <InTex0_id26 return value>.z; r0.w <- <InTex0_id26 return value>.w

#line 545
itof r1.x, cb1[5].x

#line 376
mad r1.y, -cb0[1].z, l(0.500000), cb0[1].x  // r1.y <- range.x

#line 377
mad r1.z, cb0[1].z, l(0.500000), cb0[1].x  // r1.z <- range.y

#line 516
div r1.w, l(0.500000), r1.x
add r1.w, r1.w, cb0[1].y
add r1.z, -r1.y, r1.z

#line 546
mov r2.y, v1.y

#line 154
mov r3.zw, l(0,0,-1.000000,0.666667)
mov r4.zw, l(0,0,0,-0.333333)
mov r5.zw, l(0,0,-1.000000,0.666667)
mov r6.zw, l(0,0,0,-0.333333)
mov r7.zw, l(0,0,-1.000000,0.666667)
mov r8.zw, l(0,0,0,-0.333333)
mov r9.zw, l(0,0,-1.000000,0.666667)
mov r10.zw, l(0,0,0,-0.333333)
mov r11.zw, l(0,0,-1.000000,0.666667)
mov r12.zw, l(0,0,0,-0.333333)

#line 543
mov r13.xyzw, l(0,0,0,0)  // r13.x <- c.x; r13.y <- c.y; r13.z <- c.z; r13.w <- c.w
mov r2.z, l(0)  // r2.z <- i
loop 
  ige r2.w, r2.z, cb1[5].x
  breakc_nz r2.w

#line 545
  itof r2.w, r2.z  // r2.w <- index

#line 516
  div r2.w, r2.w, r1.x
  add r2.w, r1.w, r2.w
  frc r2.w, r2.w
  mad r2.w, r2.w, r1.z, r1.y  // r2.w <- <CreateLinear_id114 return value>

#line 546
  add r2.x, r2.w, v1.x
  sample_l_indexable(texture2d)(float,float,float,float) r14.xyzw, r2.xyxx, t0.xyzw, s0, l(0.000000)  // r14.x <- c1.x; r14.y <- c1.y; r14.z <- c1.z; r14.w <- c1.w

#line 384
  switch cb1[5].y

#line 387
    case l(0)

#line 389
    mov r15.xyz, r14.xyzx  // r15.x <- col.x; r15.y <- col.y; r15.z <- col.z
    break 

#line 390
    case l(1)

#line 367
    add r16.xyz, r13.xyzx, r14.xyzx
    mul r15.xyz, r16.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r15.x <- <Average_id72 return value>.x; r15.y <- <Average_id72 return value>.y; r15.z <- <Average_id72 return value>.z

#line 392
    break 

#line 393
    case l(2)

#line 363
    mul r16.xyz, r13.xyzx, r14.xyzx
    sqrt r15.xyz, r16.xyzx  // r15.x <- <GeometricMean_id73 return value>.x; r15.y <- <GeometricMean_id73 return value>.y; r15.z <- <GeometricMean_id73 return value>.z

#line 395
    break 

#line 396
    case l(3)

#line 210
    min r15.xyz, r13.xyzx, r14.xyzx  // r15.x <- <Darken_id74 return value>.x; r15.y <- <Darken_id74 return value>.y; r15.z <- <Darken_id74 return value>.z

#line 398
    break 

#line 399
    case l(4)

#line 359
    mul r15.xyz, r13.xyzx, r14.xyzx  // r15.x <- <Multiply_id75 return value>.x; r15.y <- <Multiply_id75 return value>.y; r15.z <- <Multiply_id75 return value>.z

#line 401
    break 

#line 402
    case l(5)

#line 202
    eq r16.xyz, r14.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    add r17.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    div r17.xyz, r17.xyzx, r14.xyzx
    add r17.xyz, -r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    max r17.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    movc r15.xyz, r16.xyzx, l(0,0,0,0), r17.xyzx  // r15.x <- <ColorBurn_id76 return value>.x; r15.y <- <ColorBurn_id76 return value>.y; r15.z <- <ColorBurn_id76 return value>.z

#line 404
    break 

#line 405
    case l(6)

#line 355
    add r16.xyz, r13.xyzx, r14.xyzx
    add r15.xyz, r16.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r15.x <- <LinearBurn_id77 return value>.x; r15.y <- <LinearBurn_id77 return value>.y; r15.z <- <LinearBurn_id77 return value>.z

#line 407
    break 

#line 408
    case l(7)

#line 351
    add r2.x, r13.y, r13.x
    add r2.x, r13.z, r2.x
    add r2.w, r14.y, r14.x
    add r2.w, r14.z, r2.w
    lt r2.x, r2.x, r2.w
    movc r15.xyz, r2.xxxx, r13.xyzx, r14.xyzx  // r15.x <- <DarkerColor_id78 return value>.x; r15.y <- <DarkerColor_id78 return value>.y; r15.z <- <DarkerColor_id78 return value>.z

#line 410
    break 

#line 411
    case l(8)

#line 206
    max r15.xyz, r13.xyzx, r14.xyzx  // r15.x <- <Lighten_id79 return value>.x; r15.y <- <Lighten_id79 return value>.y; r15.z <- <Lighten_id79 return value>.z

#line 413
    break 

#line 414
    case l(9)

#line 347
    add r16.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    add r17.xyz, -r14.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mad r15.xyz, -r16.xyzx, r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r15.x <- <Screen_id80 return value>.x; r15.y <- <Screen_id80 return value>.y; r15.z <- <Screen_id80 return value>.z

#line 416
    break 

#line 417
    case l(10)

#line 343
    add r15.xyz, r13.xyzx, r14.xyzx  // r15.x <- <Add_id81 return value>.x; r15.y <- <Add_id81 return value>.y; r15.z <- <Add_id81 return value>.z

#line 419
    break 

#line 420
    case l(11)

#line 339
    add r2.x, r13.y, r13.x
    add r2.x, r13.z, r2.x
    add r2.w, r14.y, r14.x
    add r2.w, r14.z, r2.w
    lt r2.x, r2.w, r2.x
    movc r15.xyz, r2.xxxx, r13.xyzx, r14.xyzx  // r15.x <- <LighterColor_id82 return value>.x; r15.y <- <LighterColor_id82 return value>.y; r15.z <- <LighterColor_id82 return value>.z

#line 422
    break 

#line 423
    case l(12)

#line 162
    eq r16.xyz, r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mul r17.xyz, r14.xyzx, r14.xyzx
    add r18.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    div r17.xyz, r17.xyzx, r18.xyzx
    min r17.xyz, r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r15.xyz, r16.xyzx, r13.xyzx, r17.xyzx  // r15.x <- <Reflect_id87 return value>.x; r15.y <- <Reflect_id87 return value>.y; r15.z <- <Reflect_id87 return value>.z

#line 425
    break 

#line 426
    case l(13)

#line 335
    lt r16.xyz, r13.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r17.xyz, r13.xyzx, r14.xyzx
    add r17.xyz, r17.xyzx, r17.xyzx
    add r18.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    add r18.xyz, r18.xyzx, r18.xyzx
    add r19.xyz, -r14.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mad r18.xyz, -r18.xyzx, r19.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r15.xyz, r16.xyzx, r17.xyzx, r18.xyzx  // r15.x <- <Overlay_id84 return value>.x; r15.y <- <Overlay_id84 return value>.y; r15.z <- <Overlay_id84 return value>.z

#line 428
    break 

#line 429
    case l(14)

#line 331
    add r16.xyz, r13.xyzx, r13.xyzx
    mul r17.xyz, r13.xyzx, r13.xyzx
    mad r17.xyz, r16.xyzx, r14.xyzx, r17.xyzx
    mul r16.xyz, r13.xyzx, r16.xyzx
    mad r15.xyz, -r16.xyzx, r14.xyzx, r17.xyzx  // r15.x <- <Softlight_id85 return value>.x; r15.y <- <Softlight_id85 return value>.y; r15.z <- <Softlight_id85 return value>.z

#line 431
    break 

#line 432
    case l(15)

#line 198
    add r16.xyz, -r14.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    div r15.xyz, r13.xyzx, r16.xyzx  // r15.x <- <ColorDodge_id86 return value>.x; r15.y <- <ColorDodge_id86 return value>.y; r15.z <- <ColorDodge_id86 return value>.z

#line 434
    break 

#line 435
    case l(16)

#line 162
    eq r16.xyz, r14.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mul r17.xyz, r13.xyzx, r13.xyzx
    add r18.xyz, -r14.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    div r17.xyz, r17.xyzx, r18.xyzx
    min r17.xyz, r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r15.xyz, r16.xyzx, l(1.000000,1.000000,1.000000,0), r17.xyzx  // r15.x <- <Reflect_id87 return value>.x; r15.y <- <Reflect_id87 return value>.y; r15.z <- <Reflect_id87 return value>.z

#line 437
    break 

#line 438
    case l(17)

#line 327
    add r16.xyz, r13.xyzx, r14.xyzx
    round_ni r15.xyz, r16.xyzx  // r15.x <- <HardMix_id88 return value>.x; r15.y <- <HardMix_id88 return value>.y; r15.z <- <HardMix_id88 return value>.z

#line 440
    break 

#line 441
    case l(18)

#line 323
    eq r16.xyz, r14.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    add r17.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mul r17.xyz, r17.xyzx, r17.xyzx
    div r17.xyz, r17.xyzx, r14.xyzx
    add r17.xyz, -r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r15.xyz, r16.xyzx, l(0,0,0,0), r17.xyzx  // r15.x <- <Freeze_id89 return value>.x; r15.y <- <Freeze_id89 return value>.y; r15.z <- <Freeze_id89 return value>.z

#line 443
    break 

#line 444
    case l(19)

#line 319
    lt r16.xyz, r14.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    add r17.xyz, r14.xyzx, r14.xyzx

#line 210
    min r17.xyz, r13.xyzx, r17.xyzx  // r17.x <- <Darken_id74 return value>.x; r17.y <- <Darken_id74 return value>.y; r17.z <- <Darken_id74 return value>.z

#line 319
    add r18.xyz, r14.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
    add r18.xyz, r18.xyzx, r18.xyzx

#line 206
    max r18.xyz, r13.xyzx, r18.xyzx  // r18.x <- <Lighten_id79 return value>.x; r18.y <- <Lighten_id79 return value>.y; r18.z <- <Lighten_id79 return value>.z

#line 319
    movc r15.xyz, r16.xyzx, r17.xyzx, r18.xyzx  // r15.x <- <Pinlight_id90 return value>.x; r15.y <- <Pinlight_id90 return value>.y; r15.z <- <Pinlight_id90 return value>.z

#line 446
    break 

#line 447
    case l(20)

#line 315
    lt r16.xyz, r14.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    mul r17.xyz, r13.xyzx, r14.xyzx
    add r17.xyz, r17.xyzx, r17.xyzx
    add r18.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    add r18.xyz, r18.xyzx, r18.xyzx
    add r19.xyz, -r14.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mad r18.xyz, -r18.xyzx, r19.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r15.xyz, r16.xyzx, r17.xyzx, r18.xyzx  // r15.x <- <Hardlight_id91 return value>.x; r15.y <- <Hardlight_id91 return value>.y; r15.z <- <Hardlight_id91 return value>.z

#line 449
    break 

#line 450
    case l(21)

#line 311
    lt r16.xyz, r14.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    add r17.xyz, r14.xyzx, r14.xyzx

#line 202
    eq r18.xyz, r14.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    add r19.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    div r17.xyz, r19.xyzx, r17.xyzx
    add r17.xyz, -r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    max r17.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    movc r17.xyz, r18.xyzx, l(0,0,0,0), r17.xyzx  // r17.x <- <ColorBurn_id76 return value>.x; r17.y <- <ColorBurn_id76 return value>.y; r17.z <- <ColorBurn_id76 return value>.z

#line 311
    add r18.xyz, r14.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)

#line 198
    mad r18.xyz, -r18.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
    div r18.xyz, r13.xyzx, r18.xyzx  // r18.x <- <ColorDodge_id86 return value>.x; r18.y <- <ColorDodge_id86 return value>.y; r18.z <- <ColorDodge_id86 return value>.z

#line 311
    movc r15.xyz, r16.xyzx, r17.xyzx, r18.xyzx  // r15.x <- <VividLight_id92 return value>.x; r15.y <- <VividLight_id92 return value>.y; r15.z <- <VividLight_id92 return value>.z

#line 452
    break 

#line 453
    case l(22)

#line 307
    lt r16.xyz, r14.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    mad r17.xyz, r14.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r13.xyzx
    add r17.xyz, r17.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
    max r17.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    add r18.xyz, r14.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
    mad r18.xyz, r18.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r13.xyzx
    min r18.xyz, r18.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r15.xyz, r16.xyzx, r17.xyzx, r18.xyzx  // r15.x <- <LinearLight_id93 return value>.x; r15.y <- <LinearLight_id93 return value>.y; r15.z <- <LinearLight_id93 return value>.z

#line 455
    break 

#line 456
    case l(23)

#line 303
    add r15.xyz, r13.xyzx, -r14.xyzx

#line 458
    mov r15.xyz, |r15.xyzx|  // r15.x <- col.x; r15.y <- col.y; r15.z <- col.z
    break 

#line 459
    case l(24)

#line 299
    add r16.xyz, r13.xyzx, r14.xyzx
    mul r17.xyz, r13.xyzx, r14.xyzx
    mad r15.xyz, -r17.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r16.xyzx  // r15.x <- <Exclusion_id95 return value>.x; r15.y <- <Exclusion_id95 return value>.y; r15.z <- <Exclusion_id95 return value>.z

#line 461
    break 

#line 462
    case l(25)

#line 295
    add r15.xyz, r13.xyzx, -r14.xyzx  // r15.x <- <Subtract_id96 return value>.x; r15.y <- <Subtract_id96 return value>.y; r15.z <- <Subtract_id96 return value>.z

#line 464
    break 

#line 465
    case l(26)

#line 291
    div r15.xyz, r13.xyzx, r14.xyzx  // r15.x <- <Divide_id97 return value>.x; r15.y <- <Divide_id97 return value>.y; r15.z <- <Divide_id97 return value>.z

#line 467
    break 

#line 468
    case l(27)

#line 287
    add r16.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    add r16.xyz, -r14.xyzx, r16.xyzx
    add r15.xyz, -|r16.xyzx|, l(1.000000, 1.000000, 1.000000, 0.000000)  // r15.x <- <Negation_id98 return value>.x; r15.y <- <Negation_id98 return value>.y; r15.z <- <Negation_id98 return value>.z

#line 470
    break 

#line 471
    case l(28)

#line 283
    sqrt r16.xyz, r13.xyzx
    add r15.xyz, r14.xyzx, -r16.xyzx  // r15.x <- <AdditiveSubstractive_id99 return value>.x; r15.y <- <AdditiveSubstractive_id99 return value>.y; r15.z <- <AdditiveSubstractive_id99 return value>.z

#line 473
    break 

#line 474
    case l(29)

#line 162
    eq r16.xyz, r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mul r17.xyz, r14.xyzx, r14.xyzx
    add r18.xyz, -r13.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    div r17.xyz, r17.xyzx, r18.xyzx
    min r17.xyz, r17.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    movc r16.xyz, r16.xyzx, r13.xyzx, r17.xyzx  // r16.x <- <Reflect_id87 return value>.x; r16.y <- <Reflect_id87 return value>.y; r16.z <- <Reflect_id87 return value>.z

#line 279
    add r15.xyz, -r16.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r15.x <- <Heat_id100 return value>.x; r15.y <- <Heat_id100 return value>.y; r15.z <- <Heat_id100 return value>.z

#line 476
    break 

#line 477
    case l(30)

#line 275
    min r16.xyz, r13.xyzx, r14.xyzx
    max r17.xyz, r13.xyzx, r14.xyzx
    add r16.xyz, r16.xyzx, -r17.xyzx
    add r15.xyz, r16.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r15.x <- <Phoenix_id101 return value>.x; r15.y <- <Phoenix_id101 return value>.y; r15.z <- <Phoenix_id101 return value>.z

#line 479
    break 

#line 480
    case l(31)

#line 271
    add r16.xyz, r13.xyzx, -r14.xyzx
    add r15.xyz, r16.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r15.x <- <GrainExtract_id102 return value>.x; r15.y <- <GrainExtract_id102 return value>.y; r15.z <- <GrainExtract_id102 return value>.z

#line 482
    break 

#line 483
    case l(32)

#line 267
    add r16.xyz, r13.xyzx, -r14.xyzx
    add r15.xyz, r16.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)  // r15.x <- <GrainMerge_id103 return value>.x; r15.y <- <GrainMerge_id103 return value>.y; r15.z <- <GrainMerge_id103 return value>.z

#line 485
    break 

#line 486
    case l(33)

#line 154
    lt r2.x, r13.y, r13.z
    movc r16.xy, r2.xxxx, r13.zyzz, r13.yzyy  // r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y

#line 155
    lt r2.x, r13.x, r16.x
    mov r16.z, r13.x
    movc r16.xyz, r2.xxxx, r16.xyzx, r16.zyxz  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w

#line 156
    min r2.x, r16.y, r16.z
    add r2.x, -r2.x, r16.x  // r2.x <- C; r2.x <- C; r2.x <- C; r2.x <- C; r2.x <- C; r2.x <- C

#line 188
    mad r2.w, -r2.x, l(0.500000), r16.x  // r2.w <- L; r2.w <- L; r2.w <- L; r2.w <- L

#line 154
    lt r15.w, r14.y, r14.z
    mov r3.xy, r14.zyzz
    mov r4.xy, r3.yxyy
    movc r16.xyzw, r15.wwww, r3.xyzw, r4.xyzw  // r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w

#line 155
    lt r3.x, r14.x, r16.x
    mov r17.xyz, r16.xywx
    mov r17.w, r14.x
    mov r16.xyw, r17.wywx
    movc r16.xyzw, r3.xxxx, r17.xyzw, r16.xyzw  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w

#line 156
    min r3.x, r16.y, r16.w
    add r3.x, -r3.x, r16.x  // r3.x <- C; r3.x <- C; r3.x <- C; r3.x <- C; r3.x <- C

#line 157
    add r3.y, -r16.y, r16.w
    mad r3.x, r3.x, l(6.000000), l(0.000000)
    div r3.x, r3.y, r3.x
    add r3.x, r16.z, r3.x

#line 146
    frc r3.x, |r3.x|  // r3.x <- H

#line 149
    mad r16.xyz, r3.xxxx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 150
    mad_sat r16.xyz, |r16.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r16.x <- <HUEtoRGB_id8 return value>.x; r16.y <- <HUEtoRGB_id8 return value>.y; r16.z <- <HUEtoRGB_id8 return value>.z

#line 183
    add r16.xyz, r16.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
    mad r15.xyz, r16.xyzx, r2.xxxx, r2.wwww  // r15.x <- <HSLtoRGB_id10 return value>.x; r15.y <- <HSLtoRGB_id10 return value>.y; r15.z <- <HSLtoRGB_id10 return value>.z

#line 488
    break 

#line 489
    case l(34)

#line 154
    lt r2.x, r13.y, r13.z
    mov r5.xy, r13.zyzz
    mov r6.xy, r5.yxyy
    movc r16.xyzw, r2.xxxx, r5.xyzw, r6.xyzw  // r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w

#line 155
    lt r2.x, r13.x, r16.x
    mov r17.xyz, r16.xywx
    mov r17.w, r13.x
    mov r16.xyw, r17.wywx
    movc r16.xyzw, r2.xxxx, r17.xyzw, r16.xyzw  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w

#line 156
    min r2.x, r16.y, r16.w
    add r2.x, -r2.x, r16.x  // r2.x <- C; r2.x <- C; r2.x <- C; r2.x <- C

#line 157
    add r2.w, -r16.y, r16.w
    mad r2.x, r2.x, l(6.000000), l(0.000000)
    div r2.x, r2.w, r2.x
    add r2.x, r16.z, r2.x

#line 154
    lt r2.w, r14.y, r14.z
    movc r17.xy, r2.wwww, r14.zyzz, r14.yzyy  // r17.x <- P.x; r17.y <- P.y; r17.x <- P.x; r17.y <- P.y; r17.x <- P.x; r17.y <- P.y; r17.x <- P.x; r17.y <- P.y

#line 155
    lt r2.w, r14.x, r17.x
    mov r17.z, r14.x
    movc r16.yzw, r2.wwww, r17.xxyz, r17.zzyx  // r16.y <- Q.x; r16.z <- Q.y; r16.y <- Q.x; r16.z <- Q.y; r16.y <- Q.x; r16.z <- Q.y; r16.y <- Q.x; r16.z <- Q.y

#line 156
    min r2.w, r16.z, r16.w
    add r2.w, -r2.w, r16.y  // r2.w <- C; r2.w <- C; r2.w <- C; r2.w <- C

#line 176
    add r3.x, r16.y, l(0.000000)
    div r2.w, r2.w, r3.x  // r2.w <- S; r2.w <- S

#line 146
    frc r2.x, |r2.x|  // r2.x <- H

#line 149
    mad r16.yzw, r2.xxxx, l(0.000000, 6.000000, 6.000000, 6.000000), l(0.000000, -3.000000, -2.000000, -4.000000)

#line 150
    mad_sat r16.yzw, |r16.yyzw|, l(0.000000, 1.000000, -1.000000, -1.000000), l(0.000000, -1.000000, 2.000000, 2.000000)  // r16.y <- <HUEtoRGB_id8 return value>.x; r16.z <- <HUEtoRGB_id8 return value>.y; r16.w <- <HUEtoRGB_id8 return value>.z

#line 171
    add r16.yzw, r16.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)
    mad r16.yzw, r16.yyzw, r2.wwww, l(0.000000, 1.000000, 1.000000, 1.000000)
    mul r15.xyz, r16.xxxx, r16.yzwy  // r15.x <- <HSVtoRGB_id9 return value>.x; r15.y <- <HSVtoRGB_id9 return value>.y; r15.z <- <HSVtoRGB_id9 return value>.z

#line 491
    break 

#line 492
    case l(35)

#line 154
    lt r2.x, r13.y, r13.z
    movc r16.xy, r2.xxxx, r13.zyzz, r13.yzyy  // r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y

#line 155
    lt r2.x, r13.x, r16.x
    mov r16.z, r13.x
    movc r16.xyz, r2.xxxx, r16.xyzx, r16.zyxz  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w

#line 156
    min r2.x, r16.y, r16.z
    add r2.x, -r2.x, r16.x  // r2.x <- C; r2.x <- C; r2.x <- C; r2.x <- C

#line 188
    mad r2.x, -r2.x, l(0.500000), r16.x  // r2.x <- L; r2.x <- L; r2.x <- L

#line 154
    lt r2.w, r14.y, r14.z
    mov r7.xy, r14.zyzz
    mov r8.xy, r7.yxyy
    movc r16.xyzw, r2.wwww, r7.xyzw, r8.xyzw  // r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w

#line 155
    lt r2.w, r14.x, r16.x
    mov r17.xyz, r16.xywx
    mov r17.w, r14.x
    mov r16.xyw, r17.wywx
    movc r16.xyzw, r2.wwww, r17.xyzw, r16.xyzw  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w

#line 156
    min r2.w, r16.y, r16.w
    add r2.w, -r2.w, r16.x  // r2.w <- C; r2.w <- C; r2.w <- C

#line 157
    add r3.x, -r16.y, r16.w
    mad r3.y, r2.w, l(6.000000), l(0.000000)
    div r3.x, r3.x, r3.y
    add r3.x, r16.z, r3.x

#line 188
    mad r3.y, -r2.w, l(0.500000), r16.x  // r3.y <- L; r3.y <- L

#line 189
    mad r3.y, r3.y, l(2.000000), l(-1.000000)
    add r3.y, -|r3.y|, l(1.000000)
    div r2.w, r2.w, r3.y  // r2.w <- S; r2.w <- S

#line 146
    frc r3.x, |r3.x|  // r3.x <- H

#line 149
    mad r16.xyz, r3.xxxx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 150
    mad_sat r16.xyz, |r16.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r16.x <- <HUEtoRGB_id8 return value>.x; r16.y <- <HUEtoRGB_id8 return value>.y; r16.z <- <HUEtoRGB_id8 return value>.z

#line 182
    mad r3.x, r2.x, l(2.000000), l(-1.000000)
    add r3.x, -|r3.x|, l(1.000000)
    mul r2.w, r2.w, r3.x  // r2.w <- C

#line 183
    add r16.xyz, r16.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
    mad r15.xyz, r16.xyzx, r2.wwww, r2.xxxx  // r15.x <- <HSLtoRGB_id10 return value>.x; r15.y <- <HSLtoRGB_id10 return value>.y; r15.z <- <HSLtoRGB_id10 return value>.z

#line 494
    break 

#line 495
    case l(36)

#line 154
    lt r2.x, r13.y, r13.z
    mov r9.xy, r13.zyzz
    mov r10.xy, r9.yxyy
    movc r16.xyzw, r2.xxxx, r9.xyzw, r10.xyzw  // r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w; r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w

#line 155
    lt r2.x, r13.x, r16.x
    mov r17.xyz, r16.xywx
    mov r17.w, r13.x
    mov r16.xyw, r17.wywx
    movc r16.xyzw, r2.xxxx, r17.xyzw, r16.xyzw  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w

#line 156
    min r2.x, r16.y, r16.w
    add r2.x, -r2.x, r16.x  // r2.x <- C; r2.x <- C

#line 157
    add r2.w, -r16.y, r16.w
    mad r3.x, r2.x, l(6.000000), l(0.000000)
    div r2.w, r2.w, r3.x
    add r2.w, r16.z, r2.w

#line 188
    mad r3.x, -r2.x, l(0.500000), r16.x  // r3.x <- L

#line 189
    mad r3.x, r3.x, l(2.000000), l(-1.000000)
    add r3.x, -|r3.x|, l(1.000000)
    div r2.x, r2.x, r3.x  // r2.x <- S

#line 154
    lt r3.x, r14.y, r14.z
    movc r16.xy, r3.xxxx, r14.zyzz, r14.yzyy  // r16.x <- P.x; r16.y <- P.y; r16.x <- P.x; r16.y <- P.y

#line 155
    lt r3.x, r14.x, r16.x
    mov r16.z, r14.x
    movc r16.xyz, r3.xxxx, r16.xyzx, r16.zyxz  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w; r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.w

#line 156
    min r3.x, r16.y, r16.z
    add r3.x, -r3.x, r16.x  // r3.x <- C; r3.x <- C

#line 188
    mad r3.x, -r3.x, l(0.500000), r16.x  // r3.x <- L

#line 146
    frc r2.w, |r2.w|  // r2.w <- H

#line 149
    mad r16.xyz, r2.wwww, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 150
    mad_sat r16.xyz, |r16.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r16.x <- <HUEtoRGB_id8 return value>.x; r16.y <- <HUEtoRGB_id8 return value>.y; r16.z <- <HUEtoRGB_id8 return value>.z

#line 182
    mad r2.w, r3.x, l(2.000000), l(-1.000000)
    add r2.w, -|r2.w|, l(1.000000)
    mul r2.x, r2.x, r2.w  // r2.x <- C

#line 183
    add r16.xyz, r16.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
    mad r15.xyz, r16.xyzx, r2.xxxx, r3.xxxx  // r15.x <- <HSLtoRGB_id10 return value>.x; r15.y <- <HSLtoRGB_id10 return value>.y; r15.z <- <HSLtoRGB_id10 return value>.z

#line 497
    break 

#line 498
    case l(37)

#line 154
    lt r2.x, r13.y, r13.z
    mov r11.xy, r13.zyzz
    mov r12.xy, r11.yxyy
    movc r16.xyzw, r2.xxxx, r11.xyzw, r12.xyzw  // r16.x <- P.x; r16.y <- P.y; r16.z <- P.z; r16.w <- P.w

#line 155
    lt r2.x, r13.x, r16.x
    mov r17.xyz, r16.xywx
    mov r17.w, r13.x
    mov r16.xyw, r17.wywx
    movc r16.xyzw, r2.xxxx, r17.xyzw, r16.xyzw  // r16.x <- Q.x; r16.y <- Q.y; r16.z <- Q.z; r16.w <- Q.w

#line 156
    min r2.x, r16.y, r16.w
    add r2.x, -r2.x, r16.x  // r2.x <- C

#line 157
    add r2.w, -r16.y, r16.w
    mad r3.x, r2.x, l(6.000000), l(0.000000)
    div r2.w, r2.w, r3.x
    add r2.w, r16.z, r2.w

#line 176
    add r3.x, r16.x, l(0.000000)
    div r2.x, r2.x, r3.x  // r2.x <- S

#line 154
    max r3.x, r14.z, r14.y  // r3.x <- P.x

#line 155
    max r3.x, r3.x, r14.x  // r3.x <- Q.x

#line 146
    frc r2.w, |r2.w|  // r2.w <- H

#line 149
    mad r16.xyz, r2.wwww, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 150
    mad_sat r16.xyz, |r16.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r16.x <- <HUEtoRGB_id8 return value>.x; r16.y <- <HUEtoRGB_id8 return value>.y; r16.z <- <HUEtoRGB_id8 return value>.z

#line 171
    add r16.xyz, r16.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
    mad r16.xyz, r16.xyzx, r2.xxxx, l(1.000000, 1.000000, 1.000000, 0.000000)
    mul r15.xyz, r3.xxxx, r16.xyzx  // r15.x <- <HSVtoRGB_id9 return value>.x; r15.y <- <HSVtoRGB_id9 return value>.y; r15.z <- <HSVtoRGB_id9 return value>.z

#line 500
    break 

#line 501
    case l(38)

#line 503
    mov r15.x, r14.x  // r15.x <- col.x
    mov r15.yz, r13.yyzy  // r15.y <- col.y; r15.z <- col.z
    break 

#line 504
    case l(39)

#line 506
    mov r15.xz, r13.xxzx  // r15.x <- col.x; r15.z <- col.z
    mov r15.y, r14.y  // r15.y <- col.y
    break 

#line 507
    case l(40)

#line 509
    mov r15.xy, r13.xyxx  // r15.x <- col.x; r15.y <- col.y
    mov r15.z, r14.z  // r15.z <- col.z
    break 

#line 510
    default 
    break 
  endswitch   // r15.x <- col.x; r15.y <- col.y; r15.z <- col.z

#line 214
  add r2.x, -r13.w, l(1.000000)
  mad r16.w, r14.w, r2.x, r13.w  // r16.w <- alpha

#line 166
  div r2.x, r13.w, r16.w
  add r2.w, -r2.x, l(1.000000)
  add r3.x, -r14.w, l(1.000000)
  mul r2.x, r2.x, r3.x
  mul r17.xyz, r13.xyzx, r2.xxxx
  mad r14.xyz, r2.wwww, r14.xyzx, r17.xyzx
  mad r16.xyz, r14.wwww, r15.xyzx, r14.xyzx  // r16.x <- <ColorCompositing_id69 return value>.x; r16.y <- <ColorCompositing_id69 return value>.y; r16.z <- <ColorCompositing_id69 return value>.z

#line 547
  iadd r2.z, r2.z, l(1)
  mov r13.xyzw, r16.xyzw
endloop 

#line 557
add r1.xyzw, -r0.xyzw, r13.xyzw
mad o0.xyzw, cb0[0].xyzw, r1.xyzw, r0.xyzw

#line 566
ret 
// Approximately 419 instruction slots used
***************************
*************************/
static const float Epsilon_id83 = 0.0000000596;
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id99;
    float InputValue_id100;
    float InputValue_id101;
    float InputValue_id102;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
    int Count_id94 = 1;
    int type_id98;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float3 HUEtoRGB_id8(in float H)
{
    H = frac(H);
    float R = abs(H * 6 - 3) - 1;
    float G = 2 - abs(H * 6 - 2);
    float B = 2 - abs(H * 6 - 4);
    return saturate(float3(R, G, B));
}
float3 RGBtoHCV_id11(in float3 RGB)
{
    float4 P = (RGB.g < RGB.b) ? float4(RGB.bg, -1.0, 2.0 / 3.0) : float4(RGB.gb, 0.0, -1.0 / 3.0);
    float4 Q = (RGB.r < P.x) ? float4(P.xyw, RGB.r) : float4(RGB.r, P.yzx);
    float C = Q.x - min(Q.w, Q.y);
    float H = abs((Q.w - Q.y) / (6 * C + Epsilon_id83) + Q.z);
    return float3(H, C, Q.x);
}
float4 Reflect_id87(float4 c0, float4 c1)
{
    return (c1 == 1.0) ? c1 : min(c0 * c0 / (1.0 - c1), 1.0);
}
float3 ColorCompositing_id69(float as, float ab, float ar, float3 Cs, float3 Cb, float3 Bbs)
{
    return (1 - (as / ar)) * Cb + (as / ar) * (1 - ab) * Cs + ab * Bbs;
}
float3 HSVtoRGB_id9(in float3 HSV)
{
    float3 RGB = HUEtoRGB_id8(HSV.x);
    return ((RGB - 1) * HSV.y + 1) * HSV.z;
}
float3 RGBtoHSV_id12(in float3 RGB)
{
    float3 HCV = RGBtoHCV_id11(RGB);
    float S = HCV.y / (HCV.z + Epsilon_id83);
    return float3(HCV.x, S, HCV.z);
}
float3 HSLtoRGB_id10(in float3 HSL)
{
    float3 RGB = HUEtoRGB_id8(HSL.x);
    float C = (1 - abs(2 * HSL.z - 1)) * HSL.y;
    return (RGB - 0.5) * C + HSL.z;
}
float3 RGBtoHSL_id13(in float3 RGB)
{
    float3 HCV = RGBtoHCV_id11(RGB);
    float L = HCV.z - HCV.y * 0.5;
    float S = HCV.y / (1 - abs(L * 2 - 1) + Epsilon_id83);
    return float3(HCV.x, S, L);
}
float4 Glow_id83(float4 c0, float4 c1)
{
    return Reflect_id87(c1, c0);
}
float4 ColorDodge_id86(float4 c0, float4 c1)
{
    return c0 / (1.0 - c1);
}
float4 ColorBurn_id76(float4 c0, float4 c1)
{
    return (c1 == 0.0) ? c1 : max((1.0 - (1.0 - c0) / c1), 0.0);
}
float4 Lighten_id79(float4 c0, float4 c1)
{
    return max(c0, c1);
}
float4 Darken_id74(float4 c0, float4 c1)
{
    return min(c0, c1);
}
float4 ComputeAlpha_id70(float4 c0, float4 c1, float4 composite)
{
    float alpha = (c1.a + c0.a * (1.0 - c1.a));
    float3 color = ColorCompositing_id69(c1.a, c0.a, alpha, c1.rgb, c0.rgb, composite.rgb);
    return float4(color, alpha);
}
float4 Blue_id111(float4 c0, float4 c1)
{
    return float4(c0.r, c0.g, c1.b, 1.0);
}
float4 Green_id110(float4 c0, float4 c1)
{
    return float4(c0.r, c1.g, c0.b, 1.0);
}
float4 Red_id109(float4 c0, float4 c1)
{
    return float4(c1.r, c0.g, c0.b, 1.0);
}
float4 Value_id108(float4 c0, float4 c1)
{
    float3 hsv0 = RGBtoHSV_id12(c0.rgb);
    float3 hsv1 = RGBtoHSV_id12(c1.rgb);
    float3 col = HSVtoRGB_id9(float3(hsv0.x, hsv0.y, hsv1.z));
    return float4(col, c1.a);
}
float4 Lightness_id107(float4 c0, float4 c1)
{
    float3 hsv0 = RGBtoHSL_id13(c0.rgb);
    float3 hsv1 = RGBtoHSL_id13(c1.rgb);
    float3 col = HSLtoRGB_id10(float3(hsv0.x, hsv0.y, hsv1.z));
    return float4(col, c1.a);
}
float4 Color_id106(float4 c0, float4 c1)
{
    float3 hsv0 = RGBtoHSL_id13(c0.rgb);
    float3 hsv1 = RGBtoHSL_id13(c1.rgb);
    float3 col = HSLtoRGB_id10(float3(hsv1.x, hsv1.y, hsv0.z));
    return float4(col, c1.a);
}
float4 Saturation_id105(float4 c0, float4 c1)
{
    float3 hsv0 = RGBtoHSV_id12(c0.rgb);
    float3 hsv1 = RGBtoHSV_id12(c1.rgb);
    float3 col = HSVtoRGB_id9(float3(hsv0.x, hsv1.y, hsv0.z));
    return float4(col, c1.a);
}
float4 Hue_id104(float4 c0, float4 c1)
{
    float3 hsv0 = RGBtoHSL_id13(c0.rgb);
    float3 hsv1 = RGBtoHSL_id13(c1.rgb);
    float3 col = HSLtoRGB_id10(float3(hsv1.x, hsv0.y, hsv0.z));
    return float4(col, c1.a);
}
float4 GrainMerge_id103(float4 c0, float4 c1)
{
    return (c0 - c1) - 0.5;
}
float4 GrainExtract_id102(float4 c0, float4 c1)
{
    return (c0 - c1) + 0.5;
}
float4 Phoenix_id101(float4 c0, float4 c1)
{
    return min(c0, c1) - max(c0, c1) + 1.0;
}
float4 Heat_id100(float4 c0, float4 c1)
{
    return 1.0 - Glow_id83(c0, c1);
}
float4 AdditiveSubstractive_id99(float4 c0, float4 c1)
{
    return c1 - sqrt(c0);
}
float4 Negation_id98(float4 c0, float4 c1)
{
    return 1.0 - abs(1.0 - c0 - c1);
}
float4 Divide_id97(float4 c0, float4 c1)
{
    return c0 / c1;
}
float4 Subtract_id96(float4 c0, float4 c1)
{
    return c0 - c1;
}
float4 Exclusion_id95(float4 c0, float4 c1)
{
    return c0 + c1 - 2.0 * c0 * c1;
}
float4 Difference_id94(float4 c0, float4 c1)
{
    return abs(c0 - c1);
}
float4 LinearLight_id93(float4 c0, float4 c1)
{
    return (c1 < 0.5) ? max(c0 + 2.0 * c1 - 1.0, 0.0) : min(c0 + 2.0 * (c1 - 0.5), 1.0);
}
float4 VividLight_id92(float4 c0, float4 c1)
{
    return (c1 < 0.5) ? ColorBurn_id76(c0, 2.0 * c1) : ColorDodge_id86(c0, (2.0 * (c1 - 0.5)));
}
float4 Hardlight_id91(float4 c0, float4 c1)
{
    return (c1 < 0.5) ? (2.0 * c0 * c1) : 1.0 - 2.0 * (1.0 - c0) * (1.0 - c1);
}
float4 Pinlight_id90(float4 c0, float4 c1)
{
    return (c1 < 0.5) ? Darken_id74(c0, (2.0 * c1)) : Lighten_id79(c0, (2.0 * (c1 - 0.5)));
}
float4 Freeze_id89(float4 c0, float4 c1)
{
    return (c1 == 0.0) ? 0.0 : 1.0 - pow(1.0 - c0, 2.0) / c1;
}
float4 HardMix_id88(float4 c0, float4 c1)
{
    return floor(c0 + c1);
}
float4 Softlight_id85(float4 c0, float4 c1)
{
    return 2.0 * c0 * c1 + c0 * c0 - 2.0 * c0 * c0 * c1;
}
float4 Overlay_id84(float4 c0, float4 c1)
{
    return (c0 < 0.5) ? (2.0 * c0 * c1) : 1.0 - 2.0 * (1 - c0) * (1.0 - c1);
}
float4 LighterColor_id82(float4 c0, float4 c1)
{
    return (c0.r + c0.g + c0.b > c1.r + c1.g + c1.b) ? c0 : c1;
}
float4 Add_id81(float4 c0, float4 c1)
{
    return c0 + c1;
}
float4 Screen_id80(float4 c0, float4 c1)
{
    return 1.0 - ((1.0 - c0) * (1.0 - c1));
}
float4 DarkerColor_id78(float4 c0, float4 c1)
{
    return (c0.r + c0.g + c0.b < c1.r + c1.g + c1.b) ? c0 : c1;
}
float4 LinearBurn_id77(float4 c0, float4 c1)
{
    return (c0 + c1) - 1.0;
}
float4 Multiply_id75(float4 c0, float4 c1)
{
    return c0 * c1;
}
float4 GeometricMean_id73(float4 c0, float4 c1)
{
    return sqrt(c0 * c1);
}
float4 Average_id72(float4 c0, float4 c1)
{
    return (c0 + c1) * 0.5;
}
float4 Normal_id71(float4 c0, float4 c1)
{
    return c1;
}
float2 GetRange_id113(float width, float center)
{
    float2 range;
    range.x = center - width / 2;
    range.y = center + width / 2;
    return range;
}
float4 Blend_id112(float4 c0, float4 c1, float fader, bool computeAlpha, int type)
{
    float4 col;
    c1.a *= saturate(fader);
    switch (type)

    {
        case 0:
            col = Normal_id71(c0, c1);
            break;
        case 1:
            col = Average_id72(c0, c1);
            break;
        case 2:
            col = GeometricMean_id73(c0, c1);
            break;
        case 3:
            col = Darken_id74(c0, c1);
            break;
        case 4:
            col = Multiply_id75(c0, c1);
            break;
        case 5:
            col = ColorBurn_id76(c0, c1);
            break;
        case 6:
            col = LinearBurn_id77(c0, c1);
            break;
        case 7:
            col = DarkerColor_id78(c0, c1);
            break;
        case 8:
            col = Lighten_id79(c0, c1);
            break;
        case 9:
            col = Screen_id80(c0, c1);
            break;
        case 10:
            col = Add_id81(c0, c1);
            break;
        case 11:
            col = LighterColor_id82(c0, c1);
            break;
        case 12:
            col = Glow_id83(c0, c1);
            break;
        case 13:
            col = Overlay_id84(c0, c1);
            break;
        case 14:
            col = Softlight_id85(c0, c1);
            break;
        case 15:
            col = ColorDodge_id86(c0, c1);
            break;
        case 16:
            col = Reflect_id87(c0, c1);
            break;
        case 17:
            col = HardMix_id88(c0, c1);
            break;
        case 18:
            col = Freeze_id89(c0, c1);
            break;
        case 19:
            col = Pinlight_id90(c0, c1);
            break;
        case 20:
            col = Hardlight_id91(c0, c1);
            break;
        case 21:
            col = VividLight_id92(c0, c1);
            break;
        case 22:
            col = LinearLight_id93(c0, c1);
            break;
        case 23:
            col = Difference_id94(c0, c1);
            break;
        case 24:
            col = Exclusion_id95(c0, c1);
            break;
        case 25:
            col = Subtract_id96(c0, c1);
            break;
        case 26:
            col = Divide_id97(c0, c1);
            break;
        case 27:
            col = Negation_id98(c0, c1);
            break;
        case 28:
            col = AdditiveSubstractive_id99(c0, c1);
            break;
        case 29:
            col = Heat_id100(c0, c1);
            break;
        case 30:
            col = Phoenix_id101(c0, c1);
            break;
        case 31:
            col = GrainExtract_id102(c0, c1);
            break;
        case 32:
            col = GrainMerge_id103(c0, c1);
            break;
        case 33:
            col = Hue_id104(c0, c1);
            break;
        case 34:
            col = Saturation_id105(c0, c1);
            break;
        case 35:
            col = Color_id106(c0, c1);
            break;
        case 36:
            col = Lightness_id107(c0, c1);
            break;
        case 37:
            col = Value_id108(c0, c1);
            break;
        case 38:
            col = Red_id109(c0, c1);
            break;
        case 39:
            col = Green_id110(c0, c1);
            break;
        case 40:
            col = Blue_id111(c0, c1);
            break;
    }
    return (computeAlpha) ? ComputeAlpha_id70(c1, c0, col) : col;
}
float CreateLinear_id114(float center, float width, float phase, float index, float count)
{
    float2 range = GetRange_id113(width, center);
    return lerp(range.x, range.y, frac((phase + 0.5 / count) + index / count));
}
float Compute_id119()
{
    return InputValue_id100;
}
float Compute_id118()
{
    return InputValue_id102;
}
float Compute_id117()
{
    return InputValue_id101;
}
float4 Compute_id116()
{
    return InputValue_id99;
}
float4 Filter_id115(inout PS_STREAMS streams, float4 tex0col)
{
    float2 uv = streams.TexCoord_id62;
    float phase = Compute_id117();
    float size = Compute_id118();
    float center = Compute_id119();
    float4 c = 0;
    float shift = 0;

    for (int i = 0; i < Count_id94; i++)
    {
        shift = CreateLinear_id114(center, size, phase, i, Count_id94);
        c = Blend_id112(c, Texture0_id14.SampleLevel(LinearSampler_id44, float2(streams.TexCoord_id62.x + shift, streams.TexCoord_id62.y), 0), 1.0, true, type_id98);
    }
    return c;
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id115(streams, col), Compute_id116());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
