/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1288232892]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 48]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_4027469542_id16 => input_4027469542
@C    input_4088460044_id17 => input_4088460044
@C    input_3030679232_id18 => input_3030679232
***************************
******  Resources    ******
***************************
@R    TextureInput_3445202295_id12 => TextureInput_3445202295 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_3674091956_id13 => TextureInput_3674091956 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_2990988801_id14 => TextureInput_2990988801 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_2255746994_id15 => TextureInput_2255746994 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1288232892 => 55a0cc082278591ca5b2a29b6860f14e
***************************
*****     Stages      *****
***************************
@G    Compute => 870bc176bdd2c713da6f19e950256362
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_4027469542_id16;        // Offset:   16 Size:    12
//   float input_4088460044_id17;       // Offset:   28 Size:     4 [unused]
//   float3 input_3030679232_id18;      // Offset:   32 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_3445202295_id12      texture  float4          3d             t0      1 
// TextureInput_3674091956_id13      texture   float          3d             t1      1 
// TextureInput_2990988801_id14      texture   float          3d             t2      1 
// TextureInput_2255746994_id15          UAV  float4          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 6
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 38 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_52ae6e6359247e351ca19321d7fde88d.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_2669607774; r0.y <- Assign_2401786989; r0.z <- Assign_3128971616

#line 39
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2293831901

#line 44
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyz, r0.xyzw, t0.xyzw  // r1.x <- velocity_2773640457.x; r1.y <- velocity_2773640457.y; r1.z <- velocity_2773640457.z

#line 45
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- pressure_3039937939

#line 54
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_724897725.x; r2.y <- result_724897725.y; r2.z <- result_724897725.z

#line 55
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t2.yzwx  // r1.w <- getTextureValue_2593130865

#line 56
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_3856115163

#line 58
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t1.yzxw  // r0.z <- getTextureValue_1326562748

#line 65
  mov r0.yw, l(0,0,0,1.000000)
  movc r0.zw, r1.wwww, r0.xxxy, r0.zzzw  // r0.z <- output_1728126123; r0.w <- output_2793696976

#line 66
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_1004940954.x; r2.y <- result_1004940954.y; r2.z <- result_1004940954.z

#line 67
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t2.yzwx  // r1.w <- getTextureValue_1851087222

#line 68
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_972240793

#line 70
  ld_indexable(texture3d)(float,float,float,float) r2.x, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_713662755

#line 90
  mov r2.yw, l(0,1.000000,0,1.000000)

#line 77
  movc r2.xy, r1.wwww, r0.xyxx, r2.xyxx  // r2.x <- output_1399981973; r2.y <- output_1815496314

#line 78
  add r3.x, r0.z, -r2.x  // r3.x <- result_77501090

#line 79
  iadd r4.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r4.x <- result_199687991.x; r4.y <- result_199687991.y; r4.z <- result_199687991.z

#line 80
  mov r4.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r4.xyzw, t2.yzxw  // r0.z <- getTextureValue_4292008959

#line 81
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_251535315

#line 83
  ld_indexable(texture3d)(float,float,float,float) r2.z, r4.xyzw, t1.yzxw  // r2.z <- getTextureValue_3630052716

#line 90
  movc r2.xz, r0.zzzz, r0.xxyx, r2.zzwz  // r2.x <- output_1101645603; r2.z <- output_1097219656

#line 91
  iadd r4.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r4.x <- result_4032072200.x; r4.y <- result_4032072200.y; r4.z <- result_4032072200.z

#line 92
  mov r4.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r4.xyzw, t2.yzxw  // r0.z <- getTextureValue_3579714356

#line 93
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_3878460703

#line 95
  ld_indexable(texture3d)(float,float,float,float) r4.x, r4.xyzw, t1.xyzw  // r4.x <- getTextureValue_1488811859

#line 115
  mov r4.yw, l(0,1.000000,0,1.000000)

#line 102
  movc r4.xy, r0.zzzz, r0.xyxx, r4.xyxx  // r4.x <- output_3078886559; r4.y <- output_3444809732

#line 103
  add r3.y, r2.x, -r4.x  // r3.y <- result_4015742423

#line 104
  iadd r5.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r5.x <- result_4152501819.x; r5.y <- result_4152501819.y; r5.z <- result_4152501819.z

#line 105
  mov r5.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r5.xyzw, t2.yzxw  // r0.z <- getTextureValue_4286367683

#line 106
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_1742647618

#line 108
  ld_indexable(texture3d)(float,float,float,float) r4.z, r5.xyzw, t1.yzxw  // r4.z <- getTextureValue_2368091970

#line 115
  movc r2.xw, r0.zzzz, r0.xxxy, r4.zzzw  // r2.x <- output_2018265800; r2.w <- output_2282979181

#line 116
  iadd r5.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r5.x <- result_1374619076.x; r5.y <- result_1374619076.y; r5.z <- result_1374619076.z

#line 117
  mov r5.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r5.xyzw, t2.yzxw  // r0.z <- getTextureValue_206142520

#line 118
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_3563541456

#line 120
  ld_indexable(texture3d)(float,float,float,float) r4.x, r5.xyzw, t1.xzyw  // r4.x <- getTextureValue_1178843595

#line 127
  mov r4.z, l(1.000000)
  movc r0.xy, r0.zzzz, r0.xyxx, r4.xzxx  // r0.x <- output_300637138; r0.y <- output_3962912877

#line 128
  add r3.z, -r0.x, r2.x  // r3.z <- result_2145433435

#line 131
  mad r1.xyz, -r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx  // r1.x <- result_1247250741.x; r1.y <- result_1247250741.y; r1.z <- result_1247250741.z

#line 132
  min r3.x, r0.w, r2.y  // r3.x <- min_58486984

#line 133
  min r3.y, r2.z, r4.y  // r3.y <- min_9171956

#line 134
  min r3.z, r2.w, r0.y  // r3.z <- min_1475533084

#line 136
  mul r0.xyz, r1.xyzx, r3.xyzx  // r0.x <- result_420986370.x; r0.y <- result_420986370.y; r0.z <- result_420986370.z

#line 139
  mov r0.w, l(0)
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xyzw
endif 

#line 165
ret 
// Approximately 60 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_4027469542_id16;
    float input_4088460044_id17;
    float3 input_3030679232_id18;
};
Texture3D<float4> TextureInput_3445202295_id12;
Texture3D<float> TextureInput_3674091956_id13;
Texture3D<float> TextureInput_2990988801_id14;
RWTexture3D<float4> TextureInput_2255746994_id15;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_1705848389 = streams.DispatchThreadId_id1.x;
    int inputX_3964728810 = input_4027469542_id16.x;
    bool Assign_2669607774 = DispatchThreadIdX_1705848389 >= inputX_3964728810;
    int DispatchThreadIdY_1152064971 = streams.DispatchThreadId_id1.y;
    int inputY_3132258850 = input_4027469542_id16.y;
    bool Assign_2401786989 = DispatchThreadIdY_1152064971 >= inputY_3132258850;
    int DispatchThreadIdZ_1595855846 = streams.DispatchThreadId_id1.z;
    int inputZ_47154949 = input_4027469542_id16.z;
    bool Assign_3128971616 = DispatchThreadIdZ_1595855846 >= inputZ_47154949;
    bool result_2293831901 = (Assign_2669607774 || Assign_2401786989 || Assign_3128971616);
    if (result_2293831901)
    {
        return;
    }
    float4 velocity_2773640457 = TextureInput_3445202295_id12[streams.DispatchThreadId_id1];
    float pressure_3039937939 = TextureInput_3674091956_id13[streams.DispatchThreadId_id1];
    float obstacle_103807989 = TextureInput_2990988801_id14[streams.DispatchThreadId_id1];
    float deltatime_3022387453 = 0;
    deltatime_3022387453 = input_4088460044_id17;
    int3 index_4133278520 = int3(0, 0, 0);
    index_4133278520 = streams.DispatchThreadId_id1;
    float3 resourcescale_1346329991 = float3(0, 0, 0);
    resourcescale_1346329991 = input_3030679232_id18;
    float3 VelocityXyz_1705780810 = velocity_2773640457.xyz;
    int3 result_724897725 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_2593130865 = TextureInput_2990988801_id14[result_724897725];
    bool Assign_3856115163 = getTextureValue_2593130865 > 0;
    int3 result_1282927028 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_1326562748 = TextureInput_3674091956_id13[result_1282927028];
    float output_1728126123 = getTextureValue_1326562748;
    float output_2793696976 = 1;
    if (Assign_3856115163)
    {
        output_1728126123 = pressure_3039937939;
        output_2793696976 = 0;
    }
    int3 result_1004940954 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_1851087222 = TextureInput_2990988801_id14[result_1004940954];
    bool Assign_972240793 = getTextureValue_1851087222 > 0;
    int3 result_2487825051 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_713662755 = TextureInput_3674091956_id13[result_2487825051];
    float output_1399981973 = getTextureValue_713662755;
    float output_1815496314 = 1;
    if (Assign_972240793)
    {
        output_1399981973 = pressure_3039937939;
        output_1815496314 = 0;
    }
    float result_77501090 = (output_1728126123 - output_1399981973);
    int3 result_199687991 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_4292008959 = TextureInput_2990988801_id14[result_199687991];
    bool Assign_251535315 = getTextureValue_4292008959 > 0;
    int3 result_4259508728 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_3630052716 = TextureInput_3674091956_id13[result_4259508728];
    float output_1101645603 = getTextureValue_3630052716;
    float output_1097219656 = 1;
    if (Assign_251535315)
    {
        output_1101645603 = pressure_3039937939;
        output_1097219656 = 0;
    }
    int3 result_4032072200 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_3579714356 = TextureInput_2990988801_id14[result_4032072200];
    bool Assign_3878460703 = getTextureValue_3579714356 > 0;
    int3 result_592800187 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_1488811859 = TextureInput_3674091956_id13[result_592800187];
    float output_3078886559 = getTextureValue_1488811859;
    float output_3444809732 = 1;
    if (Assign_3878460703)
    {
        output_3078886559 = pressure_3039937939;
        output_3444809732 = 0;
    }
    float result_4015742423 = (output_1101645603 - output_3078886559);
    int3 result_4152501819 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_4286367683 = TextureInput_2990988801_id14[result_4152501819];
    bool Assign_1742647618 = getTextureValue_4286367683 > 0;
    int3 result_1883130382 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_2368091970 = TextureInput_3674091956_id13[result_1883130382];
    float output_2018265800 = getTextureValue_2368091970;
    float output_2282979181 = 1;
    if (Assign_1742647618)
    {
        output_2018265800 = pressure_3039937939;
        output_2282979181 = 0;
    }
    int3 result_1374619076 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_206142520 = TextureInput_2990988801_id14[result_1374619076];
    bool Assign_3563541456 = getTextureValue_206142520 > 0;
    int3 result_3923509507 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_1178843595 = TextureInput_3674091956_id13[result_3923509507];
    float output_300637138 = getTextureValue_1178843595;
    float output_3962912877 = 1;
    if (Assign_3563541456)
    {
        output_300637138 = pressure_3039937939;
        output_3962912877 = 0;
    }
    float result_2145433435 = (output_2018265800 - output_300637138);
    float3 Float3Join_2951161168 = float3(result_77501090, result_4015742423, result_2145433435);
    float3 result_3677043461 = (Float3Join_2951161168 * 0.5);
    float3 result_1247250741 = (VelocityXyz_1705780810 - result_3677043461);
    float min_58486984 = min(output_1815496314, output_2793696976);
    float min_9171956 = min(output_3444809732, output_1097219656);
    float min_1475533084 = min(output_3962912877, output_2282979181);
    float3 Float3Join_731238842 = float3(min_58486984, min_9171956, min_1475533084);
    float3 result_420986370 = (result_1247250741 * Float3Join_731238842);
    float4 join_1703656177 = float4(result_420986370, 0);
    velocity_2773640457 = join_1703656177;
    TextureInput_2255746994_id15[streams.DispatchThreadId_id1] = velocity_2773640457;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
