/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ShaderFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin ModuloGPU_ShaderFX [{ShaderInput = InputUInt<ShaderFX.InputValueUInt,PerUpdate>}, {ShaderInput2 = InputUInt<ShaderFX.InputValueUInt.i1,PerUpdate>}]
@P ShaderInput: InputUInt<ShaderFX.InputValueUInt,PerUpdate>
@P ShaderInput2: InputUInt<ShaderFX.InputValueUInt.i1,PerUpdate>
***************************
*****     Sources     *****
***************************
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    ModuloGPU_ShaderFX => 2ed043b54a0352f92da8b4cc39313816
@S    ComputeUInt => 707f4166cd9f83784b42c78a0cc57287
@S    InputUInt => e8bcca0c5de594d673cd9669b7bdad68
@S    DeclUInt => a5c3b92d01d17f67ecdac3662ed6737d
***************************
*****     Stages      *****
***************************
@G    Vertex => 7ae935036a1b3058f70dafa629ea5dea
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
vs_5_0
dcl_globalFlags refactoringAllowed

#line 15 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ShaderFXEffect_d02ef8cf597987350c722e91217bb44b.hlsl"
ret 
// Approximately 1 instruction slots used
***************************
*************************/
struct VS_STREAMS 
{
};
struct VS_INPUT 
{
};
cbuffer PerUpdate 
{
    uint InputValue_id16;
    uint InputValue_id17;
};
void VSMain()
{
    VS_STREAMS streams = (VS_STREAMS)0;
}
