/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1008503824]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 64]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_4027469542_id15 => input_4027469542
@C    input_3930303053_id16 => input_3930303053
@C    input_1756470321_id17 => input_1756470321
@C    input_3679965283_id18 => input_3679965283
@C    input_1861078990_id19 => input_1861078990
***************************
******  Resources    ******
***************************
@R    TextureInput_3445202295_id12 => TextureInput_3445202295 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_1544422243_id13 => TextureInput_1544422243 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_2255746994_id14 => TextureInput_2255746994 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1008503824 => 3918fa8d7260294e9265dc0de76a3681
***************************
*****     Stages      *****
***************************
@G    Compute => 1453ea2cac5f325640835b02e70ca165
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_4027469542_id15;        // Offset:   16 Size:    12
//   float input_3930303053_id16;       // Offset:   28 Size:     4 [unused]
//   float3 input_1756470321_id17;      // Offset:   32 Size:    12 [unused]
//   float input_3679965283_id18;       // Offset:   44 Size:     4
//   float input_1861078990_id19;       // Offset:   48 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_3445202295_id12      texture  float4          3d             t0      1 
// TextureInput_1544422243_id13      texture  float4          3d             t1      1 
// TextureInput_2255746994_id14          UAV  float4          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 4
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 39 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_fa7cf86f50161e63c13c0798c3025d0a.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_2669607774; r0.y <- Assign_2401786989; r0.z <- Assign_3128971616

#line 40
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2293831901

#line 45
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyzw, r0.xyzw, t0.xyzw  // r1.x <- velocity_2773640457.x; r1.y <- velocity_2773640457.y; r1.z <- velocity_2773640457.z; r1.w <- velocity_2773640457.w

#line 46
  ld_indexable(texture3d)(float,float,float,float) r0.xyz, r0.xyzw, t1.xyzw  // r0.x <- vorticity_3039937939.x; r0.y <- vorticity_3039937939.y; r0.z <- vorticity_3039937939.z

#line 53
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_4288180693.x; r2.y <- result_4288180693.y; r2.z <- result_4288180693.z

#line 54
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r2.xyzw, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_2335041817.x; r2.y <- getTextureValue_2335041817.y; r2.z <- getTextureValue_2335041817.z; r2.w <- getTextureValue_2335041817.w

#line 55
  dp4 r0.w, r2.xyzw, r2.xyzw
  sqrt r0.w, r0.w  // r0.w <- length_4271130433

#line 56
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_3474011010.x; r2.y <- result_3474011010.y; r2.z <- result_3474011010.z

#line 57
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r2.xyzw, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_2189551566.x; r2.y <- getTextureValue_2189551566.y; r2.z <- getTextureValue_2189551566.z; r2.w <- getTextureValue_2189551566.w

#line 58
  dp4 r2.x, r2.xyzw, r2.xyzw
  sqrt r2.x, r2.x  // r2.x <- length_3998145463

#line 59
  add r2.y, r0.w, -r2.x  // r2.y <- result_2890633578

#line 60
  iadd r3.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r3.x <- result_3289046927.x; r3.y <- result_3289046927.y; r3.z <- result_3289046927.z

#line 61
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_560502887.x; r3.y <- getTextureValue_560502887.y; r3.z <- getTextureValue_560502887.z; r3.w <- getTextureValue_560502887.w

#line 62
  dp4 r0.w, r3.xyzw, r3.xyzw
  sqrt r0.w, r0.w  // r0.w <- length_3240437473

#line 63
  iadd r3.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r3.x <- result_2826665008.x; r3.y <- result_2826665008.y; r3.z <- result_2826665008.z

#line 64
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_1778620236.x; r3.y <- getTextureValue_1778620236.y; r3.z <- getTextureValue_1778620236.z; r3.w <- getTextureValue_1778620236.w

#line 65
  dp4 r2.w, r3.xyzw, r3.xyzw
  sqrt r2.w, r2.w  // r2.w <- length_1498667331

#line 66
  add r2.z, r0.w, -r2.w  // r2.z <- result_502281360

#line 67
  iadd r3.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r3.x <- result_1913242659.x; r3.y <- result_1913242659.y; r3.z <- result_1913242659.z

#line 68
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_2803903771.x; r3.y <- getTextureValue_2803903771.y; r3.z <- getTextureValue_2803903771.z; r3.w <- getTextureValue_2803903771.w

#line 69
  dp4 r0.w, r3.xyzw, r3.xyzw
  sqrt r0.w, r0.w  // r0.w <- length_3896194248

#line 70
  iadd r3.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r3.x <- result_2713700252.x; r3.y <- result_2713700252.y; r3.z <- result_2713700252.z

#line 71
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_1377351712.x; r3.y <- getTextureValue_1377351712.y; r3.z <- getTextureValue_1377351712.z; r3.w <- getTextureValue_1377351712.w

#line 72
  dp4 r2.w, r3.xyzw, r3.xyzw
  sqrt r2.w, r2.w  // r2.w <- length_3842828190

#line 73
  add r2.x, r0.w, -r2.w  // r2.x <- result_1097392523

#line 76
  mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.001000, 0.001000, 0.001000, 0.000000)  // r2.x <- result_1266656361.z; r2.y <- result_1266656361.x; r2.z <- result_1266656361.y

#line 77
  dp3 r0.w, r2.xyzx, r2.xyzx
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r2.xyzx  // r2.x <- normalize_838437929.z; r2.y <- normalize_838437929.x; r2.z <- normalize_838437929.y

#line 79
  mul r3.xyz, r0.yzxy, r2.xyzx
  mad r0.xyz, r2.zxyz, r0.zxyz, -r3.xyzx  // r0.x <- cross_2578707039.x; r0.y <- cross_2578707039.y; r0.z <- cross_2578707039.z

#line 80
  mul r0.w, cb0[2].w, cb0[3].x  // r0.w <- result_1790963352

#line 81
  mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- result_4288464047.x; r0.y <- result_4288464047.y; r0.z <- result_4288464047.z

#line 83
  mov r0.w, l(0)
  add r0.xyzw, r0.xyzw, r1.xyzw  // r0.x <- result_1321535992.x; r0.y <- result_1321535992.y; r0.z <- result_1321535992.z; r0.w <- result_1321535992.w

#line 85
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xyzw
endif 

#line 111
ret 
// Approximately 54 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_4027469542_id15;
    float input_3930303053_id16;
    float3 input_1756470321_id17;
    float input_3679965283_id18;
    float input_1861078990_id19;
};
Texture3D<float4> TextureInput_3445202295_id12;
Texture3D<float4> TextureInput_1544422243_id13;
RWTexture3D<float4> TextureInput_2255746994_id14;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_1705848389 = streams.DispatchThreadId_id1.x;
    int inputX_3964728810 = input_4027469542_id15.x;
    bool Assign_2669607774 = DispatchThreadIdX_1705848389 >= inputX_3964728810;
    int DispatchThreadIdY_1152064971 = streams.DispatchThreadId_id1.y;
    int inputY_3132258850 = input_4027469542_id15.y;
    bool Assign_2401786989 = DispatchThreadIdY_1152064971 >= inputY_3132258850;
    int DispatchThreadIdZ_1595855846 = streams.DispatchThreadId_id1.z;
    int inputZ_47154949 = input_4027469542_id15.z;
    bool Assign_3128971616 = DispatchThreadIdZ_1595855846 >= inputZ_47154949;
    bool result_2293831901 = (Assign_2669607774 || Assign_2401786989 || Assign_3128971616);
    if (result_2293831901)
    {
        return;
    }
    float4 velocity_2773640457 = TextureInput_3445202295_id12[streams.DispatchThreadId_id1];
    float4 vorticity_3039937939 = TextureInput_1544422243_id13[streams.DispatchThreadId_id1];
    float deltatime_2329952960 = 0;
    deltatime_2329952960 = input_3930303053_id16;
    int3 index_1003651195 = int3(0, 0, 0);
    index_1003651195 = streams.DispatchThreadId_id1;
    float3 resourcescale_2268009290 = float3(0, 0, 0);
    resourcescale_2268009290 = input_1756470321_id17;
    int3 result_4288180693 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float4 getTextureValue_2335041817 = TextureInput_1544422243_id13[result_4288180693];
    float length_4271130433 = length(getTextureValue_2335041817);
    int3 result_3474011010 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float4 getTextureValue_2189551566 = TextureInput_1544422243_id13[result_3474011010];
    float length_3998145463 = length(getTextureValue_2189551566);
    float result_2890633578 = (length_4271130433 - length_3998145463);
    int3 result_3289046927 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float4 getTextureValue_560502887 = TextureInput_1544422243_id13[result_3289046927];
    float length_3240437473 = length(getTextureValue_560502887);
    int3 result_2826665008 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float4 getTextureValue_1778620236 = TextureInput_1544422243_id13[result_2826665008];
    float length_1498667331 = length(getTextureValue_1778620236);
    float result_502281360 = (length_3240437473 - length_1498667331);
    int3 result_1913242659 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float4 getTextureValue_2803903771 = TextureInput_1544422243_id13[result_1913242659];
    float length_3896194248 = length(getTextureValue_2803903771);
    int3 result_2713700252 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float4 getTextureValue_1377351712 = TextureInput_1544422243_id13[result_2713700252];
    float length_3842828190 = length(getTextureValue_1377351712);
    float result_1097392523 = (length_3896194248 - length_3842828190);
    float3 Float3Join_2788595451 = float3(result_2890633578, result_502281360, result_1097392523);
    float3 result_3756893856 = (Float3Join_2788595451 * 0.5);
    float3 result_1266656361 = (result_3756893856 + 0.001);
    float3 normalize_838437929 = normalize(result_1266656361);
    float3 VorticityXyz_4001449510 = vorticity_3039937939.xyz;
    float3 cross_2578707039 = cross(normalize_838437929, VorticityXyz_4001449510);
    float result_1790963352 = (input_3679965283_id18 * input_1861078990_id19);
    float3 result_4288464047 = (cross_2578707039 * result_1790963352);
    float4 join_542375605 = float4(result_4288464047, 0);
    float4 result_1321535992 = (velocity_2773640457 + join_542375605);
    velocity_2773640457 = result_1321535992;
    TextureInput_2255746994_id14[streams.DispatchThreadId_id1] = velocity_2773640457;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
