/**************************
***** Compiler Parameters *****
***************************
@P EffectName: DrawFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin Constant_TextureTransform_DrawFX
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 416]
@C    World_id29 => Transformation.World
@C    WorldInverse_id30 => Transformation.WorldInverse
@C    WorldInverseTranspose_id31 => Transformation.WorldInverseTranspose
@C    WorldView_id32 => Transformation.WorldView
@C    WorldViewInverse_id33 => Transformation.WorldViewInverse
@C    WorldViewProjection_id34 => Transformation.WorldViewProjection
@C    WorldScale_id35 => Transformation.WorldScale
@C    EyeMS_id36 => Transformation.EyeMS
cbuffer Globals [Size: 160]
@C    Texture0TexelSize_id47 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id49 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id51 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id53 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id55 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id57 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id59 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id61 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id63 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id65 => Texturing.Texture9TexelSize
@C    ColorInput_id104 => Constant_TextureTransform_DrawFX.ColorInput
@C    TextureTransform_id105 => Constant_TextureTransform_DrawFX.TextureTransform
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    Globals => Globals [Stage: Vertex, Slot: (1-1)]
@R    MySampler_id106 => Constant_TextureTransform_DrawFX.MySampler [Stage: Pixel, Slot: (0-0)]
@R    Texture0_id46 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Constant_TextureTransform_DrawFX => cb1ff761164d362138b5f02e35a4d851
@S    VS_PS_Base => f089dc4ce5d5868b962b08793ef74fd9
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    NormalStream => ea68512133899a045766d21afb59733a
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    ColorBase => b8b78679285939723aa5d9647437398b
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
***************************
*****     Stages      *****
***************************
@G    Vertex => 753e8657d9baa4ce589151965e2a9234
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id29;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id30;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id31;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id32;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id33;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id34; // Offset:  320 Size:    64
//   float3 WorldScale_id35;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id36;                 // Offset:  400 Size:    16 [unused]
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id47;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id49;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id51;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id53;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id55;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id57;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id59;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id61;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id63;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id65;     // Offset:   72 Size:     8 [unused]
//   float4 ColorInput_id104;           // Offset:   80 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4x4 TextureTransform_id105;   // Offset:   96 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
// Globals                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// POSITION                 0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_Position              0   xyzw        1      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_constantbuffer CB1[8], immediateIndexed
dcl_input v0.xy
dcl_input v1.xyzw
dcl_output o0.xy
dcl_output_siv o1.xyzw, position
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- __input__.TexCoord_id94.x; v0.y <- __input__.TexCoord_id94.y; 
//   v1.x <- __input__.Position_id14.x; v1.y <- __input__.Position_id14.y; v1.z <- __input__.Position_id14.z; v1.w <- __input__.Position_id14.w; 
//   o1.x <- <VSMain return value>.ShadingPosition_id0.x; o1.y <- <VSMain return value>.ShadingPosition_id0.y; o1.z <- <VSMain return value>.ShadingPosition_id0.z; o1.w <- <VSMain return value>.ShadingPosition_id0.w; 
//   o0.x <- <VSMain return value>.TexCoord_id94.x; o0.y <- <VSMain return value>.TexCoord_id94.y
//
#line 160 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_DrawFXEffect_9afbe714d80946ce534a60df9dc1e20a.hlsl"
mad r0.xy, v0.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(-0.500000, 0.500000, 0.000000, 0.000000)
mov r0.z, l(1.000000)
dp3 r1.x, r0.xyzx, cb1[6].xywx
dp3 r1.y, r0.xyzx, cb1[7].xywx
mad o0.xy, r1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)

#line 161
dp4 o1.x, v1.xyzw, cb0[20].xyzw
dp4 o1.y, v1.xyzw, cb0[21].xyzw
dp4 o1.z, v1.xyzw, cb0[22].xyzw
dp4 o1.w, v1.xyzw, cb0[23].xyzw

#line 165
ret 
// Approximately 10 instruction slots used
@G    Pixel => e601eb9076d6bac86322b830aad115b9
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id47;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id49;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id51;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id53;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id55;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id57;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id59;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id61;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id63;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id65;     // Offset:   72 Size:     8 [unused]
//   float4 ColorInput_id104;           // Offset:   80 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4x4 TextureTransform_id105;   // Offset:   96 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// MySampler_id106                   sampler      NA          NA             s0      1 
// Texture0_id46                     texture  float4          2d             t0      1 
// Globals                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_Position              0   xyzw        1      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[6], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xy
dcl_output o0.xyzw
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- __input__.TexCoord_id94.x; v0.y <- __input__.TexCoord_id94.y; 
//   v1.x <- __input__.ShadingPosition_id0.x; v1.y <- __input__.ShadingPosition_id0.y; v1.z <- __input__.ShadingPosition_id0.z; v1.w <- __input__.ShadingPosition_id0.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 150 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_DrawFXEffect_9afbe714d80946ce534a60df9dc1e20a.hlsl"
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v0.xyxx, t0.xyzw, s0
mul o0.xyzw, r0.xyzw, cb0[5].xyzw

#line 153
ret 
// Approximately 3 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id94;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float2 TexCoord_id94 : TEXCOORD0;
    float4 ShadingPosition_id0 : SV_Position;
};
struct VS_STREAMS 
{
    float2 TexCoord_id94;
    float4 Position_id14;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float2 TexCoord_id94 : TEXCOORD0;
    float4 ShadingPosition_id0 : SV_Position;
};
struct VS_INPUT 
{
    float2 TexCoord_id94 : TEXCOORD0;
    float4 Position_id14 : POSITION;
};
cbuffer PerDraw 
{
    float4x4 World_id29;
    float4x4 WorldInverse_id30;
    float4x4 WorldInverseTranspose_id31;
    float4x4 WorldView_id32;
    float4x4 WorldViewInverse_id33;
    float4x4 WorldViewProjection_id34;
    float3 WorldScale_id35;
    float4 EyeMS_id36;
};
cbuffer PerView 
{
    float4x4 View_id22;
    float4x4 ViewInverse_id23;
    float4x4 Projection_id24;
    float4x4 ProjectionInverse_id25;
    float4x4 ViewProjection_id26;
    float2 ProjScreenRay_id27;
    float4 Eye_id28;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id47;
    float2 Texture1TexelSize_id49;
    float2 Texture2TexelSize_id51;
    float2 Texture3TexelSize_id53;
    float2 Texture4TexelSize_id55;
    float2 Texture5TexelSize_id57;
    float2 Texture6TexelSize_id59;
    float2 Texture7TexelSize_id61;
    float2 Texture8TexelSize_id63;
    float2 Texture9TexelSize_id65;
    float4 ColorInput_id104 = float4(1, 1, 1, 1);
    matrix TextureTransform_id105;
};
Texture2D Texture0_id46;
Texture2D Texture1_id48;
Texture2D Texture2_id50;
Texture2D Texture3_id52;
Texture2D Texture4_id54;
Texture2D Texture5_id56;
Texture2D Texture6_id58;
Texture2D Texture7_id60;
Texture2D Texture8_id62;
Texture2D Texture9_id64;
TextureCube TextureCube0_id66;
TextureCube TextureCube1_id67;
TextureCube TextureCube2_id68;
TextureCube TextureCube3_id69;
Texture3D Texture3D0_id70;
Texture3D Texture3D1_id71;
Texture3D Texture3D2_id72;
Texture3D Texture3D3_id73;
SamplerState Sampler_id74;
SamplerState PointSampler_id75 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id76 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id77 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id78 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id79 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id80 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id81 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id82 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id83 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id84;
SamplerState Sampler1_id85;
SamplerState Sampler2_id86;
SamplerState Sampler3_id87;
SamplerState Sampler4_id88;
SamplerState Sampler5_id89;
SamplerState Sampler6_id90;
SamplerState Sampler7_id91;
SamplerState Sampler8_id92;
SamplerState Sampler9_id93;
SamplerState MySampler_id106;
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id94 = __input__.TexCoord_id94;
    streams.ColorTarget_id2 = Texture0_id46.Sample(MySampler_id106, streams.TexCoord_id94) * ColorInput_id104;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.TexCoord_id94 = __input__.TexCoord_id94;
    streams.Position_id14 = __input__.Position_id14;
    streams.TexCoord_id94 = mul(float4((streams.TexCoord_id94 * 2 - 1) * float2(1, -1) * .5, 0, 1), TextureTransform_id105).xy * float2(1, -1) + 0.5;
    streams.ShadingPosition_id0 = mul(streams.Position_id14, WorldViewProjection_id34);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.TexCoord_id94 = streams.TexCoord_id94;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    return __output__;
}
