/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin QuasiCrystal_Internal_TextureFX [{ColorA = InputFloat4<ShaderFX.InputValueFloat4_Color,PerUpdate>}, {ColorB = InputFloat4<ShaderFX.InputValueFloat4_Color.i1,PerUpdate>}, {N = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}, {Scale = InputFloat2<ShaderFX.InputValueFloat2,PerUpdate>}, {Time = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}]
@P ColorA: InputFloat4<ShaderFX.InputValueFloat4_Color,PerUpdate>
@P ColorB: InputFloat4<ShaderFX.InputValueFloat4_Color.i1,PerUpdate>
@P Time: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P Scale: InputFloat2<ShaderFX.InputValueFloat2,PerUpdate>
@P N: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 48]
@C    InputValue_id92 => ShaderFX.InputValueFloat4_Color
@C    InputValue_id93 => ShaderFX.InputValueFloat4_Color.i1
@C    InputValue_id94 => ShaderFX.InputValueFloat.i1
@C    InputValue_id95 => ShaderFX.InputValueFloat2
@C    InputValue_id96 => ShaderFX.InputValueFloat
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    QuasiCrystal_Internal_TextureFX => 9fbaf18f6a5b2f05613d258d31124bbf
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    ComputeFloat2 => 4826dbf2e774b7283c93b6121c851c5d
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
@S    InputFloat2 => d6238a7d677592382c8158617d803399
@S    DeclFloat2 => d5fe6f879293db53179d13cf4b1d1f3d
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 207 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_870180f9efb4faf66791d6b20f50ed9c.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 211
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => e6cbe727990e2341146f4cc96ed24cab
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id92;            // Offset:    0 Size:    16
//   float4 InputValue_id93;            // Offset:   16 Size:    16
//   float InputValue_id94;             // Offset:   32 Size:     4
//   float2 InputValue_id95;            // Offset:   36 Size:     8
//   float InputValue_id96;             // Offset:   44 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerUpdate                         cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 174 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_870180f9efb4faf66791d6b20f50ed9c.hlsl"
add r0.xy, v1.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
mul r0.xy, r0.xyxx, cb0[2].yzyy
mul r0.xy, r0.xyxx, l(100.000000, 100.000000, 0.000000, 0.000000)  // r0.x <- p.x; r0.y <- p.y

#line 180
div r0.z, l(6.283185), cb0[2].x

#line 178
mov r1.xyzw, l(0,0,0,0)  // r1.x <- rgba.x; r1.y <- rgba.y; r1.z <- rgba.z; r1.w <- rgba.w
mov r0.w, l(0)  // r0.w <- i
loop 
  ge r2.x, r0.w, cb0[2].x
  breakc_nz r2.x

#line 180
  mul r2.x, r0.z, r0.w  // r2.x <- a

#line 181
  sincos r2.x, r3.x, r2.x
  mul r2.x, r0.y, r2.x
  mad r2.x, r0.x, r3.x, r2.x
  add r2.x, r2.x, cb0[2].w
  sincos null, r2.x, r2.x

#line 182
  mad r2.x, r2.x, l(0.500000), r0.w

#line 185
  add r1.xyzw, r1.xyzw, r2.xxxx

#line 186
  add r0.w, r0.w, l(1.000000)
endloop 

#line 153
add r0.xyzw, r1.xyzw, r1.xyzw
ge r0.xyzw, r0.xyzw, -r0.xyzw
movc r2.xyzw, r0.xxyy, l(2.000000,0.500000,2.000000,0.500000), l(-2.000000,-0.500000,-2.000000,-0.500000)
mul r0.xy, r1.xyxx, r2.ywyy
frc r0.xy, r0.xyxx
mul r1.xy, r0.xyxx, r2.xzxx  // r1.y <- m; r1.y <- m

#line 154
ge r2.yw, r1.xxxy, l(0.000000, 1.000000, 0.000000, 1.000000)

#line 155
mad r0.xy, -r2.xzxx, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)  // r0.y <- color; r0.y <- color

#line 157
movc r2.xy, r2.ywyy, r0.xyxx, r1.xyxx  // r2.y <- color; r2.y <- color

#line 153
movc r0.xyzw, r0.zzww, l(2.000000,0.500000,2.000000,0.500000), l(-2.000000,-0.500000,-2.000000,-0.500000)
mul r0.yw, r0.yyyw, r1.zzzw
frc r0.yw, r0.yyyw
mul r1.xy, r0.ywyy, r0.xzxx

#line 154
ge r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)

#line 155
mad r0.xy, -r0.xzxx, r0.ywyy, l(2.000000, 2.000000, 0.000000, 0.000000)  // r0.y <- color

#line 157
movc r2.zw, r1.zzzw, r0.xxxy, r1.xxxy  // r2.w <- color

#line 191
add r0.xyzw, -cb0[0].xyzw, cb0[1].xyzw
mad o0.xyzw, r2.xyzw, r0.xyzw, cb0[0].xyzw

#line 200
ret 
// Approximately 38 instruction slots used
***************************
*************************/
static const float Pi_id79 = 3.1415926535897932384626433832795;
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id92;
    float4 InputValue_id93;
    float InputValue_id94;
    float2 InputValue_id95;
    float InputValue_id96;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float4 Compute_id34()
{
    return InputValue_id93;
}
float4 Compute_id33()
{
    return InputValue_id92;
}
float post_process_id28(float color)
{
    float m = color % 2.0;
    if (m >= 1.0)
        color = 2.0 - m;
    else
        color = m;
    return color;
}
float Compute_id32()
{
    return InputValue_id96;
}
float Compute_id31()
{
    return InputValue_id94;
}
float2 Compute_id30()
{
    return InputValue_id95;
}
float4 Shading_id29(inout PS_STREAMS streams)
{
    float2 p = (streams.TexCoord_id62.xy - 0.5) * Compute_id30() * 100;
    float4 rgba = float4(0.0, 0.0, 0.0, 0.0);
    float n = Compute_id31();

    for (float i = 0.0; i < n; ++i)
    {
        float a = i * (2.0 * Pi_id79 / n);
        float t = cos((p.x * cos(a) + p.y * sin(a)) + Compute_id32()) / 2.0;
        rgba.r += t + i;
        rgba.g += t + i;
        rgba.b += t + i;
        rgba.a += t + i;
    }
    rgba.r = post_process_id28(rgba.r);
    rgba.g = post_process_id28(rgba.g);
    rgba.b = post_process_id28(rgba.b);
    rgba.a = post_process_id28(rgba.a);
    return lerp(Compute_id33(), Compute_id34(), rgba);
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id29(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
