/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin Plasma_Internal_TextureFX [{ColorA = InputFloat4<ShaderFX.InputValueFloat4_Color,PerUpdate>}, {ColorB = InputFloat4<ShaderFX.InputValueFloat4_Color.i1,PerUpdate>}, {FrequencyA = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}, {FrequencyB = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}, {Time = InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>}]
@P ColorA: InputFloat4<ShaderFX.InputValueFloat4_Color,PerUpdate>
@P ColorB: InputFloat4<ShaderFX.InputValueFloat4_Color.i1,PerUpdate>
@P FrequencyA: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P FrequencyB: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
@P Time: InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 48]
@C    InputValue_id99 => ShaderFX.InputValueFloat4_Color
@C    InputValue_id100 => ShaderFX.InputValueFloat4_Color.i1
@C    InputValue_id101 => ShaderFX.InputValueFloat
@C    InputValue_id102 => ShaderFX.InputValueFloat.i1
@C    InputValue_id103 => ShaderFX.InputValueFloat.i2
cbuffer Globals [Size: 144]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
@C    Transform_id98 => Plasma_Internal_TextureFX.Transform
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (1-1)]
***************************
*****     Sources     *****
***************************
@S    Plasma_Internal_TextureFX => 749ed7f92574f13592ea15e5fefc896e
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    AddonShaderUtils => 0d3496ddd24bfcbde4abd1deae724f64
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 202 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_5a966c48e1d31a3a7b60fcab96acb94e.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 206
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 43283f881ba86ccc26ec5149f01037be
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id99;            // Offset:    0 Size:    16
//   float4 InputValue_id100;           // Offset:   16 Size:    16
//   float InputValue_id101;            // Offset:   32 Size:     4
//   float InputValue_id102;            // Offset:   36 Size:     4
//   float InputValue_id103;            // Offset:   40 Size:     4
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//   float4x4 Transform_id98;           // Offset:   80 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// Globals                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_constantbuffer CB1[9], immediateIndexed
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 176 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_5a966c48e1d31a3a7b60fcab96acb94e.hlsl"
add r0.xy, v1.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
mov r0.z, l(1.000000)
dp3 r1.x, r0.xyzx, cb1[5].xywx  // r1.x <- x2.x
dp3 r1.y, r0.xyzx, cb1[6].xywx  // r1.y <- x2.y
dp3 r0.x, r0.xyzx, cb1[8].xywx  // r0.x <- x2.w

#line 177
div r0.xy, r1.xyxx, r0.xxxx  // r0.x <- x.x; r0.y <- x.y

#line 178
mad r0.zw, r0.yyyx, l(0.000000, 0.000000, 3.605551, 3.000000), cb0[2].zzzz
sincos r0.zw, null, r0.zzzw
mad r0.xy, r0.zwzz, l(0.200000, 0.200000, 0.000000, 0.000000), r0.xyxx

#line 179
mad r0.zw, r0.xxxy, l(0.000000, 0.000000, 5.744563, 6.557438), -cb0[2].zzzz
sincos r0.zw, null, r0.zzzw

#line 165
add r1.xy, r0.zwzz, l(7.000000, 7.000000, 0.000000, 0.000000)
add r2.xyzw, r0.zwzw, l(5.000000, 5.000000, 6.000000, 6.000000)
dp2 r0.z, r1.xyxx, r1.xyxx
sqrt r0.z, r0.z  // r0.z <- <lungth_id68 return value>.z

#line 180
mad r1.xy, r0.yxyy, l(8.544003, 7.280110, 0.000000, 0.000000), cb0[2].zzzz
sincos r1.xy, null, r1.xyxx
mad r0.xy, r1.xyxx, l(0.200000, 0.200000, 0.000000, 0.000000), r0.xyxx

#line 181
mad r1.xy, r0.xyxx, l(5.744563, 4.795832, 0.000000, 0.000000), -cb0[2].zzzz
sincos r1.xy, null, r1.xyxx  // r1.x <- x.x; r1.y <- x.y

#line 165
mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 0.111111, 0.111111), r1.xxxy
dp2 r0.z, r0.zwzz, r0.zwzz
sqrt r0.z, r0.z  // r0.z <- <lungth_id68 return value>.z; r0.z <- <lungth_id68 return value>.z

#line 182
mad r1.zw, r0.yyyx, l(0.000000, 0.000000, 9.643651, 8.544003), cb0[2].zzzz
sincos r1.zw, null, r1.zzzw
mad r0.xy, r1.zwzz, l(0.142857, 0.142857, 0.000000, 0.000000), r0.xyxx

#line 183
mul r1.zw, cb0[2].xxxy, l(0.000000, 0.000000, 100.000000, 100.000000)
sqrt r1.zw, r1.zzzw
mad r0.xy, r0.xyxx, r1.zwzz, -cb0[2].zzzz
sincos r0.xy, null, r0.xyxx  // r0.x <- x.x; r0.y <- x.y; r0.x <- x.x; r0.y <- x.y

#line 165
add r0.zw, r0.zzzz, r0.xxxy
dp2 r0.z, r0.zwzz, r0.zwzz
sqrt r3.z, r0.z  // r3.z <- <lungth_id68 return value>.z; r3.z <- <lungth_id68 return value>.z; r3.z <- <lungth_id68 return value>.z
dp2 r0.z, r2.xyxx, r2.xyxx
dp2 r0.w, r2.zwzz, r2.zwzz
sqrt r2.xy, r0.zwzz  // r2.x <- <lungth_id68 return value>.x; r2.y <- <lungth_id68 return value>.y; r2.x <- <lungth_id68 return value>.x; r2.y <- <lungth_id68 return value>.y; r2.x <- <lungth_id68 return value>.x; r2.y <- <lungth_id68 return value>.y
mad r1.xyzw, r2.xxyy, l(0.111111, 0.111111, 0.111111, 0.111111), r1.xyxy
dp2 r0.z, r1.xyxx, r1.xyxx
dp2 r0.w, r1.zwzz, r1.zwzz
sqrt r0.zw, r0.zzzw  // r0.z <- <lungth_id68 return value>.x; r0.w <- <lungth_id68 return value>.y; r0.z <- <lungth_id68 return value>.x; r0.w <- <lungth_id68 return value>.y
add r1.xy, r0.wwww, r0.xyxx
dp2 r0.w, r1.xyxx, r1.xyxx
add r0.xy, r0.zzzz, r0.xyxx
dp2 r0.x, r0.xyxx, r0.xyxx
sqrt r3.xy, r0.xwxx  // r3.x <- <lungth_id68 return value>.x; r3.y <- <lungth_id68 return value>.y

#line 184
mad r0.xyz, r3.xyzx, l(8.000000, 8.000000, 8.000000, 0.000000), cb0[2].zzzz
sincos r0.xyz, null, r0.xyzx
mad r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)  // r0.x <- c.x; r0.y <- c.y; r0.z <- c.z

#line 145
dp3 r0.x, l(0.212656, 0.715158, 0.072186, 0.000000), r0.xyzx  // r0.x <- <GetLuminance_id33 return value>

#line 186
add r1.xyzw, -cb0[0].xyzw, cb0[1].xyzw
mad o0.xyzw, r0.xxxx, r1.xyzw, cb0[0].xyzw

#line 195
ret 
// Approximately 52 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id99;
    float4 InputValue_id100;
    float InputValue_id101;
    float InputValue_id102;
    float InputValue_id103;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
    float4x4 Transform_id98;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float GetLuminance_id33(float3 rgb)
{
    return dot(float3(0.212656f, 0.715158f, 0.072186f), rgb);
}
float4 Compute_id74()
{
    return InputValue_id100;
}
float4 Compute_id73()
{
    return InputValue_id99;
}
float Compute_id72()
{
    return InputValue_id102;
}
float Compute_id71()
{
    return InputValue_id101;
}
float3 lungth_id68(float2 x, float3 c)
{
    return float3(length(x + c.r), length(x + c.g), length(x + c.b));
}
float Compute_id70()
{
    return InputValue_id103;
}
float4 Shading_id69(inout PS_STREAMS streams)
{
    float4 c = 0;
    float2 x = streams.TexCoord_id62 - 0.5;
    float time = Compute_id70();
    float4 x2 = mul(float4(x, 0, 1), Transform_id98);
    x = x2.xy / x2.w;
    x += sin(time + x.yx * sqrt(float2(13, 9))) / 5;
    c.rgb = lungth_id68(sin(-time + x * sqrt(float2(33, 43))), float3(5, 6, 7));
    x += sin(time + x.yx * sqrt(float2(73, 53))) / 5;
    c.rgb = 2 * lungth_id68(sin(-time + x * sqrt(float2(33, 23))), c / 9);
    x += sin(time + x.yx * sqrt(float2(93, 73))) / 7;
    c.rgb = lungth_id68(sin(-time + x * sqrt(float2(Compute_id71(), Compute_id72()) * 100)), c / 2);
    c = .5 + .5 * sin(time + c * 8);
    c.a = 1;
    return lerp(Compute_id73(), Compute_id74(), GetLuminance_id33(c.rgb));
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id69(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
