/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_2052566173]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 48]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_1703154449_id16 => input_1703154449
@C    input_3960510402_id17 => input_3960510402
@C    input_2879468750_id18 => input_2879468750
***************************
******  Resources    ******
***************************
@R    TextureInput_2229373571_id12 => TextureInput_2229373571 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_2694680050_id13 => TextureInput_2694680050 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_4017298458_id14 => TextureInput_4017298458 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_3450046882_id15 => TextureInput_3450046882 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_2052566173 => 588aa49ca1f0e88af1b2651e4896dcfd
***************************
*****     Stages      *****
***************************
@G    Compute => 90aeecb26eb7a8b9017cec4ac8e83a09
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_1703154449_id16;        // Offset:   16 Size:    12
//   float input_3960510402_id17;       // Offset:   28 Size:     4 [unused]
//   float3 input_2879468750_id18;      // Offset:   32 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_2229373571_id12      texture   float          3d             t0      1 
// TextureInput_2694680050_id13      texture   float          3d             t1      1 
// TextureInput_4017298458_id14      texture   float          3d             t2      1 
// TextureInput_3450046882_id15          UAV   float          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 3
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 38 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_d0a3e4e40ea8f47025a0edc8ed85c951.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_1403220339; r0.y <- Assign_1745898688; r0.z <- Assign_4076023683

#line 39
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2861774432

#line 44
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.x, r0.xyzw, t0.xyzw  // r1.x <- pressure_2109589880

#line 46
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t2.xyzw  // r0.x <- divergence_3460948108

#line 53
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_527103725.x; r2.y <- result_527103725.y; r2.z <- result_527103725.z

#line 54
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.y, r2.xyzw, t1.yxzw  // r0.y <- getTextureValue_4218983497

#line 55
  lt r0.y, l(0.000000), r0.y  // r0.y <- Assign_26270224

#line 57
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t0.yzxw  // r0.z <- getTextureValue_1068014080

#line 64
  movc r0.y, r0.y, r1.x, r0.z  // r0.y <- output_2290193458

#line 65
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_3048881400.x; r2.y <- result_3048881400.y; r2.z <- result_3048881400.z

#line 66
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t1.yzxw  // r0.z <- getTextureValue_3907735308

#line 67
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_712695600

#line 69
  ld_indexable(texture3d)(float,float,float,float) r0.w, r2.xyzw, t0.yzwx  // r0.w <- getTextureValue_4060046159

#line 76
  movc r0.z, r0.z, r1.x, r0.w  // r0.z <- output_2276822794

#line 77
  iadd r2.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r2.x <- result_229494061.x; r2.y <- result_229494061.y; r2.z <- result_229494061.z

#line 78
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.w, r2.xyzw, t1.yzwx  // r0.w <- getTextureValue_1118225977

#line 79
  lt r0.w, l(0.000000), r0.w  // r0.w <- Assign_2332684075

#line 81
  ld_indexable(texture3d)(float,float,float,float) r1.y, r2.xyzw, t0.yxzw  // r1.y <- getTextureValue_1786356246

#line 88
  movc r0.w, r0.w, r1.x, r1.y  // r0.w <- output_1808405483

#line 89
  iadd r2.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r2.x <- result_3957940500.x; r2.y <- result_3957940500.y; r2.z <- result_3957940500.z

#line 90
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.y, r2.xyzw, t1.yxzw  // r1.y <- getTextureValue_2958143356

#line 91
  lt r1.y, l(0.000000), r1.y  // r1.y <- Assign_1217976115

#line 93
  ld_indexable(texture3d)(float,float,float,float) r1.z, r2.xyzw, t0.yzxw  // r1.z <- getTextureValue_896587101

#line 100
  movc r1.y, r1.y, r1.x, r1.z  // r1.y <- output_2701209747

#line 101
  iadd r2.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r2.x <- result_1350523369.x; r2.y <- result_1350523369.y; r2.z <- result_1350523369.z

#line 102
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.z, r2.xyzw, t1.yzxw  // r1.z <- getTextureValue_963652925

#line 103
  lt r1.z, l(0.000000), r1.z  // r1.z <- Assign_19258173

#line 105
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t0.yzwx  // r1.w <- getTextureValue_3079069854

#line 112
  movc r1.z, r1.z, r1.x, r1.w  // r1.z <- output_4115922145

#line 113
  iadd r2.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r2.x <- result_3836296830.x; r2.y <- result_3836296830.y; r2.z <- result_3836296830.z

#line 114
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t1.yzwx  // r1.w <- getTextureValue_3409152806

#line 115
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_839105959

#line 117
  ld_indexable(texture3d)(float,float,float,float) r2.x, r2.xyzw, t0.xyzw  // r2.x <- getTextureValue_3659840553

#line 124
  movc r1.x, r1.w, r1.x, r2.x  // r1.x <- output_4157131303

#line 125
  add r0.y, r0.z, r0.y
  add r0.y, r0.w, r0.y
  add r0.y, r1.y, r0.y
  add r0.y, r1.z, r0.y
  add r0.y, r1.x, r0.y  // r0.y <- result_3344909092

#line 126
  add r0.x, -r0.x, r0.y  // r0.x <- result_2538366463

#line 127
  mul r0.x, r0.x, l(0.166667)  // r0.x <- result_1233336981

#line 129
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 155
ret 
// Approximately 54 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_1703154449_id16;
    float input_3960510402_id17;
    float3 input_2879468750_id18;
};
Texture3D<float> TextureInput_2229373571_id12;
Texture3D<float> TextureInput_2694680050_id13;
Texture3D<float> TextureInput_4017298458_id14;
RWTexture3D<float> TextureInput_3450046882_id15;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_622466782 = streams.DispatchThreadId_id1.x;
    int inputX_793017481 = input_1703154449_id16.x;
    bool Assign_1403220339 = DispatchThreadIdX_622466782 >= inputX_793017481;
    int DispatchThreadIdY_909295366 = streams.DispatchThreadId_id1.y;
    int inputY_4159513183 = input_1703154449_id16.y;
    bool Assign_1745898688 = DispatchThreadIdY_909295366 >= inputY_4159513183;
    int DispatchThreadIdZ_281173665 = streams.DispatchThreadId_id1.z;
    int inputZ_1973991986 = input_1703154449_id16.z;
    bool Assign_4076023683 = DispatchThreadIdZ_281173665 >= inputZ_1973991986;
    bool result_2861774432 = (Assign_1403220339 || Assign_1745898688 || Assign_4076023683);
    if (result_2861774432)
    {
        return;
    }
    float pressure_2109589880 = TextureInput_2229373571_id12[streams.DispatchThreadId_id1];
    float obstacle_3389810030 = TextureInput_2694680050_id13[streams.DispatchThreadId_id1];
    float divergence_3460948108 = TextureInput_4017298458_id14[streams.DispatchThreadId_id1];
    float deltatime_3503122811 = 0;
    deltatime_3503122811 = input_3960510402_id17;
    int3 index_3893727862 = int3(0, 0, 0);
    index_3893727862 = streams.DispatchThreadId_id1;
    float3 resourcescale_478241009 = float3(0, 0, 0);
    resourcescale_478241009 = input_2879468750_id18;
    int3 result_527103725 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_4218983497 = TextureInput_2694680050_id13[result_527103725];
    bool Assign_26270224 = getTextureValue_4218983497 > 0;
    int3 result_1535585928 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_1068014080 = TextureInput_2229373571_id12[result_1535585928];
    float output_2290193458 = getTextureValue_1068014080;
    float output_1796015373 = 1;
    if (Assign_26270224)
    {
        output_2290193458 = pressure_2109589880;
        output_1796015373 = 0;
    }
    int3 result_3048881400 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_3907735308 = TextureInput_2694680050_id13[result_3048881400];
    bool Assign_712695600 = getTextureValue_3907735308 > 0;
    int3 result_1689125079 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_4060046159 = TextureInput_2229373571_id12[result_1689125079];
    float output_2276822794 = getTextureValue_4060046159;
    float output_2546361189 = 1;
    if (Assign_712695600)
    {
        output_2276822794 = pressure_2109589880;
        output_2546361189 = 0;
    }
    int3 result_229494061 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_1118225977 = TextureInput_2694680050_id13[result_229494061];
    bool Assign_2332684075 = getTextureValue_1118225977 > 0;
    int3 result_3436893614 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_1786356246 = TextureInput_2229373571_id12[result_3436893614];
    float output_1808405483 = getTextureValue_1786356246;
    float output_420579590 = 1;
    if (Assign_2332684075)
    {
        output_1808405483 = pressure_2109589880;
        output_420579590 = 0;
    }
    int3 result_3957940500 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_2958143356 = TextureInput_2694680050_id13[result_3957940500];
    bool Assign_1217976115 = getTextureValue_2958143356 > 0;
    int3 result_2175018449 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_896587101 = TextureInput_2229373571_id12[result_2175018449];
    float output_2701209747 = getTextureValue_896587101;
    float output_65526894 = 1;
    if (Assign_1217976115)
    {
        output_2701209747 = pressure_2109589880;
        output_65526894 = 0;
    }
    int3 result_1350523369 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_963652925 = TextureInput_2694680050_id13[result_1350523369];
    bool Assign_19258173 = getTextureValue_963652925 > 0;
    int3 result_4124795238 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_3079069854 = TextureInput_2229373571_id12[result_4124795238];
    float output_4115922145 = getTextureValue_3079069854;
    float output_3986207494 = 1;
    if (Assign_19258173)
    {
        output_4115922145 = pressure_2109589880;
        output_3986207494 = 0;
    }
    int3 result_3836296830 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_3409152806 = TextureInput_2694680050_id13[result_3836296830];
    bool Assign_839105959 = getTextureValue_3409152806 > 0;
    int3 result_2412841053 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_3659840553 = TextureInput_2229373571_id12[result_2412841053];
    float output_4157131303 = getTextureValue_3659840553;
    float output_235346252 = 1;
    if (Assign_839105959)
    {
        output_4157131303 = pressure_2109589880;
        output_235346252 = 0;
    }
    float result_3344909092 = (output_2290193458 + output_2276822794 + output_1808405483 + output_2701209747 + output_4115922145 + output_4157131303);
    float result_2538366463 = (result_3344909092 - divergence_3460948108);
    float result_1233336981 = (result_2538366463 / 6);
    pressure_2109589880 = result_1233336981;
    TextureInput_3450046882_id15[streams.DispatchThreadId_id1] = pressure_2109589880;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
