/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1079521976]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 176]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_1703154449_id23 => input_1703154449
@C    input_2519643014_id24 => input_2519643014
@C    input_3059385978_id25 => input_3059385978
@C    input_59850909_id26 => input_59850909
@C    input_3690712591_id27 => input_3690712591
@C    input_3325263015_id28 => input_3325263015
@C    input_1421030465_id29 => input_1421030465
@C    input_1218968720_id30 => input_1218968720
***************************
******  Resources    ******
***************************
@R    TextureInput_1821092279_id22 => TextureInput_1821092279 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1079521976 => 256d78fb4556e10d642cf4616825b0fe
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCommonSDF => fd4404bbb9c85d9cbb82982e21c1e34b
@S    FuseCoreMath => b5527ab1f8082f68a6dcc7c3959ee99a
@S    FuseCoreTransform => b43eea1eed94d0f94cf8f317663a8207
@S    FuseCommonTypes => 6c2f0b095ce5f1d9e2781b56961676cd
@S    FuseCoreDomain => c1f7878dfca3e7c2b893bc77be2f5c29
@S    FuseCoreMathMap => a3c63d7e99620b0750ae90d499eee2ad
***************************
*****     Stages      *****
***************************
@G    Compute => 111a917ffff5afaf1a52cab3bc22bf7a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_1703154449_id23;        // Offset:   16 Size:    12
//   float input_2519643014_id24;       // Offset:   28 Size:     4 [unused]
//   float3 input_3059385978_id25;      // Offset:   32 Size:    12 [unused]
//   int3 input_59850909_id26;          // Offset:   48 Size:    12
//   float3 input_3690712591_id27;      // Offset:   64 Size:    12 [unused]
//   float4x4 input_3325263015_id28;    // Offset:   80 Size:    64
//   float3 input_1421030465_id29;      // Offset:  144 Size:    12
//   float3 input_1218968720_id30;      // Offset:  160 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_1821092279_id22          UAV   float          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[11], immediateIndexed
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 2
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 58 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_12c8239a04deea507f960a701404cb5f.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_1403220339; r0.y <- Assign_1745898688; r0.z <- Assign_4076023683

#line 59
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2861774432

#line 64
if_z r0.x

#line 71
  utof r0.xyz, vThreadID.xyzx

#line 72
  add r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r0.x <- result_1473126598.x; r0.y <- result_1473126598.y; r0.z <- result_1473126598.z

#line 73
  itof r1.xyz, cb0[3].xyzx

#line 74
  div r0.xyz, r0.xyzx, r1.xyzx  // r0.x <- result_4162807275.x; r0.y <- result_4162807275.y; r0.z <- result_4162807275.z

#line 75
  add r0.xyz, r0.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)  // r0.x <- result_2133585113.x; r0.y <- result_2133585113.y; r0.z <- result_2133585113.z

#line 80
  mov r0.w, l(1.000000)
  dp4 r1.x, r0.xyzw, cb0[5].xyzw  // r1.x <- mul_4245781215.x
  dp4 r1.y, r0.xyzw, cb0[6].xyzw  // r1.y <- mul_4245781215.y
  dp4 r1.z, r0.xyzw, cb0[7].xyzw  // r1.z <- mul_4245781215.z

#line 82
  add r0.xyz, r1.xyzx, -cb0[9].xyzx  // r0.x <- result_2334881447.x; r0.y <- result_2334881447.y; r0.z <- result_2334881447.z

#line 42
  mad r0.xyz, -cb0[10].xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), |r0.xyzx|
  add r0.xyz, r0.xyzx, l(8.000000, 8.000000, 8.000000, 0.000000)
  max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  dp3 r0.x, r0.xyzx, r0.xyzx
  sqrt r0.x, r0.x
  add r0.x, r0.x, l(-8.000000)  // r0.x <- <fRBox_id75 return value>

#line 85
  lt r0.x, l(0.100000), r0.x  // r0.x <- Assign_594260676

#line 86
  and r0.x, r0.x, l(0x3f800000)

#line 88
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 114
ret 
// Approximately 25 instruction slots used
***************************
*************************/
static const float PI_id12 = 3.1415926535897;
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct Matrix4x4 
{
    float4x4 Matrix;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_1703154449_id23;
    float input_2519643014_id24;
    float3 input_3059385978_id25;
    int3 input_59850909_id26;
    float3 input_3690712591_id27;
    float4x4 input_3325263015_id28;
    float3 input_1421030465_id29;
    float3 input_1218968720_id30;
};
Texture3D<float> TextureInput_2694680050_id21;
RWTexture3D<float> TextureInput_1821092279_id22;
float cast11_id76(float p)
{
    return p;
}
float fRBox_id75(float3 p, float3 b, float rad)
{
    return length(max(abs(p) - b + rad, 0.0)) - rad;
}
float3 cast33_id74(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_622466782 = streams.DispatchThreadId_id1.x;
    int inputX_793017481 = input_1703154449_id23.x;
    bool Assign_1403220339 = DispatchThreadIdX_622466782 >= inputX_793017481;
    int DispatchThreadIdY_909295366 = streams.DispatchThreadId_id1.y;
    int inputY_4159513183 = input_1703154449_id23.y;
    bool Assign_1745898688 = DispatchThreadIdY_909295366 >= inputY_4159513183;
    int DispatchThreadIdZ_281173665 = streams.DispatchThreadId_id1.z;
    int inputZ_1973991986 = input_1703154449_id23.z;
    bool Assign_4076023683 = DispatchThreadIdZ_281173665 >= inputZ_1973991986;
    bool result_2861774432 = (Assign_1403220339 || Assign_1745898688 || Assign_4076023683);
    if (result_2861774432)
    {
        return;
    }
    float obstacle_2109589880 = TextureInput_2694680050_id21[streams.DispatchThreadId_id1];
    float deltatime_3731538207 = 0;
    deltatime_3731538207 = input_2519643014_id24;
    int3 index_3225087578 = int3(0, 0, 0);
    index_3225087578 = streams.DispatchThreadId_id1;
    float3 resourcescale_527083029 = float3(0, 0, 0);
    resourcescale_527083029 = input_3059385978_id25;
    float3 cast33_530444815 = cast33_id74(streams.DispatchThreadId_id1);
    float3 result_1473126598 = (cast33_530444815 + float3(0.5, 0.5, 0.5));
    float3 cast33_3122116249 = cast33_id74(input_59850909_id26);
    float3 result_4162807275 = (result_1473126598 / cast33_3122116249);
    float3 result_2133585113 = (result_4162807275 - 0.5);
    float3 result_1381991010 = (float3(0.5, 0.5, 0.5) - float3(0.5, 0.5, 0.5));
    float3 result_1275529357 = (result_1381991010 * input_3690712591_id27);
    float3 result_1344204095 = (result_2133585113 + result_1275529357);
    float4 join_3597033850 = float4(result_1344204095, 1);
    float4 mul_4245781215 = mul(join_3597033850, input_3325263015_id28);
    float3 mulXyz_2442471908 = mul_4245781215.xyz;
    float3 result_2334881447 = (mulXyz_2442471908 - input_1421030465_id29);
    float3 result_3739578549 = (input_1218968720_id30 * 0.5);
    float fRBox_1433147619 = fRBox_id75(result_2334881447, result_3739578549, 8);
    bool Assign_594260676 = fRBox_1433147619 > 0.1;
    float cast11_166269051 = cast11_id76(Assign_594260676);
    obstacle_2109589880 = cast11_166269051;
    TextureInput_1821092279_id22[streams.DispatchThreadId_id1] = obstacle_2109589880;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
