/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1496176109]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 48]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_2286105837_id16 => input_2286105837
@C    input_1605285521_id17 => input_1605285521
@C    input_1364864973_id18 => input_1364864973
***************************
******  Resources    ******
***************************
@R    TextureInput_2669864248_id12 => TextureInput_2669864248 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_2283284131_id13 => TextureInput_2283284131 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_2510865218_id14 => TextureInput_2510865218 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_1226110717_id15 => TextureInput_1226110717 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1496176109 => 4ec806bb53eef473f804042072cfcdc5
***************************
*****     Stages      *****
***************************
@G    Compute => 870bc176bdd2c713da6f19e950256362
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_2286105837_id16;        // Offset:   16 Size:    12
//   float input_1605285521_id17;       // Offset:   28 Size:     4 [unused]
//   float3 input_1364864973_id18;      // Offset:   32 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_2669864248_id12      texture  float4          3d             t0      1 
// TextureInput_2283284131_id13      texture   float          3d             t1      1 
// TextureInput_2510865218_id14      texture   float          3d             t2      1 
// TextureInput_1226110717_id15          UAV  float4          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 6
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 38 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_0d0992cfcefe96c6afa35b33e02485b9.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_536001411; r0.y <- Assign_3859735600; r0.z <- Assign_42903651

#line 39
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_1581015312

#line 44
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyz, r0.xyzw, t0.xyzw  // r1.x <- velocity_169094072.x; r1.y <- velocity_169094072.y; r1.z <- velocity_169094072.z

#line 45
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- pressure_480588738

#line 54
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_3209176986.x; r2.y <- result_3209176986.y; r2.z <- result_3209176986.z

#line 55
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t2.yzwx  // r1.w <- getTextureValue_136344354

#line 56
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_2953530348

#line 58
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t1.yzxw  // r0.z <- getTextureValue_2869430305

#line 65
  mov r0.yw, l(0,0,0,1.000000)
  movc r0.zw, r1.wwww, r0.xxxy, r0.zzzw  // r0.z <- output_2023465654; r0.w <- output_1067417617

#line 66
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_1894766323.x; r2.y <- result_1894766323.y; r2.z <- result_1894766323.z

#line 67
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t2.yzwx  // r1.w <- getTextureValue_2033878395

#line 68
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_996231594

#line 70
  ld_indexable(texture3d)(float,float,float,float) r2.x, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_2539775492

#line 90
  mov r2.yw, l(0,1.000000,0,1.000000)

#line 77
  movc r2.xy, r1.wwww, r0.xyxx, r2.xyxx  // r2.x <- output_1291075296; r2.y <- output_1163351675

#line 78
  add r3.x, r0.z, -r2.x  // r3.x <- result_2049612091

#line 79
  iadd r4.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r4.x <- result_2950975722.x; r4.y <- result_2950975722.y; r4.z <- result_2950975722.z

#line 80
  mov r4.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r4.xyzw, t2.yzxw  // r0.z <- getTextureValue_2023940062

#line 81
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_1661755908

#line 83
  ld_indexable(texture3d)(float,float,float,float) r2.z, r4.xyzw, t1.yzxw  // r2.z <- getTextureValue_1420415399

#line 90
  movc r2.xz, r0.zzzz, r0.xxyx, r2.zzwz  // r2.x <- output_4289901710; r2.z <- output_2975788265

#line 91
  iadd r4.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r4.x <- result_889255819.x; r4.y <- result_889255819.y; r4.z <- result_889255819.z

#line 92
  mov r4.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r4.xyzw, t2.yzxw  // r0.z <- getTextureValue_1320296099

#line 93
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_2535344184

#line 95
  ld_indexable(texture3d)(float,float,float,float) r4.x, r4.xyzw, t1.xyzw  // r4.x <- getTextureValue_2096451534

#line 115
  mov r4.yw, l(0,1.000000,0,1.000000)

#line 102
  movc r4.xy, r0.zzzz, r0.xyxx, r4.xyxx  // r4.x <- output_2942354450; r4.y <- output_881495213

#line 103
  add r3.y, r2.x, -r4.x  // r3.y <- result_2988962812

#line 104
  iadd r5.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r5.x <- result_4070302172.x; r5.y <- result_4070302172.y; r5.z <- result_4070302172.z

#line 105
  mov r5.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r5.xyzw, t2.yzxw  // r0.z <- getTextureValue_2214461456

#line 106
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_3372203995

#line 108
  ld_indexable(texture3d)(float,float,float,float) r4.z, r5.xyzw, t1.yzxw  // r4.z <- getTextureValue_1711613147

#line 115
  movc r2.xw, r0.zzzz, r0.xxxy, r4.zzzw  // r2.x <- output_3860190331; r2.w <- output_3752036950

#line 116
  iadd r5.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r5.x <- result_3907771027.x; r5.y <- result_3907771027.y; r5.z <- result_3907771027.z

#line 117
  mov r5.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r5.xyzw, t2.yzxw  // r0.z <- getTextureValue_3783931355

#line 118
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_2461750611

#line 120
  ld_indexable(texture3d)(float,float,float,float) r4.x, r5.xyzw, t1.xzyw  // r4.x <- getTextureValue_1764699026

#line 127
  mov r4.z, l(1.000000)
  movc r0.xy, r0.zzzz, r0.xyxx, r4.xzxx  // r0.x <- output_265688835; r0.y <- output_1846681704

#line 128
  add r3.z, -r0.x, r2.x  // r3.z <- result_740101116

#line 131
  mad r1.xyz, -r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx  // r1.x <- result_3652685916.x; r1.y <- result_3652685916.y; r1.z <- result_3652685916.z

#line 132
  min r3.x, r0.w, r2.y  // r3.x <- min_231345627

#line 133
  min r3.y, r2.z, r4.y  // r3.y <- min_286287055

#line 134
  min r3.z, r2.w, r0.y  // r3.z <- min_732996597

#line 136
  mul r0.xyz, r1.xyzx, r3.xyzx  // r0.x <- result_3246382491.x; r0.y <- result_3246382491.y; r0.z <- result_3246382491.z

#line 139
  mov r0.w, l(0)
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xyzw
endif 

#line 165
ret 
// Approximately 60 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_2286105837_id16;
    float input_1605285521_id17;
    float3 input_1364864973_id18;
};
Texture3D<float4> TextureInput_2669864248_id12;
Texture3D<float> TextureInput_2283284131_id13;
Texture3D<float> TextureInput_2510865218_id14;
RWTexture3D<float4> TextureInput_1226110717_id15;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_2247141374 = streams.DispatchThreadId_id1.x;
    int inputX_1046803885 = input_2286105837_id16.x;
    bool Assign_536001411 = DispatchThreadIdX_2247141374 >= inputX_1046803885;
    int DispatchThreadIdY_717330578 = streams.DispatchThreadId_id1.y;
    int inputY_3027621359 = input_2286105837_id16.y;
    bool Assign_3859735600 = DispatchThreadIdY_717330578 >= inputY_3027621359;
    int DispatchThreadIdZ_2793580973 = streams.DispatchThreadId_id1.z;
    int inputZ_1984482882 = input_2286105837_id16.z;
    bool Assign_42903651 = DispatchThreadIdZ_2793580973 >= inputZ_1984482882;
    bool result_1581015312 = (Assign_536001411 || Assign_3859735600 || Assign_42903651);
    if (result_1581015312)
    {
        return;
    }
    float4 velocity_169094072 = TextureInput_2669864248_id12[streams.DispatchThreadId_id1];
    float pressure_480588738 = TextureInput_2283284131_id13[streams.DispatchThreadId_id1];
    float obstacle_2716743372 = TextureInput_2510865218_id14[streams.DispatchThreadId_id1];
    float deltatime_3023238498 = 0;
    deltatime_3023238498 = input_1605285521_id17;
    int3 index_4118288039 = int3(0, 0, 0);
    index_4118288039 = streams.DispatchThreadId_id1;
    float3 resourcescale_247452268 = float3(0, 0, 0);
    resourcescale_247452268 = input_1364864973_id18;
    float3 VelocityXyz_1062518807 = velocity_169094072.xyz;
    int3 result_3209176986 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_136344354 = TextureInput_2510865218_id14[result_3209176986];
    bool Assign_2953530348 = getTextureValue_136344354 > 0;
    int3 result_1059801069 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_2869430305 = TextureInput_2283284131_id13[result_1059801069];
    float output_2023465654 = getTextureValue_2869430305;
    float output_1067417617 = 1;
    if (Assign_2953530348)
    {
        output_2023465654 = pressure_480588738;
        output_1067417617 = 0;
    }
    int3 result_1894766323 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_2033878395 = TextureInput_2510865218_id14[result_1894766323];
    bool Assign_996231594 = getTextureValue_2033878395 > 0;
    int3 result_698497320 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_2539775492 = TextureInput_2283284131_id13[result_698497320];
    float output_1291075296 = getTextureValue_2539775492;
    float output_1163351675 = 1;
    if (Assign_996231594)
    {
        output_1291075296 = pressure_480588738;
        output_1163351675 = 0;
    }
    float result_2049612091 = (output_2023465654 - output_1291075296);
    int3 result_2950975722 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_2023940062 = TextureInput_2510865218_id14[result_2950975722];
    bool Assign_1661755908 = getTextureValue_2023940062 > 0;
    int3 result_3141377375 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_1420415399 = TextureInput_2283284131_id13[result_3141377375];
    float output_4289901710 = getTextureValue_1420415399;
    float output_2975788265 = 1;
    if (Assign_1661755908)
    {
        output_4289901710 = pressure_480588738;
        output_2975788265 = 0;
    }
    int3 result_889255819 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_1320296099 = TextureInput_2510865218_id14[result_889255819];
    bool Assign_2535344184 = getTextureValue_1320296099 > 0;
    int3 result_4178158882 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_2096451534 = TextureInput_2283284131_id13[result_4178158882];
    float output_2942354450 = getTextureValue_2096451534;
    float output_881495213 = 1;
    if (Assign_2535344184)
    {
        output_2942354450 = pressure_480588738;
        output_881495213 = 0;
    }
    float result_2988962812 = (output_4289901710 - output_2942354450);
    int3 result_4070302172 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_2214461456 = TextureInput_2510865218_id14[result_4070302172];
    bool Assign_3372203995 = getTextureValue_2214461456 > 0;
    int3 result_2564502355 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_1711613147 = TextureInput_2283284131_id13[result_2564502355];
    float output_3860190331 = getTextureValue_1711613147;
    float output_3752036950 = 1;
    if (Assign_3372203995)
    {
        output_3860190331 = pressure_480588738;
        output_3752036950 = 0;
    }
    int3 result_3907771027 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_3783931355 = TextureInput_2510865218_id14[result_3907771027];
    bool Assign_2461750611 = getTextureValue_3783931355 > 0;
    int3 result_2506214046 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_1764699026 = TextureInput_2283284131_id13[result_2506214046];
    float output_265688835 = getTextureValue_1764699026;
    float output_1846681704 = 1;
    if (Assign_2461750611)
    {
        output_265688835 = pressure_480588738;
        output_1846681704 = 0;
    }
    float result_740101116 = (output_3860190331 - output_265688835);
    float3 Float3Join_1883312209 = float3(result_2049612091, result_2988962812, result_740101116);
    float3 result_308579340 = (Float3Join_1883312209 * 0.5);
    float3 result_3652685916 = (VelocityXyz_1062518807 - result_308579340);
    float min_231345627 = min(output_1163351675, output_1067417617);
    float min_286287055 = min(output_881495213, output_2975788265);
    float min_732996597 = min(output_1846681704, output_3752036950);
    float3 Float3Join_2814202717 = float3(min_231345627, min_286287055, min_732996597);
    float3 result_3246382491 = (result_3652685916 * Float3Join_2814202717);
    float4 join_4127134882 = float4(result_3246382491, 0);
    velocity_169094072 = join_4127134882;
    TextureInput_1226110717_id15[streams.DispatchThreadId_id1] = velocity_169094072;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
