/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1282937828]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 64]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_1703154449_id15 => input_1703154449
@C    input_1217370278_id16 => input_1217370278
@C    input_2359453762_id17 => input_2359453762
@C    input_313248266_id18 => input_313248266
@C    input_85620376_id19 => input_85620376
@C    input_2931971424_id20 => input_2931971424
@C    input_3615746021_id21 => input_3615746021
***************************
******  Resources    ******
***************************
@R    TextureInput_3751006716_id12 => TextureInput_3751006716 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_1576450064_id13 => TextureInput_1576450064 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_3468441537_id14 => TextureInput_3468441537 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1282937828 => c0b753f25d5d1be67f1fd6e34e509bdf
***************************
*****     Stages      *****
***************************
@G    Compute => 450c556e78d8ff2f1227f91c3ee1d01c
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_1703154449_id15;        // Offset:   16 Size:    12
//   float input_1217370278_id16;       // Offset:   28 Size:     4 [unused]
//   float3 input_2359453762_id17;      // Offset:   32 Size:    12 [unused]
//   float input_313248266_id18;        // Offset:   44 Size:     4
//   float input_85620376_id19;         // Offset:   48 Size:     4
//   float input_2931971424_id20;       // Offset:   52 Size:     4
//   float input_3615746021_id21;       // Offset:   56 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_3751006716_id12      texture  float4          3d             t0      1 
// TextureInput_1576450064_id13      texture  float4          3d             t1      1 
// TextureInput_3468441537_id14          UAV  float4          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 4
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 41 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_6404f132c4a4c9240147f0d7f6a6803e.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_1403220339; r0.y <- Assign_1745898688; r0.z <- Assign_4076023683

#line 42
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2861774432

#line 47
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyzw, r0.xyzw, t0.xyzw  // r1.x <- velocity_2109589880.x; r1.y <- velocity_2109589880.y; r1.z <- velocity_2109589880.z; r1.w <- velocity_2109589880.w

#line 48
  ld_indexable(texture3d)(float,float,float,float) r0.xyz, r0.xyzw, t1.xyzw  // r0.x <- vorticity_3389810030.x; r0.y <- vorticity_3389810030.y; r0.z <- vorticity_3389810030.z

#line 55
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_717965666.x; r2.y <- result_717965666.y; r2.z <- result_717965666.z

#line 56
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r2.xyzw, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_3060123162.x; r2.y <- getTextureValue_3060123162.y; r2.z <- getTextureValue_3060123162.z; r2.w <- getTextureValue_3060123162.w

#line 57
  dp4 r0.w, r2.xyzw, r2.xyzw
  sqrt r0.w, r0.w  // r0.w <- length_2906514044

#line 58
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_1955752875.x; r2.y <- result_1955752875.y; r2.z <- result_1955752875.z

#line 59
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r2.xyzw, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_844666115.x; r2.y <- getTextureValue_844666115.y; r2.z <- getTextureValue_844666115.z; r2.w <- getTextureValue_844666115.w

#line 60
  dp4 r2.x, r2.xyzw, r2.xyzw
  sqrt r2.x, r2.x  // r2.x <- length_1648039568

#line 61
  add r2.y, r0.w, -r2.x  // r2.y <- result_777834727

#line 62
  iadd r3.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r3.x <- result_877083742.x; r3.y <- result_877083742.y; r3.z <- result_877083742.z

#line 63
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_3905621930.x; r3.y <- getTextureValue_3905621930.y; r3.z <- getTextureValue_3905621930.z; r3.w <- getTextureValue_3905621930.w

#line 64
  dp4 r0.w, r3.xyzw, r3.xyzw
  sqrt r0.w, r0.w  // r0.w <- length_1093066060

#line 65
  iadd r3.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r3.x <- result_1815655491.x; r3.y <- result_1815655491.y; r3.z <- result_1815655491.z

#line 66
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_892528555.x; r3.y <- getTextureValue_892528555.y; r3.z <- getTextureValue_892528555.z; r3.w <- getTextureValue_892528555.w

#line 67
  dp4 r2.w, r3.xyzw, r3.xyzw
  sqrt r2.w, r2.w  // r2.w <- length_3475955012

#line 68
  add r2.z, r0.w, -r2.w  // r2.z <- result_1967553265

#line 69
  iadd r3.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r3.x <- result_1092766480.x; r3.y <- result_1092766480.y; r3.z <- result_1092766480.z

#line 70
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_3598906908.x; r3.y <- getTextureValue_3598906908.y; r3.z <- getTextureValue_3598906908.z; r3.w <- getTextureValue_3598906908.w

#line 71
  dp4 r0.w, r3.xyzw, r3.xyzw
  sqrt r0.w, r0.w  // r0.w <- length_1740354047

#line 72
  iadd r3.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r3.x <- result_2114527707.x; r3.y <- result_2114527707.y; r3.z <- result_2114527707.z

#line 73
  mov r3.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r3.xyzw, r3.xyzw, t1.xyzw  // r3.x <- getTextureValue_2452572371.x; r3.y <- getTextureValue_2452572371.y; r3.z <- getTextureValue_2452572371.z; r3.w <- getTextureValue_2452572371.w

#line 74
  dp4 r2.w, r3.xyzw, r3.xyzw
  sqrt r2.w, r2.w  // r2.w <- length_4196322581

#line 75
  add r2.x, r0.w, -r2.w  // r2.x <- result_1220164722

#line 78
  mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.001000, 0.001000, 0.001000, 0.000000)  // r2.x <- result_2244230760.z; r2.y <- result_2244230760.x; r2.z <- result_2244230760.y

#line 79
  dp3 r0.w, r2.xyzx, r2.xyzx
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r2.xyzx  // r2.x <- normalize_2595148666.z; r2.y <- normalize_2595148666.x; r2.z <- normalize_2595148666.y

#line 81
  mul r3.xyz, r0.yzxy, r2.xyzx
  mad r0.xyz, r2.zxyz, r0.zxyz, -r3.xyzx  // r0.x <- cross_3550159336.x; r0.y <- cross_3550159336.y; r0.z <- cross_3550159336.z

#line 82
  add r0.w, -cb0[3].x, cb0[3].y
  mad r0.w, cb0[3].z, r0.w, cb0[3].x  // r0.w <- lerp_3245109345

#line 83
  mul r0.w, r0.w, cb0[2].w  // r0.w <- result_3404440789

#line 84
  mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- result_4015401150.x; r0.y <- result_4015401150.y; r0.z <- result_4015401150.z

#line 86
  mov r0.w, l(0)
  add r0.xyzw, r0.xyzw, r1.xyzw  // r0.x <- result_1331015931.x; r0.y <- result_1331015931.y; r0.z <- result_1331015931.z; r0.w <- result_1331015931.w

#line 88
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xyzw
endif 

#line 114
ret 
// Approximately 56 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_1703154449_id15;
    float input_1217370278_id16;
    float3 input_2359453762_id17;
    float input_313248266_id18;
    float input_85620376_id19;
    float input_2931971424_id20;
    float input_3615746021_id21;
};
Texture3D<float4> TextureInput_3751006716_id12;
Texture3D<float4> TextureInput_1576450064_id13;
RWTexture3D<float4> TextureInput_3468441537_id14;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_622466782 = streams.DispatchThreadId_id1.x;
    int inputX_793017481 = input_1703154449_id15.x;
    bool Assign_1403220339 = DispatchThreadIdX_622466782 >= inputX_793017481;
    int DispatchThreadIdY_909295366 = streams.DispatchThreadId_id1.y;
    int inputY_4159513183 = input_1703154449_id15.y;
    bool Assign_1745898688 = DispatchThreadIdY_909295366 >= inputY_4159513183;
    int DispatchThreadIdZ_281173665 = streams.DispatchThreadId_id1.z;
    int inputZ_1973991986 = input_1703154449_id15.z;
    bool Assign_4076023683 = DispatchThreadIdZ_281173665 >= inputZ_1973991986;
    bool result_2861774432 = (Assign_1403220339 || Assign_1745898688 || Assign_4076023683);
    if (result_2861774432)
    {
        return;
    }
    float4 velocity_2109589880 = TextureInput_3751006716_id12[streams.DispatchThreadId_id1];
    float4 vorticity_3389810030 = TextureInput_1576450064_id13[streams.DispatchThreadId_id1];
    float deltatime_557935429 = 0;
    deltatime_557935429 = input_1217370278_id16;
    int3 index_3851885706 = int3(0, 0, 0);
    index_3851885706 = streams.DispatchThreadId_id1;
    float3 resourcescale_1691648315 = float3(0, 0, 0);
    resourcescale_1691648315 = input_2359453762_id17;
    int3 result_717965666 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float4 getTextureValue_3060123162 = TextureInput_1576450064_id13[result_717965666];
    float length_2906514044 = length(getTextureValue_3060123162);
    int3 result_1955752875 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float4 getTextureValue_844666115 = TextureInput_1576450064_id13[result_1955752875];
    float length_1648039568 = length(getTextureValue_844666115);
    float result_777834727 = (length_2906514044 - length_1648039568);
    int3 result_877083742 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float4 getTextureValue_3905621930 = TextureInput_1576450064_id13[result_877083742];
    float length_1093066060 = length(getTextureValue_3905621930);
    int3 result_1815655491 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float4 getTextureValue_892528555 = TextureInput_1576450064_id13[result_1815655491];
    float length_3475955012 = length(getTextureValue_892528555);
    float result_1967553265 = (length_1093066060 - length_3475955012);
    int3 result_1092766480 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float4 getTextureValue_3598906908 = TextureInput_1576450064_id13[result_1092766480];
    float length_1740354047 = length(getTextureValue_3598906908);
    int3 result_2114527707 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float4 getTextureValue_2452572371 = TextureInput_1576450064_id13[result_2114527707];
    float length_4196322581 = length(getTextureValue_2452572371);
    float result_1220164722 = (length_1740354047 - length_4196322581);
    float3 Float3Join_3318185896 = float3(result_777834727, result_1967553265, result_1220164722);
    float3 result_3437845857 = (Float3Join_3318185896 * 0.5);
    float3 result_2244230760 = (result_3437845857 + 0.001);
    float3 normalize_2595148666 = normalize(result_2244230760);
    float3 VorticityXyz_4062166033 = vorticity_3389810030.xyz;
    float3 cross_3550159336 = cross(normalize_2595148666, VorticityXyz_4062166033);
    float lerp_3245109345 = lerp(input_85620376_id19, input_2931971424_id20, input_3615746021_id21);
    float result_3404440789 = (input_313248266_id18 * lerp_3245109345);
    float3 result_4015401150 = (cross_3550159336 * result_3404440789);
    float4 join_3276110108 = float4(result_4015401150, 0);
    float4 result_1331015931 = (velocity_2109589880 + join_3276110108);
    velocity_2109589880 = result_1331015931;
    TextureInput_3468441537_id14[streams.DispatchThreadId_id1] = velocity_2109589880;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
