/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_331844078]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 48]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_838590723_id16 => input_838590723
@C    input_3796337407_id17 => input_3796337407
@C    input_321535963_id18 => input_321535963
***************************
******  Resources    ******
***************************
@R    TextureInput_2957714998_id12 => TextureInput_2957714998 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_1030055249_id13 => TextureInput_1030055249 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_1224669504_id14 => TextureInput_1224669504 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_1941307003_id15 => TextureInput_1941307003 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_331844078 => a749dab513d2373d2071018f739c65c7
***************************
*****     Stages      *****
***************************
@G    Compute => 870bc176bdd2c713da6f19e950256362
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_838590723_id16;         // Offset:   16 Size:    12
//   float input_3796337407_id17;       // Offset:   28 Size:     4 [unused]
//   float3 input_321535963_id18;       // Offset:   32 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_2957714998_id12      texture  float4          3d             t0      1 
// TextureInput_1030055249_id13      texture   float          3d             t1      1 
// TextureInput_1224669504_id14      texture   float          3d             t2      1 
// TextureInput_1941307003_id15          UAV  float4          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 6
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 38 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_30519592db1809204d041b630863c57f.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_3689940353; r0.y <- Assign_1627392202; r0.z <- Assign_1774890877

#line 39
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_1149744962

#line 44
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyz, r0.xyzw, t0.xyzw  // r1.x <- velocity_977671682.x; r1.y <- velocity_977671682.y; r1.z <- velocity_977671682.z

#line 45
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- pressure_2320042252

#line 54
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_4277293680.x; r2.y <- result_4277293680.y; r2.z <- result_4277293680.z

#line 55
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t2.yzwx  // r1.w <- getTextureValue_1795709652

#line 56
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_1894347406

#line 58
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t1.yzxw  // r0.z <- getTextureValue_1151665119

#line 65
  mov r0.yw, l(0,0,0,1.000000)
  movc r0.zw, r1.wwww, r0.xxxy, r0.zzzw  // r0.z <- output_954361140; r0.w <- output_353287887

#line 66
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_259741365.x; r2.y <- result_259741365.y; r2.z <- result_259741365.z

#line 67
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t2.yzwx  // r1.w <- getTextureValue_2410727873

#line 68
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_4062632012

#line 70
  ld_indexable(texture3d)(float,float,float,float) r2.x, r2.xyzw, t1.xyzw  // r2.x <- getTextureValue_296687790

#line 90
  mov r2.yw, l(0,1.000000,0,1.000000)

#line 77
  movc r2.xy, r1.wwww, r0.xyxx, r2.xyxx  // r2.x <- output_2024438814; r2.y <- output_3040666617

#line 78
  add r3.x, r0.z, -r2.x  // r3.x <- result_3168498413

#line 79
  iadd r4.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r4.x <- result_2485676908.x; r4.y <- result_2485676908.y; r4.z <- result_2485676908.z

#line 80
  mov r4.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r4.xyzw, t2.yzxw  // r0.z <- getTextureValue_1700522468

#line 81
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_3447917318

#line 83
  ld_indexable(texture3d)(float,float,float,float) r2.z, r4.xyzw, t1.yzxw  // r2.z <- getTextureValue_758541073

#line 90
  movc r2.xz, r0.zzzz, r0.xxyx, r2.zzwz  // r2.x <- output_258931628; r2.z <- output_4005931335

#line 91
  iadd r4.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r4.x <- result_633267413.x; r4.y <- result_633267413.y; r4.z <- result_633267413.z

#line 92
  mov r4.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r4.xyzw, t2.yzxw  // r0.z <- getTextureValue_3738288721

#line 93
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_480778834

#line 95
  ld_indexable(texture3d)(float,float,float,float) r4.x, r4.xyzw, t1.xyzw  // r4.x <- getTextureValue_1702428976

#line 115
  mov r4.yw, l(0,1.000000,0,1.000000)

#line 102
  movc r4.xy, r0.zzzz, r0.xyxx, r4.xyxx  // r4.x <- output_3476135976; r4.y <- output_138826755

#line 103
  add r3.y, r2.x, -r4.x  // r3.y <- result_533103114

#line 104
  iadd r5.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r5.x <- result_228724166.x; r5.y <- result_228724166.y; r5.z <- result_228724166.z

#line 105
  mov r5.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r5.xyzw, t2.yzxw  // r0.z <- getTextureValue_2682593822

#line 106
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_3150853429

#line 108
  ld_indexable(texture3d)(float,float,float,float) r4.z, r5.xyzw, t1.yzxw  // r4.z <- getTextureValue_1185161437

#line 115
  movc r2.xw, r0.zzzz, r0.xxxy, r4.zzzw  // r2.x <- output_1695445009; r2.w <- output_2251648044

#line 116
  iadd r5.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r5.x <- result_307240417.x; r5.y <- result_307240417.y; r5.z <- result_307240417.z

#line 117
  mov r5.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r5.xyzw, t2.yzxw  // r0.z <- getTextureValue_2635657221

#line 118
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_1808311581

#line 120
  ld_indexable(texture3d)(float,float,float,float) r4.x, r5.xyzw, t1.xzyw  // r4.x <- getTextureValue_821691352

#line 127
  mov r4.z, l(1.000000)
  movc r0.xy, r0.zzzz, r0.xyxx, r4.xzxx  // r0.x <- output_4098330697; r0.y <- output_852457582

#line 128
  add r3.z, -r0.x, r2.x  // r3.z <- result_3826294838

#line 131
  mad r1.xyz, -r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx  // r1.x <- result_3980734354.x; r1.y <- result_3980734354.y; r1.z <- result_3980734354.z

#line 132
  min r3.x, r0.w, r2.y  // r3.x <- min_3725740653

#line 133
  min r3.y, r2.z, r4.y  // r3.y <- min_4046617193

#line 134
  min r3.z, r2.w, r0.y  // r3.z <- min_95028791

#line 136
  mul r0.xyz, r1.xyzx, r3.xyzx  // r0.x <- result_4089719157.x; r0.y <- result_4089719157.y; r0.z <- result_4089719157.z

#line 139
  mov r0.w, l(0)
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xyzw
endif 

#line 165
ret 
// Approximately 60 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_838590723_id16;
    float input_3796337407_id17;
    float3 input_321535963_id18;
};
Texture3D<float4> TextureInput_2957714998_id12;
Texture3D<float> TextureInput_1030055249_id13;
Texture3D<float> TextureInput_1224669504_id14;
RWTexture3D<float4> TextureInput_1941307003_id15;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_2062887072 = streams.DispatchThreadId_id1.x;
    int inputX_181602231 = input_838590723_id16.x;
    bool Assign_3689940353 = DispatchThreadIdX_2062887072 >= inputX_181602231;
    int DispatchThreadIdY_1977333336 = streams.DispatchThreadId_id1.y;
    int inputY_3191009213 = input_838590723_id16.y;
    bool Assign_1627392202 = DispatchThreadIdY_1977333336 >= inputY_3191009213;
    int DispatchThreadIdZ_1073105291 = streams.DispatchThreadId_id1.z;
    int inputZ_1725069496 = input_838590723_id16.z;
    bool Assign_1774890877 = DispatchThreadIdZ_1073105291 >= inputZ_1725069496;
    bool result_1149744962 = (Assign_3689940353 || Assign_1627392202 || Assign_1774890877);
    if (result_1149744962)
    {
        return;
    }
    float4 velocity_977671682 = TextureInput_2957714998_id12[streams.DispatchThreadId_id1];
    float pressure_2320042252 = TextureInput_1030055249_id13[streams.DispatchThreadId_id1];
    float obstacle_271962606 = TextureInput_1224669504_id14[streams.DispatchThreadId_id1];
    float deltatime_2211604156 = 0;
    deltatime_2211604156 = input_3796337407_id17;
    int3 index_3610754817 = int3(0, 0, 0);
    index_3610754817 = streams.DispatchThreadId_id1;
    float3 resourcescale_828581830 = float3(0, 0, 0);
    resourcescale_828581830 = input_321535963_id18;
    float3 VelocityXyz_3536234389 = velocity_977671682.xyz;
    int3 result_4277293680 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_1795709652 = TextureInput_1224669504_id14[result_4277293680];
    bool Assign_1894347406 = getTextureValue_1795709652 > 0;
    int3 result_3828181415 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_1151665119 = TextureInput_1030055249_id13[result_3828181415];
    float output_954361140 = getTextureValue_1151665119;
    float output_353287887 = 1;
    if (Assign_1894347406)
    {
        output_954361140 = pressure_2320042252;
        output_353287887 = 0;
    }
    int3 result_259741365 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_2410727873 = TextureInput_1224669504_id14[result_259741365];
    bool Assign_4062632012 = getTextureValue_2410727873 > 0;
    int3 result_2742490742 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_296687790 = TextureInput_1030055249_id13[result_2742490742];
    float output_2024438814 = getTextureValue_296687790;
    float output_3040666617 = 1;
    if (Assign_4062632012)
    {
        output_2024438814 = pressure_2320042252;
        output_3040666617 = 0;
    }
    float result_3168498413 = (output_954361140 - output_2024438814);
    int3 result_2485676908 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_1700522468 = TextureInput_1224669504_id14[result_2485676908];
    bool Assign_3447917318 = getTextureValue_1700522468 > 0;
    int3 result_3519339373 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_758541073 = TextureInput_1030055249_id13[result_3519339373];
    float output_258931628 = getTextureValue_758541073;
    float output_4005931335 = 1;
    if (Assign_3447917318)
    {
        output_258931628 = pressure_2320042252;
        output_4005931335 = 0;
    }
    int3 result_633267413 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_3738288721 = TextureInput_1224669504_id14[result_633267413];
    bool Assign_480778834 = getTextureValue_3738288721 > 0;
    int3 result_2955117256 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_1702428976 = TextureInput_1030055249_id13[result_2955117256];
    float output_3476135976 = getTextureValue_1702428976;
    float output_138826755 = 1;
    if (Assign_480778834)
    {
        output_3476135976 = pressure_2320042252;
        output_138826755 = 0;
    }
    float result_533103114 = (output_258931628 - output_3476135976);
    int3 result_228724166 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_2682593822 = TextureInput_1224669504_id14[result_228724166];
    bool Assign_3150853429 = getTextureValue_2682593822 > 0;
    int3 result_1382251097 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_1185161437 = TextureInput_1030055249_id13[result_1382251097];
    float output_1695445009 = getTextureValue_1185161437;
    float output_2251648044 = 1;
    if (Assign_3150853429)
    {
        output_1695445009 = pressure_2320042252;
        output_2251648044 = 0;
    }
    int3 result_307240417 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_2635657221 = TextureInput_1224669504_id14[result_307240417];
    bool Assign_1808311581 = getTextureValue_2635657221 > 0;
    int3 result_3149439968 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_821691352 = TextureInput_1030055249_id13[result_3149439968];
    float output_4098330697 = getTextureValue_821691352;
    float output_852457582 = 1;
    if (Assign_1808311581)
    {
        output_4098330697 = pressure_2320042252;
        output_852457582 = 0;
    }
    float result_3826294838 = (output_1695445009 - output_4098330697);
    float3 Float3Join_3783268715 = float3(result_3168498413, result_533103114, result_3826294838);
    float3 result_1811043170 = (Float3Join_3783268715 * 0.5);
    float3 result_3980734354 = (VelocityXyz_3536234389 - result_1811043170);
    float min_3725740653 = min(output_3040666617, output_353287887);
    float min_4046617193 = min(output_138826755, output_4005931335);
    float min_95028791 = min(output_852457582, output_2251648044);
    float3 Float3Join_3976609927 = float3(min_3725740653, min_4046617193, min_95028791);
    float3 result_4089719157 = (result_3980734354 * Float3Join_3976609927);
    float4 join_4143332820 = float4(result_4089719157, 0);
    velocity_977671682 = join_4143332820;
    TextureInput_1941307003_id15[streams.DispatchThreadId_id1] = velocity_977671682;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
