/**************************
***** Compiler Parameters *****
***************************
@P EffectName: Shader_10346568
***************************
****  ConstantBuffers  ****
***************************
cbuffer Inputs [Size: 112]
@C    input_2363487899_id39 => input_2363487899
@C    input_694888891_id40 => input_694888891
@C    input_2101078675_id41 => input_2101078675
@C    input_2768893694_id42 => input_2768893694
@C    input_763341816_id43 => input_763341816
cbuffer PerDraw [Size: 416]
@C    World_id24 => Transformation.World
@C    WorldInverse_id25 => Transformation.WorldInverse
@C    WorldInverseTranspose_id26 => Transformation.WorldInverseTranspose
@C    WorldView_id27 => Transformation.WorldView
@C    WorldViewInverse_id28 => Transformation.WorldViewInverse
@C    WorldViewProjection_id29 => Transformation.WorldViewProjection
@C    WorldScale_id30 => Transformation.WorldScale
@C    EyeMS_id31 => Transformation.EyeMS
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    SamplerInput_1602519085_id38 => SamplerInput_1602519085 [Stage: Pixel, Slot: (0-0)]
@R    TextureInput_2261099559_id37 => TextureInput_2261099559 [Stage: Pixel, Slot: (0-0)]
@R    Inputs => Inputs [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Shader_10346568 => 056e55f51ad9170c5a1b2096be6c8a77
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    NormalStream => ea68512133899a045766d21afb59733a
***************************
*****     Stages      *****
***************************
@G    Vertex => 9274efd9116d5ab7a947f1996630bc3c
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id24;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id25;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id26;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id27;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id28;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id29; // Offset:  320 Size:    64
//   float3 WorldScale_id30;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id31;                 // Offset:  400 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyzw        1     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.Position_id14.x; v0.y <- __input__.Position_id14.y; v0.z <- __input__.Position_id14.z; v0.w <- __input__.Position_id14.w; 
//   v1.x <- __input__.meshNormal_id32.x; v1.y <- __input__.meshNormal_id32.y; v1.z <- __input__.meshNormal_id32.z; 
//   o1.x <- <VSMain return value>.Position_id14.x; o1.y <- <VSMain return value>.Position_id14.y; o1.z <- <VSMain return value>.Position_id14.z; o1.w <- <VSMain return value>.Position_id14.w; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 141 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_10346568_552546c3fab108491641259679a5af71.hlsl"
dp4 o0.x, v0.xyzw, cb0[20].xyzw
dp4 o0.y, v0.xyzw, cb0[21].xyzw
dp4 o0.z, v0.xyzw, cb0[22].xyzw
dp4 o0.w, v0.xyzw, cb0[23].xyzw

#line 150
mov o1.xyzw, v0.xyzw
ret 
// Approximately 6 instruction slots used
@G    Pixel => 127da17bf4a352355a53ac0871be0698
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Inputs
// {
//
//   float3 input_2363487899_id39;      // Offset:    0 Size:    12
//   float4x4 input_694888891_id40;     // Offset:   16 Size:    64
//   float2 input_2101078675_id41;      // Offset:   80 Size:     8
//   float input_2768893694_id42;       // Offset:   88 Size:     4
//   float4 input_763341816_id43;       // Offset:   96 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_1602519085_id38      sampler      NA          NA             s0      1 
// TextureInput_2261099559_id37      texture  float4          2d             t0      1 
// Inputs                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// POSITION                 0   xyzw        1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.Position_id14.x; v1.y <- __input__.Position_id14.y; v1.z <- __input__.Position_id14.z; v1.w <- __input__.Position_id14.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 69 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_10346568_552546c3fab108491641259679a5af71.hlsl"
add r0.xyz, v1.xyzx, cb0[0].xyzx  // r0.x <- result_4133839695.x; r0.y <- result_4133839695.y; r0.z <- result_4133839695.z

#line 72
max r0.w, |r0.x|, |r0.z|
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
min r1.x, |r0.x|, |r0.z|
mul r0.w, r0.w, r1.x
mul r1.x, r0.w, r0.w
mad r1.y, r1.x, l(0.020835), l(-0.085133)
mad r1.y, r1.x, r1.y, l(0.180141)
mad r1.y, r1.x, r1.y, l(-0.330299)
mad r1.x, r1.x, r1.y, l(0.999866)
mul r1.y, r0.w, r1.x
mad r1.y, r1.y, l(-2.000000), l(1.570796)
lt r1.z, |r0.x|, |r0.z|
and r1.y, r1.z, r1.y
mad r0.w, r0.w, r1.x, r1.y
lt r1.x, r0.x, -r0.x
and r1.x, r1.x, l(0xc0490fdb)
add r0.w, r0.w, r1.x
min r1.x, r0.x, r0.z
lt r1.x, r1.x, -r1.x
max r1.y, r0.x, r0.z
ge r1.y, r1.y, -r1.y
and r1.x, r1.y, r1.x
movc r0.w, r1.x, -r0.w, r0.w  // r0.w <- atan2_1424550211

#line 73
mul r0.w, r0.w, l(0.159155)  // r0.w <- result_2885559235

#line 75
frc r0.w, r0.w  // r0.w <- frac_4119920722

#line 84
add r0.w, r0.w, l(0.500000)  // r0.w <- result_158580973

#line 85
frc r0.w, r0.w  // r0.w <- frac_2041640007

#line 90
mul r0.w, r0.w, l(6.283185)  // r0.w <- result_3325942375

#line 91
sincos r1.x, r2.x, r0.w  // r2.x <- cos_214079312; r1.x <- sin_1315075286

#line 77
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x  // r0.x <- length_2330920607

#line 78
div r0.x, r0.y, r0.x  // r0.x <- result_1746180292

#line 79
mad r0.y, |r0.x|, l(-0.018729), l(0.074261)
mad r0.y, r0.y, |r0.x|, l(-0.212114)
mad r0.y, r0.y, |r0.x|, l(1.570729)
add r0.z, -|r0.x|, l(1.000000)
lt r0.x, r0.x, -r0.x
sqrt r0.z, r0.z
mul r0.w, r0.z, r0.y
mad r0.w, r0.w, l(-2.000000), l(3.141593)
and r0.x, r0.x, r0.w
mad r0.x, r0.y, r0.z, r0.x

#line 80
add r0.x, -r0.x, l(3.141593)  // r0.x <- result_410456704

#line 87
mad r0.x, -r0.x, l(0.318310), l(1.000000)  // r0.x <- result_3393320330

#line 94
mad r0.x, r0.x, l(3.141593), l(-1.570796)  // r0.x <- result_3715525757

#line 95
sincos r0.x, r3.x, r0.x  // r3.x <- cos_1357021820; r0.x <- sin_4138375511

#line 96
mul r2.x, r2.x, r3.x  // r2.x <- result_3782548796

#line 99
mul r2.z, r1.x, r3.x  // r2.z <- result_2504010742

#line 102
mov r2.y, r0.x
mov r2.w, l(1.000000)
dp4 r0.z, r2.xyzw, cb0[3].xyzw  // r0.z <- mul_1815962262.z
dp4 r0.x, r2.xyzw, cb0[1].xyzw  // r0.x <- mul_1815962262.x
dp4 r0.y, r2.xyzw, cb0[2].xyzw  // r0.y <- mul_1815962262.y

#line 106
max r0.w, |r0.x|, |r0.z|
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
min r1.x, |r0.x|, |r0.z|
mul r0.w, r0.w, r1.x
mul r1.x, r0.w, r0.w
mad r1.y, r1.x, l(0.020835), l(-0.085133)
mad r1.y, r1.x, r1.y, l(0.180141)
mad r1.y, r1.x, r1.y, l(-0.330299)
mad r1.x, r1.x, r1.y, l(0.999866)
mul r1.y, r0.w, r1.x
mad r1.y, r1.y, l(-2.000000), l(1.570796)
lt r1.z, |r0.x|, |r0.z|
and r1.y, r1.z, r1.y
mad r0.w, r0.w, r1.x, r1.y
lt r1.x, r0.x, -r0.x
and r1.x, r1.x, l(0xc0490fdb)
add r0.w, r0.w, r1.x
min r1.x, r0.x, r0.z
lt r1.x, r1.x, -r1.x
max r1.y, r0.x, r0.z

#line 111
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x  // r0.x <- length_1844827251

#line 112
div r0.x, r0.y, r0.x  // r0.x <- result_1950727344

#line 106
ge r0.y, r1.y, -r1.y
and r0.y, r0.y, r1.x
movc r0.y, r0.y, -r0.w, r0.w  // r0.y <- atan2_3082932567

#line 107
mul r0.y, r0.y, l(0.159155)  // r0.y <- result_674745839

#line 109
frc r1.x, r0.y  // r1.x <- frac_2908018718

#line 113
mad r0.y, |r0.x|, l(-0.018729), l(0.074261)
mad r0.y, r0.y, |r0.x|, l(-0.212114)
mad r0.y, r0.y, |r0.x|, l(1.570729)
add r0.z, -|r0.x|, l(1.000000)
lt r0.x, r0.x, -r0.x
sqrt r0.z, r0.z
mul r0.w, r0.z, r0.y
mad r0.w, r0.w, l(-2.000000), l(3.141593)
and r0.x, r0.x, r0.w
mad r0.x, r0.y, r0.z, r0.x

#line 114
add r0.x, -r0.x, l(3.141593)  // r0.x <- result_307941228

#line 115
mul r1.y, r0.x, l(0.318310)  // r1.y <- result_60364942

#line 117
add r0.xy, r1.xyxx, l(-0.375000, -0.250000, 0.000000, 0.000000)  // r0.x <- result_2836711601.x; r0.y <- result_2836711601.y

#line 121
mad r0.xy, r0.xyxx, l(8.000000, 4.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)  // r0.x <- result_750105693.x; r0.y <- result_750105693.y

#line 122
div r0.xy, r0.xyxx, cb0[5].xyxx  // r0.x <- result_3404572437.x; r0.y <- result_3404572437.y

#line 123
add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // r0.x <- result_3764463951.x; r0.y <- result_3764463951.y

#line 124
mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)  // r0.x <- result_2491286565.x; r0.y <- result_2491286565.y

#line 125
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyxx, t0.xyzw, s0  // r0.x <- textureNode_1003766041.x; r0.y <- textureNode_1003766041.y; r0.z <- textureNode_1003766041.z; r0.w <- textureNode_1003766041.w

#line 127
eq r1.x, r0.w, cb0[5].z  // r1.x <- Assign_2089226289

#line 128
movc o0.xyzw, r1.xxxx, cb0[6].xyzw, r0.xyzw

#line 132
ret 
// Approximately 103 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float4 Position_id14;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
};
struct VS_STREAMS 
{
    float4 Position_id14;
    float3 meshNormal_id32;
    float4 PositionWS_id15;
    float3 normalWS_id35;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
};
struct VS_INPUT 
{
    float4 Position_id14 : POSITION;
    float3 meshNormal_id32 : NORMAL;
};
cbuffer Inputs 
{
    float3 input_2363487899_id39;
    float4x4 input_694888891_id40;
    float2 input_2101078675_id41;
    float input_2768893694_id42;
    float4 input_763341816_id43;
};
cbuffer PerDraw 
{
    float4x4 World_id24;
    float4x4 WorldInverse_id25;
    float4x4 WorldInverseTranspose_id26;
    float4x4 WorldView_id27;
    float4x4 WorldViewInverse_id28;
    float4x4 WorldViewProjection_id29;
    float3 WorldScale_id30;
    float4 EyeMS_id31;
};
cbuffer PerView 
{
    float4x4 View_id17;
    float4x4 ViewInverse_id18;
    float4x4 Projection_id19;
    float4x4 ProjectionInverse_id20;
    float4x4 ViewProjection_id21;
    float2 ProjScreenRay_id22;
    float4 Eye_id23;
};
Texture2D TextureInput_2261099559_id37;
SamplerState SamplerInput_1602519085_id38;
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    float3 PositionXyz_3458310707 = streams.Position_id14.xyz;
    float3 result_4133839695 = (PositionXyz_3458310707 + input_2363487899_id39);
    float resultZ_2961077498 = result_4133839695.z;
    float resultX_1774640555 = result_4133839695.x;
    float atan2_1424550211 = atan2(resultZ_2961077498, resultX_1774640555);
    float result_2885559235 = (atan2_1424550211 / 6.2831855);
    float result_1562849674 = (result_2885559235 + 1);
    float frac_4119920722 = frac(result_1562849674);
    float resultY_1748602150 = result_4133839695.y;
    float length_2330920607 = length(result_4133839695);
    float result_1746180292 = (resultY_1748602150 / length_2330920607);
    float asin_1062120072 = asin(result_1746180292);
    float result_410456704 = (asin_1062120072 + 1.5707964);
    float result_343355138 = (result_410456704 / 3.1415927);
    float2 float2Join_3112951277 = float2(frac_4119920722, result_343355138);
    float float2JoinX_2967258910 = float2Join_3112951277.x;
    float result_158580973 = (float2JoinX_2967258910 + 0.5);
    float frac_2041640007 = frac(result_158580973);
    float float2JoinY_837484270 = float2Join_3112951277.y;
    float result_3393320330 = (1 - float2JoinY_837484270);
    float2 float2Join_3127876154 = float2(frac_2041640007, result_3393320330);
    float float2JoinX_773604340 = float2Join_3127876154.x;
    float result_3325942375 = (float2JoinX_773604340 * 6.2831855);
    float cos_214079312 = cos(result_3325942375);
    float float2JoinY_2555769368 = float2Join_3127876154.y;
    float result_2662660109 = (float2JoinY_2555769368 * 3.1415927);
    float result_3715525757 = (result_2662660109 - 1.5707964);
    float cos_1357021820 = cos(result_3715525757);
    float result_3782548796 = (cos_214079312 * cos_1357021820);
    float sin_4138375511 = sin(result_3715525757);
    float sin_1315075286 = sin(result_3325942375);
    float result_2504010742 = (cos_1357021820 * sin_1315075286);
    float3 Float3Join_1685077102 = float3(result_3782548796, sin_4138375511, result_2504010742);
    float4 join_2125562133 = float4(Float3Join_1685077102, 1);
    float4 mul_1815962262 = mul(join_2125562133, input_694888891_id40);
    float3 mulXyz_2426515051 = mul_1815962262.xyz;
    float mulXyzZ_3863089134 = mulXyz_2426515051.z;
    float mulXyzX_3837713815 = mulXyz_2426515051.x;
    float atan2_3082932567 = atan2(mulXyzZ_3863089134, mulXyzX_3837713815);
    float result_674745839 = (atan2_3082932567 / 6.2831855);
    float result_3671481782 = (result_674745839 + 1);
    float frac_2908018718 = frac(result_3671481782);
    float mulXyzY_953897882 = mulXyz_2426515051.y;
    float length_1844827251 = length(mulXyz_2426515051);
    float result_1950727344 = (mulXyzY_953897882 / length_1844827251);
    float asin_620120028 = asin(result_1950727344);
    float result_307941228 = (asin_620120028 + 1.5707964);
    float result_60364942 = (result_307941228 / 3.1415927);
    float2 float2Join_802717977 = float2(frac_2908018718, result_60364942);
    float2 result_2836711601 = (float2Join_802717977 - float2(0.375, 0.25));
    float2 result_295119244 = (float2(0.625, 0.75) - float2(0.375, 0.25));
    float2 result_423046628 = (result_2836711601 / result_295119244);
    float2 result_2170337961 = (result_423046628 * float2(2, 2));
    float2 result_750105693 = (result_2170337961 - float2(1, 1));
    float2 result_3404572437 = (result_750105693 / input_2101078675_id41);
    float2 result_3764463951 = (result_3404572437 + float2(1, 1));
    float2 result_2491286565 = (result_3764463951 * float2(0.5, 0.5));
    float4 textureNode_1003766041 = TextureInput_2261099559_id37.Sample(SamplerInput_1602519085_id38, result_2491286565);
    float textureNodeW_1167171313 = textureNode_1003766041.w;
    bool Assign_2089226289 = textureNodeW_1167171313 == input_2768893694_id42;
    float4 expression_3815724557 = Assign_2089226289 ? input_763341816_id43 : textureNode_1003766041;
    streams.ColorTarget_id2 = expression_3815724557;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    streams.meshNormal_id32 = __input__.meshNormal_id32;
    float4 mul_144149361 = mul(streams.Position_id14, World_id24);
    streams.PositionWS_id15 = mul_144149361;
    float4 mul_2473923110 = mul(streams.Position_id14, WorldViewProjection_id29);
    streams.ShadingPosition_id0 = mul_2473923110;
    float4 join_288639843 = float4(streams.meshNormal_id32, 0);
    float4 mul_3225139503 = mul(join_288639843, WorldInverseTranspose_id26);
    float3 mulXyz_3569760232 = mul_3225139503.xyz;
    streams.normalWS_id35 = mulXyz_3569760232;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.Position_id14 = streams.Position_id14;
    return __output__;
}
