/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin HeightShadows_Pass1_Internal_TextureFX [{Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}, {LightDirection = InputFloat3<ShaderFX.InputValueFloat3,PerUpdate>}, {ShadowBlurAmount = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}, {ShadowBlurPow = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}, {SharpOffset = InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>}]
@P LightDirection: InputFloat3<ShaderFX.InputValueFloat3,PerUpdate>
@P ShadowBlurAmount: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P ShadowBlurPow: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
@P SharpOffset: InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 48]
@C    InputValue_id103 => ShaderFX.InputValueFloat4
@C    InputValue_id104 => ShaderFX.InputValueFloat3
@C    InputValue_id105 => ShaderFX.InputValueFloat
@C    InputValue_id106 => ShaderFX.InputValueFloat.i1
@C    InputValue_id107 => ShaderFX.InputValueFloat.i2
cbuffer PerView [Size: 32]
@C    NearClipPlane_id74 => Camera.NearClipPlane
@C    FarClipPlane_id75 => Camera.FarClipPlane
@C    ZProjection_id76 => Camera.ZProjection
@C    ViewSize_id77 => Camera.ViewSize
@C    AspectRatio_id78 => Camera.AspectRatio
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (0-0)]
@R    BorderSampler_id102 => HeightShadows_Pass1_Internal_TextureFX.BorderSampler [Stage: Pixel, Slot: (1-1)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    PerView => PerView [Stage: Pixel, Slot: (1-1)]
***************************
*****     Sources     *****
***************************
@S    HeightShadows_Pass1_Internal_TextureFX => 4a9a04670b4e2482e83f18b49941d7d1
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    AddonShaderUtils => 0d3496ddd24bfcbde4abd1deae724f64
@S    NoiseFunctions => 98db2858f268d9a8c1c8a5d521e3dce2
@S    ComputeFloat3 => fcd85992058d53e05e3805fecfe8c7a7
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
@S    InputFloat3 => 8982608ad2ca3465dcfa300c570359d5
@S    DeclFloat3 => f8ad0be4bea340b9223aeec02eb4c744
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 243 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_3826422f3ef0bda721eedfaa1f6c3c11.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 247
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 45c3f79b19d8e25a79717b5e5078fe0d
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id103;           // Offset:    0 Size:    16
//   float3 InputValue_id104;           // Offset:   16 Size:    12 [unused]
//   float InputValue_id105;            // Offset:   28 Size:     4
//   float InputValue_id106;            // Offset:   32 Size:     4
//   float InputValue_id107;            // Offset:   36 Size:     4
//
// }
//
// cbuffer PerView
// {
//
//   float NearClipPlane_id74;          // Offset:    0 Size:     4 [unused]
//      = 0x3f800000 
//   float FarClipPlane_id75;           // Offset:    4 Size:     4 [unused]
//      = 0x42c80000 
//   float2 ZProjection_id76;           // Offset:    8 Size:     8 [unused]
//   float2 ViewSize_id77;              // Offset:   16 Size:     8
//   float AspectRatio_id78;            // Offset:   24 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Sampler0_id52                     sampler      NA          NA             s0      1 
// BorderSampler_id102               sampler      NA          NA             s1      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// PerView                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_constantbuffer CB1[2], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 6
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 171 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_3826422f3ef0bda721eedfaa1f6c3c11.hlsl"
mad r0.xy, v1.xyxx, l(1000.000000, 1000.000000, 0.000000, 0.000000), l(324.000000, 324.000000, 0.000000, 0.000000)
mov r0.z, l(0)
mul r0.xyz, r0.xyzx, l(0.103100, 0.103100, 0.103100, 0.000000)
frc r0.xyz, r0.xyzx  // r0.x <- p3.x; r0.y <- p3.y; r0.z <- p3.z

#line 172
add r1.xy, r0.yzyy, l(19.190001, 19.190001, 0.000000, 0.000000)
dp2 r0.w, r0.xyxx, r1.xyxx
add r0.xyz, r0.wwww, r0.xyzx

#line 173
add r0.x, r0.y, r0.x
mul r0.x, r0.z, r0.x
frc r0.x, r0.x  // r0.x <- <hash13_id79 return value>

#line 210
rsq r0.x, r0.x
div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x  // r0.x <- rand

#line 171
mov r1.xy, v1.xyxx
mov r1.z, l(0)
mul r0.yzw, r1.xxyz, l(0.000000, 103.099998, 103.099998, 0.103100)
frc r0.yzw, r0.yyzw  // r0.y <- p3.x; r0.z <- p3.y; r0.w <- p3.z; r0.y <- p3.x; r0.z <- p3.y; r0.w <- p3.z

#line 172
add r1.xy, r0.zwzz, l(19.190001, 19.190001, 0.000000, 0.000000)
dp2 r1.x, r0.yzyy, r1.xyxx
add r0.yzw, r0.yyzw, r1.xxxx

#line 173
add r0.y, r0.z, r0.y
mul r0.y, r0.w, r0.y
frc r0.y, r0.y  // r0.y <- <hash13_id79 return value>; r0.y <- <hash13_id79 return value>

#line 199
mul r0.y, r0.y, cb0[1].w
mul r1.x, r0.y, l(1.250000)

#line 212
mov r1.yw, l(0,0,0,0)

#line 199
add r0.yz, r1.xxyx, v1.xxyx  // r0.y <- uv2.x; r0.z <- uv2.y

#line 200
sample_l_indexable(texture2d)(float,float,float,float) r0.yz, r0.yzyy, t0.xyzw, s1, l(0.000000)  // r0.y <- cinput.y; r0.z <- cinput.z

#line 190
sample_l_indexable(texture2d)(float,float,float,float) r2.xyz, v1.xyxx, t0.xyzw, s1, l(0.000000)  // r2.x <- input.x; r2.y <- input.y; r2.z <- input.z

#line 201
ge r0.z, r0.z, r2.z
and r0.z, r0.z, l(0x3f800000)
mul r0.y, r0.z, r0.y
max r0.y, r0.y, r2.y  // r0.y <- bluram

#line 171
mov r3.xy, v1.xyxx
mov r3.z, l(1.000000)
mul r3.xyz, r3.xyzx, l(103.099998, 103.099998, 0.103100, 0.000000)
frc r3.xyz, r3.xyzx  // r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z; r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z

#line 172
add r4.xyz, r3.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
dp3 r0.z, r3.xyzx, r4.xyzx
add r3.xyz, r0.zzzz, r3.xyzx

#line 173
add r0.z, r3.y, r3.x
mul r0.z, r3.z, r0.z
frc r0.z, r0.z  // r0.z <- <hash13_id79 return value>; r0.z <- <hash13_id79 return value>

#line 199
mul r3.xyzw, cb0[1].wwww, l(0.499998, 0.866027, -0.500004, 0.866023)
mul r0.zw, r0.zzzz, r3.xxxy
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 1.250000, 1.250000), v1.xxxy  // r0.z <- uv2.x; r0.w <- uv2.y

#line 200
sample_l_indexable(texture2d)(float,float,float,float) r0.zw, r0.zwzz, t0.xwyz, s1, l(0.000000)  // r0.z <- cinput.y; r0.w <- cinput.z

#line 201
ge r0.w, r0.w, r2.z
and r0.w, r0.w, l(0x3f800000)
mul r0.z, r0.w, r0.z
max r0.y, r0.z, r0.y

#line 171
mov r4.xy, v1.xyxx
mov r4.z, l(2.000000)
mul r4.xyz, r4.xyzx, l(103.099998, 103.099998, 0.103100, 0.000000)
frc r4.xyz, r4.xyzx  // r4.x <- p3.x; r4.y <- p3.y; r4.z <- p3.z; r4.x <- p3.x; r4.y <- p3.y; r4.z <- p3.z

#line 172
add r5.xyz, r4.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
dp3 r0.z, r4.xyzx, r5.xyzx
add r4.xyz, r0.zzzz, r4.xyzx

#line 173
add r0.z, r4.y, r4.x
mul r0.z, r4.z, r0.z
frc r0.z, r0.z  // r0.z <- <hash13_id79 return value>; r0.z <- <hash13_id79 return value>

#line 199
mul r0.zw, r0.zzzz, r3.zzzw
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 1.250000, 1.250000), v1.xxxy  // r0.z <- uv2.x; r0.w <- uv2.y

#line 200
sample_l_indexable(texture2d)(float,float,float,float) r0.zw, r0.zwzz, t0.xwyz, s1, l(0.000000)  // r0.z <- cinput.y; r0.w <- cinput.z

#line 201
ge r0.w, r0.w, r2.z
and r0.w, r0.w, l(0x3f800000)
mul r0.z, r0.w, r0.z
max r0.y, r0.z, r0.y

#line 171
mov r3.xy, v1.xyxx
mov r3.z, l(3.000000)
mul r3.xyz, r3.xyzx, l(103.099998, 103.099998, 0.103100, 0.000000)
frc r3.xyz, r3.xyzx  // r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z; r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z

#line 172
add r4.xyz, r3.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
dp3 r0.z, r3.xyzx, r4.xyzx
add r3.xyz, r0.zzzz, r3.xyzx

#line 173
add r0.z, r3.y, r3.x
mul r0.z, r3.z, r0.z
frc r0.z, r0.z  // r0.z <- <hash13_id79 return value>; r0.z <- <hash13_id79 return value>

#line 199
mul r3.xyzw, cb0[1].wwww, l(-1.000000, -0.000007, -0.499992, -0.866030)
mul r0.zw, r0.zzzz, r3.xxxy
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 1.250000, 1.250000), v1.xxxy  // r0.z <- uv2.x; r0.w <- uv2.y

#line 200
sample_l_indexable(texture2d)(float,float,float,float) r0.zw, r0.zwzz, t0.xwyz, s1, l(0.000000)  // r0.z <- cinput.y; r0.w <- cinput.z

#line 201
ge r0.w, r0.w, r2.z
and r0.w, r0.w, l(0x3f800000)
mul r0.z, r0.w, r0.z
max r0.y, r0.z, r0.y

#line 171
mov r4.xy, v1.xyxx
mov r4.z, l(4.000000)
mul r4.xyz, r4.xyzx, l(103.099998, 103.099998, 0.103100, 0.000000)
frc r4.xyz, r4.xyzx  // r4.x <- p3.x; r4.y <- p3.y; r4.z <- p3.z; r4.x <- p3.x; r4.y <- p3.y; r4.z <- p3.z

#line 172
add r5.xyz, r4.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
dp3 r0.z, r4.xyzx, r5.xyzx
add r4.xyz, r0.zzzz, r4.xyzx

#line 173
add r0.z, r4.y, r4.x
mul r0.z, r4.z, r0.z
frc r0.z, r0.z  // r0.z <- <hash13_id79 return value>; r0.z <- <hash13_id79 return value>

#line 199
mul r0.zw, r0.zzzz, r3.zzzw
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 1.250000, 1.250000), v1.xxxy  // r0.z <- uv2.x; r0.w <- uv2.y

#line 200
sample_l_indexable(texture2d)(float,float,float,float) r0.zw, r0.zwzz, t0.xwyz, s1, l(0.000000)  // r0.z <- cinput.y; r0.w <- cinput.z

#line 201
ge r0.w, r0.w, r2.z
and r0.w, r0.w, l(0x3f800000)
mul r0.z, r0.w, r0.z
max r0.y, r0.z, r0.y

#line 171
mov r3.xy, v1.xyxx
mov r3.z, l(5.000000)
mul r3.xyz, r3.xyzx, l(103.099998, 103.099998, 0.103100, 0.000000)
frc r3.xyz, r3.xyzx  // r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z; r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z

#line 172
add r4.xyz, r3.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
dp3 r0.z, r3.xyzx, r4.xyzx
add r3.xyz, r0.zzzz, r3.xyzx

#line 173
add r0.z, r3.y, r3.x
mul r0.z, r3.z, r0.z
frc r0.z, r0.z  // r0.z <- <hash13_id79 return value>; r0.z <- <hash13_id79 return value>

#line 199
mul r1.xy, cb0[1].wwww, l(0.500009, -0.866020, 0.000000, 0.000000)
mul r0.zw, r0.zzzz, r1.xxxy
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 1.250000, 1.250000), v1.xxxy  // r0.z <- uv2.x; r0.w <- uv2.y

#line 200
sample_l_indexable(texture2d)(float,float,float,float) r0.zw, r0.zwzz, t0.xwyz, s1, l(0.000000)  // r0.z <- cinput.y; r0.w <- cinput.z

#line 201
ge r0.w, r0.w, r2.z
and r0.w, r0.w, l(0x3f800000)
mul r0.z, r0.w, r0.z
max r0.y, r0.z, r0.y

#line 203
add r0.y, r0.y, -cb0[2].y
max r0.y, r0.y, l(0.000000)
log r0.y, r0.y
mul r0.y, r0.y, cb0[2].x
exp r3.x, r0.y  // r3.x <- bluram

#line 211
mov r3.y, l(1.000000)
mul r0.xy, r0.xxxx, r3.yxyy  // r0.x <- deviation.x

#line 212
mov r3.z, cb0[1].w
mul r0.xy, r0.xyxx, r3.xzxx
mov r1.z, cb0[1].w

#line 213
mad r0.xy, r0.xyxx, r1.zwzz, v1.xyxx  // r0.x <- uv2.x; r0.y <- uv2.y

#line 204
min r0.z, r3.x, l(1.000000)

#line 159
max r0.w, cb1[1].y, cb1[1].x
log r0.w, r0.w  // r0.w <- <Lod_id29 return value>

#line 204
mul r0.w, r0.w, l(0.250000)
mul r0.z, r0.z, r0.w  // r0.z <- lod

#line 214
sample_l_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t0.xzyw, s1, r0.z  // r0.x <- curr.x; r0.y <- curr.z

#line 215
ge r0.y, r0.y, r2.z
add r0.x, -r2.x, r0.x
and r0.y, r0.y, l(0x3f800000)
mad r0.x, r0.y, r0.x, r2.x

#line 171
mad r1.xy, v1.xyxx, l(1000.000000, 1000.000000, 0.000000, 0.000000), l(324.000000, 324.000000, 0.000000, 0.000000)
mov r1.z, l(1.000000)
mul r1.xyz, r1.xyzx, l(0.103100, 0.103100, 0.103100, 0.000000)
frc r1.xyz, r1.xyzx  // r1.x <- p3.x; r1.y <- p3.y; r1.z <- p3.z

#line 172
add r3.yzw, r1.yyzx, l(0.000000, 19.190001, 19.190001, 19.190001)
dp3 r0.y, r1.xyzx, r3.yzwy
add r1.xyz, r0.yyyy, r1.xyzx

#line 173
add r0.y, r1.y, r1.x
mul r0.y, r1.z, r0.y
frc r0.y, r0.y  // r0.y <- <hash13_id79 return value>

#line 210
rsq r0.y, r0.y
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y  // r0.y <- rand

#line 211
mul r0.y, r0.y, r3.x

#line 212
mul r0.y, r0.y, cb0[1].w

#line 213
mad r0.yw, r0.yyyy, l(0.000000, 0.499998, 0.000000, 0.866027), v1.xxxy  // r0.y <- uv2.x; r0.w <- uv2.y

#line 214
sample_l_indexable(texture2d)(float,float,float,float) r0.yw, r0.ywyy, t0.yxwz, s1, r0.z  // r0.y <- curr.x; r0.w <- curr.z

#line 215
ge r0.w, r0.w, r2.z
add r0.y, -r2.x, r0.y
and r0.w, r0.w, l(0x3f800000)
mad r0.y, r0.w, r0.y, r2.x
mul r0.y, r0.y, l(0.166667)  // r0.y <- curr.x

#line 216
mad r0.x, r0.x, l(0.166667), r0.y  // r0.x <- c.x

#line 171
mad r1.xy, v1.xyxx, l(1000.000000, 1000.000000, 0.000000, 0.000000), l(324.000000, 324.000000, 0.000000, 0.000000)
mov r1.z, l(2.000000)
mul r1.xyz, r1.xyzx, l(0.103100, 0.103100, 0.103100, 0.000000)
frc r1.xyz, r1.xyzx  // r1.x <- p3.x; r1.y <- p3.y; r1.z <- p3.z

#line 172
add r3.yzw, r1.yyzx, l(0.000000, 19.190001, 19.190001, 19.190001)
dp3 r0.y, r1.xyzx, r3.yzwy
add r1.xyz, r0.yyyy, r1.xyzx

#line 173
add r0.y, r1.y, r1.x
mul r0.y, r1.z, r0.y
frc r0.y, r0.y  // r0.y <- <hash13_id79 return value>

#line 210
rsq r0.y, r0.y
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y  // r0.y <- rand

#line 211
mul r0.y, r0.y, r3.x

#line 212
mul r0.y, r0.y, cb0[1].w

#line 213
mad r0.yw, r0.yyyy, l(0.000000, -0.500004, 0.000000, 0.866023), v1.xxxy  // r0.y <- uv2.x; r0.w <- uv2.y

#line 214
sample_l_indexable(texture2d)(float,float,float,float) r0.yw, r0.ywyy, t0.yxwz, s1, r0.z  // r0.y <- curr.x; r0.w <- curr.z

#line 215
ge r0.w, r0.w, r2.z
add r0.y, -r2.x, r0.y
and r0.w, r0.w, l(0x3f800000)
mad r0.y, r0.w, r0.y, r2.x

#line 216
mad r0.x, r0.y, l(0.166667), r0.x

#line 171
mad r1.xy, v1.xyxx, l(1000.000000, 1000.000000, 0.000000, 0.000000), l(324.000000, 324.000000, 0.000000, 0.000000)
mov r1.z, l(3.000000)
mul r1.xyz, r1.xyzx, l(0.103100, 0.103100, 0.103100, 0.000000)
frc r1.xyz, r1.xyzx  // r1.x <- p3.x; r1.y <- p3.y; r1.z <- p3.z

#line 172
add r3.yzw, r1.yyzx, l(0.000000, 19.190001, 19.190001, 19.190001)
dp3 r0.y, r1.xyzx, r3.yzwy
add r1.xyz, r0.yyyy, r1.xyzx

#line 173
add r0.y, r1.y, r1.x
mul r0.y, r1.z, r0.y
frc r0.y, r0.y  // r0.y <- <hash13_id79 return value>

#line 210
rsq r0.y, r0.y
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y  // r0.y <- rand

#line 211
mul r0.y, r0.y, r3.x

#line 212
mul r0.y, r0.y, cb0[1].w

#line 213
mad r0.yw, r0.yyyy, l(0.000000, -1.000000, 0.000000, -0.000007), v1.xxxy  // r0.y <- uv2.x; r0.w <- uv2.y

#line 214
sample_l_indexable(texture2d)(float,float,float,float) r0.yw, r0.ywyy, t0.yxwz, s1, r0.z  // r0.y <- curr.x; r0.w <- curr.z

#line 215
ge r0.w, r0.w, r2.z
add r0.y, -r2.x, r0.y
and r0.w, r0.w, l(0x3f800000)
mad r0.y, r0.w, r0.y, r2.x

#line 216
mad r0.x, r0.y, l(0.166667), r0.x

#line 171
mad r1.xy, v1.xyxx, l(1000.000000, 1000.000000, 0.000000, 0.000000), l(324.000000, 324.000000, 0.000000, 0.000000)
mov r1.z, l(4.000000)
mul r1.xyz, r1.xyzx, l(0.103100, 0.103100, 0.103100, 0.000000)
frc r1.xyz, r1.xyzx  // r1.x <- p3.x; r1.y <- p3.y; r1.z <- p3.z

#line 172
add r3.yzw, r1.yyzx, l(0.000000, 19.190001, 19.190001, 19.190001)
dp3 r0.y, r1.xyzx, r3.yzwy
add r1.xyz, r0.yyyy, r1.xyzx

#line 173
add r0.y, r1.y, r1.x
mul r0.y, r1.z, r0.y
frc r0.y, r0.y  // r0.y <- <hash13_id79 return value>

#line 210
rsq r0.y, r0.y
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y  // r0.y <- rand

#line 211
mul r0.y, r0.y, r3.x

#line 212
mul r0.y, r0.y, cb0[1].w

#line 213
mad r0.yw, r0.yyyy, l(0.000000, -0.499992, 0.000000, -0.866030), v1.xxxy  // r0.y <- uv2.x; r0.w <- uv2.y

#line 214
sample_l_indexable(texture2d)(float,float,float,float) r0.yw, r0.ywyy, t0.yxwz, s1, r0.z  // r0.y <- curr.x; r0.w <- curr.z

#line 215
ge r0.w, r0.w, r2.z
add r0.y, -r2.x, r0.y
and r0.w, r0.w, l(0x3f800000)
mad r0.y, r0.w, r0.y, r2.x

#line 216
mad r0.x, r0.y, l(0.166667), r0.x

#line 171
mad r1.xy, v1.xyxx, l(1000.000000, 1000.000000, 0.000000, 0.000000), l(324.000000, 324.000000, 0.000000, 0.000000)
mov r1.z, l(5.000000)
mul r1.xyz, r1.xyzx, l(0.103100, 0.103100, 0.103100, 0.000000)
frc r1.xyz, r1.xyzx  // r1.x <- p3.x; r1.y <- p3.y; r1.z <- p3.z

#line 172
add r3.yzw, r1.yyzx, l(0.000000, 19.190001, 19.190001, 19.190001)
dp3 r0.y, r1.xyzx, r3.yzwy
add r1.xyz, r0.yyyy, r1.xyzx

#line 173
add r0.y, r1.y, r1.x
mul r0.y, r1.z, r0.y
frc r0.y, r0.y  // r0.y <- <hash13_id79 return value>

#line 210
rsq r0.y, r0.y
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y  // r0.y <- rand

#line 211
mul r0.y, r0.y, r3.x

#line 212
mul r0.y, r0.y, cb0[1].w

#line 213
mad r0.yw, r0.yyyy, l(0.000000, 0.500009, 0.000000, -0.866020), v1.xxxy  // r0.y <- uv2.x; r0.w <- uv2.y

#line 214
sample_l_indexable(texture2d)(float,float,float,float) r0.yz, r0.ywyy, t0.yxzw, s1, r0.z  // r0.y <- curr.x; r0.z <- curr.z

#line 215
ge r0.z, r0.z, r2.z
add r0.y, -r2.x, r0.y
and r0.z, r0.z, l(0x3f800000)
mad r0.y, r0.z, r0.y, r2.x

#line 216
mad r0.xyz, r0.yyyy, l(0.166667, 0.166667, 0.166667, 0.000000), r0.xxxx  // r0.z <- c.x

#line 227
mov r0.w, l(1.000000)

#line 222
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)  // r1.x <- <InTex0_id26 return value>.x; r1.y <- <InTex0_id26 return value>.y; r1.z <- <InTex0_id26 return value>.z; r1.w <- <InTex0_id26 return value>.w

#line 227
add r0.xyzw, r0.xyzw, -r1.xyzw
mad o0.xyzw, cb0[0].xyzw, r0.xyzw, r1.xyzw

#line 236
ret 
// Approximately 252 instruction slots used
***************************
*************************/
static const float PI_id98 = 3.1415926535897932384626433832795;
static const float invBlurTaps_id99 = 0.166667;
static const int BlurTaps_id100 = 6;
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id103;
    float3 InputValue_id104;
    float InputValue_id105;
    float InputValue_id106;
    float InputValue_id107;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
SamplerState ClampSampler_id101 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Clamp;
    AddressV = Clamp;
};
SamplerState BorderSampler_id102 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
float Lod_id29(float2 viewSize)
{
    return log2(max(viewSize.x, viewSize.y));
}
float Compute_id96()
{
    return InputValue_id106;
}
float Compute_id95()
{
    return InputValue_id107;
}
float hash13_id79(float3 p3)
{
    p3 = frac(p3 * .1031);
    p3 += dot(p3, p3.yzx + 19.19);
    return frac((p3.x + p3.y) * p3.z);
}
float Compute_id94()
{
    return InputValue_id105;
}
float3 Compute_id93()
{
    return InputValue_id104;
}
float4 Compute_id92()
{
    return InputValue_id103;
}
float4 Filter_id91(inout PS_STREAMS streams, float4 tex0col)
{
    float2 uv = streams.TexCoord_id62;
    float4 input = Texture0_id14.SampleLevel(BorderSampler_id102, uv, 0);
    float3 orig = float3(uv, input.z);
    float3 raydir = normalize(-Compute_id93());
    float bluram = input.y;
    float shadowBlurAmount = Compute_id94();

    [unroll]
    for (float i = 0; i < BlurTaps_id100; i++)
    {
        float2 uv2 = uv + float2(cos(i * invBlurTaps_id99 * PI_id98 * 2), sin(i * invBlurTaps_id99 * PI_id98 * 2)) * shadowBlurAmount * hash13_id79(float3(uv * 1000, i)) * 1.25;
        float4 cinput = Texture0_id14.SampleLevel(BorderSampler_id102, uv2, 0);
        bluram = max(bluram, cinput.y * (cinput.z >= input.z));
    }
    bluram = pow(max(bluram - Compute_id95(), 0), Compute_id96());
    float lod = Lod_id29(ViewSize_id77) * 0.25 * saturate(bluram);
    float4 c = 0;

    [unroll]
    for (float i = 0; i < BlurTaps_id100; i++)
    {
        float rand = pow(hash13_id79(float3(uv * 1000 + 324, i)), 0.5);
        float2 deviation = float2(cos(i * invBlurTaps_id99 * PI_id98 * 2), sin(i * invBlurTaps_id99 * PI_id98 * 2)) * rand;
        float2 amount = deviation * bluram * shadowBlurAmount;
        float2 uv2 = uv + amount;
        float4 curr = Texture0_id14.SampleLevel(BorderSampler_id102, uv2, lod);
        curr = lerp(input, curr, curr.z >= input.z) * invBlurTaps_id99;
        c += curr;
    }
    return float4(c.x, c.x, c.x, 1.0);
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id91(streams, col), Compute_id92());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
