/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_98893764]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 144]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_4027469542_id19 => input_4027469542
@C    input_4092939107_id20 => input_4092939107
@C    input_2275321327_id21 => input_2275321327
@C    input_2532946976_id22 => input_2532946976
@C    input_1507466896_id23 => input_1507466896
@C    input_440749699_id24 => input_440749699
@C    input_3316271543_id25 => input_3316271543
@C    input_1483639967_id26 => input_1483639967
@C    input_527187317_id27 => input_527187317
@C    input_2810134271_id28 => input_2810134271
@C    input_77335853_id29 => input_77335853
@C    input_3590984981_id30 => input_3590984981
@C    input_1395649429_id31 => input_1395649429
@C    input_4067504017_id32 => input_4067504017
***************************
******  Resources    ******
***************************
@R    SamplerInput_355120245_id15 => SamplerInput_355120245 [Stage: Compute, Slot: (0-0)]
@R    SamplerInput_1459870303_id16 => SamplerInput_1459870303 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_3445202295_id12 => TextureInput_3445202295 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_2990988801_id13 => TextureInput_2990988801 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_1090208749_id14 => TextureInput_1090208749 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_2255746994_id17 => TextureInput_2255746994 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_3422964264_id18 => TextureInput_3422964264 [Stage: Compute, Slot: (1-1)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_98893764 => 2100d6e33fb000644296259761e31480
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
***************************
*****     Stages      *****
***************************
@G    Compute => d92cbb7fd7ba2ab1d5a54036da1ad8dd
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_4027469542_id19;        // Offset:   16 Size:    12
//   float input_4092939107_id20;       // Offset:   28 Size:     4 [unused]
//   float3 input_2275321327_id21;      // Offset:   32 Size:    12 [unused]
//   bool input_2532946976_id22;        // Offset:   44 Size:     4
//   float input_1507466896_id23;       // Offset:   48 Size:     4
//   float input_440749699_id24;        // Offset:   52 Size:     4
//   int3 input_3316271543_id25;        // Offset:   64 Size:    12
//   int3 input_1483639967_id26;        // Offset:   80 Size:    12
//   float input_527187317_id27;        // Offset:   92 Size:     4
//   float input_2810134271_id28;       // Offset:   96 Size:     4
//   float input_77335853_id29;         // Offset:  100 Size:     4
//   int3 input_3590984981_id30;        // Offset:  112 Size:    12
//   int3 input_1395649429_id31;        // Offset:  128 Size:    12
//   float input_4067504017_id32;       // Offset:  140 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_355120245_id15       sampler      NA          NA             s0      1 
// SamplerInput_1459870303_id16      sampler      NA          NA             s1      1 
// TextureInput_3445202295_id12      texture  float4          3d             t0      1 
// TextureInput_2990988801_id13      texture   float          3d             t1      1 
// TextureInput_1090208749_id14      texture   float          3d             t2      1 
// TextureInput_2255746994_id17          UAV  float4          3d             u0      1 
// TextureInput_3422964264_id18          UAV   float          3d             u1      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[9], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_uav_typed_texture3d (float,float,float,float) u1
dcl_input vThreadID.xyz
dcl_temps 3
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 56 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_bb1197edad9bad3cd1627993cfa5b0e7.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_2669607774; r0.y <- Assign_2401786989; r0.z <- Assign_3128971616

#line 57
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2293831901

#line 62
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyz, r0.xyzw, t0.xyzw  // r1.x <- velocity_2_2773640457.x; r1.y <- velocity_2_2773640457.y; r1.z <- velocity_2_2773640457.z

#line 63
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- obstacle_3039937939

#line 71
  lt r0.x, l(0.000000), r0.x  // r0.x <- Assign_2565208625

#line 72
  ine r0.y, cb0[2].w, l(0)
  or r0.x, r0.x, r0.y  // r0.x <- result_3768689136

#line 73
  utof r0.yzw, vThreadID.xxyz

#line 75
  mul r1.w, cb0[3].y, cb0[3].x  // r1.w <- result_263997860

#line 77
  mad r1.xyz, -r1.xyzx, r1.wwww, r0.yzwy  // r1.x <- result_756321283.x; r1.y <- result_756321283.y; r1.z <- result_756321283.z

#line 78
  itof r2.xyz, cb0[4].xyzx

#line 79
  add r2.xyz, r2.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- result_2769802300.x; r2.y <- result_2769802300.y; r2.z <- result_2769802300.z

#line 80
  max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r1.xyz, r2.xyzx, r1.xyzx  // r1.x <- clamp_824499389.x; r1.y <- clamp_824499389.y; r1.z <- clamp_824499389.z

#line 81
  add r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r1.x <- result_2004979765.x; r1.y <- result_2004979765.y; r1.z <- result_2004979765.z

#line 82
  itof r2.xyz, cb0[5].xyzx

#line 83
  div r1.xyz, r1.xyzx, r2.xyzx  // r1.x <- result_4129154503.x; r1.y <- result_4129154503.y; r1.z <- result_4129154503.z

#line 84
  sample_l_indexable(texture3d)(float,float,float,float) r2.xyzw, r1.xyzx, t0.xyzw, s0, l(0.000000)  // r2.x <- textureNode_655775014.x; r2.y <- textureNode_655775014.y; r2.z <- textureNode_655775014.z; r2.w <- textureNode_655775014.w

#line 86
  mul r1.x, r1.w, cb0[5].w  // r1.x <- result_3288289239

#line 88
  mad r1.xyzw, -r2.xyzw, r1.xxxx, r2.xyzw  // r1.x <- result_931384577.x; r1.y <- result_931384577.y; r1.z <- result_931384577.z; r1.w <- result_931384577.w

#line 93
  movc r1.xyzw, r0.xxxx, l(0,0,0,0), r1.xyzw  // r1.x <- output_4099486372.x; r1.y <- output_4099486372.y; r1.z <- output_4099486372.z; r1.w <- output_4099486372.w

#line 99
  mul r2.x, cb0[6].y, cb0[6].x  // r2.x <- result_878736946

#line 101
  mad r0.yzw, -r1.xxyz, r2.xxxx, r0.yyzw  // r0.y <- result_365328137.x; r0.z <- result_365328137.y; r0.w <- result_365328137.z

#line 102
  itof r2.yzw, cb0[7].xxyz

#line 103
  add r2.yzw, r2.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)  // r2.y <- result_1562342774.x; r2.z <- result_1562342774.y; r2.w <- result_1562342774.z

#line 104
  max r0.yzw, r0.yyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  min r0.yzw, r2.yyzw, r0.yyzw  // r0.y <- clamp_3976421283.x; r0.z <- clamp_3976421283.y; r0.w <- clamp_3976421283.z

#line 105
  add r0.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)  // r0.y <- result_2413642355.x; r0.z <- result_2413642355.y; r0.w <- result_2413642355.z

#line 106
  itof r2.yzw, cb0[8].xxyz

#line 107
  div r0.yzw, r0.yyzw, r2.yyzw  // r0.y <- result_1832504601.x; r0.z <- result_1832504601.y; r0.w <- result_1832504601.z

#line 108
  sample_l_indexable(texture3d)(float,float,float,float) r0.y, r0.yzwy, t2.yxzw, s1, l(0.000000)  // r0.y <- textureNode_3248479876

#line 110
  mul r0.z, r2.x, cb0[8].w  // r0.z <- result_302016981

#line 112
  mad r0.y, -r0.y, r0.z, r0.y  // r0.y <- result_697680403

#line 117
  movc r0.x, r0.x, l(0), r0.y  // r0.x <- output_102869078

#line 119
  store_uav_typed u0.xyzw, vThreadID.xyzz, r1.xyzw

#line 120
  store_uav_typed u1.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 146
ret 
// Approximately 42 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_4027469542_id19;
    float input_4092939107_id20;
    float3 input_2275321327_id21;
    bool input_2532946976_id22;
    float input_1507466896_id23;
    float input_440749699_id24;
    int3 input_3316271543_id25;
    int3 input_1483639967_id26;
    float input_527187317_id27;
    float input_2810134271_id28;
    float input_77335853_id29;
    int3 input_3590984981_id30;
    int3 input_1395649429_id31;
    float input_4067504017_id32;
};
Texture3D<float4> TextureInput_3445202295_id12;
Texture3D<float> TextureInput_2990988801_id13;
Texture3D<float> TextureInput_1090208749_id14;
SamplerState SamplerInput_355120245_id15;
SamplerState SamplerInput_1459870303_id16;
RWTexture3D<float4> TextureInput_2255746994_id17;
RWTexture3D<float> TextureInput_3422964264_id18;
float3 cast33_id5(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_1705848389 = streams.DispatchThreadId_id1.x;
    int inputX_3964728810 = input_4027469542_id19.x;
    bool Assign_2669607774 = DispatchThreadIdX_1705848389 >= inputX_3964728810;
    int DispatchThreadIdY_1152064971 = streams.DispatchThreadId_id1.y;
    int inputY_3132258850 = input_4027469542_id19.y;
    bool Assign_2401786989 = DispatchThreadIdY_1152064971 >= inputY_3132258850;
    int DispatchThreadIdZ_1595855846 = streams.DispatchThreadId_id1.z;
    int inputZ_47154949 = input_4027469542_id19.z;
    bool Assign_3128971616 = DispatchThreadIdZ_1595855846 >= inputZ_47154949;
    bool result_2293831901 = (Assign_2669607774 || Assign_2401786989 || Assign_3128971616);
    if (result_2293831901)
    {
        return;
    }
    float4 velocity_2_2773640457 = TextureInput_3445202295_id12[streams.DispatchThreadId_id1];
    float obstacle_3039937939 = TextureInput_2990988801_id13[streams.DispatchThreadId_id1];
    float density_103807989 = TextureInput_1090208749_id14[streams.DispatchThreadId_id1];
    float deltatime_3991802478 = 0;
    deltatime_3991802478 = input_4092939107_id20;
    int3 index_28702793 = int3(0, 0, 0);
    index_28702793 = streams.DispatchThreadId_id1;
    float3 resourcescale_1340830372 = float3(0, 0, 0);
    resourcescale_1340830372 = input_2275321327_id21;
    bool Assign_2565208625 = obstacle_3039937939 > 0;
    bool result_3768689136 = (input_2532946976_id22 || Assign_2565208625);
    float3 cast33_3840827716 = cast33_id5(streams.DispatchThreadId_id1);
    float3 VelocityXyz_499189292 = velocity_2_2773640457.xyz;
    float result_263997860 = (input_1507466896_id23 * input_440749699_id24);
    float3 result_2137138160 = (VelocityXyz_499189292 * result_263997860);
    float3 result_756321283 = (cast33_3840827716 - result_2137138160);
    float3 cast33_3337182889 = cast33_id5(input_3316271543_id25);
    float3 result_2769802300 = (cast33_3337182889 - float3(1, 1, 1));
    float3 clamp_824499389 = clamp(result_756321283, float3(0, 0, 0), result_2769802300);
    float3 result_2004979765 = (clamp_824499389 + float3(0.5, 0.5, 0.5));
    float3 cast33_2292507747 = cast33_id5(input_1483639967_id26);
    float3 result_4129154503 = (result_2004979765 / cast33_2292507747);
    float4 textureNode_655775014 = TextureInput_3445202295_id12.SampleLevel(SamplerInput_355120245_id15, result_4129154503, 0);
    float4 result_1361146541 = (float4(0, 0, 0, 0) - textureNode_655775014);
    float result_3288289239 = (input_527187317_id27 * result_263997860);
    float4 result_1004901149 = (result_1361146541 * result_3288289239);
    float4 result_931384577 = (textureNode_655775014 + result_1004901149);
    float4 output_4099486372 = result_931384577;
    if (result_3768689136)
    {
        output_4099486372 = float4(0, 0, 0, 0);
    }
    velocity_2_2773640457 = output_4099486372;
    bool Assign_2798435927 = obstacle_3039937939 > 0;
    bool result_3748356694 = (input_2532946976_id22 || Assign_2798435927);
    float3 cast33_834518426 = cast33_id5(streams.DispatchThreadId_id1);
    float3 VelocityXyz_1325534058 = velocity_2_2773640457.xyz;
    float result_878736946 = (input_2810134271_id28 * input_77335853_id29);
    float3 result_3542116214 = (VelocityXyz_1325534058 * result_878736946);
    float3 result_365328137 = (cast33_834518426 - result_3542116214);
    float3 cast33_3914049023 = cast33_id5(input_3590984981_id30);
    float3 result_1562342774 = (cast33_3914049023 - float3(1, 1, 1));
    float3 clamp_3976421283 = clamp(result_365328137, float3(0, 0, 0), result_1562342774);
    float3 result_2413642355 = (clamp_3976421283 + float3(0.5, 0.5, 0.5));
    float3 cast33_2355537089 = cast33_id5(input_1395649429_id31);
    float3 result_1832504601 = (result_2413642355 / cast33_2355537089);
    float textureNode_3248479876 = TextureInput_1090208749_id14.SampleLevel(SamplerInput_1459870303_id16, result_1832504601, 0);
    float result_4216192787 = (0 - textureNode_3248479876);
    float result_302016981 = (input_4067504017_id32 * result_878736946);
    float result_583907655 = (result_4216192787 * result_302016981);
    float result_697680403 = (textureNode_3248479876 + result_583907655);
    float output_102869078 = result_697680403;
    if (result_3748356694)
    {
        output_102869078 = 0;
    }
    density_103807989 = output_102869078;
    TextureInput_2255746994_id17[streams.DispatchThreadId_id1] = velocity_2_2773640457;
    TextureInput_3422964264_id18[streams.DispatchThreadId_id1] = density_103807989;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
