/**************************
***** Compiler Parameters *****
***************************
@P EffectName: Shader_1662581069
***************************
****  ConstantBuffers  ****
***************************
cbuffer Inputs [Size: 16]
@C    input_127441718_id97 => input_127441718
cbuffer PerDraw [Size: 416]
@C    World_id24 => Transformation.World
@C    WorldInverse_id25 => Transformation.WorldInverse
@C    WorldInverseTranspose_id26 => Transformation.WorldInverseTranspose
@C    WorldView_id27 => Transformation.WorldView
@C    WorldViewInverse_id28 => Transformation.WorldViewInverse
@C    WorldViewProjection_id29 => Transformation.WorldViewProjection
@C    WorldScale_id30 => Transformation.WorldScale
@C    EyeMS_id31 => Transformation.EyeMS
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    SamplerInput_848331922_id96 => SamplerInput_848331922 [Stage: Pixel, Slot: (0-0)]
@R    TextureInput_3509624453_id95 => TextureInput_3509624453 [Stage: Pixel, Slot: (0-0)]
@R    Inputs => Inputs [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Shader_1662581069 => 02198d38e5585f4470b2c445a490e022
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    NormalStream => ea68512133899a045766d21afb59733a
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
***************************
*****     Stages      *****
***************************
@G    Vertex => ff9c19abbff8fb50e9327462f0b66e1f
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id24;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id25;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id26;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id27;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id28;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id29; // Offset:  320 Size:    64
//   float3 WorldScale_id30;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id31;                 // Offset:  400 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_input v0.xyzw
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id14.x; v0.y <- __input__.Position_id14.y; v0.z <- __input__.Position_id14.z; v0.w <- __input__.Position_id14.w; 
//   v1.x <- __input__.meshNormal_id32.x; v1.y <- __input__.meshNormal_id32.y; v1.z <- __input__.meshNormal_id32.z; 
//   v2.x <- __input__.TexCoord_id85.x; v2.y <- __input__.TexCoord_id85.y; 
//   o1.x <- <VSMain return value>.TexCoord_id85.x; o1.y <- <VSMain return value>.TexCoord_id85.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 211 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_1662581069_e8148d0d233d21f6238745210d6655ec.hlsl"
dp4 o0.x, v0.xyzw, cb0[20].xyzw
dp4 o0.y, v0.xyzw, cb0[21].xyzw
dp4 o0.z, v0.xyzw, cb0[22].xyzw
dp4 o0.w, v0.xyzw, cb0[23].xyzw

#line 220
mov o1.xy, v2.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 2839ec92a0770df2fb170efa0aa034bb
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Inputs
// {
//
//   float2 input_127441718_id97;       // Offset:    0 Size:     8
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_848331922_id96       sampler      NA          NA             s0      1 
// TextureInput_3509624453_id95      texture  float4          2d             t0      1 
// Inputs                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id85.x; v1.y <- __input__.TexCoord_id85.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 157 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_Shader_1662581069_e8148d0d233d21f6238745210d6655ec.hlsl"
mad r0.xy, v1.xyxx, l(0.250000, 0.500000, 0.000000, 0.000000), l(0.375000, 0.250000, 0.000000, 0.000000)  // r0.x <- lerp_735656592.x; r0.y <- lerp_735656592.y

#line 159
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)  // r0.x <- result_194868429.x; r0.y <- result_194868429.y

#line 161
mad r0.xy, r0.xyxx, cb0[0].xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // r0.x <- result_3111504127.x; r0.y <- result_3111504127.y

#line 167
mul r0.x, r0.x, l(3.141593)  // r0.x <- result_3869871022

#line 168
mad r0.y, r0.y, l(1.570796), l(-1.570796)  // r0.y <- result_1136027346

#line 169
sincos r1.x, r2.x, r0.y  // r2.x <- cos_793362769; r1.x <- sin_1037173314

#line 165
sincos r0.x, r3.x, r0.x  // r3.x <- cos_2856485601; r0.x <- sin_2796422757

#line 173
mul r0.y, r0.x, r2.x  // r0.y <- result_2310288393

#line 170
mul r0.x, r2.x, r3.x  // r0.x <- result_37418297

#line 175
mov r0.z, r1.x
mov r0.w, -r1.x

#line 180
lt r1.xy, |r0.zyzz|, |r0.xxxx|  // r1.x <- Assign_2967816234; r1.y <- Assign_695648496

#line 183
and r0.z, r1.y, r1.x

#line 182
lt r1.x, r0.x, l(0.000000)  // r1.x <- Assign_3409592955

#line 188
div r0.x, l(0.500000), |r0.x|  // r0.x <- result_1033079021

#line 190
mad r0.xy, r0.ywyy, r0.xxxx, l(0.500000, 0.500000, 0.000000, 0.000000)  // r0.x <- result_730431735.x; r0.y <- result_730431735.y

#line 192
mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)  // r0.x <- result_2771376188.x; r0.y <- result_2771376188.y

#line 193
div r0.xy, r0.xyxx, cb0[0].xyxx  // r0.x <- result_67924452.x; r0.y <- result_67924452.y

#line 194
add r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // r0.x <- result_872177753.x; r0.y <- result_872177753.y

#line 195
mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)  // r0.x <- result_3523915359.x; r0.y <- result_3523915359.y

#line 196
sample_l_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyxx, t0.xyzw, s0, l(0.000000)  // r2.x <- textureNode_2121495858.x; r2.y <- textureNode_2121495858.y; r2.z <- textureNode_2121495858.z; r2.w <- textureNode_2121495858.w

#line 183
and r0.x, r0.z, r1.x  // r0.x <- result_3559379380

#line 197
movc o0.xyzw, r0.xxxx, r2.xyzw, l(1.000000,1.000000,0,1.000000)

#line 201
ret 
// Approximately 24 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id85;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id85 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id14;
    float3 meshNormal_id32;
    float2 TexCoord_id85;
    float4 PositionWS_id15;
    float3 normalWS_id35;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id85 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id14 : POSITION;
    float3 meshNormal_id32 : NORMAL;
    float2 TexCoord_id85 : TEXCOORD0;
};
cbuffer Inputs 
{
    float2 input_127441718_id97;
};
cbuffer PerDraw 
{
    float4x4 World_id24;
    float4x4 WorldInverse_id25;
    float4x4 WorldInverseTranspose_id26;
    float4x4 WorldView_id27;
    float4x4 WorldViewInverse_id28;
    float4x4 WorldViewProjection_id29;
    float3 WorldScale_id30;
    float4 EyeMS_id31;
};
cbuffer PerView 
{
    float4x4 View_id17;
    float4x4 ViewInverse_id18;
    float4x4 Projection_id19;
    float4x4 ProjectionInverse_id20;
    float4x4 ViewProjection_id21;
    float2 ProjScreenRay_id22;
    float4 Eye_id23;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id38;
    float2 Texture1TexelSize_id40;
    float2 Texture2TexelSize_id42;
    float2 Texture3TexelSize_id44;
    float2 Texture4TexelSize_id46;
    float2 Texture5TexelSize_id48;
    float2 Texture6TexelSize_id50;
    float2 Texture7TexelSize_id52;
    float2 Texture8TexelSize_id54;
    float2 Texture9TexelSize_id56;
};
Texture2D Texture0_id37;
Texture2D Texture1_id39;
Texture2D Texture2_id41;
Texture2D Texture3_id43;
Texture2D Texture4_id45;
Texture2D Texture5_id47;
Texture2D Texture6_id49;
Texture2D Texture7_id51;
Texture2D Texture8_id53;
Texture2D Texture9_id55;
TextureCube TextureCube0_id57;
TextureCube TextureCube1_id58;
TextureCube TextureCube2_id59;
TextureCube TextureCube3_id60;
Texture3D Texture3D0_id61;
Texture3D Texture3D1_id62;
Texture3D Texture3D2_id63;
Texture3D Texture3D3_id64;
SamplerState Sampler_id65;
SamplerState PointSampler_id66 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id67 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id68 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id69 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id70 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id71 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id72 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id73 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id74 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id75;
SamplerState Sampler1_id76;
SamplerState Sampler2_id77;
SamplerState Sampler3_id78;
SamplerState Sampler4_id79;
SamplerState Sampler5_id80;
SamplerState Sampler6_id81;
SamplerState Sampler7_id82;
SamplerState Sampler8_id83;
SamplerState Sampler9_id84;
Texture2D TextureInput_3509624453_id95;
SamplerState SamplerInput_848331922_id96;
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id85 = __input__.TexCoord_id85;
    float2 lerp_735656592 = lerp(float2(0.375, 0.25), float2(0.625, 0.75), streams.TexCoord_id85);
    float2 result_4178413665 = (lerp_735656592 * float2(2, 2));
    float2 result_194868429 = (result_4178413665 - float2(1, 1));
    float2 result_955993027 = (result_194868429 * input_127441718_id97);
    float2 result_3111504127 = (result_955993027 + float2(1, 1));
    float2 result_482660921 = (result_3111504127 * float2(0.5, 0.5));
    float resultX_840233033 = result_482660921.x;
    float result_3869871022 = (resultX_840233033 * 6.2831855);
    float cos_2856485601 = cos(result_3869871022);
    float resultY_3142870039 = result_482660921.y;
    float result_3235327192 = (resultY_3142870039 * 3.1415927);
    float result_1136027346 = (result_3235327192 - 1.5707964);
    float cos_793362769 = cos(result_1136027346);
    float result_37418297 = (cos_2856485601 * cos_793362769);
    float sin_1037173314 = sin(result_1136027346);
    float sin_2796422757 = sin(result_3869871022);
    float result_2310288393 = (cos_793362769 * sin_2796422757);
    float3 Float3Join_4112080347 = float3(result_37418297, sin_1037173314, result_2310288393);
    float3 abs_4027403196 = abs(Float3Join_4112080347);
    float absX_97193011 = abs_4027403196.x;
    float absY_953546192 = abs_4027403196.y;
    bool Assign_2967816234 = absX_97193011 > absY_953546192;
    float absZ_2654310268 = abs_4027403196.z;
    bool Assign_695648496 = absX_97193011 > absZ_2654310268;
    float Float3JoinX_4154802995 = Float3Join_4112080347.x;
    bool Assign_3409592955 = Float3JoinX_4154802995 < 0;
    bool result_3559379380 = (Assign_2967816234 && Assign_695648496 && Assign_3409592955);
    float Float3JoinZ_2051511586 = Float3Join_4112080347.z;
    float Float3JoinY_2445929598 = Float3Join_4112080347.y;
    float negate_2183903051 = -Float3JoinY_2445929598;
    float2 float2Join_4232474074 = float2(Float3JoinZ_2051511586, negate_2183903051);
    float result_1033079021 = (0.5 / absX_97193011);
    float2 result_2328558899 = (float2Join_4232474074 * result_1033079021);
    float2 result_730431735 = (result_2328558899 + float2(0.5, 0.5));
    float2 result_128723698 = (result_730431735 * float2(2, 2));
    float2 result_2771376188 = (result_128723698 - float2(1, 1));
    float2 result_67924452 = (result_2771376188 / input_127441718_id97);
    float2 result_872177753 = (result_67924452 + float2(1, 1));
    float2 result_3523915359 = (result_872177753 * float2(0.5, 0.5));
    float4 textureNode_2121495858 = TextureInput_3509624453_id95.SampleLevel(SamplerInput_848331922_id96, result_3523915359, 0);
    float4 expression_3293633336 = result_3559379380 ? textureNode_2121495858 : float4(1, 1, 0, 1);
    streams.ColorTarget_id2 = expression_3293633336;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    streams.meshNormal_id32 = __input__.meshNormal_id32;
    streams.TexCoord_id85 = __input__.TexCoord_id85;
    float4 mul_3934800831 = mul(streams.Position_id14, World_id24);
    streams.PositionWS_id15 = mul_3934800831;
    float4 mul_97870330 = mul(streams.Position_id14, WorldViewProjection_id29);
    streams.ShadingPosition_id0 = mul_97870330;
    float4 join_1031001101 = float4(streams.meshNormal_id32, 0);
    float4 mul_2581861345 = mul(join_1031001101, WorldInverseTranspose_id26);
    float3 mulXyz_2605093884 = mul_2581861345.xyz;
    streams.normalWS_id35 = mulXyz_2605093884;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id85 = streams.TexCoord_id85;
    return __output__;
}
