/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_297427762]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 48]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_2286105837_id16 => input_2286105837
@C    input_1254490846_id17 => input_1254490846
@C    input_3842531802_id18 => input_3842531802
***************************
******  Resources    ******
***************************
@R    TextureInput_2283284131_id12 => TextureInput_2283284131 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_2510865218_id13 => TextureInput_2510865218 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_1221118746_id14 => TextureInput_1221118746 [Stage: Compute, Slot: (2-2)]
@R    TextureInput_561523650_id15 => TextureInput_561523650 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_297427762 => 4be5324cd6792df172798239df86697c
***************************
*****     Stages      *****
***************************
@G    Compute => 90aeecb26eb7a8b9017cec4ac8e83a09
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_2286105837_id16;        // Offset:   16 Size:    12
//   float input_1254490846_id17;       // Offset:   28 Size:     4 [unused]
//   float3 input_3842531802_id18;      // Offset:   32 Size:    12 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_2283284131_id12      texture   float          3d             t0      1 
// TextureInput_2510865218_id13      texture   float          3d             t1      1 
// TextureInput_1221118746_id14      texture   float          3d             t2      1 
// TextureInput_561523650_id15           UAV   float          3d             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_resource_texture3d (float,float,float,float) t2
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_input vThreadID.xyz
dcl_temps 3
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 38 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_6e2de5ba636e1fe59a76480431301f58.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_536001411; r0.y <- Assign_3859735600; r0.z <- Assign_42903651

#line 39
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_1581015312

#line 44
if_z r0.x
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.x, r0.xyzw, t0.xyzw  // r1.x <- pressure_169094072

#line 46
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t2.xyzw  // r0.x <- divergence_2716743372

#line 53
  iadd r2.xyz, vThreadID.xyzx, l(-1, 0, 0, 0)  // r2.x <- result_295063953.x; r2.y <- result_295063953.y; r2.z <- result_295063953.z

#line 54
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.y, r2.xyzw, t1.yxzw  // r0.y <- getTextureValue_3174365733

#line 55
  lt r0.y, l(0.000000), r0.y  // r0.y <- Assign_2520409268

#line 57
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t0.yzxw  // r0.z <- getTextureValue_1142021280

#line 64
  movc r0.y, r0.y, r1.x, r0.z  // r0.y <- output_1975933726

#line 65
  iadd r2.xyz, vThreadID.xyzx, l(1, 0, 0, 0)  // r2.x <- result_1611522772.x; r2.y <- result_1611522772.y; r2.z <- result_1611522772.z

#line 66
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.z, r2.xyzw, t1.yzxw  // r0.z <- getTextureValue_2091399088

#line 67
  lt r0.z, l(0.000000), r0.z  // r0.z <- Assign_3422572364

#line 69
  ld_indexable(texture3d)(float,float,float,float) r0.w, r2.xyzw, t0.yzwx  // r0.w <- getTextureValue_2643372847

#line 76
  movc r0.z, r0.z, r1.x, r0.w  // r0.z <- output_2139606366

#line 77
  iadd r2.xyz, vThreadID.xyzx, l(0, -1, 0, 0)  // r2.x <- result_1711883665.x; r2.y <- result_1711883665.y; r2.z <- result_1711883665.z

#line 78
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r0.w, r2.xyzw, t1.yzwx  // r0.w <- getTextureValue_939605205

#line 79
  lt r0.w, l(0.000000), r0.w  // r0.w <- Assign_241354251

#line 81
  ld_indexable(texture3d)(float,float,float,float) r1.y, r2.xyzw, t0.yxzw  // r1.y <- getTextureValue_3096659574

#line 88
  movc r0.w, r0.w, r1.x, r1.y  // r0.w <- output_2846291051

#line 89
  iadd r2.xyz, vThreadID.xyzx, l(0, 1, 0, 0)  // r2.x <- result_2808196484.x; r2.y <- result_2808196484.y; r2.z <- result_2808196484.z

#line 90
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.y, r2.xyzw, t1.yxzw  // r1.y <- getTextureValue_2740499980

#line 91
  lt r1.y, l(0.000000), r1.y  // r1.y <- Assign_38112611

#line 93
  ld_indexable(texture3d)(float,float,float,float) r1.z, r2.xyzw, t0.yzxw  // r1.z <- getTextureValue_961926441

#line 100
  movc r1.y, r1.y, r1.x, r1.z  // r1.y <- output_3940074723

#line 101
  iadd r2.xyz, vThreadID.xyzx, l(0, 0, -1, 0)  // r2.x <- result_311831429.x; r2.y <- result_311831429.y; r2.z <- result_311831429.z

#line 102
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.z, r2.xyzw, t1.yzxw  // r1.z <- getTextureValue_1022350497

#line 103
  lt r1.z, l(0.000000), r1.z  // r1.z <- Assign_183616329

#line 105
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t0.yzwx  // r1.w <- getTextureValue_1870835390

#line 112
  movc r1.z, r1.z, r1.x, r1.w  // r1.z <- output_2307576165

#line 113
  iadd r2.xyz, vThreadID.xyzx, l(0, 0, 1, 0)  // r2.x <- result_1819791518.x; r2.y <- result_1819791518.y; r2.z <- result_1819791518.z

#line 114
  mov r2.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.w, r2.xyzw, t1.yzwx  // r1.w <- getTextureValue_144896646

#line 115
  lt r1.w, l(0.000000), r1.w  // r1.w <- Assign_2830174647

#line 117
  ld_indexable(texture3d)(float,float,float,float) r2.x, r2.xyzw, t0.xyzw  // r2.x <- getTextureValue_3760811973

#line 124
  movc r1.x, r1.w, r1.x, r2.x  // r1.x <- output_492687767

#line 125
  add r0.y, r0.z, r0.y
  add r0.y, r0.w, r0.y
  add r0.y, r1.y, r0.y
  add r0.y, r1.z, r0.y
  add r0.y, r1.x, r0.y  // r0.y <- result_1050139760

#line 126
  add r0.x, -r0.x, r0.y  // r0.x <- result_990391215

#line 127
  mul r0.x, r0.x, l(0.166667)  // r0.x <- result_3300216433

#line 129
  store_uav_typed u0.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 155
ret 
// Approximately 54 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_2286105837_id16;
    float input_1254490846_id17;
    float3 input_3842531802_id18;
};
Texture3D<float> TextureInput_2283284131_id12;
Texture3D<float> TextureInput_2510865218_id13;
Texture3D<float> TextureInput_1221118746_id14;
RWTexture3D<float> TextureInput_561523650_id15;
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_2247141374 = streams.DispatchThreadId_id1.x;
    int inputX_1046803885 = input_2286105837_id16.x;
    bool Assign_536001411 = DispatchThreadIdX_2247141374 >= inputX_1046803885;
    int DispatchThreadIdY_717330578 = streams.DispatchThreadId_id1.y;
    int inputY_3027621359 = input_2286105837_id16.y;
    bool Assign_3859735600 = DispatchThreadIdY_717330578 >= inputY_3027621359;
    int DispatchThreadIdZ_2793580973 = streams.DispatchThreadId_id1.z;
    int inputZ_1984482882 = input_2286105837_id16.z;
    bool Assign_42903651 = DispatchThreadIdZ_2793580973 >= inputZ_1984482882;
    bool result_1581015312 = (Assign_536001411 || Assign_3859735600 || Assign_42903651);
    if (result_1581015312)
    {
        return;
    }
    float pressure_169094072 = TextureInput_2283284131_id12[streams.DispatchThreadId_id1];
    float obstacle_480588738 = TextureInput_2510865218_id13[streams.DispatchThreadId_id1];
    float divergence_2716743372 = TextureInput_1221118746_id14[streams.DispatchThreadId_id1];
    float deltatime_3703179883 = 0;
    deltatime_3703179883 = input_1254490846_id17;
    int3 index_873893990 = int3(0, 0, 0);
    index_873893990 = streams.DispatchThreadId_id1;
    float3 resourcescale_4004539893 = float3(0, 0, 0);
    resourcescale_4004539893 = input_3842531802_id18;
    int3 result_295063953 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_3174365733 = TextureInput_2510865218_id13[result_295063953];
    bool Assign_2520409268 = getTextureValue_3174365733 > 0;
    int3 result_2894855400 = (streams.DispatchThreadId_id1 + int3(-1, 0, 0));
    float getTextureValue_1142021280 = TextureInput_2283284131_id12[result_2894855400];
    float output_1975933726 = getTextureValue_1142021280;
    float output_2950803897 = 1;
    if (Assign_2520409268)
    {
        output_1975933726 = pressure_169094072;
        output_2950803897 = 0;
    }
    int3 result_1611522772 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_2091399088 = TextureInput_2510865218_id13[result_1611522772];
    bool Assign_3422572364 = getTextureValue_2091399088 > 0;
    int3 result_2247993847 = (streams.DispatchThreadId_id1 + int3(1, 0, 0));
    float getTextureValue_2643372847 = TextureInput_2283284131_id12[result_2247993847];
    float output_2139606366 = getTextureValue_2643372847;
    float output_1672265081 = 1;
    if (Assign_3422572364)
    {
        output_2139606366 = pressure_169094072;
        output_1672265081 = 0;
    }
    int3 result_1711883665 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_939605205 = TextureInput_2510865218_id13[result_1711883665];
    bool Assign_241354251 = getTextureValue_939605205 > 0;
    int3 result_2517562574 = (streams.DispatchThreadId_id1 + int3(0, -1, 0));
    float getTextureValue_3096659574 = TextureInput_2283284131_id12[result_2517562574];
    float output_2846291051 = getTextureValue_3096659574;
    float output_2562385478 = 1;
    if (Assign_241354251)
    {
        output_2846291051 = pressure_169094072;
        output_2562385478 = 0;
    }
    int3 result_2808196484 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_2740499980 = TextureInput_2510865218_id13[result_2808196484];
    bool Assign_38112611 = getTextureValue_2740499980 > 0;
    int3 result_1984242309 = (streams.DispatchThreadId_id1 + int3(0, 1, 0));
    float getTextureValue_961926441 = TextureInput_2283284131_id12[result_1984242309];
    float output_3940074723 = getTextureValue_961926441;
    float output_441586046 = 1;
    if (Assign_38112611)
    {
        output_3940074723 = pressure_169094072;
        output_441586046 = 0;
    }
    int3 result_311831429 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_1022350497 = TextureInput_2510865218_id13[result_311831429];
    bool Assign_183616329 = getTextureValue_1022350497 > 0;
    int3 result_979951814 = (streams.DispatchThreadId_id1 + int3(0, 0, -1));
    float getTextureValue_1870835390 = TextureInput_2283284131_id12[result_979951814];
    float output_2307576165 = getTextureValue_1870835390;
    float output_3677494474 = 1;
    if (Assign_183616329)
    {
        output_2307576165 = pressure_169094072;
        output_3677494474 = 0;
    }
    int3 result_1819791518 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_144896646 = TextureInput_2510865218_id13[result_1819791518];
    bool Assign_2830174647 = getTextureValue_144896646 > 0;
    int3 result_44680385 = (streams.DispatchThreadId_id1 + int3(0, 0, 1));
    float getTextureValue_3760811973 = TextureInput_2283284131_id12[result_44680385];
    float output_492687767 = getTextureValue_3760811973;
    float output_3173599740 = 1;
    if (Assign_2830174647)
    {
        output_492687767 = pressure_169094072;
        output_3173599740 = 0;
    }
    float result_1050139760 = (output_1975933726 + output_2139606366 + output_2846291051 + output_3940074723 + output_2307576165 + output_492687767);
    float result_990391215 = (result_1050139760 - divergence_2716743372);
    float result_3300216433 = (result_990391215 / 6);
    pressure_169094072 = result_3300216433;
    TextureInput_561523650_id15[streams.DispatchThreadId_id1] = pressure_169094072;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
