/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_2037834541]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 288]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_838590723_id27 => input_838590723
@C    input_1058178022_id28 => input_1058178022
@C    input_407320090_id29 => input_407320090
@C    input_1157260306_id30 => input_1157260306
@C    input_645245252_id31 => input_645245252
@C    input_568116523_id32 => input_568116523
@C    input_4140015311_id33 => input_4140015311
@C    input_1740323861_id34 => input_1740323861
@C    input_4251367585_id35 => input_4251367585
@C    input_1310941215_id36 => input_1310941215
@C    input_159017704_id37 => input_159017704
@C    input_776891185_id38 => input_776891185
@C    input_1239917863_id39 => input_1239917863
@C    input_4274391210_id40 => input_4274391210
@C    input_2465657493_id41 => input_2465657493
@C    input_2051487400_id42 => input_2051487400
@C    input_579890576_id43 => input_579890576
@C    input_57480610_id44 => input_57480610
@C    input_2861981802_id45 => input_2861981802
@C    input_3660883841_id46 => input_3660883841
@C    input_2814605708_id47 => input_2814605708
@C    input_641060572_id48 => input_641060572
***************************
******  Resources    ******
***************************
@R    TextureInput_2957714998_id23 => TextureInput_2957714998 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_1288012844_id24 => TextureInput_1288012844 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_1941307003_id25 => TextureInput_1941307003 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_1905746801_id26 => TextureInput_1905746801 [Stage: Compute, Slot: (1-1)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_2037834541 => 39452df088e956317654921f5f02b595
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCommonNoise => f3e94fe4a03a0b02051750e5b6a831ca
@S    FuseCommonNoiseSine => d8c809697d88a8d534414c8b788f34bd
@S    FuseCoreMath => b5527ab1f8082f68a6dcc7c3959ee99a
@S    FuseCoreMathHash => 9e8ec916d08625592014904eea5076c5
@S    FuseCommonNoiseValueNoise => 598ea3c9dd7c5fed506e079ef91b1d81
@S    FuseCommonNoiseGradientNoise => 275a1c68a04d0e8c934e4792e8de1a02
@S    FuseCommonNoiseSimplex => cff83c6dcba0e92106f65f2c730e3e35
@S    FuseCommonNoiseRandom => c9e5885d1263580889df6cfb5c437ec3
@S    FuseCommonNoiseWorley => d0830642cb2e69b2f30256019c06d7a7
***************************
*****     Stages      *****
***************************
@G    Compute => 80c319a43293e4d6924380d87010f5eb
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_838590723_id27;         // Offset:   16 Size:    12
//   float input_1058178022_id28;       // Offset:   28 Size:     4 [unused]
//   float3 input_407320090_id29;       // Offset:   32 Size:    12 [unused]
//   float3 input_1157260306_id30;      // Offset:   48 Size:    12
//   float input_645245252_id31;        // Offset:   60 Size:     4
//   float3 input_568116523_id32;       // Offset:   64 Size:    12
//   int3 input_4140015311_id33;        // Offset:   80 Size:    12
//   float3 input_1740323861_id34;      // Offset:   96 Size:    12 [unused]
//   float4x4 input_4251367585_id35;    // Offset:  112 Size:    64
//   float3 input_1310941215_id36;      // Offset:  176 Size:    12
//   float input_159017704_id37;        // Offset:  188 Size:     4
//   float input_776891185_id38;        // Offset:  192 Size:     4
//   float3 input_1239917863_id39;      // Offset:  196 Size:    12
//   float3 input_4274391210_id40;      // Offset:  208 Size:    12
//   float input_2465657493_id41;       // Offset:  220 Size:     4
//   float input_2051487400_id42;       // Offset:  224 Size:     4
//   float input_579890576_id43;        // Offset:  228 Size:     4
//   float3 input_57480610_id44;        // Offset:  240 Size:    12
//   float input_2861981802_id45;       // Offset:  252 Size:     4
//   float3 input_3660883841_id46;      // Offset:  256 Size:    12
//   float input_2814605708_id47;       // Offset:  268 Size:     4
//   float input_641060572_id48;        // Offset:  272 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_2957714998_id23      texture  float4          3d             t0      1 
// TextureInput_1288012844_id24      texture   float          3d             t1      1 
// TextureInput_1941307003_id25          UAV  float4          3d             u0      1 
// TextureInput_1905746801_id26          UAV   float          3d             u1      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[18], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_uav_typed_texture3d (float,float,float,float) u1
dcl_input vThreadID.xyz
dcl_temps 20
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 134 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_6b5bf81781da5ac1b10596bb61f4401c.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_3689940353; r0.y <- Assign_1627392202; r0.z <- Assign_1774890877

#line 135
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_1149744962

#line 140
if_z r0.x

#line 148
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyzw, r0.xyzw, t0.xyzw  // r1.x <- velocity_2_977671682.x; r1.y <- velocity_2_977671682.y; r1.z <- velocity_2_977671682.z; r1.w <- velocity_2_977671682.w

#line 149
  utof r2.xyz, vThreadID.xyzx

#line 150
  add r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r2.x <- result_2524718450.x; r2.y <- result_2524718450.y; r2.z <- result_2524718450.z

#line 151
  itof r3.xyz, cb0[5].xyzx

#line 152
  div r2.xyz, r2.xyzx, r3.xyzx  // r2.x <- result_3593319729.x; r2.y <- result_3593319729.y; r2.z <- result_3593319729.z

#line 153
  add r2.xyz, r2.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)  // r2.x <- result_1044597739.x; r2.y <- result_1044597739.y; r2.z <- result_1044597739.z

#line 158
  mov r2.w, l(1.000000)
  dp4 r3.x, r2.xyzw, cb0[7].xyzw  // r3.x <- mul_1350355877.x
  dp4 r3.y, r2.xyzw, cb0[8].xyzw  // r3.y <- mul_1350355877.y
  dp4 r3.z, r2.xyzw, cb0[9].xyzw  // r3.z <- mul_1350355877.z

#line 113
  add r2.xyz, r3.xyzx, -cb0[3].xyzx  // r2.x <- result_310773393.x; r2.y <- result_310773393.y; r2.z <- result_310773393.z

#line 114
  dp3 r2.x, r2.xyzx, r2.xyzx
  sqrt r2.x, r2.x  // r2.x <- length_1284112446

#line 115
  add r2.x, r2.x, -cb0[3].w  // r2.x <- result_2455429488

#line 165
  mul r2.x, -r2.x, l(1.#INF00)  // r2.x <- result_1122315373

#line 166
  mov_sat r2.xyz, r2.xxxx  // r2.z <- saturate_2935286286

#line 169
  add r4.xyz, -r1.xyzx, cb0[4].xyzx
  add r4.w, -r1.w, l(1.000000)
  mov r2.w, l(1.000000)
  mad r1.xyzw, r2.xyzw, r4.xyzw, r1.xyzw  // r1.x <- lerp_424500790.x; r1.y <- lerp_424500790.y; r1.z <- lerp_424500790.z; r1.w <- lerp_424500790.w

#line 171
  round_pi r2.x, cb0[14].x  // r2.x <- ceil_4294286268

#line 172
  ftoi r2.x, r2.x  // r2.x <- cast11_3304455865

#line 178
  mov r2.yzw, r3.xxyz  // r2.y <- output_2313305742.x; r2.z <- output_2313305742.y; r2.w <- output_2313305742.z
  mov r4.xyz, l(0,0,0,0)  // r4.x <- output_3434651123.x; r4.y <- output_3434651123.y; r4.z <- output_3434651123.z
  mov r3.w, l(0)  // r3.w <- output_2735912516
  mov r4.w, cb0[13].w  // r4.w <- output_1136910249
  mov r5.x, l(0)  // r5.x <- index_290661277
  loop 
    ige r5.y, r5.x, r2.x
    breakc_nz r5.y

#line 180
    mul r5.yzw, r2.yyzw, cb0[14].yyyy  // r5.y <- result_2782021489.x; r5.z <- result_2782021489.y; r5.w <- result_2782021489.z

#line 91
    mul r6.w, r2.w, cb0[11].z  // r6.w <- result_1503178597.z

#line 93
    mad r6.x, r2.y, cb0[11].x, cb0[11].w  // r6.x <- result_3587333782.x
    mad r6.y, r2.z, cb0[11].y, cb0[12].x  // r6.y <- result_3587333782.y

#line 64
    mov r6.zw, r6.wwww  // r6.z <- result_3587333782.z
    add r7.xyz, r6.wyxw, l(17.000000, 17.000000, 17.000000, 0.000000)  // r7.x <- p2.z; r7.y <- p2.y; r7.z <- p2.x

#line 65
    add r8.xyz, r6.xywx, l(-43.700001, -43.700001, -43.700001, 0.000000)  // r8.x <- p3.x; r8.y <- p3.y; r8.z <- p3.z

#line 57
    round_ni r9.xyz, r6.zyxz  // r9.x <- i.z; r9.y <- i.y; r9.z <- i.x

#line 58
    frc r6.xyz, r6.xyzx  // r6.x <- f.x; r6.y <- f.y; r6.z <- f.z

#line 59
    mul r10.xyz, r6.xyzx, r6.xyzx
    mad r11.xyz, -r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(3.000000, 3.000000, 3.000000, 0.000000)
    mul r10.xyz, r10.xyzx, r11.xyzx  // r10.x <- u.x; r10.y <- u.y; r10.z <- u.z

#line 51
    mul r11.xyz, r9.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r12.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r11.zyxz, r12.xyzx
    add r11.xyz, r6.wwww, r11.xyzx

#line 53
    add r12.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r12.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.w, r11.xyzx, r6.xyzx
    add r11.xyz, r9.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r12.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r11.zyxz, r12.xyzx
    add r11.xyz, r7.wwww, r11.xyzx

#line 53
    add r12.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r12.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r12.xyz, r6.xyzx, l(-1.000000, -0.000000, -0.000000, 0.000000)
    dp3 r7.w, r11.xyzx, r12.xyzx
    add r7.w, -r6.w, r7.w
    mad r6.w, r10.x, r7.w, r6.w
    add r11.xyz, r9.xyzx, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r13.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r11.zyxz, r13.xyzx
    add r11.xyz, r7.wwww, r11.xyzx

#line 53
    add r13.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r13.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r13.xyz, r6.xyzx, l(-0.000000, -1.000000, -0.000000, 0.000000)
    dp3 r7.w, r11.xyzx, r13.xyzx
    add r11.xyz, r9.xyzx, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r14.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r11.zyxz, r14.xyzx
    add r11.xyz, r8.wwww, r11.xyzx

#line 53
    add r14.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r14.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r14.xyz, r6.xyzx, l(-1.000000, -1.000000, -0.000000, 0.000000)
    dp3 r8.w, r11.xyzx, r14.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r10.x, r8.w, r7.w
    add r7.w, -r6.w, r7.w
    mad r6.w, r10.y, r7.w, r6.w
    add r11.xyz, r9.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r15.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r11.zyxz, r15.xyzx
    add r11.xyz, r7.wwww, r11.xyzx

#line 53
    add r15.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r15.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r15.xyz, r6.xyzx, l(-0.000000, -0.000000, -1.000000, 0.000000)
    dp3 r7.w, r11.xyzx, r15.xyzx
    add r11.xyz, r9.xyzx, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r16.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r11.zyxz, r16.xyzx
    add r11.xyz, r8.wwww, r11.xyzx

#line 53
    add r16.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r16.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r16.xyz, r6.xyzx, l(-1.000000, -0.000000, -1.000000, 0.000000)
    dp3 r8.w, r11.xyzx, r16.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r10.x, r8.w, r7.w
    add r11.xyz, r9.xyzx, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r17.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r11.zyxz, r17.xyzx
    add r11.xyz, r8.wwww, r11.xyzx

#line 53
    add r17.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r17.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r17.xyz, r6.xyzx, l(-0.000000, -1.000000, -1.000000, 0.000000)
    dp3 r8.w, r11.xyzx, r17.xyzx
    add r9.xyz, r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r9.xyz, r9.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r9.xyz, r9.xyzx  // r9.x <- p3.z; r9.y <- p3.y; r9.z <- p3.x

#line 52
    add r11.xyz, r9.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r9.w, r9.zyxz, r11.xyzx
    add r9.xyz, r9.wwww, r9.xyzx

#line 53
    add r11.xyz, r9.yzyy, r9.zzzz
    mul r9.xyz, r9.xyzx, r11.xyzx
    frc r9.xyz, r9.xyzx  // r9.x <- <hash33_id14 return value>.x; r9.y <- <hash33_id14 return value>.y; r9.z <- <hash33_id14 return value>.z

#line 60
    mad r9.xyz, r9.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r6.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r9.x, r9.xyzx, r11.xyzx
    add r9.x, -r8.w, r9.x
    mad r8.w, r10.x, r9.x, r8.w
    add r8.w, -r7.w, r8.w
    mad r7.w, r10.y, r8.w, r7.w
    add r7.w, -r6.w, r7.w
    mad r6.w, r10.z, r7.w, r6.w
    mul r9.x, r6.w, cb0[12].y

#line 57
    round_ni r7.xyz, r7.xyzx  // r7.x <- i.z; r7.y <- i.y; r7.z <- i.x

#line 51
    mul r18.xyz, r7.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r18.xyz, r18.xyzx  // r18.x <- p3.z; r18.y <- p3.y; r18.z <- p3.x

#line 52
    add r19.xyz, r18.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r18.zyxz, r19.xyzx
    add r18.xyz, r6.wwww, r18.xyzx

#line 53
    add r19.xyz, r18.yzyy, r18.zzzz
    mul r18.xyz, r18.xyzx, r19.xyzx
    frc r18.xyz, r18.xyzx  // r18.x <- <hash33_id14 return value>.x; r18.y <- <hash33_id14 return value>.y; r18.z <- <hash33_id14 return value>.z

#line 60
    mad r18.xyz, r18.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.x, r18.xyzx, r6.xyzx
    add r6.yzw, r7.xxyz, l(0.000000, 0.000000, 0.000000, 1.000000)

#line 51
    mul r6.yzw, r6.yyzw, l(0.000000, 0.097300, 0.103000, 0.103100)
    frc r6.yzw, r6.yyzw  // r6.y <- p3.z; r6.z <- p3.y; r6.w <- p3.x

#line 52
    add r18.xyz, r6.zwyz, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r6.wzyw, r18.xyzx
    add r6.yzw, r6.yyzw, r7.wwww

#line 53
    add r18.xyz, r6.zwzz, r6.wwww
    mul r6.yzw, r6.yyzw, r18.xxyz
    frc r6.yzw, r6.yyzw  // r6.y <- <hash33_id14 return value>.x; r6.z <- <hash33_id14 return value>.y; r6.w <- <hash33_id14 return value>.z

#line 60
    mad r6.yzw, r6.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
    dp3 r6.y, r6.yzwy, r12.xyzx
    add r6.y, -r6.x, r6.y
    mad r6.x, r10.x, r6.y, r6.x
    add r6.yzw, r7.xxyz, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r6.yzw, r6.yyzw, l(0.000000, 0.097300, 0.103000, 0.103100)
    frc r6.yzw, r6.yyzw  // r6.y <- p3.z; r6.z <- p3.y; r6.w <- p3.x

#line 52
    add r12.xyz, r6.zwyz, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r6.wzyw, r12.xyzx
    add r6.yzw, r6.yyzw, r7.wwww

#line 53
    add r12.xyz, r6.zwzz, r6.wwww
    mul r6.yzw, r6.yyzw, r12.xxyz
    frc r6.yzw, r6.yyzw  // r6.y <- <hash33_id14 return value>.x; r6.z <- <hash33_id14 return value>.y; r6.w <- <hash33_id14 return value>.z

#line 60
    mad r6.yzw, r6.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
    dp3 r6.y, r6.yzwy, r13.xyzx
    add r12.xyz, r7.xyzx, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r12.xyz, r12.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r12.xyz, r12.xyzx  // r12.x <- p3.z; r12.y <- p3.y; r12.z <- p3.x

#line 52
    add r13.xyz, r12.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.z, r12.zyxz, r13.xyzx
    add r12.xyz, r6.zzzz, r12.xyzx

#line 53
    add r13.xyz, r12.yzyy, r12.zzzz
    mul r12.xyz, r12.xyzx, r13.xyzx
    frc r12.xyz, r12.xyzx  // r12.x <- <hash33_id14 return value>.x; r12.y <- <hash33_id14 return value>.y; r12.z <- <hash33_id14 return value>.z

#line 60
    mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.z, r12.xyzx, r14.xyzx
    add r6.z, -r6.y, r6.z
    mad r6.y, r10.x, r6.z, r6.y
    add r6.y, -r6.x, r6.y
    mad r6.x, r10.y, r6.y, r6.x
    add r6.yzw, r7.xxyz, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r6.yzw, r6.yyzw, l(0.000000, 0.097300, 0.103000, 0.103100)
    frc r6.yzw, r6.yyzw  // r6.y <- p3.z; r6.z <- p3.y; r6.w <- p3.x

#line 52
    add r12.xyz, r6.zwyz, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r6.wzyw, r12.xyzx
    add r6.yzw, r6.yyzw, r7.wwww

#line 53
    add r12.xyz, r6.zwzz, r6.wwww
    mul r6.yzw, r6.yyzw, r12.xxyz
    frc r6.yzw, r6.yyzw  // r6.y <- <hash33_id14 return value>.x; r6.z <- <hash33_id14 return value>.y; r6.w <- <hash33_id14 return value>.z

#line 60
    mad r6.yzw, r6.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
    dp3 r6.y, r6.yzwy, r15.xyzx
    add r12.xyz, r7.xyzx, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r12.xyz, r12.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r12.xyz, r12.xyzx  // r12.x <- p3.z; r12.y <- p3.y; r12.z <- p3.x

#line 52
    add r13.xyz, r12.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.z, r12.zyxz, r13.xyzx
    add r12.xyz, r6.zzzz, r12.xyzx

#line 53
    add r13.xyz, r12.yzyy, r12.zzzz
    mul r12.xyz, r12.xyzx, r13.xyzx
    frc r12.xyz, r12.xyzx  // r12.x <- <hash33_id14 return value>.x; r12.y <- <hash33_id14 return value>.y; r12.z <- <hash33_id14 return value>.z

#line 60
    mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.z, r12.xyzx, r16.xyzx
    add r6.z, -r6.y, r6.z
    mad r6.y, r10.x, r6.z, r6.y
    add r12.xyz, r7.xyzx, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r12.xyz, r12.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r12.xyz, r12.xyzx  // r12.x <- p3.z; r12.y <- p3.y; r12.z <- p3.x

#line 52
    add r13.xyz, r12.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.z, r12.zyxz, r13.xyzx
    add r12.xyz, r6.zzzz, r12.xyzx

#line 53
    add r13.xyz, r12.yzyy, r12.zzzz
    mul r12.xyz, r12.xyzx, r13.xyzx
    frc r12.xyz, r12.xyzx  // r12.x <- <hash33_id14 return value>.x; r12.y <- <hash33_id14 return value>.y; r12.z <- <hash33_id14 return value>.z

#line 60
    mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.z, r12.xyzx, r17.xyzx
    add r7.xyz, r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r7.xyz, r7.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r7.xyz, r7.xyzx  // r7.x <- p3.z; r7.y <- p3.y; r7.z <- p3.x

#line 52
    add r12.xyz, r7.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r7.zyxz, r12.xyzx
    add r7.xyz, r6.wwww, r7.xyzx

#line 53
    add r12.xyz, r7.yzyy, r7.zzzz
    mul r7.xyz, r7.xyzx, r12.xyzx
    frc r7.xyz, r7.xyzx  // r7.x <- <hash33_id14 return value>.x; r7.y <- <hash33_id14 return value>.y; r7.z <- <hash33_id14 return value>.z

#line 60
    mad r7.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.w, r7.xyzx, r11.xyzx
    add r6.w, -r6.z, r6.w
    mad r6.z, r10.x, r6.w, r6.z
    add r6.z, -r6.y, r6.z
    mad r6.y, r10.y, r6.z, r6.y
    add r6.y, -r6.x, r6.y
    mad r6.x, r10.z, r6.y, r6.x
    mul r9.y, r6.x, cb0[12].z

#line 57
    round_ni r6.xyz, r8.zyxz  // r6.x <- i.z; r6.y <- i.y; r6.z <- i.x

#line 58
    frc r7.xyz, r8.xyzx  // r7.x <- f.x; r7.y <- f.y; r7.z <- f.z

#line 59
    mul r8.xyz, r7.xyzx, r7.xyzx
    mad r10.xyz, -r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(3.000000, 3.000000, 3.000000, 0.000000)
    mul r8.xyz, r8.xyzx, r10.xyzx  // r8.x <- u.x; r8.y <- u.y; r8.z <- u.z

#line 51
    mul r10.xyz, r6.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r10.zyxz, r11.xyzx
    add r10.xyz, r6.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.w, r10.xyzx, r7.xyzx
    add r10.xyz, r6.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r10.zyxz, r11.xyzx
    add r10.xyz, r7.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-1.000000, -0.000000, -0.000000, 0.000000)
    dp3 r7.w, r10.xyzx, r11.xyzx
    add r7.w, -r6.w, r7.w
    mad r6.w, r8.x, r7.w, r6.w
    add r10.xyz, r6.xyzx, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r10.zyxz, r11.xyzx
    add r10.xyz, r7.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-0.000000, -1.000000, -0.000000, 0.000000)
    dp3 r7.w, r10.xyzx, r11.xyzx
    add r10.xyz, r6.xyzx, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r10.zyxz, r11.xyzx
    add r10.xyz, r8.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-1.000000, -1.000000, -0.000000, 0.000000)
    dp3 r8.w, r10.xyzx, r11.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r8.x, r8.w, r7.w
    add r7.w, -r6.w, r7.w
    mad r6.w, r8.y, r7.w, r6.w
    add r10.xyz, r6.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r10.zyxz, r11.xyzx
    add r10.xyz, r7.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-0.000000, -0.000000, -1.000000, 0.000000)
    dp3 r7.w, r10.xyzx, r11.xyzx
    add r10.xyz, r6.xyzx, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r10.zyxz, r11.xyzx
    add r10.xyz, r8.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-1.000000, -0.000000, -1.000000, 0.000000)
    dp3 r8.w, r10.xyzx, r11.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r8.x, r8.w, r7.w
    add r10.xyz, r6.xyzx, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r10.zyxz, r11.xyzx
    add r10.xyz, r8.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-0.000000, -1.000000, -1.000000, 0.000000)
    dp3 r8.w, r10.xyzx, r11.xyzx
    add r6.xyz, r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r6.xyz, r6.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r6.xyz, r6.xyzx  // r6.x <- p3.z; r6.y <- p3.y; r6.z <- p3.x

#line 52
    add r10.xyz, r6.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r9.w, r6.zyxz, r10.xyzx
    add r6.xyz, r6.xyzx, r9.wwww

#line 53
    add r10.xyz, r6.yzyy, r6.zzzz
    mul r6.xyz, r6.xyzx, r10.xyzx
    frc r6.xyz, r6.xyzx  // r6.x <- <hash33_id14 return value>.x; r6.y <- <hash33_id14 return value>.y; r6.z <- <hash33_id14 return value>.z

#line 60
    mad r6.xyz, r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r7.xyz, r7.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.x, r6.xyzx, r7.xyzx
    add r6.x, -r8.w, r6.x
    mad r6.x, r8.x, r6.x, r8.w
    add r6.x, -r7.w, r6.x
    mad r6.x, r8.y, r6.x, r7.w
    add r6.x, -r6.w, r6.x
    mad r6.x, r8.z, r6.x, r6.w
    mul r9.z, r6.x, cb0[12].w

#line 96
    mad r6.xyz, r9.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), cb0[13].xyzx  // r6.x <- result_766315301.x; r6.y <- result_766315301.y; r6.z <- result_766315301.z

#line 182
    itof r6.w, r5.x

#line 183
    add r6.w, -r6.w, cb0[14].x  // r6.w <- result_3423540216

#line 184
    min r6.w, r6.w, l(1.000000)  // r6.w <- min_2381392272

#line 185
    mul r7.x, r4.w, r6.w  // r7.x <- result_3976223168

#line 187
    mad r4.xyz, r6.xyzx, r7.xxxx, r4.xyzx  // r4.x <- result_3074941784.x; r4.y <- result_3074941784.y; r4.z <- result_3074941784.z

#line 188
    mad r3.w, r6.w, r4.w, r3.w  // r3.w <- result_2986031310

#line 189
    mul r4.w, r4.w, cb0[13].w  // r4.w <- result_2569548736

#line 194
    iadd r5.x, r5.x, l(1)
    mov r2.yzw, r5.yyzw
  endloop   // r4.x <- output_3434651123.x; r4.y <- output_3434651123.y; r4.z <- output_3434651123.z; r3.w <- output_2735912516; r4.w <- output_1136910249

#line 195
  lt r2.x, l(0.000000), r3.w  // r2.x <- Assign_1036286839

#line 196
  movc r2.x, r2.x, r3.w, l(1.000000)  // r2.x <- expression_4225115170

#line 198
  div r2.xyz, r4.xyzx, r2.xxxx  // r2.x <- result_1716249591.x; r2.y <- result_1716249591.y; r2.z <- result_1716249591.z

#line 199
  add r2.xyz, r2.xyzx, cb0[15].xyzx  // r2.x <- result_261652760.x; r2.y <- result_261652760.y; r2.z <- result_261652760.z

#line 201
  add r2.xyz, r1.xyzx, r2.xyzx  // r2.x <- result_1280460646.x; r2.y <- result_1280460646.y; r2.z <- result_1280460646.z

#line 209
  mov r2.w, l(1.000000)
  add r2.xyzw, -r1.xyzw, r2.xyzw
  mov r4.x, cb0[15].w
  mov r4.w, l(1.000000)
  mad r1.xyzw, r4.xxxw, r2.xyzw, r1.xyzw  // r1.x <- lerp_2778180493.x; r1.y <- lerp_2778180493.y; r1.z <- lerp_2778180493.z; r1.w <- lerp_2778180493.w

#line 211
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- density_271962606

#line 79
  add r0.yzw, r3.xxyz, -cb0[16].xxyz  // r0.y <- result_2932810882.x; r0.z <- result_2932810882.y; r0.w <- result_2932810882.z

#line 80
  dp3 r0.y, r0.yzwy, r0.yzwy
  sqrt r0.y, r0.y  // r0.y <- length_1655730897

#line 81
  add r0.y, r0.y, -cb0[16].w  // r0.y <- result_865967073

#line 217
  mul_sat r0.y, -r0.y, l(1.#INF00)  // r0.y <- saturate_3099562544

#line 221
  add r0.z, -r0.x, cb0[17].x
  mad r0.x, r0.y, r0.z, r0.x  // r0.x <- lerp_2814824100

#line 223
  store_uav_typed u0.xyzw, vThreadID.xyzz, r1.xyzw

#line 224
  store_uav_typed u1.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 250
ret 
// Approximately 407 instruction slots used
***************************
*************************/
static const float PI_id12 = 3.1415926535897;
static const float3 vectorValuedNoiseOffsets_id22 = float3(17.0, -43.7, 67.0);
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_838590723_id27;
    float input_1058178022_id28;
    float3 input_407320090_id29;
    float3 input_1157260306_id30;
    float input_645245252_id31;
    float3 input_568116523_id32;
    int3 input_4140015311_id33;
    float3 input_1740323861_id34;
    float4x4 input_4251367585_id35;
    float3 input_1310941215_id36;
    float input_159017704_id37;
    float input_776891185_id38;
    float3 input_1239917863_id39;
    float3 input_4274391210_id40;
    float input_2465657493_id41;
    float input_2051487400_id42;
    float input_579890576_id43;
    float3 input_57480610_id44;
    float input_2861981802_id45;
    float3 input_3660883841_id46;
    float input_2814605708_id47;
    float input_641060572_id48;
};
Texture3D<float4> TextureInput_2957714998_id23;
Texture3D<float> TextureInput_1288012844_id24;
RWTexture3D<float4> TextureInput_1941307003_id25;
RWTexture3D<float> TextureInput_1905746801_id26;
float3 hash33_id14(float3 p3)
{
    p3 = frac(p3 * float3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz + 19.19);
    return frac((p3.xxy + p3.yxx) * p3.zyx);
}
float gradientNoise_id54(float3 p)
{
    float3 i = floor(p);
    float3 f = frac(p);
    float3 u = f * f * (3.0 - 2.0 * f);
    return 2. * lerp(lerp(lerp(dot(hash33_id14(i + float3(0.0, 0.0, 0.0)) * 2.0 - 1.0, f - float3(0.0, 0.0, 0.0)), dot(hash33_id14(i + float3(1.0, 0.0, 0.0)) * 2.0 - 1.0, f - float3(1.0, 0.0, 0.0)), u.x), lerp(dot(hash33_id14(i + float3(0.0, 1.0, 0.0)) * 2.0 - 1.0, f - float3(0.0, 1.0, 0.0)), dot(hash33_id14(i + float3(1.0, 1.0, 0.0)) * 2.0 - 1.0, f - float3(1.0, 1.0, 0.0)), u.x), u.y), lerp(lerp(dot(hash33_id14(i + float3(0.0, 0.0, 1.0)) * 2.0 - 1.0, f - float3(0.0, 0.0, 1.0)), dot(hash33_id14(i + float3(1.0, 0.0, 1.0)) * 2.0 - 1.0, f - float3(1.0, 0.0, 1.0)), u.x), lerp(dot(hash33_id14(i + float3(0.0, 1.0, 1.0)) * 2.0 - 1.0, f - float3(0.0, 1.0, 1.0)), dot(hash33_id14(i + float3(1.0, 1.0, 1.0)) * 2.0 - 1.0, f - float3(1.0, 1.0, 1.0)), u.x), u.y), u.z);
}
void noiseDomainOffset_id42(inout float3 p1, out float3 p2, out float3 p3)
{
    p2 = p1 + vectorValuedNoiseOffsets_id22.x;
    p3 = p1 + vectorValuedNoiseOffsets_id22.y;
}
float3 gradientNoise33_id68(float3 p)
{
    float3 p2, p3;
    noiseDomainOffset_id42(p, p2, p3);
    return float3(gradientNoise_id54(p), gradientNoise_id54(p2), gradientNoise_id54(p3));
}
float Function_1547685564_id77(in float arg_0)
{
    return arg_0;
}
float Function_3847791208_id76(in float3 arg_0, out float arg_1)
{
    float3 result_2932810882 = (arg_0 - input_3660883841_id46);
    float length_1655730897 = length(result_2932810882);
    float result_865967073 = (length_1655730897 - input_2814605708_id47);
    arg_1 = result_865967073;
    return input_641060572_id48;
}
float3 cast31_id75(float p)
{
    return p.xxx;
}
float3 Function_1983649234_id74(in float3 arg_0)
{
    float3 result_1503178597 = (arg_0 * input_1310941215_id36);
    float3 Float3Join_1828410946 = float3(input_159017704_id37, input_776891185_id38, 0);
    float3 result_3587333782 = (result_1503178597 + Float3Join_1828410946);
    float3 gradientNoise33_2948582019 = gradientNoise33_id68(result_3587333782);
    float3 result_2006876878 = (gradientNoise33_2948582019 * input_1239917863_id39);
    float3 result_766315301 = (result_2006876878 + input_4274391210_id40);
    return result_766315301;
}
float cast11_id73(float p)
{
    return p;
}
float4 cast41_id72(float p)
{
    return float4(p, p, p, 1);
}
float Function_573297690_id71(in float arg_0)
{
    return arg_0;
}
float4 Function_3104157604_id70(in float3 arg_0, out float arg_1)
{
    float3 result_310773393 = (arg_0 - input_1157260306_id30);
    float length_1284112446 = length(result_310773393);
    float result_2455429488 = (length_1284112446 - input_645245252_id31);
    arg_1 = result_2455429488;
    float4 join_4079291855 = float4(input_568116523_id32, 1);
    return join_4079291855;
}
float3 cast33_id69(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_2062887072 = streams.DispatchThreadId_id1.x;
    int inputX_181602231 = input_838590723_id27.x;
    bool Assign_3689940353 = DispatchThreadIdX_2062887072 >= inputX_181602231;
    int DispatchThreadIdY_1977333336 = streams.DispatchThreadId_id1.y;
    int inputY_3191009213 = input_838590723_id27.y;
    bool Assign_1627392202 = DispatchThreadIdY_1977333336 >= inputY_3191009213;
    int DispatchThreadIdZ_1073105291 = streams.DispatchThreadId_id1.z;
    int inputZ_1725069496 = input_838590723_id27.z;
    bool Assign_1774890877 = DispatchThreadIdZ_1073105291 >= inputZ_1725069496;
    bool result_1149744962 = (Assign_3689940353 || Assign_1627392202 || Assign_1774890877);
    if (result_1149744962)
    {
        return;
    }
    float4 velocity_977671682 = TextureInput_2957714998_id23[streams.DispatchThreadId_id1];
    float density_2320042252 = TextureInput_1288012844_id24[streams.DispatchThreadId_id1];
    float deltatime_2067742189 = 0;
    deltatime_2067742189 = input_1058178022_id28;
    int3 index_116816658 = int3(0, 0, 0);
    index_116816658 = streams.DispatchThreadId_id1;
    float3 resourcescale_3944039459 = float3(0, 0, 0);
    resourcescale_3944039459 = input_407320090_id29;
    float4 velocity_2_977671682 = TextureInput_2957714998_id23[streams.DispatchThreadId_id1];
    float3 cast33_1287558517 = cast33_id69(streams.DispatchThreadId_id1);
    float3 result_2524718450 = (cast33_1287558517 + float3(0.5, 0.5, 0.5));
    float3 cast33_867565431 = cast33_id69(input_4140015311_id33);
    float3 result_3593319729 = (result_2524718450 / cast33_867565431);
    float3 result_1044597739 = (result_3593319729 - 0.5);
    float3 result_3498572618 = (float3(0.5, 0.5, 0.5) - float3(0.5, 0.5, 0.5));
    float3 result_1022909267 = (result_3498572618 * input_1740323861_id34);
    float3 result_1656580637 = (result_1044597739 + result_1022909267);
    float4 join_3627650546 = float4(result_1656580637, 1);
    float4 mul_1350355877 = mul(join_3627650546, input_4251367585_id35);
    float3 mulXyz_297910940 = mul_1350355877.xyz;
    float output_2122746194 = 0;
    float4 Invoke_1662571361 = Function_3104157604_id70(mulXyz_297910940, output_2122746194);
    float negate_445408833 = -output_2122746194;
    float result_1550056128 = (negate_445408833 - 0);
    float result_3205724771 = (0 - 0);
    float result_1122315373 = (result_1550056128 / result_3205724771);
    float saturate_2935286286 = saturate(result_1122315373);
    float Invoke_987678189 = Function_573297690_id71(saturate_2935286286);
    float4 cast41_811699533 = cast41_id72(Invoke_987678189);
    float4 lerp_424500790 = lerp(velocity_2_977671682, Invoke_1662571361, cast41_811699533);
    velocity_2_977671682 = lerp_424500790;
    float ceil_4294286268 = ceil(input_2051487400_id42);
    int cast11_3304455865 = cast11_id73(ceil_4294286268);
    float3 output_2313305742 = mulXyz_297910940;
    float3 output_3434651123 = float3(0, 0, 0);
    float output_2735912516 = 0;
    float output_1136910249 = input_2465657493_id41;

    for (int index_290661277 = 0; index_290661277 < cast11_3304455865; index_290661277++)
    {
        float3 result_2782021489 = (output_2313305742 * input_579890576_id43);
        float3 Invoke_3646940830 = Function_1983649234_id74(output_2313305742);
        float cast11_533358101 = cast11_id73(index_290661277);
        float result_3423540216 = (input_2051487400_id42 - cast11_533358101);
        float min_2381392272 = min(result_3423540216, 1);
        float result_3976223168 = (min_2381392272 * output_1136910249);
        float3 result_1243284689 = (Invoke_3646940830 * result_3976223168);
        float3 result_3074941784 = (output_3434651123 + result_1243284689);
        float result_2986031310 = (output_2735912516 + result_3976223168);
        float result_2569548736 = (output_1136910249 * input_2465657493_id41);
        output_2313305742 = result_2782021489;
        output_3434651123 = result_3074941784;
        output_2735912516 = result_2986031310;
        output_1136910249 = result_2569548736;
    }
    bool Assign_1036286839 = output_2735912516 > 0;
    float expression_4225115170 = Assign_1036286839 ? output_2735912516 : 1;
    float3 cast31_298070812 = cast31_id75(expression_4225115170);
    float3 result_1716249591 = (output_3434651123 / cast31_298070812);
    float3 result_261652760 = (result_1716249591 + input_57480610_id44);
    float4 join_3411492255 = float4(result_261652760, 1);
    float4 result_1280460646 = (velocity_2_977671682 + join_3411492255);
    float3 resultXyz_3271431999 = result_1280460646.xyz;
    float VelocityW_1667792265 = velocity_2_977671682.w;
    float joinW_212047312 = join_3411492255.w;
    float4 cast41_2222156496 = cast41_id72(input_2861981802_id45);
    float cast41W_279890670 = cast41_2222156496.w;
    float lerp_2680930479 = lerp(VelocityW_1667792265, joinW_212047312, cast41W_279890670);
    float4 join_1392407605 = float4(resultXyz_3271431999, lerp_2680930479);
    float4 lerp_2778180493 = lerp(velocity_2_977671682, join_1392407605, cast41_2222156496);
    velocity_2_977671682 = lerp_2778180493;
    float density_271962606 = TextureInput_1288012844_id24[streams.DispatchThreadId_id1];
    float output_1747542768 = 0;
    float Invoke_1866861173 = Function_3847791208_id76(mulXyz_297910940, output_1747542768);
    float negate_1649460757 = -output_1747542768;
    float result_705627010 = (negate_1649460757 - 0);
    float result_526997639 = (0 - 0);
    float result_2456431321 = (result_705627010 / result_526997639);
    float saturate_3099562544 = saturate(result_2456431321);
    float Invoke_3288184337 = Function_1547685564_id77(saturate_3099562544);
    float cast11_3762684425 = cast11_id73(Invoke_3288184337);
    float lerp_2814824100 = lerp(density_271962606, Invoke_1866861173, cast11_3762684425);
    density_271962606 = lerp_2814824100;
    TextureInput_1941307003_id25[streams.DispatchThreadId_id1] = velocity_2_977671682;
    TextureInput_1905746801_id26[streams.DispatchThreadId_id1] = density_271962606;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
