/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin Lava_Internal_TextureFX [{ColorA = InputFloat4<ShaderFX.InputValueFloat4_Color,PerUpdate>}, {ColorB = InputFloat4<ShaderFX.InputValueFloat4_Color.i1,PerUpdate>}, {Phi = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}, {Time = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}]
@P ColorA: InputFloat4<ShaderFX.InputValueFloat4_Color,PerUpdate>
@P ColorB: InputFloat4<ShaderFX.InputValueFloat4_Color.i1,PerUpdate>
@P Phi: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P Time: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 48]
@C    InputValue_id97 => ShaderFX.InputValueFloat4_Color
@C    InputValue_id98 => ShaderFX.InputValueFloat4_Color.i1
@C    InputValue_id99 => ShaderFX.InputValueFloat
@C    InputValue_id100 => ShaderFX.InputValueFloat.i1
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Lava_Internal_TextureFX => 5876a999082b69c12964d4cfb5db0fe3
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    AddonShaderUtils => 0d3496ddd24bfcbde4abd1deae724f64
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 272 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_acce9246ec0ba94d1c2aec0c6336f7fd.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 276
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => edd5912fdaf21eb993f484d2b0e3387d
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id97;            // Offset:    0 Size:    16
//   float4 InputValue_id98;            // Offset:   16 Size:    16
//   float InputValue_id99;             // Offset:   32 Size:     4
//   float InputValue_id100;            // Offset:   36 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerUpdate                         cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 14
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 238 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_acce9246ec0ba94d1c2aec0c6336f7fd.hlsl"
mov r0.xy, v1.xyxx
mov r0.z, cb0[2].y
mul r1.xyz, r0.xyzx, l(4.000000, 4.000000, 0.400000, 0.000000)

#line 167
round_ni r2.xyz, r1.xyzx  // r2.x <- Pi0.x; r2.y <- Pi0.y; r2.z <- Pi0.z

#line 171
frc r1.xyz, r1.xyzx  // r1.x <- Pf0.x; r1.y <- Pf0.y; r1.z <- Pf0.z

#line 168
add r3.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r3.x <- Pi1.x; r3.y <- Pi1.y; r3.z <- Pi1.z

#line 163
mul r4.xyz, r3.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r4.xyz, r4.xyzx
mad r3.xyz, -r4.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r3.xyzx  // r3.x <- <mod289_id68 return value>.x; r3.y <- <mod289_id68 return value>.y; r3.z <- <mod289_id68 return value>.z

#line 159
mov r4.w, r3.x

#line 163
mul r5.xyz, r2.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r5.xyz, r5.xyzx
mad r4.xyz, -r5.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r2.xyzx  // r4.x <- <mod289_id68 return value>.x; r4.y <- <mod289_id68 return value>.y; r4.z <- <mod289_id68 return value>.z

#line 159
mad r2.xyzw, r4.xwxw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r4.xwxw, r2.xyzw

#line 147
mul r5.xyzw, r2.zwzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.z <- <mod289_id69 return value>.x; r2.w <- <mod289_id69 return value>.y

#line 177
mov r3.w, r4.y
add r2.xyzw, r3.wwyy, r2.xyzw

#line 159
mad r5.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r5.xyzw

#line 147
mul r5.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 178
add r4.xyzw, r4.zzzz, r2.xyzw

#line 179
add r2.xyzw, r3.zzzz, r2.xyzw

#line 159
mad r3.xyzw, r4.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r4.xyzw, r3.xyzw

#line 147
mul r4.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r4.xyzw, r4.xyzw
mad r3.xyzw, -r4.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id69 return value>.x; r3.y <- <mod289_id69 return value>.y; r3.z <- <mod289_id69 return value>.z; r3.w <- <mod289_id69 return value>.w

#line 180
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r3.x <- gx0.x; r3.y <- gx0.y; r3.z <- gx0.z; r3.w <- gx0.w

#line 182
frc r4.xyzw, r3.xyzw  // r4.x <- gx0.x; r4.y <- gx0.y; r4.z <- gx0.z; r4.w <- gx0.w

#line 181
round_ni r3.xyzw, r3.xyzw
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r3.xyzw, r3.xyzw
add r3.xyzw, r3.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r3.x <- gy0.x; r3.y <- gy0.y; r3.z <- gy0.z; r3.w <- gy0.w

#line 185
ge r5.xyzw, r4.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r5.xyzw, r5.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 183
add r6.xyzw, -r4.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r6.xyzw, -|r3.xywz|, r6.xywz  // r6.x <- gz0.x; r6.y <- gz0.y; r6.z <- gz0.w; r6.w <- gz0.z

#line 184
ge r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r6.xywz
and r7.xyzw, r7.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r7.x <- sz0.x; r7.y <- sz0.y; r7.z <- sz0.z; r7.w <- sz0.w

#line 185
mad r4.xyzw, -r7.xyzw, r5.xyzw, r4.xyzw

#line 202
mov r5.x, r4.x

#line 186
ge r8.xyzw, r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r8.xyzw, r8.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r3.xyzw, -r7.xyzw, r8.xyzw, r3.xyzw

#line 202
mov r5.y, r3.x
mov r5.z, r6.x
dp3 r7.x, r5.xyzx, r5.xyzx
mov r8.z, r6.w
mov r8.x, r4.z
mov r8.y, r3.z
dp3 r7.y, r8.xyzx, r8.xyzx
mov r3.z, r6.y
mov r3.x, r4.y
mov r6.x, r4.w
mov r6.y, r3.w
dp3 r7.z, r3.xyzx, r3.xyzx
dp3 r7.w, r6.xyzx, r6.xyzx

#line 155
mul r4.xyzw, r7.xyzw, cb0[2].xxxx
mad r4.xyzw, -r4.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r4.x <- <taylorInvSqrt_id71 return value>.x; r4.y <- <taylorInvSqrt_id71 return value>.y; r4.z <- <taylorInvSqrt_id71 return value>.z; r4.w <- <taylorInvSqrt_id71 return value>.w

#line 205
mul r3.xyz, r3.xyzx, r4.zzzz  // r3.x <- g100.x; r3.y <- g100.y; r3.z <- g100.z

#line 213
add r1.w, r1.x, l(-1.000000)
dp3 r3.y, r3.yzxy, r1.yzwy  // r3.y <- n100

#line 159
mad r7.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r7.xyzw

#line 147
mul r7.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r7.xyzw, r7.xyzw
mad r2.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 187
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r2.x <- gx1.x; r2.y <- gx1.y; r2.z <- gx1.z; r2.w <- gx1.w

#line 189
frc r7.xyzw, r2.xyzw  // r7.x <- gx1.x; r7.y <- gx1.y; r7.z <- gx1.z; r7.w <- gx1.w

#line 188
round_ni r2.xyzw, r2.xyzw
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r2.xyzw, r2.xyzw
add r2.xyzw, r2.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r2.x <- gy1.x; r2.y <- gy1.y; r2.z <- gy1.z; r2.w <- gy1.w

#line 192
ge r9.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r9.xyzw, r9.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 190
add r10.xyzw, -r7.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r10.xyzw, -|r2.xywz|, r10.xywz  // r10.x <- gz1.x; r10.y <- gz1.y; r10.z <- gz1.w; r10.w <- gz1.z

#line 191
ge r11.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r10.xywz
and r11.xyzw, r11.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r11.x <- sz1.x; r11.y <- sz1.y; r11.z <- sz1.z; r11.w <- sz1.w

#line 192
mad r7.xyzw, -r11.xyzw, r9.xyzw, r7.xyzw

#line 207
mov r9.x, r7.x

#line 193
ge r12.xyzw, r2.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r12.xyzw, r12.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r2.xyzw, -r11.xyzw, r12.xyzw, r2.xyzw

#line 207
mov r9.y, r2.x
mov r9.z, r10.x
dp3 r11.x, r9.xyzx, r9.xyzx
mov r12.z, r10.w
mov r12.x, r7.z
mov r12.y, r2.z
dp3 r11.y, r12.xyzx, r12.xyzx
mov r2.z, r10.y
mov r2.x, r7.y
mov r10.x, r7.w
mov r10.y, r2.w
dp3 r11.z, r2.xyzx, r2.xyzx
dp3 r11.w, r10.xyzx, r10.xyzx

#line 155
mul r7.xyzw, r11.xyzw, cb0[2].xxxx
mad r7.xyzw, -r7.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r7.x <- <taylorInvSqrt_id71 return value>.x; r7.y <- <taylorInvSqrt_id71 return value>.y; r7.z <- <taylorInvSqrt_id71 return value>.z; r7.w <- <taylorInvSqrt_id71 return value>.w

#line 208
mul r9.xyz, r7.xxxx, r9.xyzx  // r9.x <- g001.x; r9.y <- g001.y; r9.z <- g001.z

#line 216
add r11.xyz, r1.xyzx, l(0.000000, 0.000000, -1.000000, 0.000000)
dp3 r9.x, r9.xyzx, r11.xyzx  // r9.x <- n001

#line 210
mul r2.xyz, r2.xyzx, r7.zzzz  // r2.x <- g101.x; r2.y <- g101.y; r2.z <- g101.z

#line 217
add r11.xyz, r1.xyzx, l(-1.000000, 0.000000, -1.000000, 0.000000)
dp3 r9.y, r2.xyzx, r11.xyzx  // r9.y <- n101

#line 209
mul r2.xyz, r7.yyyy, r12.xyzx  // r2.x <- g011.x; r2.y <- g011.y; r2.z <- g011.z

#line 211
mul r7.xyz, r7.wwww, r10.xyzx  // r7.x <- g111.x; r7.y <- g111.y; r7.z <- g111.z

#line 218
add r10.xyz, r1.xyzx, l(0.000000, -1.000000, -1.000000, 0.000000)
dp3 r9.z, r2.xyzx, r10.xyzx  // r9.z <- n011

#line 172
add r2.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- Pf1.x; r2.y <- Pf1.y; r2.z <- Pf1.z

#line 219
dp3 r9.w, r7.xyzx, r2.xyzx  // r9.w <- n111

#line 204
mul r2.xyz, r4.yyyy, r8.xyzx  // r2.x <- g010.x; r2.y <- g010.y; r2.z <- g010.z

#line 214
add r7.xyz, r1.xyzx, l(0.000000, -1.000000, 0.000000, 0.000000)
dp3 r3.z, r2.xyzx, r7.xyzx  // r3.z <- n010

#line 206
mul r2.xyz, r4.wwww, r6.xyzx  // r2.x <- g110.x; r2.y <- g110.y; r2.z <- g110.z

#line 203
mul r4.xyz, r4.xxxx, r5.xyzx  // r4.x <- g000.x; r4.y <- g000.y; r4.z <- g000.z

#line 212
dp3 r3.x, r4.xyzx, r1.xyzx  // r3.x <- n000

#line 215
add r4.xyz, r1.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
dp3 r3.w, r2.xyzx, r4.xyzx  // r3.w <- n110

#line 221
add r2.xyzw, -r3.xyzw, r9.xyzw

#line 151
mul r4.xyz, r1.xyzx, r1.xyzx
mul r4.xyz, r1.xyzx, r4.xyzx
mad r5.xyz, r1.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-15.000000, -15.000000, -15.000000, 0.000000)
mad r1.xyz, r1.xyzx, r5.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
mul r1.xyz, r1.xyzx, r4.xyzx  // r1.x <- <fade_id72 return value>.x; r1.y <- <fade_id72 return value>.y; r1.z <- <fade_id72 return value>.z

#line 221
mad r2.xyzw, r1.zzzz, r2.xyzw, r3.xyzw  // r2.x <- n_z.x; r2.y <- n_z.y; r2.z <- n_z.z; r2.w <- n_z.w

#line 222
add r1.zw, -r2.xxxy, r2.zzzw
mad r1.yz, r1.yyyy, r1.zzwz, r2.xxyx  // r1.y <- n_yz.x; r1.z <- n_yz.y

#line 223
add r0.w, -r1.y, r1.z
mad r0.w, r1.x, r0.w, r1.y  // r0.w <- n_xyz

#line 224
mul r0.w, r0.w, l(2.200000)  // r0.w <- <cnoise_id73 return value>

#line 239
mul r1.xyz, r0.xyzx, l(8.000000, 8.000000, 0.800000, 0.000000)

#line 167
round_ni r2.xyz, r1.xyzx  // r2.x <- Pi0.x; r2.y <- Pi0.y; r2.z <- Pi0.z

#line 171
frc r1.xyz, r1.xyzx  // r1.x <- Pf0.x; r1.y <- Pf0.y; r1.z <- Pf0.z

#line 168
add r3.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r3.x <- Pi1.x; r3.y <- Pi1.y; r3.z <- Pi1.z

#line 163
mul r4.xyz, r3.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r4.xyz, r4.xyzx
mad r3.xyz, -r4.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r3.xyzx  // r3.x <- <mod289_id68 return value>.x; r3.y <- <mod289_id68 return value>.y; r3.z <- <mod289_id68 return value>.z

#line 159
mov r4.w, r3.x

#line 163
mul r5.xyz, r2.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r5.xyz, r5.xyzx
mad r4.xyz, -r5.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r2.xyzx  // r4.x <- <mod289_id68 return value>.x; r4.y <- <mod289_id68 return value>.y; r4.z <- <mod289_id68 return value>.z

#line 159
mad r2.xyzw, r4.xwxw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r4.xwxw, r2.xyzw

#line 147
mul r5.xyzw, r2.zwzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.z <- <mod289_id69 return value>.x; r2.w <- <mod289_id69 return value>.y

#line 177
mov r3.w, r4.y
add r2.xyzw, r3.wwyy, r2.xyzw

#line 159
mad r5.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r5.xyzw

#line 147
mul r5.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 178
add r4.xyzw, r4.zzzz, r2.xyzw

#line 179
add r2.xyzw, r3.zzzz, r2.xyzw

#line 159
mad r3.xyzw, r4.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r4.xyzw, r3.xyzw

#line 147
mul r4.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r4.xyzw, r4.xyzw
mad r3.xyzw, -r4.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id69 return value>.x; r3.y <- <mod289_id69 return value>.y; r3.z <- <mod289_id69 return value>.z; r3.w <- <mod289_id69 return value>.w

#line 180
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r3.x <- gx0.x; r3.y <- gx0.y; r3.z <- gx0.z; r3.w <- gx0.w

#line 182
frc r4.xyzw, r3.xyzw  // r4.x <- gx0.x; r4.y <- gx0.y; r4.z <- gx0.z; r4.w <- gx0.w

#line 181
round_ni r3.xyzw, r3.xyzw
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r3.xyzw, r3.xyzw
add r3.xyzw, r3.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r3.x <- gy0.x; r3.y <- gy0.y; r3.z <- gy0.z; r3.w <- gy0.w

#line 185
ge r5.xyzw, r4.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r5.xyzw, r5.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 183
add r6.xyzw, -r4.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r6.xyzw, -|r3.xywz|, r6.xywz  // r6.x <- gz0.x; r6.y <- gz0.y; r6.z <- gz0.w; r6.w <- gz0.z

#line 184
ge r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r6.xywz
and r7.xyzw, r7.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r7.x <- sz0.x; r7.y <- sz0.y; r7.z <- sz0.z; r7.w <- sz0.w

#line 185
mad r4.xyzw, -r7.xyzw, r5.xyzw, r4.xyzw

#line 202
mov r5.x, r4.x

#line 186
ge r8.xyzw, r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r8.xyzw, r8.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r3.xyzw, -r7.xyzw, r8.xyzw, r3.xyzw

#line 202
mov r5.y, r3.x
mov r5.z, r6.x
dp3 r7.x, r5.xyzx, r5.xyzx
mov r8.z, r6.w
mov r8.x, r4.z
mov r8.y, r3.z
dp3 r7.y, r8.xyzx, r8.xyzx
mov r3.z, r6.y
mov r3.x, r4.y
mov r6.x, r4.w
mov r6.y, r3.w
dp3 r7.z, r3.xyzx, r3.xyzx
dp3 r7.w, r6.xyzx, r6.xyzx

#line 155
mul r4.xyzw, r7.xyzw, cb0[2].xxxx
mad r4.xyzw, -r4.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r4.x <- <taylorInvSqrt_id71 return value>.x; r4.y <- <taylorInvSqrt_id71 return value>.y; r4.z <- <taylorInvSqrt_id71 return value>.z; r4.w <- <taylorInvSqrt_id71 return value>.w

#line 205
mul r3.xyz, r3.xyzx, r4.zzzz  // r3.x <- g100.x; r3.y <- g100.y; r3.z <- g100.z

#line 213
add r1.w, r1.x, l(-1.000000)
dp3 r3.y, r3.yzxy, r1.yzwy  // r3.y <- n100

#line 159
mad r7.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r7.xyzw

#line 147
mul r7.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r7.xyzw, r7.xyzw
mad r2.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 187
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r2.x <- gx1.x; r2.y <- gx1.y; r2.z <- gx1.z; r2.w <- gx1.w

#line 189
frc r7.xyzw, r2.xyzw  // r7.x <- gx1.x; r7.y <- gx1.y; r7.z <- gx1.z; r7.w <- gx1.w

#line 188
round_ni r2.xyzw, r2.xyzw
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r2.xyzw, r2.xyzw
add r2.xyzw, r2.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r2.x <- gy1.x; r2.y <- gy1.y; r2.z <- gy1.z; r2.w <- gy1.w

#line 192
ge r9.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r9.xyzw, r9.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 190
add r10.xyzw, -r7.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r10.xyzw, -|r2.xywz|, r10.xywz  // r10.x <- gz1.x; r10.y <- gz1.y; r10.z <- gz1.w; r10.w <- gz1.z

#line 191
ge r11.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r10.xywz
and r11.xyzw, r11.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r11.x <- sz1.x; r11.y <- sz1.y; r11.z <- sz1.z; r11.w <- sz1.w

#line 192
mad r7.xyzw, -r11.xyzw, r9.xyzw, r7.xyzw

#line 207
mov r9.x, r7.x

#line 193
ge r12.xyzw, r2.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r12.xyzw, r12.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r2.xyzw, -r11.xyzw, r12.xyzw, r2.xyzw

#line 207
mov r9.y, r2.x
mov r9.z, r10.x
dp3 r11.x, r9.xyzx, r9.xyzx
mov r12.z, r10.w
mov r12.x, r7.z
mov r12.y, r2.z
dp3 r11.y, r12.xyzx, r12.xyzx
mov r2.z, r10.y
mov r2.x, r7.y
mov r10.x, r7.w
mov r10.y, r2.w
dp3 r11.z, r2.xyzx, r2.xyzx
dp3 r11.w, r10.xyzx, r10.xyzx

#line 155
mul r7.xyzw, r11.xyzw, cb0[2].xxxx
mad r7.xyzw, -r7.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r7.x <- <taylorInvSqrt_id71 return value>.x; r7.y <- <taylorInvSqrt_id71 return value>.y; r7.z <- <taylorInvSqrt_id71 return value>.z; r7.w <- <taylorInvSqrt_id71 return value>.w

#line 208
mul r9.xyz, r7.xxxx, r9.xyzx  // r9.x <- g001.x; r9.y <- g001.y; r9.z <- g001.z

#line 216
add r11.xyz, r1.xyzx, l(0.000000, 0.000000, -1.000000, 0.000000)
dp3 r9.x, r9.xyzx, r11.xyzx  // r9.x <- n001

#line 210
mul r2.xyz, r2.xyzx, r7.zzzz  // r2.x <- g101.x; r2.y <- g101.y; r2.z <- g101.z

#line 217
add r11.xyz, r1.xyzx, l(-1.000000, 0.000000, -1.000000, 0.000000)
dp3 r9.y, r2.xyzx, r11.xyzx  // r9.y <- n101

#line 209
mul r2.xyz, r7.yyyy, r12.xyzx  // r2.x <- g011.x; r2.y <- g011.y; r2.z <- g011.z

#line 211
mul r7.xyz, r7.wwww, r10.xyzx  // r7.x <- g111.x; r7.y <- g111.y; r7.z <- g111.z

#line 218
add r10.xyz, r1.xyzx, l(0.000000, -1.000000, -1.000000, 0.000000)
dp3 r9.z, r2.xyzx, r10.xyzx  // r9.z <- n011

#line 172
add r2.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- Pf1.x; r2.y <- Pf1.y; r2.z <- Pf1.z

#line 219
dp3 r9.w, r7.xyzx, r2.xyzx  // r9.w <- n111

#line 204
mul r2.xyz, r4.yyyy, r8.xyzx  // r2.x <- g010.x; r2.y <- g010.y; r2.z <- g010.z

#line 214
add r7.xyz, r1.xyzx, l(0.000000, -1.000000, 0.000000, 0.000000)
dp3 r3.z, r2.xyzx, r7.xyzx  // r3.z <- n010

#line 206
mul r2.xyz, r4.wwww, r6.xyzx  // r2.x <- g110.x; r2.y <- g110.y; r2.z <- g110.z

#line 203
mul r4.xyz, r4.xxxx, r5.xyzx  // r4.x <- g000.x; r4.y <- g000.y; r4.z <- g000.z

#line 212
dp3 r3.x, r4.xyzx, r1.xyzx  // r3.x <- n000

#line 215
add r4.xyz, r1.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
dp3 r3.w, r2.xyzx, r4.xyzx  // r3.w <- n110

#line 221
add r2.xyzw, -r3.xyzw, r9.xyzw

#line 151
mul r4.xyz, r1.xyzx, r1.xyzx
mul r4.xyz, r1.xyzx, r4.xyzx
mad r5.xyz, r1.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-15.000000, -15.000000, -15.000000, 0.000000)
mad r1.xyz, r1.xyzx, r5.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
mul r1.xyz, r1.xyzx, r4.xyzx  // r1.x <- <fade_id72 return value>.x; r1.y <- <fade_id72 return value>.y; r1.z <- <fade_id72 return value>.z

#line 221
mad r2.xyzw, r1.zzzz, r2.xyzw, r3.xyzw  // r2.x <- n_z.x; r2.y <- n_z.y; r2.z <- n_z.z; r2.w <- n_z.w

#line 222
add r1.zw, -r2.xxxy, r2.zzzw
mad r1.yz, r1.yyyy, r1.zzwz, r2.xxyx  // r1.y <- n_yz.x; r1.z <- n_yz.y

#line 223
add r1.z, -r1.y, r1.z
mad r1.x, r1.x, r1.z, r1.y  // r1.x <- n_xyz

#line 224
mul r1.x, r1.x, l(2.200000)  // r1.x <- <cnoise_id73 return value>

#line 239
mad r0.w, |r1.x|, l(0.500000), |r0.w|  // r0.w <- n

#line 240
mul r1.xyz, r0.xyzx, l(16.000000, 16.000000, 1.600000, 0.000000)

#line 167
round_ni r2.xyz, r1.xyzx  // r2.x <- Pi0.x; r2.y <- Pi0.y; r2.z <- Pi0.z

#line 171
frc r1.xyz, r1.xyzx  // r1.x <- Pf0.x; r1.y <- Pf0.y; r1.z <- Pf0.z

#line 168
add r3.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r3.x <- Pi1.x; r3.y <- Pi1.y; r3.z <- Pi1.z

#line 163
mul r4.xyz, r3.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r4.xyz, r4.xyzx
mad r3.xyz, -r4.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r3.xyzx  // r3.x <- <mod289_id68 return value>.x; r3.y <- <mod289_id68 return value>.y; r3.z <- <mod289_id68 return value>.z

#line 159
mov r4.w, r3.x

#line 163
mul r5.xyz, r2.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r5.xyz, r5.xyzx
mad r4.xyz, -r5.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r2.xyzx  // r4.x <- <mod289_id68 return value>.x; r4.y <- <mod289_id68 return value>.y; r4.z <- <mod289_id68 return value>.z

#line 159
mad r2.xyzw, r4.xwxw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r4.xwxw, r2.xyzw

#line 147
mul r5.xyzw, r2.zwzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.z <- <mod289_id69 return value>.x; r2.w <- <mod289_id69 return value>.y

#line 177
mov r3.w, r4.y
add r2.xyzw, r3.wwyy, r2.xyzw

#line 159
mad r5.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r5.xyzw

#line 147
mul r5.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 178
add r4.xyzw, r4.zzzz, r2.xyzw

#line 179
add r2.xyzw, r3.zzzz, r2.xyzw

#line 159
mad r3.xyzw, r4.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r4.xyzw, r3.xyzw

#line 147
mul r4.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r4.xyzw, r4.xyzw
mad r3.xyzw, -r4.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id69 return value>.x; r3.y <- <mod289_id69 return value>.y; r3.z <- <mod289_id69 return value>.z; r3.w <- <mod289_id69 return value>.w

#line 180
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r3.x <- gx0.x; r3.y <- gx0.y; r3.z <- gx0.z; r3.w <- gx0.w

#line 182
frc r4.xyzw, r3.xyzw  // r4.x <- gx0.x; r4.y <- gx0.y; r4.z <- gx0.z; r4.w <- gx0.w

#line 181
round_ni r3.xyzw, r3.xyzw
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r3.xyzw, r3.xyzw
add r3.xyzw, r3.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r3.x <- gy0.x; r3.y <- gy0.y; r3.z <- gy0.z; r3.w <- gy0.w

#line 185
ge r5.xyzw, r4.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r5.xyzw, r5.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 183
add r6.xyzw, -r4.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r6.xyzw, -|r3.xywz|, r6.xywz  // r6.x <- gz0.x; r6.y <- gz0.y; r6.z <- gz0.w; r6.w <- gz0.z

#line 184
ge r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r6.xywz
and r7.xyzw, r7.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r7.x <- sz0.x; r7.y <- sz0.y; r7.z <- sz0.z; r7.w <- sz0.w

#line 185
mad r4.xyzw, -r7.xyzw, r5.xyzw, r4.xyzw

#line 202
mov r5.x, r4.x

#line 186
ge r8.xyzw, r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r8.xyzw, r8.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r3.xyzw, -r7.xyzw, r8.xyzw, r3.xyzw

#line 202
mov r5.y, r3.x
mov r5.z, r6.x
dp3 r7.x, r5.xyzx, r5.xyzx
mov r8.z, r6.w
mov r8.x, r4.z
mov r8.y, r3.z
dp3 r7.y, r8.xyzx, r8.xyzx
mov r3.z, r6.y
mov r3.x, r4.y
mov r6.x, r4.w
mov r6.y, r3.w
dp3 r7.z, r3.xyzx, r3.xyzx
dp3 r7.w, r6.xyzx, r6.xyzx

#line 155
mul r4.xyzw, r7.xyzw, cb0[2].xxxx
mad r4.xyzw, -r4.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r4.x <- <taylorInvSqrt_id71 return value>.x; r4.y <- <taylorInvSqrt_id71 return value>.y; r4.z <- <taylorInvSqrt_id71 return value>.z; r4.w <- <taylorInvSqrt_id71 return value>.w

#line 205
mul r3.xyz, r3.xyzx, r4.zzzz  // r3.x <- g100.x; r3.y <- g100.y; r3.z <- g100.z

#line 213
add r1.w, r1.x, l(-1.000000)
dp3 r3.y, r3.yzxy, r1.yzwy  // r3.y <- n100

#line 159
mad r7.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r7.xyzw

#line 147
mul r7.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r7.xyzw, r7.xyzw
mad r2.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 187
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r2.x <- gx1.x; r2.y <- gx1.y; r2.z <- gx1.z; r2.w <- gx1.w

#line 188
round_ni r7.xyzw, r2.xyzw

#line 189
frc r2.xyzw, r2.xyzw

#line 188
mul r7.xyzw, r7.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r7.xyzw, r7.xyzw
add r7.xyzw, r7.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r7.x <- gy1.x; r7.y <- gy1.y; r7.z <- gy1.z; r7.w <- gy1.w

#line 190
add r9.xyzw, -r2.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r9.xyzw, -|r7.xywz|, r9.xywz  // r9.x <- gz1.x; r9.y <- gz1.y; r9.z <- gz1.w; r9.w <- gz1.z

#line 207
mov r10.z, r9.x

#line 192
ge r11.xyzw, r2.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r11.xyzw, r11.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 191
ge r12.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xywz
and r12.xyzw, r12.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r12.x <- sz1.x; r12.y <- sz1.y; r12.z <- sz1.z; r12.w <- sz1.w

#line 192
mad r2.xyzw, -r12.xyzw, r11.xyzw, r2.xyzw

#line 207
mov r10.x, r2.x

#line 193
ge r11.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r11.xyzw, r11.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r7.xyzw, -r12.xyzw, r11.xyzw, r7.xyzw

#line 207
mov r10.y, r7.x
dp3 r11.x, r10.xyzx, r10.xyzx
mov r12.z, r9.w
mov r12.x, r2.z
mov r12.y, r7.z
dp3 r11.y, r12.xyzx, r12.xyzx
mov r7.z, r9.y
mov r7.x, r2.y
mov r9.x, r2.w
mov r9.y, r7.w
dp3 r11.z, r7.xyzx, r7.xyzx
dp3 r11.w, r9.xyzx, r9.xyzx

#line 155
mul r2.xyzw, r11.xyzw, cb0[2].xxxx
mad r2.xyzw, -r2.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r2.x <- <taylorInvSqrt_id71 return value>.x; r2.y <- <taylorInvSqrt_id71 return value>.y; r2.z <- <taylorInvSqrt_id71 return value>.z; r2.w <- <taylorInvSqrt_id71 return value>.w

#line 208
mul r10.xyz, r2.xxxx, r10.xyzx  // r10.x <- g001.x; r10.y <- g001.y; r10.z <- g001.z

#line 216
add r11.xyz, r1.xyzx, l(0.000000, 0.000000, -1.000000, 0.000000)
dp3 r10.x, r10.xyzx, r11.xyzx  // r10.x <- n001

#line 210
mul r7.xyz, r2.zzzz, r7.xyzx  // r7.x <- g101.x; r7.y <- g101.y; r7.z <- g101.z

#line 217
add r11.xyz, r1.xyzx, l(-1.000000, 0.000000, -1.000000, 0.000000)
dp3 r10.y, r7.xyzx, r11.xyzx  // r10.y <- n101

#line 209
mul r2.xyz, r2.yyyy, r12.xyzx  // r2.x <- g011.x; r2.y <- g011.y; r2.z <- g011.z

#line 211
mul r7.xyz, r2.wwww, r9.xyzx  // r7.x <- g111.x; r7.y <- g111.y; r7.z <- g111.z

#line 218
add r9.xyz, r1.xyzx, l(0.000000, -1.000000, -1.000000, 0.000000)
dp3 r10.z, r2.xyzx, r9.xyzx  // r10.z <- n011

#line 172
add r2.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- Pf1.x; r2.y <- Pf1.y; r2.z <- Pf1.z

#line 219
dp3 r10.w, r7.xyzx, r2.xyzx  // r10.w <- n111

#line 204
mul r2.xyz, r4.yyyy, r8.xyzx  // r2.x <- g010.x; r2.y <- g010.y; r2.z <- g010.z

#line 214
add r7.xyz, r1.xyzx, l(0.000000, -1.000000, 0.000000, 0.000000)
dp3 r3.z, r2.xyzx, r7.xyzx  // r3.z <- n010

#line 206
mul r2.xyz, r4.wwww, r6.xyzx  // r2.x <- g110.x; r2.y <- g110.y; r2.z <- g110.z

#line 203
mul r4.xyz, r4.xxxx, r5.xyzx  // r4.x <- g000.x; r4.y <- g000.y; r4.z <- g000.z

#line 212
dp3 r3.x, r4.xyzx, r1.xyzx  // r3.x <- n000

#line 215
add r4.xyz, r1.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
dp3 r3.w, r2.xyzx, r4.xyzx  // r3.w <- n110

#line 221
add r2.xyzw, -r3.xyzw, r10.xyzw

#line 151
mul r4.xyz, r1.xyzx, r1.xyzx
mul r4.xyz, r1.xyzx, r4.xyzx
mad r5.xyz, r1.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-15.000000, -15.000000, -15.000000, 0.000000)
mad r1.xyz, r1.xyzx, r5.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
mul r1.xyz, r1.xyzx, r4.xyzx  // r1.x <- <fade_id72 return value>.x; r1.y <- <fade_id72 return value>.y; r1.z <- <fade_id72 return value>.z

#line 221
mad r2.xyzw, r1.zzzz, r2.xyzw, r3.xyzw  // r2.x <- n_z.x; r2.y <- n_z.y; r2.z <- n_z.z; r2.w <- n_z.w

#line 222
add r1.zw, -r2.xxxy, r2.zzzw
mad r1.yz, r1.yyyy, r1.zzwz, r2.xxyx  // r1.y <- n_yz.x; r1.z <- n_yz.y

#line 223
add r1.z, -r1.y, r1.z
mad r1.x, r1.x, r1.z, r1.y  // r1.x <- n_xyz

#line 224
mul r1.x, r1.x, l(2.200000)  // r1.x <- <cnoise_id73 return value>

#line 240
mad r0.w, |r1.x|, l(0.250000), r0.w

#line 241
mul r1.xyz, r0.xyzx, l(32.000000, 32.000000, 3.200000, 0.000000)

#line 167
round_ni r2.xyz, r1.xyzx  // r2.x <- Pi0.x; r2.y <- Pi0.y; r2.z <- Pi0.z

#line 171
frc r1.xyz, r1.xyzx  // r1.x <- Pf0.x; r1.y <- Pf0.y; r1.z <- Pf0.z

#line 168
add r3.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r3.x <- Pi1.x; r3.y <- Pi1.y; r3.z <- Pi1.z

#line 163
mul r4.xyz, r3.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r4.xyz, r4.xyzx
mad r3.xyz, -r4.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r3.xyzx  // r3.x <- <mod289_id68 return value>.x; r3.y <- <mod289_id68 return value>.y; r3.z <- <mod289_id68 return value>.z

#line 159
mov r4.w, r3.x

#line 163
mul r5.xyz, r2.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r5.xyz, r5.xyzx
mad r4.xyz, -r5.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r2.xyzx  // r4.x <- <mod289_id68 return value>.x; r4.y <- <mod289_id68 return value>.y; r4.z <- <mod289_id68 return value>.z

#line 159
mad r2.xyzw, r4.xwxw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r4.xwxw, r2.xyzw

#line 147
mul r5.xyzw, r2.zwzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.z <- <mod289_id69 return value>.x; r2.w <- <mod289_id69 return value>.y

#line 177
mov r3.w, r4.y
add r2.xyzw, r3.wwyy, r2.xyzw

#line 159
mad r5.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r5.xyzw

#line 147
mul r5.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 178
add r4.xyzw, r4.zzzz, r2.xyzw

#line 179
add r2.xyzw, r3.zzzz, r2.xyzw

#line 159
mad r3.xyzw, r4.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r4.xyzw, r3.xyzw

#line 147
mul r4.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r4.xyzw, r4.xyzw
mad r3.xyzw, -r4.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id69 return value>.x; r3.y <- <mod289_id69 return value>.y; r3.z <- <mod289_id69 return value>.z; r3.w <- <mod289_id69 return value>.w

#line 180
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r3.x <- gx0.x; r3.y <- gx0.y; r3.z <- gx0.z; r3.w <- gx0.w

#line 181
round_ni r4.xyzw, r3.xyzw

#line 182
frc r3.xyzw, r3.xyzw

#line 181
mul r4.xyzw, r4.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r4.xyzw, r4.xyzw
add r4.xyzw, r4.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r4.x <- gy0.x; r4.y <- gy0.y; r4.z <- gy0.z; r4.w <- gy0.w

#line 183
add r5.xyzw, -r3.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r5.xyzw, -|r4.xywz|, r5.xywz  // r5.x <- gz0.x; r5.y <- gz0.y; r5.z <- gz0.w; r5.w <- gz0.z

#line 202
mov r6.z, r5.x

#line 185
ge r7.xyzw, r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r7.xyzw, r7.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 184
ge r8.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r5.xywz
and r8.xyzw, r8.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r8.x <- sz0.x; r8.y <- sz0.y; r8.z <- sz0.z; r8.w <- sz0.w

#line 185
mad r3.xyzw, -r8.xyzw, r7.xyzw, r3.xyzw

#line 202
mov r6.x, r3.x

#line 186
ge r7.xyzw, r4.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r7.xyzw, r7.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r4.xyzw, -r8.xyzw, r7.xyzw, r4.xyzw

#line 202
mov r6.y, r4.x
dp3 r7.x, r6.xyzx, r6.xyzx
mov r8.z, r5.w
mov r8.x, r3.z
mov r8.y, r4.z
dp3 r7.y, r8.xyzx, r8.xyzx
mov r4.z, r5.y
mov r4.x, r3.y
mov r5.x, r3.w
mov r5.y, r4.w
dp3 r7.z, r4.xyzx, r4.xyzx
dp3 r7.w, r5.xyzx, r5.xyzx

#line 155
mul r3.xyzw, r7.xyzw, cb0[2].xxxx
mad r3.xyzw, -r3.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r3.x <- <taylorInvSqrt_id71 return value>.x; r3.y <- <taylorInvSqrt_id71 return value>.y; r3.z <- <taylorInvSqrt_id71 return value>.z; r3.w <- <taylorInvSqrt_id71 return value>.w

#line 205
mul r4.xyz, r3.zzzz, r4.xyzx  // r4.x <- g100.x; r4.y <- g100.y; r4.z <- g100.z

#line 213
add r1.w, r1.x, l(-1.000000)
dp3 r4.y, r4.yzxy, r1.yzwy  // r4.y <- n100

#line 159
mad r7.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r7.xyzw

#line 147
mul r7.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r7.xyzw, r7.xyzw
mad r2.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 187
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r2.x <- gx1.x; r2.y <- gx1.y; r2.z <- gx1.z; r2.w <- gx1.w

#line 188
round_ni r7.xyzw, r2.xyzw

#line 189
frc r2.xyzw, r2.xyzw

#line 188
mul r7.xyzw, r7.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r7.xyzw, r7.xyzw
add r7.xyzw, r7.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r7.x <- gy1.x; r7.y <- gy1.y; r7.z <- gy1.z; r7.w <- gy1.w

#line 190
add r9.xyzw, -r2.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r9.xyzw, -|r7.xywz|, r9.xywz  // r9.x <- gz1.x; r9.y <- gz1.y; r9.z <- gz1.w; r9.w <- gz1.z

#line 207
mov r10.z, r9.x

#line 192
ge r11.xyzw, r2.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r11.xyzw, r11.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 191
ge r12.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xywz
and r12.xyzw, r12.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r12.x <- sz1.x; r12.y <- sz1.y; r12.z <- sz1.z; r12.w <- sz1.w

#line 192
mad r2.xyzw, -r12.xyzw, r11.xyzw, r2.xyzw

#line 207
mov r10.x, r2.x

#line 193
ge r11.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r11.xyzw, r11.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r7.xyzw, -r12.xyzw, r11.xyzw, r7.xyzw

#line 207
mov r10.y, r7.x
dp3 r11.x, r10.xyzx, r10.xyzx
mov r12.z, r9.w
mov r12.x, r2.z
mov r12.y, r7.z
dp3 r11.y, r12.xyzx, r12.xyzx
mov r7.z, r9.y
mov r7.x, r2.y
mov r9.x, r2.w
mov r9.y, r7.w
dp3 r11.z, r7.xyzx, r7.xyzx
dp3 r11.w, r9.xyzx, r9.xyzx

#line 155
mul r2.xyzw, r11.xyzw, cb0[2].xxxx
mad r2.xyzw, -r2.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r2.x <- <taylorInvSqrt_id71 return value>.x; r2.y <- <taylorInvSqrt_id71 return value>.y; r2.z <- <taylorInvSqrt_id71 return value>.z; r2.w <- <taylorInvSqrt_id71 return value>.w

#line 208
mul r10.xyz, r2.xxxx, r10.xyzx  // r10.x <- g001.x; r10.y <- g001.y; r10.z <- g001.z

#line 216
add r11.xyz, r1.xyzx, l(0.000000, 0.000000, -1.000000, 0.000000)
dp3 r10.x, r10.xyzx, r11.xyzx  // r10.x <- n001

#line 210
mul r7.xyz, r2.zzzz, r7.xyzx  // r7.x <- g101.x; r7.y <- g101.y; r7.z <- g101.z

#line 217
add r11.xyz, r1.xyzx, l(-1.000000, 0.000000, -1.000000, 0.000000)
dp3 r10.y, r7.xyzx, r11.xyzx  // r10.y <- n101

#line 209
mul r2.xyz, r2.yyyy, r12.xyzx  // r2.x <- g011.x; r2.y <- g011.y; r2.z <- g011.z

#line 211
mul r7.xyz, r2.wwww, r9.xyzx  // r7.x <- g111.x; r7.y <- g111.y; r7.z <- g111.z

#line 218
add r9.xyz, r1.xyzx, l(0.000000, -1.000000, -1.000000, 0.000000)
dp3 r10.z, r2.xyzx, r9.xyzx  // r10.z <- n011

#line 172
add r2.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- Pf1.x; r2.y <- Pf1.y; r2.z <- Pf1.z

#line 219
dp3 r10.w, r7.xyzx, r2.xyzx

#line 204
mul r2.xyz, r3.yyyy, r8.xyzx  // r2.x <- g010.x; r2.y <- g010.y; r2.z <- g010.z

#line 214
add r7.xyz, r1.xyzx, l(0.000000, -1.000000, 0.000000, 0.000000)
dp3 r4.z, r2.xyzx, r7.xyzx  // r4.z <- n010

#line 206
mul r2.xyz, r3.wwww, r5.xyzx  // r2.x <- g110.x; r2.y <- g110.y; r2.z <- g110.z

#line 203
mul r3.xyz, r3.xxxx, r6.xyzx  // r3.x <- g000.x; r3.y <- g000.y; r3.z <- g000.z

#line 212
dp3 r4.x, r3.xyzx, r1.xyzx  // r4.x <- n000

#line 215
add r3.xyz, r1.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
dp3 r4.w, r2.xyzx, r3.xyzx  // r4.w <- n110

#line 221
add r2.xyzw, -r4.xyzw, r10.xyzw

#line 151
mul r3.xyz, r1.xyzx, r1.xyzx
mul r3.xyz, r1.xyzx, r3.xyzx
mad r5.xyz, r1.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-15.000000, -15.000000, -15.000000, 0.000000)
mad r1.xyz, r1.xyzx, r5.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
mul r1.xyz, r1.xyzx, r3.xyzx  // r1.x <- <fade_id72 return value>.x; r1.y <- <fade_id72 return value>.y; r1.z <- <fade_id72 return value>.z

#line 221
mad r2.xyzw, r1.zzzz, r2.xyzw, r4.xyzw  // r2.x <- n_z.x; r2.y <- n_z.y; r2.z <- n_z.z; r2.w <- n_z.w

#line 222
add r1.zw, -r2.xxxy, r2.zzzw
mad r1.yz, r1.yyyy, r1.zzwz, r2.xxyx  // r1.y <- n_yz.x; r1.z <- n_yz.y

#line 223
add r1.z, -r1.y, r1.z
mad r1.x, r1.x, r1.z, r1.y  // r1.x <- n_xyz

#line 224
mul r1.x, r1.x, l(2.200000)  // r1.x <- <cnoise_id73 return value>

#line 241
mad r0.w, |r1.x|, l(0.125000), r0.w

#line 242
mul r1.xyz, r0.xyzx, l(64.000000, 64.000000, 6.400000, 0.000000)

#line 243
mul r0.xyz, r0.xyzx, l(128.000000, 128.000000, 12.800000, 0.000000)

#line 167
round_ni r2.xyz, r1.xyzx  // r2.x <- Pi0.x; r2.y <- Pi0.y; r2.z <- Pi0.z

#line 171
frc r1.xyz, r1.xyzx  // r1.x <- Pf0.x; r1.y <- Pf0.y; r1.z <- Pf0.z

#line 168
add r3.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r3.x <- Pi1.x; r3.y <- Pi1.y; r3.z <- Pi1.z

#line 163
mul r4.xyz, r3.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r4.xyz, r4.xyzx
mad r3.xyz, -r4.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r3.xyzx  // r3.x <- <mod289_id68 return value>.x; r3.y <- <mod289_id68 return value>.y; r3.z <- <mod289_id68 return value>.z

#line 159
mov r4.w, r3.x

#line 163
mul r5.xyz, r2.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r5.xyz, r5.xyzx
mad r4.xyz, -r5.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r2.xyzx  // r4.x <- <mod289_id68 return value>.x; r4.y <- <mod289_id68 return value>.y; r4.z <- <mod289_id68 return value>.z

#line 159
mad r2.xyzw, r4.xwxw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r4.xwxw, r2.xyzw

#line 147
mul r5.xyzw, r2.zwzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.z <- <mod289_id69 return value>.x; r2.w <- <mod289_id69 return value>.y

#line 177
mov r3.w, r4.y
add r2.xyzw, r3.wwyy, r2.xyzw

#line 159
mad r5.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r5.xyzw

#line 147
mul r5.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r2.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 178
add r4.xyzw, r4.zzzz, r2.xyzw

#line 179
add r2.xyzw, r3.zzzz, r2.xyzw

#line 159
mad r3.xyzw, r4.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r4.xyzw, r3.xyzw

#line 147
mul r4.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r4.xyzw, r4.xyzw
mad r3.xyzw, -r4.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id69 return value>.x; r3.y <- <mod289_id69 return value>.y; r3.z <- <mod289_id69 return value>.z; r3.w <- <mod289_id69 return value>.w

#line 180
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r3.x <- gx0.x; r3.y <- gx0.y; r3.z <- gx0.z; r3.w <- gx0.w

#line 181
round_ni r4.xyzw, r3.xyzw

#line 182
frc r3.xyzw, r3.xyzw

#line 181
mul r4.xyzw, r4.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r4.xyzw, r4.xyzw
add r4.xyzw, r4.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r4.x <- gy0.x; r4.y <- gy0.y; r4.z <- gy0.z; r4.w <- gy0.w

#line 183
add r5.xyzw, -r3.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r5.xyzw, -|r4.xywz|, r5.xywz  // r5.x <- gz0.x; r5.y <- gz0.y; r5.z <- gz0.w; r5.w <- gz0.z

#line 202
mov r6.z, r5.x

#line 185
ge r7.xyzw, r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r7.xyzw, r7.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 184
ge r8.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r5.xywz
and r8.xyzw, r8.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r8.x <- sz0.x; r8.y <- sz0.y; r8.z <- sz0.z; r8.w <- sz0.w

#line 185
mad r3.xyzw, -r8.xyzw, r7.xyzw, r3.xyzw

#line 202
mov r6.x, r3.x

#line 186
ge r7.xyzw, r4.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r7.xyzw, r7.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r4.xyzw, -r8.xyzw, r7.xyzw, r4.xyzw

#line 202
mov r6.y, r4.x
dp3 r7.x, r6.xyzx, r6.xyzx
mov r8.z, r5.w
mov r8.x, r3.z
mov r8.y, r4.z
dp3 r7.y, r8.xyzx, r8.xyzx
mov r4.z, r5.y
mov r4.x, r3.y
mov r5.x, r3.w
mov r5.y, r4.w
dp3 r7.z, r4.xyzx, r4.xyzx
dp3 r7.w, r5.xyzx, r5.xyzx

#line 155
mul r3.xyzw, r7.xyzw, cb0[2].xxxx
mad r3.xyzw, -r3.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r3.x <- <taylorInvSqrt_id71 return value>.x; r3.y <- <taylorInvSqrt_id71 return value>.y; r3.z <- <taylorInvSqrt_id71 return value>.z; r3.w <- <taylorInvSqrt_id71 return value>.w

#line 205
mul r4.xyz, r3.zzzz, r4.xyzx  // r4.x <- g100.x; r4.y <- g100.y; r4.z <- g100.z

#line 213
add r1.w, r1.x, l(-1.000000)
dp3 r4.y, r4.yzxy, r1.yzwy  // r4.y <- n100

#line 159
mad r7.xyzw, r2.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r7.xyzw

#line 147
mul r7.xyzw, r2.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r7.xyzw, r7.xyzw
mad r2.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r2.xyzw  // r2.x <- <mod289_id69 return value>.x; r2.y <- <mod289_id69 return value>.y; r2.z <- <mod289_id69 return value>.z; r2.w <- <mod289_id69 return value>.w

#line 187
mul r2.xyzw, r2.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r2.x <- gx1.x; r2.y <- gx1.y; r2.z <- gx1.z; r2.w <- gx1.w

#line 188
round_ni r7.xyzw, r2.xyzw

#line 189
frc r2.xyzw, r2.xyzw

#line 188
mul r7.xyzw, r7.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r7.xyzw, r7.xyzw
add r7.xyzw, r7.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r7.x <- gy1.x; r7.y <- gy1.y; r7.z <- gy1.z; r7.w <- gy1.w

#line 190
add r9.xyzw, -r2.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r9.xyzw, -|r7.xywz|, r9.xywz  // r9.x <- gz1.x; r9.y <- gz1.y; r9.z <- gz1.w; r9.w <- gz1.z

#line 207
mov r10.z, r9.x

#line 192
ge r11.xyzw, r2.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r11.xyzw, r11.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 191
ge r12.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xywz
and r12.xyzw, r12.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r12.x <- sz1.x; r12.y <- sz1.y; r12.z <- sz1.z; r12.w <- sz1.w

#line 192
mad r2.xyzw, -r12.xyzw, r11.xyzw, r2.xyzw

#line 207
mov r11.x, r2.z

#line 193
ge r13.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r13.xyzw, r13.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r7.xyzw, -r12.xyzw, r13.xyzw, r7.xyzw

#line 207
mov r11.y, r7.z
mov r11.z, r9.w
dp3 r12.y, r11.xyzx, r11.xyzx
mov r13.z, r9.y
mov r13.x, r2.y
mov r13.y, r7.y
dp3 r12.z, r13.xyzx, r13.xyzx
mov r9.x, r2.w
mov r10.x, r2.x
mov r9.y, r7.w
mov r10.y, r7.x
dp3 r12.w, r9.xyzx, r9.xyzx
dp3 r12.x, r10.xyzx, r10.xyzx

#line 155
mul r2.xyzw, r12.xyzw, cb0[2].xxxx
mad r2.xyzw, -r2.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r2.x <- <taylorInvSqrt_id71 return value>.x; r2.y <- <taylorInvSqrt_id71 return value>.y; r2.z <- <taylorInvSqrt_id71 return value>.z; r2.w <- <taylorInvSqrt_id71 return value>.w

#line 208
mul r7.xyz, r2.xxxx, r10.xyzx  // r7.x <- g001.x; r7.y <- g001.y; r7.z <- g001.z

#line 216
add r10.xyz, r1.xyzx, l(0.000000, 0.000000, -1.000000, 0.000000)
dp3 r7.x, r7.xyzx, r10.xyzx  // r7.x <- n001

#line 210
mul r10.xyz, r2.zzzz, r13.xyzx  // r10.x <- g101.x; r10.y <- g101.y; r10.z <- g101.z

#line 217
add r12.xyz, r1.xyzx, l(-1.000000, 0.000000, -1.000000, 0.000000)
dp3 r7.y, r10.xyzx, r12.xyzx  // r7.y <- n101

#line 209
mul r2.xyz, r2.yyyy, r11.xyzx  // r2.x <- g011.x; r2.y <- g011.y; r2.z <- g011.z

#line 211
mul r9.xyz, r2.wwww, r9.xyzx  // r9.x <- g111.x; r9.y <- g111.y; r9.z <- g111.z

#line 218
add r10.xyz, r1.xyzx, l(0.000000, -1.000000, -1.000000, 0.000000)
dp3 r7.z, r2.xyzx, r10.xyzx  // r7.z <- n011

#line 172
add r2.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r2.x <- Pf1.x; r2.y <- Pf1.y; r2.z <- Pf1.z

#line 219
dp3 r7.w, r9.xyzx, r2.xyzx  // r7.w <- n111

#line 204
mul r2.xyz, r3.yyyy, r8.xyzx  // r2.x <- g010.x; r2.y <- g010.y; r2.z <- g010.z

#line 214
add r8.xyz, r1.xyzx, l(0.000000, -1.000000, 0.000000, 0.000000)
dp3 r4.z, r2.xyzx, r8.xyzx  // r4.z <- n010

#line 206
mul r2.xyz, r3.wwww, r5.xyzx  // r2.x <- g110.x; r2.y <- g110.y; r2.z <- g110.z

#line 203
mul r3.xyz, r3.xxxx, r6.xyzx  // r3.x <- g000.x; r3.y <- g000.y; r3.z <- g000.z

#line 212
dp3 r4.x, r3.xyzx, r1.xyzx  // r4.x <- n000

#line 215
add r3.xyz, r1.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
dp3 r4.w, r2.xyzx, r3.xyzx  // r4.w <- n110

#line 221
add r2.xyzw, -r4.xyzw, r7.xyzw

#line 151
mul r3.xyz, r1.xyzx, r1.xyzx
mul r3.xyz, r1.xyzx, r3.xyzx
mad r5.xyz, r1.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-15.000000, -15.000000, -15.000000, 0.000000)
mad r1.xyz, r1.xyzx, r5.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
mul r1.xyz, r1.xyzx, r3.xyzx  // r1.x <- <fade_id72 return value>.x; r1.y <- <fade_id72 return value>.y; r1.z <- <fade_id72 return value>.z

#line 221
mad r2.xyzw, r1.zzzz, r2.xyzw, r4.xyzw  // r2.x <- n_z.x; r2.y <- n_z.y; r2.z <- n_z.z; r2.w <- n_z.w

#line 222
add r1.zw, -r2.xxxy, r2.zzzw
mad r1.yz, r1.yyyy, r1.zzwz, r2.xxyx  // r1.y <- n_yz.x; r1.z <- n_yz.y

#line 223
add r1.z, -r1.y, r1.z
mad r1.x, r1.x, r1.z, r1.y  // r1.x <- n_xyz

#line 224
mul r1.x, r1.x, l(2.200000)  // r1.x <- <cnoise_id73 return value>

#line 242
mad r0.w, |r1.x|, l(0.062500), r0.w

#line 167
round_ni r1.xyz, r0.xyzx  // r1.x <- Pi0.x; r1.y <- Pi0.y; r1.z <- Pi0.z

#line 171
frc r2.xyz, r0.xyzx  // r2.x <- Pf0.x; r2.y <- Pf0.y; r2.z <- Pf0.z

#line 168
add r0.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // r0.x <- Pi1.x; r0.y <- Pi1.y; r0.z <- Pi1.z

#line 163
mul r3.xyz, r0.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r3.xyz, r3.xyzx
mad r3.xyz, -r3.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r0.xyzx  // r3.x <- <mod289_id68 return value>.x; r3.y <- <mod289_id68 return value>.y; r3.z <- <mod289_id68 return value>.z

#line 159
mov r4.w, r3.x

#line 163
mul r0.xyz, r1.xyzx, l(0.003460, 0.003460, 0.003460, 0.000000)
round_ni r0.xyz, r0.xyzx
mad r4.xyz, -r0.xyzx, l(289.000000, 289.000000, 289.000000, 0.000000), r1.xyzx  // r4.x <- <mod289_id68 return value>.x; r4.y <- <mod289_id68 return value>.y; r4.z <- <mod289_id68 return value>.z

#line 159
mad r1.xyzw, r4.xwxw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r1.xyzw, r4.xwxw, r1.xyzw

#line 147
mul r5.xyzw, r1.zwzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r1.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r1.xyzw  // r1.z <- <mod289_id69 return value>.x; r1.w <- <mod289_id69 return value>.y

#line 177
mov r3.w, r4.y
add r1.xyzw, r3.wwyy, r1.xyzw

#line 159
mad r5.xyzw, r1.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r1.xyzw, r1.xyzw, r5.xyzw

#line 147
mul r5.xyzw, r1.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r5.xyzw, r5.xyzw
mad r1.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r1.xyzw  // r1.x <- <mod289_id69 return value>.x; r1.y <- <mod289_id69 return value>.y; r1.z <- <mod289_id69 return value>.z; r1.w <- <mod289_id69 return value>.w

#line 178
add r4.xyzw, r4.zzzz, r1.xyzw

#line 179
add r1.xyzw, r3.zzzz, r1.xyzw

#line 159
mad r3.xyzw, r4.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r4.xyzw, r3.xyzw

#line 147
mul r4.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r4.xyzw, r4.xyzw
mad r3.xyzw, -r4.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id69 return value>.x; r3.y <- <mod289_id69 return value>.y; r3.z <- <mod289_id69 return value>.z; r3.w <- <mod289_id69 return value>.w

#line 180
mul r3.xyzw, r3.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r3.x <- gx0.x; r3.y <- gx0.y; r3.z <- gx0.z; r3.w <- gx0.w

#line 181
round_ni r4.xyzw, r3.xyzw

#line 182
frc r3.xyzw, r3.xyzw

#line 181
mul r4.xyzw, r4.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r4.xyzw, r4.xyzw
add r4.xyzw, r4.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r4.x <- gy0.x; r4.y <- gy0.y; r4.z <- gy0.z; r4.w <- gy0.w

#line 183
add r5.xyzw, -r3.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r5.xyzw, -|r4.xywz|, r5.xywz  // r5.x <- gz0.x; r5.y <- gz0.y; r5.z <- gz0.w; r5.w <- gz0.z

#line 202
mov r0.z, r5.x

#line 185
ge r6.xyzw, r3.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r6.xyzw, r6.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 184
ge r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r5.xywz
and r7.xyzw, r7.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r7.x <- sz0.x; r7.y <- sz0.y; r7.z <- sz0.z; r7.w <- sz0.w

#line 185
mad r3.xyzw, -r7.xyzw, r6.xyzw, r3.xyzw

#line 202
mov r0.x, r3.x

#line 186
ge r6.xyzw, r4.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r6.xyzw, r6.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r4.xyzw, -r7.xyzw, r6.xyzw, r4.xyzw

#line 202
mov r0.y, r4.x
dp3 r6.x, r0.xyzx, r0.xyzx
mov r7.z, r5.w
mov r7.x, r3.z
mov r7.y, r4.z
dp3 r6.y, r7.xyzx, r7.xyzx
mov r4.z, r5.y
mov r4.x, r3.y
mov r5.x, r3.w
mov r5.y, r4.w
dp3 r6.z, r4.xyzx, r4.xyzx
dp3 r6.w, r5.xyzx, r5.xyzx

#line 155
mul r3.xyzw, r6.xyzw, cb0[2].xxxx
mad r3.xyzw, -r3.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r3.x <- <taylorInvSqrt_id71 return value>.x; r3.y <- <taylorInvSqrt_id71 return value>.y; r3.z <- <taylorInvSqrt_id71 return value>.z; r3.w <- <taylorInvSqrt_id71 return value>.w

#line 205
mul r4.xyz, r3.zzzz, r4.xyzx  // r4.x <- g100.x; r4.y <- g100.y; r4.z <- g100.z

#line 213
add r2.w, r2.x, l(-1.000000)
dp3 r4.y, r4.yzxy, r2.yzwy  // r4.y <- n100

#line 159
mad r6.xyzw, r1.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), l(1.000000, 1.000000, 1.000000, 1.000000)
mul r1.xyzw, r1.xyzw, r6.xyzw

#line 147
mul r6.xyzw, r1.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
round_ni r6.xyzw, r6.xyzw
mad r1.xyzw, -r6.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r1.xyzw  // r1.x <- <mod289_id69 return value>.x; r1.y <- <mod289_id69 return value>.y; r1.z <- <mod289_id69 return value>.z; r1.w <- <mod289_id69 return value>.w

#line 187
mul r1.xyzw, r1.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)  // r1.x <- gx1.x; r1.y <- gx1.y; r1.z <- gx1.z; r1.w <- gx1.w

#line 188
round_ni r6.xyzw, r1.xyzw

#line 189
frc r1.xyzw, r1.xyzw

#line 188
mul r6.xyzw, r6.xyzw, l(0.142857, 0.142857, 0.142857, 0.142857)
frc r6.xyzw, r6.xyzw
add r6.xyzw, r6.xyzw, l(-0.500000, -0.500000, -0.500000, -0.500000)  // r6.x <- gy1.x; r6.y <- gy1.y; r6.z <- gy1.z; r6.w <- gy1.w

#line 190
add r8.xyzw, -r1.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r8.xyzw, -|r6.xywz|, r8.xywz  // r8.x <- gz1.x; r8.y <- gz1.y; r8.z <- gz1.w; r8.w <- gz1.z

#line 207
mov r9.z, r8.x

#line 192
ge r10.xyzw, r1.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r10.xyzw, r10.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)

#line 191
ge r11.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r8.xywz
and r11.xyzw, r11.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)  // r11.x <- sz1.x; r11.y <- sz1.y; r11.z <- sz1.z; r11.w <- sz1.w

#line 192
mad r1.xyzw, -r11.xyzw, r10.xyzw, r1.xyzw

#line 207
mov r10.x, r1.z

#line 193
ge r12.xyzw, r6.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r12.xyzw, r12.xyzw, l(0.500000,0.500000,0.500000,0.500000), l(-0.500000,-0.500000,-0.500000,-0.500000)
mad r6.xyzw, -r11.xyzw, r12.xyzw, r6.xyzw

#line 207
mov r10.y, r6.z
mov r10.z, r8.w
dp3 r11.y, r10.xyzx, r10.xyzx
mov r12.z, r8.y
mov r12.x, r1.y
mov r12.y, r6.y
dp3 r11.z, r12.xyzx, r12.xyzx
mov r8.x, r1.w
mov r9.x, r1.x
mov r8.y, r6.w
mov r9.y, r6.x
dp3 r11.w, r8.xyzx, r8.xyzx
dp3 r11.x, r9.xyzx, r9.xyzx

#line 155
mul r1.xyzw, r11.xyzw, cb0[2].xxxx
mad r1.xyzw, -r1.xyzw, l(4.268674, 4.268674, 4.268674, 4.268674), l(1.792843, 1.792843, 1.792843, 1.792843)  // r1.x <- <taylorInvSqrt_id71 return value>.x; r1.y <- <taylorInvSqrt_id71 return value>.y; r1.z <- <taylorInvSqrt_id71 return value>.z; r1.w <- <taylorInvSqrt_id71 return value>.w

#line 208
mul r6.xyz, r1.xxxx, r9.xyzx  // r6.x <- g001.x; r6.y <- g001.y; r6.z <- g001.z

#line 216
add r9.xyz, r2.xyzx, l(0.000000, 0.000000, -1.000000, 0.000000)
dp3 r6.x, r6.xyzx, r9.xyzx  // r6.x <- n001

#line 210
mul r9.xyz, r1.zzzz, r12.xyzx  // r9.x <- g101.x; r9.y <- g101.y; r9.z <- g101.z

#line 217
add r11.xyz, r2.xyzx, l(-1.000000, 0.000000, -1.000000, 0.000000)
dp3 r6.y, r9.xyzx, r11.xyzx  // r6.y <- n101

#line 209
mul r1.xyz, r1.yyyy, r10.xyzx  // r1.x <- g011.x; r1.y <- g011.y; r1.z <- g011.z

#line 211
mul r8.xyz, r1.wwww, r8.xyzx  // r8.x <- g111.x; r8.y <- g111.y; r8.z <- g111.z

#line 218
add r9.xyz, r2.xyzx, l(0.000000, -1.000000, -1.000000, 0.000000)
dp3 r6.z, r1.xyzx, r9.xyzx  // r6.z <- n011

#line 172
add r1.xyz, r2.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)  // r1.x <- Pf1.x; r1.y <- Pf1.y; r1.z <- Pf1.z

#line 219
dp3 r6.w, r8.xyzx, r1.xyzx  // r6.w <- n111

#line 204
mul r1.xyz, r3.yyyy, r7.xyzx  // r1.x <- g010.x; r1.y <- g010.y; r1.z <- g010.z

#line 214
add r7.xyz, r2.xyzx, l(0.000000, -1.000000, 0.000000, 0.000000)
dp3 r4.z, r1.xyzx, r7.xyzx  // r4.z <- n010

#line 206
mul r1.xyz, r3.wwww, r5.xyzx  // r1.x <- g110.x; r1.y <- g110.y; r1.z <- g110.z

#line 203
mul r0.xyz, r0.xyzx, r3.xxxx  // r0.x <- g000.x; r0.y <- g000.y; r0.z <- g000.z

#line 212
dp3 r4.x, r0.xyzx, r2.xyzx  // r4.x <- n000

#line 215
add r0.xyz, r2.xyzx, l(-1.000000, -1.000000, 0.000000, 0.000000)
dp3 r4.w, r1.xyzx, r0.xyzx  // r4.w <- n110

#line 221
add r1.xyzw, -r4.xyzw, r6.xyzw

#line 151
mul r0.xyz, r2.xyzx, r2.xyzx
mul r0.xyz, r2.xyzx, r0.xyzx
mad r3.xyz, r2.xyzx, l(6.000000, 6.000000, 6.000000, 0.000000), l(-15.000000, -15.000000, -15.000000, 0.000000)
mad r2.xyz, r2.xyzx, r3.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
mul r0.xyz, r0.xyzx, r2.xyzx  // r0.x <- <fade_id72 return value>.x; r0.y <- <fade_id72 return value>.y; r0.z <- <fade_id72 return value>.z

#line 221
mad r1.xyzw, r0.zzzz, r1.xyzw, r4.xyzw  // r1.x <- n_z.x; r1.y <- n_z.y; r1.z <- n_z.z; r1.w <- n_z.w

#line 222
add r1.zw, -r1.xxxy, r1.zzzw
mad r0.yz, r0.yyyy, r1.zzwz, r1.xxyx  // r0.y <- n_yz.x; r0.z <- n_yz.y

#line 223
add r0.z, -r0.y, r0.z
mad r0.x, r0.x, r0.z, r0.y  // r0.x <- n_xyz

#line 224
mul r0.x, r0.x, l(2.200000)  // r0.x <- <cnoise_id73 return value>

#line 243
mad r0.x, |r0.x|, l(0.031250), r0.w  // r0.x <- n

#line 255
add r0.x, -r0.x, l(1.000000)
add r0.x, -r0.x, l(1.000000)  // r0.x <- tc.x

#line 256
add r1.xyzw, -cb0[0].xyzw, cb0[1].xyzw
mad o0.xyzw, r0.xxxx, r1.xyzw, cb0[0].xyzw

#line 265
ret 
// Approximately 818 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id97;
    float4 InputValue_id98;
    float InputValue_id99;
    float InputValue_id100;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float Compute_id76()
{
    return InputValue_id99;
}
float4 mod289_id69(float4 x)
{
    return x - floor(x * (1.0 / 289.0)) * 289.0;
}
float3 fade_id72(float3 t)
{
    return t * t * t * (t * (t * 6.0 - 15.0) + 10.0);
}
float4 taylorInvSqrt_id71(float4 r)
{
    return 1.79284291400159 - 0.85373472095314 * r * Compute_id76() * 5.0;
}
float4 permute_id70(float4 x)
{
    return mod289_id69(((x * 34.0) + 1.0) * x);
}
float3 mod289_id68(float3 x)
{
    return x - floor(x * (1.0 / 289.0)) * 289.0;
}
float cnoise_id73(float3 P)
{
    float3 Pi0 = floor(P);
    float3 Pi1 = Pi0 + float3(1.0, 1.0, 1.0);
    Pi0 = mod289_id68(Pi0);
    Pi1 = mod289_id68(Pi1);
    float3 Pf0 = frac(P);
    float3 Pf1 = Pf0 - float3(1.0, 1.0, 1.0);
    float4 ix = float4(Pi0.x, Pi1.x, Pi0.x, Pi1.x);
    float4 iy = float4(Pi0.yy, Pi1.yy);
    float4 iz0 = Pi0.zzzz;
    float4 iz1 = Pi1.zzzz;
    float4 ixy = permute_id70(permute_id70(ix) + iy);
    float4 ixy0 = permute_id70(ixy + iz0);
    float4 ixy1 = permute_id70(ixy + iz1);
    float4 gx0 = ixy0 * (1.0 / 7.0);
    float4 gy0 = frac(floor(gx0) * (1.0 / 7.0)) - 0.5;
    gx0 = frac(gx0);
    float4 gz0 = float4(0.5, 0.5, 0.5, 0.5) - abs(gx0) - abs(gy0);
    float4 sz0 = step(gz0, float4(0.0, 0.0, 0.0, 0.0));
    gx0 -= sz0 * (step(0.0, gx0) - 0.5);
    gy0 -= sz0 * (step(0.0, gy0) - 0.5);
    float4 gx1 = ixy1 * (1.0 / 7.0);
    float4 gy1 = frac(floor(gx1) * (1.0 / 7.0)) - 0.5;
    gx1 = frac(gx1);
    float4 gz1 = float4(0.5, 0.5, 0.5, 0.5) - abs(gx1) - abs(gy1);
    float4 sz1 = step(gz1, float4(0.0, 0.0, 0.0, 0.0));
    gx1 -= sz1 * (step(0.0, gx1) - 0.5);
    gy1 -= sz1 * (step(0.0, gy1) - 0.5);
    float3 g000 = float3(gx0.x, gy0.x, gz0.x);
    float3 g100 = float3(gx0.y, gy0.y, gz0.y);
    float3 g010 = float3(gx0.z, gy0.z, gz0.z);
    float3 g110 = float3(gx0.w, gy0.w, gz0.w);
    float3 g001 = float3(gx1.x, gy1.x, gz1.x);
    float3 g101 = float3(gx1.y, gy1.y, gz1.y);
    float3 g011 = float3(gx1.z, gy1.z, gz1.z);
    float3 g111 = float3(gx1.w, gy1.w, gz1.w);
    float4 norm0 = taylorInvSqrt_id71(float4(dot(g000, g000), dot(g010, g010), dot(g100, g100), dot(g110, g110)));
    g000 *= norm0.x;
    g010 *= norm0.y;
    g100 *= norm0.z;
    g110 *= norm0.w;
    float4 norm1 = taylorInvSqrt_id71(float4(dot(g001, g001), dot(g011, g011), dot(g101, g101), dot(g111, g111)));
    g001 *= norm1.x;
    g011 *= norm1.y;
    g101 *= norm1.z;
    g111 *= norm1.w;
    float n000 = dot(g000, Pf0);
    float n100 = dot(g100, float3(Pf1.x, Pf0.yz));
    float n010 = dot(g010, float3(Pf0.x, Pf1.y, Pf0.z));
    float n110 = dot(g110, float3(Pf1.xy, Pf0.z));
    float n001 = dot(g001, float3(Pf0.xy, Pf1.z));
    float n101 = dot(g101, float3(Pf1.x, Pf0.y, Pf1.z));
    float n011 = dot(g011, float3(Pf0.x, Pf1.yz));
    float n111 = dot(g111, Pf1);
    float3 fade_xyz = fade_id72(Pf0);
    float4 n_z = lerp(float4(n000, n100, n010, n110), float4(n001, n101, n011, n111), fade_xyz.z);
    float2 n_yz = lerp(n_z.xy, n_z.zw, fade_xyz.y);
    float n_xyz = lerp(n_yz.x, n_yz.y, fade_xyz.x);
    return 2.2 * n_xyz;
}
float4 Compute_id79()
{
    return InputValue_id98;
}
float4 Compute_id78()
{
    return InputValue_id97;
}
float surface3_id74(float3 coord)
{
    float frequency = 4.0;
    float n = 0.0;
    n += 1.0 * abs(cnoise_id73(coord * frequency));
    n += 0.5 * abs(cnoise_id73(coord * frequency * 2.0));
    n += 0.25 * abs(cnoise_id73(coord * frequency * 4.0));
    n += 0.125 * abs(cnoise_id73(coord * frequency * 8.0));
    n += 0.0625 * abs(cnoise_id73(coord * frequency * 16.0));
    n += 0.03125 * abs(cnoise_id73(coord * frequency * 32.0));
    return n;
}
float Compute_id77()
{
    return InputValue_id100;
}
float4 Shading_id75(inout PS_STREAMS streams)
{
    float2 position = streams.TexCoord_id62;
    float n = surface3_id74(float3(position, Compute_id77() * 0.1));
    float lum = length(n);
    float4 tc = 1. - float4(1. - lum, 1. - lum, 1. - lum, 1 - lum);
    return lerp(Compute_id78(), Compute_id79(), tc);
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id75(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
