/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:8 Y:8 Z:8
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_1446293058]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 288]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_4027469542_id27 => input_4027469542
@C    input_3335055883_id28 => input_3335055883
@C    input_1092026727_id29 => input_1092026727
@C    input_826793605_id30 => input_826793605
@C    input_3887551545_id31 => input_3887551545
@C    input_4285495262_id32 => input_4285495262
@C    input_2612132572_id33 => input_2612132572
@C    input_706026866_id34 => input_706026866
@C    input_2145687636_id35 => input_2145687636
@C    input_545566076_id36 => input_545566076
@C    input_3530845571_id37 => input_3530845571
@C    input_1386142014_id38 => input_1386142014
@C    input_784016946_id39 => input_784016946
@C    input_3491954125_id40 => input_3491954125
@C    input_3940645616_id41 => input_3940645616
@C    input_1215088069_id42 => input_1215088069
@C    input_2966110979_id43 => input_2966110979
@C    input_3330421063_id44 => input_3330421063
@C    input_2931687735_id45 => input_2931687735
@C    input_612669918_id46 => input_612669918
@C    input_1214679681_id47 => input_1214679681
@C    input_4032468177_id48 => input_4032468177
***************************
******  Resources    ******
***************************
@R    TextureInput_3445202295_id23 => TextureInput_3445202295 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_1090208749_id24 => TextureInput_1090208749 [Stage: Compute, Slot: (1-1)]
@R    TextureInput_2255746994_id25 => TextureInput_2255746994 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_3422964264_id26 => TextureInput_3422964264 [Stage: Compute, Slot: (1-1)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_1446293058 => 65751aec9fec07c54ae9f2bd9fc582a8
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCommonNoise => f3e94fe4a03a0b02051750e5b6a831ca
@S    FuseCommonNoiseSine => d8c809697d88a8d534414c8b788f34bd
@S    FuseCoreMath => b5527ab1f8082f68a6dcc7c3959ee99a
@S    FuseCoreMathHash => 9e8ec916d08625592014904eea5076c5
@S    FuseCommonNoiseValueNoise => 598ea3c9dd7c5fed506e079ef91b1d81
@S    FuseCommonNoiseGradientNoise => 275a1c68a04d0e8c934e4792e8de1a02
@S    FuseCommonNoiseSimplex => cff83c6dcba0e92106f65f2c730e3e35
@S    FuseCommonNoiseRandom => c9e5885d1263580889df6cfb5c437ec3
@S    FuseCommonNoiseWorley => d0830642cb2e69b2f30256019c06d7a7
***************************
*****     Stages      *****
***************************
@G    Compute => 80c319a43293e4d6924380d87010f5eb
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int3 input_4027469542_id27;        // Offset:   16 Size:    12
//   float input_3335055883_id28;       // Offset:   28 Size:     4 [unused]
//   float3 input_1092026727_id29;      // Offset:   32 Size:    12 [unused]
//   float3 input_826793605_id30;       // Offset:   48 Size:    12
//   float input_3887551545_id31;       // Offset:   60 Size:     4
//   float3 input_4285495262_id32;      // Offset:   64 Size:    12
//   int3 input_2612132572_id33;        // Offset:   80 Size:    12
//   float3 input_706026866_id34;       // Offset:   96 Size:    12 [unused]
//   float4x4 input_2145687636_id35;    // Offset:  112 Size:    64
//   float3 input_545566076_id36;       // Offset:  176 Size:    12
//   float input_3530845571_id37;       // Offset:  188 Size:     4
//   float input_1386142014_id38;       // Offset:  192 Size:     4
//   float3 input_784016946_id39;       // Offset:  196 Size:    12
//   float3 input_3491954125_id40;      // Offset:  208 Size:    12
//   float input_3940645616_id41;       // Offset:  220 Size:     4
//   float input_1215088069_id42;       // Offset:  224 Size:     4
//   float input_2966110979_id43;       // Offset:  228 Size:     4
//   float3 input_3330421063_id44;      // Offset:  240 Size:    12
//   float input_2931687735_id45;       // Offset:  252 Size:     4
//   float3 input_612669918_id46;       // Offset:  256 Size:    12
//   float input_1214679681_id47;       // Offset:  268 Size:     4
//   float input_4032468177_id48;       // Offset:  272 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// TextureInput_3445202295_id23      texture  float4          3d             t0      1 
// TextureInput_1090208749_id24      texture   float          3d             t1      1 
// TextureInput_2255746994_id25          UAV  float4          3d             u0      1 
// TextureInput_3422964264_id26          UAV   float          3d             u1      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[18], immediateIndexed
dcl_resource_texture3d (float,float,float,float) t0
dcl_resource_texture3d (float,float,float,float) t1
dcl_uav_typed_texture3d (float,float,float,float) u0
dcl_uav_typed_texture3d (float,float,float,float) u1
dcl_input vThreadID.xyz
dcl_temps 20
dcl_thread_group 8, 8, 8
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 134 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_ComputeFXEffect_a3febea6befdd072bc1c3ef7e2d516c1.hlsl"
ige r0.xyz, vThreadID.xyzx, cb0[1].xyzx  // r0.x <- Assign_2669607774; r0.y <- Assign_2401786989; r0.z <- Assign_3128971616

#line 135
or r0.x, r0.y, r0.x
or r0.x, r0.z, r0.x  // r0.x <- result_2293831901

#line 140
if_z r0.x

#line 148
  mov r0.xyz, vThreadID.xyzx
  mov r0.w, l(0)
  ld_indexable(texture3d)(float,float,float,float) r1.xyzw, r0.xyzw, t0.xyzw  // r1.x <- velocity_2_2773640457.x; r1.y <- velocity_2_2773640457.y; r1.z <- velocity_2_2773640457.z; r1.w <- velocity_2_2773640457.w

#line 149
  utof r2.xyz, vThreadID.xyzx

#line 150
  add r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)  // r2.x <- result_2318118799.x; r2.y <- result_2318118799.y; r2.z <- result_2318118799.z

#line 151
  itof r3.xyz, cb0[5].xyzx

#line 152
  div r2.xyz, r2.xyzx, r3.xyzx  // r2.x <- result_1781501966.x; r2.y <- result_1781501966.y; r2.z <- result_1781501966.z

#line 153
  add r2.xyz, r2.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)  // r2.x <- result_3334746528.x; r2.y <- result_3334746528.y; r2.z <- result_3334746528.z

#line 158
  mov r2.w, l(1.000000)
  dp4 r3.x, r2.xyzw, cb0[7].xyzw  // r3.x <- mul_3753286746.x
  dp4 r3.y, r2.xyzw, cb0[8].xyzw  // r3.y <- mul_3753286746.y
  dp4 r3.z, r2.xyzw, cb0[9].xyzw  // r3.z <- mul_3753286746.z

#line 113
  add r2.xyz, r3.xyzx, -cb0[3].xyzx  // r2.x <- result_1512400414.x; r2.y <- result_1512400414.y; r2.z <- result_1512400414.z

#line 114
  dp3 r2.x, r2.xyzx, r2.xyzx
  sqrt r2.x, r2.x  // r2.x <- length_230306403

#line 115
  add r2.x, r2.x, -cb0[3].w  // r2.x <- result_2937537851

#line 165
  mul r2.x, -r2.x, l(1.#INF00)  // r2.x <- result_2365310752

#line 166
  mov_sat r2.xyz, r2.xxxx  // r2.z <- saturate_1172730497

#line 169
  add r4.xyz, -r1.xyzx, cb0[4].xyzx
  add r4.w, -r1.w, l(1.000000)
  mov r2.w, l(1.000000)
  mad r1.xyzw, r2.xyzw, r4.xyzw, r1.xyzw  // r1.x <- lerp_3358782467.x; r1.y <- lerp_3358782467.y; r1.z <- lerp_3358782467.z; r1.w <- lerp_3358782467.w

#line 171
  round_pi r2.x, cb0[14].x  // r2.x <- ceil_4176877153

#line 172
  ftoi r2.x, r2.x  // r2.x <- cast11_2713164060

#line 178
  mov r2.yzw, r3.xxyz  // r2.y <- output_2402172871.x; r2.z <- output_2402172871.y; r2.w <- output_2402172871.z
  mov r4.xyz, l(0,0,0,0)  // r4.x <- output_3815007906.x; r4.y <- output_3815007906.y; r4.z <- output_3815007906.z
  mov r3.w, l(0)  // r3.w <- output_2808590973
  mov r4.w, cb0[13].w  // r4.w <- output_3837911896
  mov r5.x, l(0)  // r5.x <- index_4912002
  loop 
    ige r5.y, r5.x, r2.x
    breakc_nz r5.y

#line 180
    mul r5.yzw, r2.yyzw, cb0[14].yyyy  // r5.y <- result_344171006.x; r5.z <- result_344171006.y; r5.w <- result_344171006.z

#line 91
    mul r6.w, r2.w, cb0[11].z  // r6.w <- result_2044114122.z

#line 93
    mad r6.x, r2.y, cb0[11].x, cb0[11].w  // r6.x <- result_783623819.x
    mad r6.y, r2.z, cb0[11].y, cb0[12].x  // r6.y <- result_783623819.y

#line 64
    mov r6.zw, r6.wwww  // r6.z <- result_783623819.z
    add r7.xyz, r6.wyxw, l(17.000000, 17.000000, 17.000000, 0.000000)  // r7.x <- p2.z; r7.y <- p2.y; r7.z <- p2.x

#line 65
    add r8.xyz, r6.xywx, l(-43.700001, -43.700001, -43.700001, 0.000000)  // r8.x <- p3.x; r8.y <- p3.y; r8.z <- p3.z

#line 57
    round_ni r9.xyz, r6.zyxz  // r9.x <- i.z; r9.y <- i.y; r9.z <- i.x

#line 58
    frc r6.xyz, r6.xyzx  // r6.x <- f.x; r6.y <- f.y; r6.z <- f.z

#line 59
    mul r10.xyz, r6.xyzx, r6.xyzx
    mad r11.xyz, -r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(3.000000, 3.000000, 3.000000, 0.000000)
    mul r10.xyz, r10.xyzx, r11.xyzx  // r10.x <- u.x; r10.y <- u.y; r10.z <- u.z

#line 51
    mul r11.xyz, r9.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r12.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r11.zyxz, r12.xyzx
    add r11.xyz, r6.wwww, r11.xyzx

#line 53
    add r12.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r12.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.w, r11.xyzx, r6.xyzx
    add r11.xyz, r9.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r12.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r11.zyxz, r12.xyzx
    add r11.xyz, r7.wwww, r11.xyzx

#line 53
    add r12.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r12.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r12.xyz, r6.xyzx, l(-1.000000, -0.000000, -0.000000, 0.000000)
    dp3 r7.w, r11.xyzx, r12.xyzx
    add r7.w, -r6.w, r7.w
    mad r6.w, r10.x, r7.w, r6.w
    add r11.xyz, r9.xyzx, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r13.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r11.zyxz, r13.xyzx
    add r11.xyz, r7.wwww, r11.xyzx

#line 53
    add r13.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r13.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r13.xyz, r6.xyzx, l(-0.000000, -1.000000, -0.000000, 0.000000)
    dp3 r7.w, r11.xyzx, r13.xyzx
    add r11.xyz, r9.xyzx, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r14.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r11.zyxz, r14.xyzx
    add r11.xyz, r8.wwww, r11.xyzx

#line 53
    add r14.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r14.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r14.xyz, r6.xyzx, l(-1.000000, -1.000000, -0.000000, 0.000000)
    dp3 r8.w, r11.xyzx, r14.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r10.x, r8.w, r7.w
    add r7.w, -r6.w, r7.w
    mad r6.w, r10.y, r7.w, r6.w
    add r11.xyz, r9.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r15.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r11.zyxz, r15.xyzx
    add r11.xyz, r7.wwww, r11.xyzx

#line 53
    add r15.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r15.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r15.xyz, r6.xyzx, l(-0.000000, -0.000000, -1.000000, 0.000000)
    dp3 r7.w, r11.xyzx, r15.xyzx
    add r11.xyz, r9.xyzx, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r16.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r11.zyxz, r16.xyzx
    add r11.xyz, r8.wwww, r11.xyzx

#line 53
    add r16.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r16.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r16.xyz, r6.xyzx, l(-1.000000, -0.000000, -1.000000, 0.000000)
    dp3 r8.w, r11.xyzx, r16.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r10.x, r8.w, r7.w
    add r11.xyz, r9.xyzx, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r11.xyz, r11.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r11.xyz, r11.xyzx  // r11.x <- p3.z; r11.y <- p3.y; r11.z <- p3.x

#line 52
    add r17.xyz, r11.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r11.zyxz, r17.xyzx
    add r11.xyz, r8.wwww, r11.xyzx

#line 53
    add r17.xyz, r11.yzyy, r11.zzzz
    mul r11.xyz, r11.xyzx, r17.xyzx
    frc r11.xyz, r11.xyzx  // r11.x <- <hash33_id14 return value>.x; r11.y <- <hash33_id14 return value>.y; r11.z <- <hash33_id14 return value>.z

#line 60
    mad r11.xyz, r11.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r17.xyz, r6.xyzx, l(-0.000000, -1.000000, -1.000000, 0.000000)
    dp3 r8.w, r11.xyzx, r17.xyzx
    add r9.xyz, r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r9.xyz, r9.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r9.xyz, r9.xyzx  // r9.x <- p3.z; r9.y <- p3.y; r9.z <- p3.x

#line 52
    add r11.xyz, r9.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r9.w, r9.zyxz, r11.xyzx
    add r9.xyz, r9.wwww, r9.xyzx

#line 53
    add r11.xyz, r9.yzyy, r9.zzzz
    mul r9.xyz, r9.xyzx, r11.xyzx
    frc r9.xyz, r9.xyzx  // r9.x <- <hash33_id14 return value>.x; r9.y <- <hash33_id14 return value>.y; r9.z <- <hash33_id14 return value>.z

#line 60
    mad r9.xyz, r9.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r6.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r9.x, r9.xyzx, r11.xyzx
    add r9.x, -r8.w, r9.x
    mad r8.w, r10.x, r9.x, r8.w
    add r8.w, -r7.w, r8.w
    mad r7.w, r10.y, r8.w, r7.w
    add r7.w, -r6.w, r7.w
    mad r6.w, r10.z, r7.w, r6.w
    mul r9.x, r6.w, cb0[12].y

#line 57
    round_ni r7.xyz, r7.xyzx  // r7.x <- i.z; r7.y <- i.y; r7.z <- i.x

#line 51
    mul r18.xyz, r7.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r18.xyz, r18.xyzx  // r18.x <- p3.z; r18.y <- p3.y; r18.z <- p3.x

#line 52
    add r19.xyz, r18.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r18.zyxz, r19.xyzx
    add r18.xyz, r6.wwww, r18.xyzx

#line 53
    add r19.xyz, r18.yzyy, r18.zzzz
    mul r18.xyz, r18.xyzx, r19.xyzx
    frc r18.xyz, r18.xyzx  // r18.x <- <hash33_id14 return value>.x; r18.y <- <hash33_id14 return value>.y; r18.z <- <hash33_id14 return value>.z

#line 60
    mad r18.xyz, r18.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.x, r18.xyzx, r6.xyzx
    add r6.yzw, r7.xxyz, l(0.000000, 0.000000, 0.000000, 1.000000)

#line 51
    mul r6.yzw, r6.yyzw, l(0.000000, 0.097300, 0.103000, 0.103100)
    frc r6.yzw, r6.yyzw  // r6.y <- p3.z; r6.z <- p3.y; r6.w <- p3.x

#line 52
    add r18.xyz, r6.zwyz, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r6.wzyw, r18.xyzx
    add r6.yzw, r6.yyzw, r7.wwww

#line 53
    add r18.xyz, r6.zwzz, r6.wwww
    mul r6.yzw, r6.yyzw, r18.xxyz
    frc r6.yzw, r6.yyzw  // r6.y <- <hash33_id14 return value>.x; r6.z <- <hash33_id14 return value>.y; r6.w <- <hash33_id14 return value>.z

#line 60
    mad r6.yzw, r6.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
    dp3 r6.y, r6.yzwy, r12.xyzx
    add r6.y, -r6.x, r6.y
    mad r6.x, r10.x, r6.y, r6.x
    add r6.yzw, r7.xxyz, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r6.yzw, r6.yyzw, l(0.000000, 0.097300, 0.103000, 0.103100)
    frc r6.yzw, r6.yyzw  // r6.y <- p3.z; r6.z <- p3.y; r6.w <- p3.x

#line 52
    add r12.xyz, r6.zwyz, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r6.wzyw, r12.xyzx
    add r6.yzw, r6.yyzw, r7.wwww

#line 53
    add r12.xyz, r6.zwzz, r6.wwww
    mul r6.yzw, r6.yyzw, r12.xxyz
    frc r6.yzw, r6.yyzw  // r6.y <- <hash33_id14 return value>.x; r6.z <- <hash33_id14 return value>.y; r6.w <- <hash33_id14 return value>.z

#line 60
    mad r6.yzw, r6.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
    dp3 r6.y, r6.yzwy, r13.xyzx
    add r12.xyz, r7.xyzx, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r12.xyz, r12.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r12.xyz, r12.xyzx  // r12.x <- p3.z; r12.y <- p3.y; r12.z <- p3.x

#line 52
    add r13.xyz, r12.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.z, r12.zyxz, r13.xyzx
    add r12.xyz, r6.zzzz, r12.xyzx

#line 53
    add r13.xyz, r12.yzyy, r12.zzzz
    mul r12.xyz, r12.xyzx, r13.xyzx
    frc r12.xyz, r12.xyzx  // r12.x <- <hash33_id14 return value>.x; r12.y <- <hash33_id14 return value>.y; r12.z <- <hash33_id14 return value>.z

#line 60
    mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.z, r12.xyzx, r14.xyzx
    add r6.z, -r6.y, r6.z
    mad r6.y, r10.x, r6.z, r6.y
    add r6.y, -r6.x, r6.y
    mad r6.x, r10.y, r6.y, r6.x
    add r6.yzw, r7.xxyz, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r6.yzw, r6.yyzw, l(0.000000, 0.097300, 0.103000, 0.103100)
    frc r6.yzw, r6.yyzw  // r6.y <- p3.z; r6.z <- p3.y; r6.w <- p3.x

#line 52
    add r12.xyz, r6.zwyz, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r6.wzyw, r12.xyzx
    add r6.yzw, r6.yyzw, r7.wwww

#line 53
    add r12.xyz, r6.zwzz, r6.wwww
    mul r6.yzw, r6.yyzw, r12.xxyz
    frc r6.yzw, r6.yyzw  // r6.y <- <hash33_id14 return value>.x; r6.z <- <hash33_id14 return value>.y; r6.w <- <hash33_id14 return value>.z

#line 60
    mad r6.yzw, r6.yyzw, l(0.000000, 2.000000, 2.000000, 2.000000), l(0.000000, -1.000000, -1.000000, -1.000000)
    dp3 r6.y, r6.yzwy, r15.xyzx
    add r12.xyz, r7.xyzx, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r12.xyz, r12.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r12.xyz, r12.xyzx  // r12.x <- p3.z; r12.y <- p3.y; r12.z <- p3.x

#line 52
    add r13.xyz, r12.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.z, r12.zyxz, r13.xyzx
    add r12.xyz, r6.zzzz, r12.xyzx

#line 53
    add r13.xyz, r12.yzyy, r12.zzzz
    mul r12.xyz, r12.xyzx, r13.xyzx
    frc r12.xyz, r12.xyzx  // r12.x <- <hash33_id14 return value>.x; r12.y <- <hash33_id14 return value>.y; r12.z <- <hash33_id14 return value>.z

#line 60
    mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.z, r12.xyzx, r16.xyzx
    add r6.z, -r6.y, r6.z
    mad r6.y, r10.x, r6.z, r6.y
    add r12.xyz, r7.xyzx, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r12.xyz, r12.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r12.xyz, r12.xyzx  // r12.x <- p3.z; r12.y <- p3.y; r12.z <- p3.x

#line 52
    add r13.xyz, r12.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.z, r12.zyxz, r13.xyzx
    add r12.xyz, r6.zzzz, r12.xyzx

#line 53
    add r13.xyz, r12.yzyy, r12.zzzz
    mul r12.xyz, r12.xyzx, r13.xyzx
    frc r12.xyz, r12.xyzx  // r12.x <- <hash33_id14 return value>.x; r12.y <- <hash33_id14 return value>.y; r12.z <- <hash33_id14 return value>.z

#line 60
    mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.z, r12.xyzx, r17.xyzx
    add r7.xyz, r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r7.xyz, r7.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r7.xyz, r7.xyzx  // r7.x <- p3.z; r7.y <- p3.y; r7.z <- p3.x

#line 52
    add r12.xyz, r7.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r7.zyxz, r12.xyzx
    add r7.xyz, r6.wwww, r7.xyzx

#line 53
    add r12.xyz, r7.yzyy, r7.zzzz
    mul r7.xyz, r7.xyzx, r12.xyzx
    frc r7.xyz, r7.xyzx  // r7.x <- <hash33_id14 return value>.x; r7.y <- <hash33_id14 return value>.y; r7.z <- <hash33_id14 return value>.z

#line 60
    mad r7.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.w, r7.xyzx, r11.xyzx
    add r6.w, -r6.z, r6.w
    mad r6.z, r10.x, r6.w, r6.z
    add r6.z, -r6.y, r6.z
    mad r6.y, r10.y, r6.z, r6.y
    add r6.y, -r6.x, r6.y
    mad r6.x, r10.z, r6.y, r6.x
    mul r9.y, r6.x, cb0[12].z

#line 57
    round_ni r6.xyz, r8.zyxz  // r6.x <- i.z; r6.y <- i.y; r6.z <- i.x

#line 58
    frc r7.xyz, r8.xyzx  // r7.x <- f.x; r7.y <- f.y; r7.z <- f.z

#line 59
    mul r8.xyz, r7.xyzx, r7.xyzx
    mad r10.xyz, -r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(3.000000, 3.000000, 3.000000, 0.000000)
    mul r8.xyz, r8.xyzx, r10.xyzx  // r8.x <- u.x; r8.y <- u.y; r8.z <- u.z

#line 51
    mul r10.xyz, r6.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r6.w, r10.zyxz, r11.xyzx
    add r10.xyz, r6.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.w, r10.xyzx, r7.xyzx
    add r10.xyz, r6.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r10.zyxz, r11.xyzx
    add r10.xyz, r7.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-1.000000, -0.000000, -0.000000, 0.000000)
    dp3 r7.w, r10.xyzx, r11.xyzx
    add r7.w, -r6.w, r7.w
    mad r6.w, r8.x, r7.w, r6.w
    add r10.xyz, r6.xyzx, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r10.zyxz, r11.xyzx
    add r10.xyz, r7.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-0.000000, -1.000000, -0.000000, 0.000000)
    dp3 r7.w, r10.xyzx, r11.xyzx
    add r10.xyz, r6.xyzx, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r10.zyxz, r11.xyzx
    add r10.xyz, r8.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-1.000000, -1.000000, -0.000000, 0.000000)
    dp3 r8.w, r10.xyzx, r11.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r8.x, r8.w, r7.w
    add r7.w, -r6.w, r7.w
    mad r6.w, r8.y, r7.w, r6.w
    add r10.xyz, r6.xyzx, l(1.000000, 0.000000, 0.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r7.w, r10.zyxz, r11.xyzx
    add r10.xyz, r7.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-0.000000, -0.000000, -1.000000, 0.000000)
    dp3 r7.w, r10.xyzx, r11.xyzx
    add r10.xyz, r6.xyzx, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r10.zyxz, r11.xyzx
    add r10.xyz, r8.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-1.000000, -0.000000, -1.000000, 0.000000)
    dp3 r8.w, r10.xyzx, r11.xyzx
    add r8.w, -r7.w, r8.w
    mad r7.w, r8.x, r8.w, r7.w
    add r10.xyz, r6.xyzx, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 51
    mul r10.xyz, r10.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r10.xyz, r10.xyzx  // r10.x <- p3.z; r10.y <- p3.y; r10.z <- p3.x

#line 52
    add r11.xyz, r10.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r8.w, r10.zyxz, r11.xyzx
    add r10.xyz, r8.wwww, r10.xyzx

#line 53
    add r11.xyz, r10.yzyy, r10.zzzz
    mul r10.xyz, r10.xyzx, r11.xyzx
    frc r10.xyz, r10.xyzx  // r10.x <- <hash33_id14 return value>.x; r10.y <- <hash33_id14 return value>.y; r10.z <- <hash33_id14 return value>.z

#line 60
    mad r10.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r11.xyz, r7.xyzx, l(-0.000000, -1.000000, -1.000000, 0.000000)
    dp3 r8.w, r10.xyzx, r11.xyzx
    add r6.xyz, r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 51
    mul r6.xyz, r6.xyzx, l(0.097300, 0.103000, 0.103100, 0.000000)
    frc r6.xyz, r6.xyzx  // r6.x <- p3.z; r6.y <- p3.y; r6.z <- p3.x

#line 52
    add r10.xyz, r6.yzxy, l(19.190001, 19.190001, 19.190001, 0.000000)
    dp3 r9.w, r6.zyxz, r10.xyzx
    add r6.xyz, r6.xyzx, r9.wwww

#line 53
    add r10.xyz, r6.yzyy, r6.zzzz
    mul r6.xyz, r6.xyzx, r10.xyzx
    frc r6.xyz, r6.xyzx  // r6.x <- <hash33_id14 return value>.x; r6.y <- <hash33_id14 return value>.y; r6.z <- <hash33_id14 return value>.z

#line 60
    mad r6.xyz, r6.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    add r7.xyz, r7.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r6.x, r6.xyzx, r7.xyzx
    add r6.x, -r8.w, r6.x
    mad r6.x, r8.x, r6.x, r8.w
    add r6.x, -r7.w, r6.x
    mad r6.x, r8.y, r6.x, r7.w
    add r6.x, -r6.w, r6.x
    mad r6.x, r8.z, r6.x, r6.w
    mul r9.z, r6.x, cb0[12].w

#line 96
    mad r6.xyz, r9.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), cb0[13].xyzx  // r6.x <- result_1784618882.x; r6.y <- result_1784618882.y; r6.z <- result_1784618882.z

#line 182
    itof r6.w, r5.x

#line 183
    add r6.w, -r6.w, cb0[14].x  // r6.w <- result_2816853187

#line 184
    min r6.w, r6.w, l(1.000000)  // r6.w <- min_2622095659

#line 185
    mul r7.x, r4.w, r6.w  // r7.x <- result_3671589725

#line 187
    mad r4.xyz, r6.xyzx, r7.xxxx, r4.xyzx  // r4.x <- result_1239294461.x; r4.y <- result_1239294461.y; r4.z <- result_1239294461.z

#line 188
    mad r3.w, r6.w, r4.w, r3.w  // r3.w <- result_738610457

#line 189
    mul r4.w, r4.w, cb0[13].w  // r4.w <- result_3949622621

#line 194
    iadd r5.x, r5.x, l(1)
    mov r2.yzw, r5.yyzw
  endloop   // r4.x <- output_3815007906.x; r4.y <- output_3815007906.y; r4.z <- output_3815007906.z; r3.w <- output_2808590973; r4.w <- output_3837911896

#line 195
  lt r2.x, l(0.000000), r3.w  // r2.x <- Assign_2179612114

#line 196
  movc r2.x, r2.x, r3.w, l(1.000000)  // r2.x <- expression_3449698237

#line 198
  div r2.xyz, r4.xyzx, r2.xxxx  // r2.x <- result_3044682796.x; r2.y <- result_3044682796.y; r2.z <- result_3044682796.z

#line 199
  add r2.xyz, r2.xyzx, cb0[15].xyzx  // r2.x <- result_1988462773.x; r2.y <- result_1988462773.y; r2.z <- result_1988462773.z

#line 201
  add r2.xyz, r1.xyzx, r2.xyzx  // r2.x <- result_3779073243.x; r2.y <- result_3779073243.y; r2.z <- result_3779073243.z

#line 209
  mov r2.w, l(1.000000)
  add r2.xyzw, -r1.xyzw, r2.xyzw
  mov r4.x, cb0[15].w
  mov r4.w, l(1.000000)
  mad r1.xyzw, r4.xxxw, r2.xyzw, r1.xyzw  // r1.x <- lerp_2233171608.x; r1.y <- lerp_2233171608.y; r1.z <- lerp_2233171608.z; r1.w <- lerp_2233171608.w

#line 211
  ld_indexable(texture3d)(float,float,float,float) r0.x, r0.xyzw, t1.xyzw  // r0.x <- density_103807989

#line 79
  add r0.yzw, r3.xxyz, -cb0[16].xxyz  // r0.y <- result_3318057383.x; r0.z <- result_3318057383.y; r0.w <- result_3318057383.z

#line 80
  dp3 r0.y, r0.yzwy, r0.yzwy
  sqrt r0.y, r0.y  // r0.y <- length_3562960734

#line 81
  add r0.y, r0.y, -cb0[16].w  // r0.y <- result_1981706564

#line 217
  mul_sat r0.y, -r0.y, l(1.#INF00)  // r0.y <- saturate_3798608805

#line 221
  add r0.z, -r0.x, cb0[17].x
  mad r0.x, r0.y, r0.z, r0.x  // r0.x <- lerp_2342350959

#line 223
  store_uav_typed u0.xyzw, vThreadID.xyzz, r1.xyzw

#line 224
  store_uav_typed u1.xyzw, vThreadID.xyzz, r0.xxxx
endif 

#line 250
ret 
// Approximately 407 instruction slots used
***************************
*************************/
static const float PI_id12 = 3.1415926535897;
static const float3 vectorValuedNoiseOffsets_id22 = float3(17.0, -43.7, 67.0);
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int3 input_4027469542_id27;
    float input_3335055883_id28;
    float3 input_1092026727_id29;
    float3 input_826793605_id30;
    float input_3887551545_id31;
    float3 input_4285495262_id32;
    int3 input_2612132572_id33;
    float3 input_706026866_id34;
    float4x4 input_2145687636_id35;
    float3 input_545566076_id36;
    float input_3530845571_id37;
    float input_1386142014_id38;
    float3 input_784016946_id39;
    float3 input_3491954125_id40;
    float input_3940645616_id41;
    float input_1215088069_id42;
    float input_2966110979_id43;
    float3 input_3330421063_id44;
    float input_2931687735_id45;
    float3 input_612669918_id46;
    float input_1214679681_id47;
    float input_4032468177_id48;
};
Texture3D<float4> TextureInput_3445202295_id23;
Texture3D<float> TextureInput_1090208749_id24;
RWTexture3D<float4> TextureInput_2255746994_id25;
RWTexture3D<float> TextureInput_3422964264_id26;
float3 hash33_id14(float3 p3)
{
    p3 = frac(p3 * float3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz + 19.19);
    return frac((p3.xxy + p3.yxx) * p3.zyx);
}
float gradientNoise_id54(float3 p)
{
    float3 i = floor(p);
    float3 f = frac(p);
    float3 u = f * f * (3.0 - 2.0 * f);
    return 2. * lerp(lerp(lerp(dot(hash33_id14(i + float3(0.0, 0.0, 0.0)) * 2.0 - 1.0, f - float3(0.0, 0.0, 0.0)), dot(hash33_id14(i + float3(1.0, 0.0, 0.0)) * 2.0 - 1.0, f - float3(1.0, 0.0, 0.0)), u.x), lerp(dot(hash33_id14(i + float3(0.0, 1.0, 0.0)) * 2.0 - 1.0, f - float3(0.0, 1.0, 0.0)), dot(hash33_id14(i + float3(1.0, 1.0, 0.0)) * 2.0 - 1.0, f - float3(1.0, 1.0, 0.0)), u.x), u.y), lerp(lerp(dot(hash33_id14(i + float3(0.0, 0.0, 1.0)) * 2.0 - 1.0, f - float3(0.0, 0.0, 1.0)), dot(hash33_id14(i + float3(1.0, 0.0, 1.0)) * 2.0 - 1.0, f - float3(1.0, 0.0, 1.0)), u.x), lerp(dot(hash33_id14(i + float3(0.0, 1.0, 1.0)) * 2.0 - 1.0, f - float3(0.0, 1.0, 1.0)), dot(hash33_id14(i + float3(1.0, 1.0, 1.0)) * 2.0 - 1.0, f - float3(1.0, 1.0, 1.0)), u.x), u.y), u.z);
}
void noiseDomainOffset_id42(inout float3 p1, out float3 p2, out float3 p3)
{
    p2 = p1 + vectorValuedNoiseOffsets_id22.x;
    p3 = p1 + vectorValuedNoiseOffsets_id22.y;
}
float3 gradientNoise33_id68(float3 p)
{
    float3 p2, p3;
    noiseDomainOffset_id42(p, p2, p3);
    return float3(gradientNoise_id54(p), gradientNoise_id54(p2), gradientNoise_id54(p3));
}
float Function_1430276449_id77(in float arg_0)
{
    return arg_0;
}
float Function_3054557535_id76(in float3 arg_0, out float arg_1)
{
    float3 result_3318057383 = (arg_0 - input_612669918_id46);
    float length_3562960734 = length(result_3318057383);
    float result_1981706564 = (length_3562960734 - input_1214679681_id47);
    arg_1 = result_1981706564;
    return input_4032468177_id48;
}
float3 cast31_id75(float p)
{
    return p.xxx;
}
float3 Function_3663475189_id74(in float3 arg_0)
{
    float3 result_2044114122 = (arg_0 * input_545566076_id36);
    float3 Float3Join_3895880077 = float3(input_3530845571_id37, input_1386142014_id38, 0);
    float3 result_783623819 = (result_2044114122 + Float3Join_3895880077);
    float3 gradientNoise33_1797686070 = gradientNoise33_id68(result_783623819);
    float3 result_1386355867 = (gradientNoise33_1797686070 * input_784016946_id39);
    float3 result_1784618882 = (result_1386355867 + input_3491954125_id40);
    return result_1784618882;
}
float cast11_id73(float p)
{
    return p;
}
float4 cast41_id72(float p)
{
    return float4(p, p, p, 1);
}
float Function_559939261_id71(in float arg_0)
{
    return arg_0;
}
float4 Function_570622739_id70(in float3 arg_0, out float arg_1)
{
    float3 result_1512400414 = (arg_0 - input_826793605_id30);
    float length_230306403 = length(result_1512400414);
    float result_2937537851 = (length_230306403 - input_3887551545_id31);
    arg_1 = result_2937537851;
    float4 join_2034726530 = float4(input_4285495262_id32, 1);
    return join_2034726530;
}
float3 cast33_id69(float3 p)
{
    return p;
}
void Compute_id4(inout CS_STREAMS streams)
{
    int DispatchThreadIdX_1705848389 = streams.DispatchThreadId_id1.x;
    int inputX_3964728810 = input_4027469542_id27.x;
    bool Assign_2669607774 = DispatchThreadIdX_1705848389 >= inputX_3964728810;
    int DispatchThreadIdY_1152064971 = streams.DispatchThreadId_id1.y;
    int inputY_3132258850 = input_4027469542_id27.y;
    bool Assign_2401786989 = DispatchThreadIdY_1152064971 >= inputY_3132258850;
    int DispatchThreadIdZ_1595855846 = streams.DispatchThreadId_id1.z;
    int inputZ_47154949 = input_4027469542_id27.z;
    bool Assign_3128971616 = DispatchThreadIdZ_1595855846 >= inputZ_47154949;
    bool result_2293831901 = (Assign_2669607774 || Assign_2401786989 || Assign_3128971616);
    if (result_2293831901)
    {
        return;
    }
    float4 velocity_2773640457 = TextureInput_3445202295_id23[streams.DispatchThreadId_id1];
    float density_3039937939 = TextureInput_1090208749_id24[streams.DispatchThreadId_id1];
    float deltatime_3823063910 = 0;
    deltatime_3823063910 = input_3335055883_id28;
    int3 index_1056028929 = int3(0, 0, 0);
    index_1056028929 = streams.DispatchThreadId_id1;
    float3 resourcescale_1424475548 = float3(0, 0, 0);
    resourcescale_1424475548 = input_1092026727_id29;
    float4 velocity_2_2773640457 = TextureInput_3445202295_id23[streams.DispatchThreadId_id1];
    float3 cast33_3178254890 = cast33_id69(streams.DispatchThreadId_id1);
    float3 result_2318118799 = (cast33_3178254890 + float3(0.5, 0.5, 0.5));
    float3 cast33_1967639258 = cast33_id69(input_2612132572_id33);
    float3 result_1781501966 = (result_2318118799 / cast33_1967639258);
    float3 result_3334746528 = (result_1781501966 - 0.5);
    float3 result_1685619903 = (float3(0.5, 0.5, 0.5) - float3(0.5, 0.5, 0.5));
    float3 result_1991503536 = (result_1685619903 * input_706026866_id34);
    float3 result_618623104 = (result_3334746528 + result_1991503536);
    float4 join_391424359 = float4(result_618623104, 1);
    float4 mul_3753286746 = mul(join_391424359, input_2145687636_id35);
    float3 mulXyz_339685817 = mul_3753286746.xyz;
    float output_3376274067 = 0;
    float4 Invoke_413004222 = Function_570622739_id70(mulXyz_339685817, output_3376274067);
    float negate_3743137054 = -output_3376274067;
    float result_3652630835 = (negate_3743137054 - 0);
    float result_2564076016 = (0 - 0);
    float result_2365310752 = (result_3652630835 / result_2564076016);
    float saturate_1172730497 = saturate(result_2365310752);
    float Invoke_3109954890 = Function_559939261_id71(saturate_1172730497);
    float4 cast41_55682224 = cast41_id72(Invoke_3109954890);
    float4 lerp_3358782467 = lerp(velocity_2_2773640457, Invoke_413004222, cast41_55682224);
    velocity_2_2773640457 = lerp_3358782467;
    float ceil_4176877153 = ceil(input_1215088069_id42);
    int cast11_2713164060 = cast11_id73(ceil_4176877153);
    float3 output_2402172871 = mulXyz_339685817;
    float3 output_3815007906 = float3(0, 0, 0);
    float output_2808590973 = 0;
    float output_3837911896 = input_3940645616_id41;

    for (int index_4912002 = 0; index_4912002 < cast11_2713164060; index_4912002++)
    {
        float3 result_344171006 = (output_2402172871 * input_2966110979_id43);
        float3 Invoke_1279114555 = Function_3663475189_id74(output_2402172871);
        float cast11_1547164192 = cast11_id73(index_4912002);
        float result_2816853187 = (input_1215088069_id42 - cast11_1547164192);
        float min_2622095659 = min(result_2816853187, 1);
        float result_3671589725 = (min_2622095659 * output_3837911896);
        float3 result_2324369118 = (Invoke_1279114555 * result_3671589725);
        float3 result_1239294461 = (output_3815007906 + result_2324369118);
        float result_738610457 = (output_2808590973 + result_3671589725);
        float result_3949622621 = (output_3837911896 * input_3940645616_id41);
        output_2402172871 = result_344171006;
        output_3815007906 = result_1239294461;
        output_2808590973 = result_738610457;
        output_3837911896 = result_3949622621;
    }
    bool Assign_2179612114 = output_2808590973 > 0;
    float expression_3449698237 = Assign_2179612114 ? output_2808590973 : 1;
    float3 cast31_1171905385 = cast31_id75(expression_3449698237);
    float3 result_3044682796 = (output_3815007906 / cast31_1171905385);
    float3 result_1988462773 = (result_3044682796 + input_3330421063_id44);
    float4 join_3401270700 = float4(result_1988462773, 1);
    float4 result_3779073243 = (velocity_2_2773640457 + join_3401270700);
    float3 resultXyz_519719242 = result_3779073243.xyz;
    float VelocityW_198668014 = velocity_2_2773640457.w;
    float joinW_943454149 = join_3401270700.w;
    float4 cast41_2116577477 = cast41_id72(input_2931687735_id45);
    float cast41W_4025974793 = cast41_2116577477.w;
    float lerp_2313369402 = lerp(VelocityW_198668014, joinW_943454149, cast41W_4025974793);
    float4 join_75234666 = float4(resultXyz_519719242, lerp_2313369402);
    float4 lerp_2233171608 = lerp(velocity_2_2773640457, join_75234666, cast41_2116577477);
    velocity_2_2773640457 = lerp_2233171608;
    float density_103807989 = TextureInput_1090208749_id24[streams.DispatchThreadId_id1];
    float output_1574828391 = 0;
    float Invoke_2287230928 = Function_3054557535_id76(mulXyz_339685817, output_1574828391);
    float negate_1431886576 = -output_1574828391;
    float result_1749536247 = (negate_1431886576 - 0);
    float result_1803605266 = (0 - 0);
    float result_1841302926 = (result_1749536247 / result_1803605266);
    float saturate_3798608805 = saturate(result_1841302926);
    float Invoke_2766904684 = Function_1430276449_id77(saturate_3798608805);
    float cast11_2557316718 = cast11_id73(Invoke_2766904684);
    float lerp_2342350959 = lerp(density_103807989, Invoke_2287230928, cast11_2557316718);
    density_103807989 = lerp_2342350959;
    TextureInput_2255746994_id25[streams.DispatchThreadId_id1] = velocity_2_2773640457;
    TextureInput_3422964264_id26[streams.DispatchThreadId_id1] = density_103807989;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(8, 8, 8)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 8;
    streams.ThreadCountY_id8 = 8;
    streams.ThreadCountZ_id9 = 8;
    streams.ThreadCountPerGroup_id5 = 8 * 8 * 8;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
