/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin Blur_Noise_Internal_TextureFX [{Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}, {Size = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}, {Time = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}]
@P Time: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P Size: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 32]
@C    InputValue_id97 => ShaderFX.InputValueFloat4
@C    InputValue_id98 => ShaderFX.InputValueFloat.i1
@C    InputValue_id99 => ShaderFX.InputValueFloat
cbuffer PerView [Size: 32]
@C    NearClipPlane_id74 => Camera.NearClipPlane
@C    FarClipPlane_id75 => Camera.FarClipPlane
@C    ZProjection_id76 => Camera.ZProjection
@C    ViewSize_id77 => Camera.ViewSize
@C    AspectRatio_id78 => Camera.AspectRatio
cbuffer Globals [Size: 96]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
@C    Iterations_id96 => Blur_Noise_Internal_TextureFX.Iterations
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    LinearSampler_id44 => Texturing.LinearSampler [Stage: Pixel, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (1-1)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    PerView => PerView [Stage: Pixel, Slot: (1-1)]
@R    Globals => Globals [Stage: Pixel, Slot: (2-2)]
***************************
*****     Sources     *****
***************************
@S    Blur_Noise_Internal_TextureFX => 0c2b53a6d873fbf4b35bfa2d3ba1055d
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    AddonShaderUtils => 0d3496ddd24bfcbde4abd1deae724f64
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 226 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_722ef6d4369a052fac142989136dac30.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 230
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 1d3555021ee3828318b593a5d617d388
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id97;            // Offset:    0 Size:    16
//   float InputValue_id98;             // Offset:   16 Size:     4
//   float InputValue_id99;             // Offset:   20 Size:     4
//
// }
//
// cbuffer PerView
// {
//
//   float NearClipPlane_id74;          // Offset:    0 Size:     4 [unused]
//      = 0x3f800000 
//   float FarClipPlane_id75;           // Offset:    4 Size:     4 [unused]
//      = 0x42c80000 
//   float2 ZProjection_id76;           // Offset:    8 Size:     8 [unused]
//   float2 ViewSize_id77;              // Offset:   16 Size:     8
//   float AspectRatio_id78;            // Offset:   24 Size:     4 [unused]
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//   int Iterations_id96;               // Offset:   80 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// LinearSampler_id44                sampler      NA          NA             s0      1 
// Sampler0_id52                     sampler      NA          NA             s1      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// PerView                           cbuffer      NA          NA            cb1      1 
// Globals                           cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_constantbuffer CB1[2], immediateIndexed
dcl_constantbuffer CB2[6], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 7
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 205 "C:\Users\sw\Documents\_projects\2024\MOTF\MOTF_VVVV_6.7\vvvv_gamma_6.7\log\shader_TextureFXEffect_722ef6d4369a052fac142989136dac30.hlsl"
sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s1, l(0.000000)  // r0.x <- <InTex0_id26 return value>.x; r0.y <- <InTex0_id26 return value>.y; r0.z <- <InTex0_id26 return value>.z; r0.w <- <InTex0_id26 return value>.w

#line 178
div r1.x, v1.x, cb1[1].x
add r1.x, r1.x, cb0[1].y  // r1.x <- offset.x

#line 166
mul r1.y, cb0[1].y, l(0.100000)
sincos r1.y, null, r1.y

#line 182
mov r1.zw, v1.xxxy  // r1.z <- uv.x; r1.w <- uv.y
mov r2.xyzw, l(0,0,0,0)  // r2.w <- acc; r2.x <- col.x; r2.y <- col.y; r2.z <- col.z
mov r3.x, l(0)  // r3.x <- i
loop 
  ige r3.y, r3.x, cb2[5].x
  breakc_nz r3.y

#line 164
  mad r3.y, r1.w, l(2.000000), cb0[1].y
  sincos r3.y, null, r3.y
  mad r4.x, r3.y, l(0.100000), r1.z  // r4.x <- p.x

#line 165
  mad r3.y, r4.x, l(2.000000), cb0[1].y
  sincos r3.y, null, r3.y
  mad r4.y, r3.y, l(0.100000), r1.w  // r4.y <- p.y

#line 166
  mad r3.yz, r4.xxyx, cb0[1].xxxx, r1.yyyy

#line 147
  round_ni r4.xy, r3.yzyy  // r4.x <- p.x; r4.y <- p.y

#line 148
  frc r3.yz, r3.yyzy  // r3.y <- f.x; r3.z <- f.y

#line 149
  mul r4.zw, r3.yyyz, r3.yyyz
  mad r3.yz, -r3.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
  mul r3.yz, r3.yyzy, r4.zzwz  // r3.y <- f.x; r3.z <- f.y

#line 150
  mad r3.w, r4.y, l(57.000000), r4.x  // r3.w <- n

#line 143
  sincos r4.x, null, r3.w
  mul r4.x, r4.x, l(43758.546875)

#line 151
  add r4.yzw, r3.wwww, l(0.000000, 1.000000, 57.000000, 58.000000)  // r4.w <- n

#line 143
  sincos r4.yzw, null, r4.yyzw
  mul r4.yzw, r4.yyzw, l(0.000000, 43758.546875, 43758.546875, 43758.546875)
  frc r4.xyzw, r4.xyzw  // r4.w <- <hash_id69 return value>

#line 151
  add r3.w, -r4.x, r4.y
  mad r3.w, r3.y, r3.w, r4.x
  add r4.x, -r4.z, r4.w
  mad r3.y, r3.y, r4.x, r4.z
  add r3.y, -r3.w, r3.y
  mad r3.y, r3.z, r3.y, r3.w  // r3.y <- <noise_id70 return value>

#line 167
  mad r3.y, r3.y, l(6.283100), -r1.x  // r3.y <- a

#line 168
  sincos r4.x, r5.x, r3.y  // r4.x <- <map_id71 return value>.y; r5.x <- <map_id71 return value>.x

#line 185
  itof r3.y, r3.x

#line 186
  mul r3.z, r3.y, l(0.125000)
  mad r3.y, -r3.y, l(0.031250), l(1.000000)
  mul r3.w, r3.y, r3.z  // r3.w <- w

#line 187
  sample_l_indexable(texture2d)(float,float,float,float) r4.yzw, r1.zwzz, t0.wxyz, s0, l(0.000000)
  mul r4.yzw, r3.wwww, r4.yyzw  // r4.y <- ttt.x; r4.z <- ttt.y; r4.w <- ttt.z

#line 188
  mov r5.y, r4.x
  mad r5.zw, r5.xxxx, l(0.000000, 0.000000, -2.000000, -0.000000), r5.xxxy
  dp2 r4.x, r5.zwzz, l(0.707000, 0.707000, 0.000000, 0.000000)
  mad r4.x, -r4.x, l(0.500000), l(0.500000)
  mad r6.xyz, r4.xxxx, l(0.400000, 0.250000, 0.200000, 0.000000), l(0.600000, 0.700000, 0.700000, 0.000000)
  mul r4.xyz, r4.yzwy, r6.xyzx  // r4.x <- ttt.x; r4.y <- ttt.y; r4.z <- ttt.z

#line 189
  mad r2.xyz, r3.wwww, r4.xyzx, r2.xyzx

#line 190
  mad r2.w, r3.z, r3.y, r2.w

#line 191
  mad r1.zw, r5.xxxy, l(0.000000, 0.000000, 0.008000, 0.008000), r1.zzzw

#line 192
  iadd r3.x, r3.x, l(1)
endloop 

#line 193
div r2.xyz, r2.xyzx, r2.wwww

#line 194
dp3 r2.w, r2.xyzx, l(0.333000, 0.333000, 0.333000, 0.000000)  // r2.w <- gg

#line 195
deriv_rtx_coarse r3.x, r2.w
deriv_rty_coarse r3.z, r2.w
mov r3.y, l(0.500000)
dp3 r2.w, r3.xyzx, r3.xyzx
rsq r2.w, r2.w
mul r3.xyz, r2.wwww, r3.xyzx  // r3.x <- nor.x; r3.y <- nor.y; r3.z <- nor.z

#line 196
dp3 r2.w, r3.xzyx, l(0.700000, 0.700000, 0.010000, 0.000000)
mad r2.xyz, r2.wwww, l(0.400000, 0.400000, 0.400000, 0.000000), r2.xyzx

#line 164
mad r2.w, r1.w, l(2.000000), cb0[1].y
sincos r2.w, null, r2.w
mad r3.x, r2.w, l(0.100000), r1.z  // r3.x <- p.x

#line 165
mad r1.z, r3.x, l(2.000000), cb0[1].y
sincos r1.z, null, r1.z
mad r3.y, r1.z, l(0.100000), r1.w  // r3.y <- p.y

#line 166
mad r1.yz, r3.xxyx, cb0[1].xxxx, r1.yyyy

#line 147
round_ni r3.xy, r1.yzyy  // r3.x <- p.x; r3.y <- p.y

#line 148
frc r1.yz, r1.yyzy  // r1.y <- f.x; r1.z <- f.y

#line 149
mul r3.zw, r1.yyyz, r1.yyyz
mad r1.yz, -r1.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
mul r1.yz, r1.yyzy, r3.zzwz  // r1.y <- f.x; r1.z <- f.y

#line 150
mad r1.w, r3.y, l(57.000000), r3.x  // r1.w <- n

#line 143
sincos r2.w, null, r1.w
mul r2.w, r2.w, l(43758.546875)
frc r2.w, r2.w  // r2.w <- <hash_id69 return value>

#line 151
add r3.xyz, r1.wwww, l(1.000000, 57.000000, 58.000000, 0.000000)

#line 143
sincos r3.xyz, null, r3.xyzx
mul r3.xyz, r3.xyzx, l(43758.546875, 43758.546875, 43758.546875, 0.000000)
frc r3.xyz, r3.xyzx  // r3.z <- <hash_id69 return value>

#line 151
add r1.w, -r2.w, r3.x
mad r1.w, r1.y, r1.w, r2.w
add r2.w, -r3.y, r3.z
mad r1.y, r1.y, r2.w, r3.y
add r1.y, -r1.w, r1.y
mad r1.y, r1.z, r1.y, r1.w  // r1.y <- <noise_id70 return value>

#line 167
mad r1.x, r1.y, l(6.283100), -r1.x  // r1.x <- a

#line 168
sincos r1.x, r3.x, r1.x  // r1.x <- <map_id71 return value>.y; r3.x <- <map_id71 return value>.x

#line 198
mov r3.y, r1.x
dp2 r1.x, r3.xyxx, l(0.707000, 0.707000, 0.000000, 0.000000)
mad r1.x, r1.x, l(0.350000), l(0.650000)
mul r1.xyz, r1.xxxx, r2.xyzx  // r1.x <- col.x; r1.y <- col.y; r1.z <- col.z

#line 199
mul r1.w, v1.x, l(4.000000)
add r2.x, -v1.x, l(1.000000)
mul r1.w, r1.w, r2.x
log r1.w, |r1.w|
mul r1.w, r1.w, l(0.100000)
exp r1.w, r1.w
mad r1.w, r1.w, l(0.800000), l(0.200000)
mul r1.xyz, r1.wwww, r1.xyzx

#line 200
mul r1.xyz, r1.xyzx, l(1.700000, 1.700000, 1.700000, 0.000000)

#line 210
mov r1.w, l(1.000000)
add r1.xyzw, -r0.xyzw, r1.xyzw
mad o0.xyzw, cb0[0].xyzw, r1.xyzw, r0.xyzw

#line 219
ret 
// Approximately 110 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id97;
    float InputValue_id98;
    float InputValue_id99;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
    int Iterations_id96;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float hash_id69(float n)
{
    return frac(sin(n) * 43758.5453);
}
float noise_id70(in float2 x)
{
    float2 p = floor(x);
    float2 f = frac(x);
    f = f * f * (3.0 - 2.0 * f);
    float n = p.x + p.y * 57.0;
    return lerp(lerp(hash_id69(n + 0.0), hash_id69(n + 1.0), f.x), lerp(hash_id69(n + 57.0), hash_id69(n + 58.0), f.x), f.y);
}
float Compute_id75()
{
    return InputValue_id98;
}
float Compute_id74()
{
    return InputValue_id99;
}
float2 map_id71(float2 p, in float offset)
{
    float time = Compute_id74();
    p.x += 0.1 * sin(time + 2.0 * p.y);
    p.y += 0.1 * sin(time + 2.0 * p.x);
    float a = noise_id70(p * Compute_id75() + sin(0.1 * time)) * 6.2831;
    a -= offset;
    return float2(cos(a), sin(a));
}
float4 Compute_id73()
{
    return InputValue_id97;
}
float4 Filter_id72(inout PS_STREAMS streams, float4 tex0col)
{
    float2 p = streams.TexCoord_id62;
    float2 uv = p;
    float2 offset = Compute_id74() + streams.TexCoord_id62.x / ViewSize_id77.x;
    float acc = 0.0;
    float3 col = float(0.0);

    for (int i = 0; i < Iterations_id96; i++)
    {
        float2 dir = map_id71(uv, offset);
        float h = float(i) / 32.0;
        float w = 4.0 * h * (1.0 - h);
        float3 ttt = w * Texture0_id14.SampleLevel(LinearSampler_id44, uv, 0).xyz;
        ttt *= lerp(float3(0.6, 0.7, 0.7), float3(1.0, 0.95, 0.9), 0.5 - 0.5 * dot(reflect(float3(dir, 0.0), float3(1.0, 0.0, 0.0)).xy, float(0.707)));
        col += w * ttt;
        acc += w;
        uv += 0.008 * dir;
    }
    col /= acc;
    float gg = dot(col, float(0.333));
    float3 nor = normalize(float3(ddx(gg), 0.5, ddy(gg)));
    col += float(0.4) * dot(nor, float3(0.7, 0.01, 0.7));
    float2 di = map_id71(uv, offset);
    col *= 0.65 + 0.35 * dot(di, float(0.707));
    col *= 0.20 + 0.80 * pow(abs(4.0 * p.x * (1.0 - p.x)), 0.1);
    col *= 1.7;
    return float4(col, 1.0);
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id72(streams, col), Compute_id73());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
